### ISSUE TITLE
HTTP block will not connect to locally-hosted servers, even if they are CORS compliant

### ISSUE THREAD

**Issue by zippynk** [jmoenig/Snap--Build-Your-Own-Blocks#1002]
Building on what was discussed in #89, the HTTP block doesn't seem to work on locally-hosted servers, disregarding CORS compliance.

I assume this is a fairly new bug, or specific to my setup, since it didn't seem to stop people building the blockext extensions. This bug blocks the extensions from running (I tried the snap-wiimote script, as well as a local CORS proxy from npm).

On the local sites, the HTTP block returns a blank response.

Firefox 41.0.2 on Ubuntu 15.10 64-bit

**Comment by jmoenig** [comment]
I cannot confirm this. I've just tried it on several different computers running OSX and Windows and it did work fine. I don't have a Linux machine, though... But I hear that the people at the Citilab are using it a lot, and it does seem to work for them, too. Hmm...

**Comment by jmoenig** [comment]
... I tried both Chrome and Firefox, and both worked...

**Comment by zippynk** [comment]
Turns out it was a NoScript issue. I had enabled JavaScript everywhere, but was still running NoScript, so I gather it was blocking some things. Although it may be useful at some point to figure that out, there's sort of an assumption that having NoScript installed breaks things, so I'll close this.
