### ISSUE TITLE
HTTP block report too wide for browser window

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1003]
The source for some bjc.edc.org pages produces a http block report too wide to read... 
For example, try passing bjc.edc.org/bjc-r/cur/programming/1-introduction/3-control-commands/2-nesting-repeats.html to the http block.

**Comment by brianharvey** [comment]
It's not clear that line wrapping is always desirable, because it can confuse you about where the lines are, and maybe that's what's important.  Really the right thing is to SPLIT the text into a list, and then display line by line, inventing a wrapping function if needed.  (They're fun to write.)
