### ISSUE TITLE
Chrome tab navigation keystrokes (e.g. cmd-1, cmd-2, etc., and cmd-tilde)

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1012]
Snap! tabs block Chrome navigation keystrokes such as cmd-1, cmd-2, etc., and cmd-tilde, which would be super helpful when having both Snap! and BJC tabs/windows open.

**Comment by jmoenig** [comment]
Snap is a programming environment and takes over control over the keyboard. That's what it *should* do. If you want the browser to handle something, unfocus Snap by clicking elsewhere, e.g. in the browser's url bar
