### ISSUE TITLE
Can key pressed accept input variable?

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1017]
Could we have a key pressed block that accepts an input variable? It would be nice to be able to loop through an array of keys and commands.

**Comment by jmoenig** [comment]
Keys don't have English names in most languages :-)

**Comment by djdolphin** [comment]
This seems to already work, but it doesn't work well with other languages for the reason Jens stated:

![key pressed](https://cloud.githubusercontent.com/assets/5834370/11288105/eacae258-8eee-11e5-81a3-30e00266d19d.png)
![key pressed spanish](https://cloud.githubusercontent.com/assets/5834370/11288106/edaac3a8-8eee-11e5-8594-36242c0675ac.png)
![key pressed espacio](https://cloud.githubusercontent.com/assets/5834370/11288109/ef783396-8eee-11e5-88f3-b97f743e7717.png)

Maybe it could accept key codes instead?

**Comment by maryfries** [comment]
Ok, yes, I got it to work. Not sure why I couldn't do it before. We can close this as far as my initial purpose for opening it is concerned. Thanks!
