### ISSUE TITLE
Snap colors - HEX and/or RGB?

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1019]
The change color blocks are not clear enough and do not support HEX colors (HEX is included in the AP CSP). It took the EDC team a few minutes to figure out that “change color by __” and “set pen color to ___” only change the hue and that the pen color’s saturation/brightness is actually set by other blocks such as “change pen shade to ___”, “set pen shade to ___”, and “set pen color to <color>”. The meaning of the word “color” is different from block to block. Perhaps  “change color by __” and “set pen color to ___” should really be  “change hue by __” and “set pen hue to ___”. And it might be especially nice to have a “set pen color to R ___ G ___ B ___” block.

**Comment by jmoenig** [comment]
Here you go:

http://snap.berkeley.edu/snapsource/snap.html#present:Username=jens&ProjectName=pen%20enhancements&editMode

Export the blocks in this projects and share them as a library.

**Comment by maryfries** [comment]
Very cool! Thanks!

**Comment by cycomachead** [comment]
Also tagging #893 

I think we could use native colors in Snap<em>!</em> :)

**Comment by jmoenig** [comment]
Sure, but we also need first-class first-class-ness a.k.a. an object system, so we don't have to special case each new first-class member

**Comment by cycomachead** [comment]
> Sure, but we also need first-class first-class-ness a.k.a. an object system, so we don't have to special case each new first-class member

Well, that wasn't what was holding up that PR... But that also seems like a ways off, and colors will still need a few modifications if they're first class (like visualizations). I still think that even with those things, something simple with human-understandable colors should be default, and available.

**Comment by brianharvey** [comment]
Will be fixed by first class colors, coming in 4.1.  Meanwhile use Dan's color library.
