### ISSUE TITLE
Snap sound high end cuts out

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1020]
The range of the “play note __ for __ beats” block seems to cut out before my hearing does (it cuts out around note 128).

**Comment by cycomachead** [comment]
Can you list a browser? This could be a browser thing, and possibly a speaker thing...

**Comment by maryfries** [comment]
I use Chrome most of the time, but I just tried this script in Safari and it cuts out after 128 also.

![image](https://cloud.githubusercontent.com/assets/6549787/11307527/cd04e582-8f86-11e5-9665-e9afe89bfcbb.png)

Probably not a big deal (or any deal at all), but I noticed it.

**Comment by brianharvey** [comment]
We can reproduce this but don't have a clue what's causing it -- we just use the browser's interface.  Can't fix.
