### ISSUE TITLE
Treatment of blank in map vs. combine

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1023]
From Al: I mapped ()*3 over a list and got what I expect (the ()  was used as a placeholder that was replaced by each elt of the list).   But when I used the same thing with combine with (I know, it’s supposed to have 2 blanks), the () became 0.

**Comment by brianharvey** [comment]
This is the advertised behavior.  If M actual arguments are provided to a function that has N empty slots, argument substitution is done iff M=N or, as a special case, M=1 (substituting the one argument into all the empty slots).  In Al's example, M=2 and N=1.  It's part of the documentation of COMBINE that it requires a two-input function.
