### ISSUE TITLE
SNAP Project Won't Load?!?

### ISSUE THREAD

**Issue by Evanforest62** [jmoenig/Snap--Build-Your-Own-Blocks#1027]
Can you guys please help me? I was working on my Snap project and I spent a lot of time and effort into it. I saved it several times just to be sure it was saved properly, cause I hate how sometimes it doesn't save or I accidentally closed it and all my work was lost. So after I saved it, I closed it and the next day it won't load! I tried waiting but I still couldn't open it. I got really upset, I don't want to do it all over again. :( Username is: Evanforest62 Project Name: The Heroic Starship (Please get back to me asap, thx...)

**Comment by Evanforest62** [comment]
Btw, the url link for my project doesn't show up when I try to open it so yeah...

**Comment by jmoenig** [comment]
Yep, I'm getting a proxy error on this one. Will investigate...

**Comment by Evanforest62** [comment]
Good news, I managed the find the link that I saved while I was working on my project. Here it is in case you need it. http://snap.berkeley.edu/snapsource/snap.html#present:Username=evanforest62&ProjectName=The%20Heroic%20Starship

**Comment by Evanforest62** [comment]
Yes, my project is working again! Idk why, but thanks for trying to help me. :)

**Comment by jmoenig** [comment]
this is the same as #1041 the - somewhat infuriating - reason this project has been failing is that it containes almost half an hour of full-quality stereo Starts Wars sound track. We need to talk to teachers about this.
