### ISSUE TITLE
Problems connecting to SNAP

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1028]
This was reported today, 11/24/15 on https://piazza.com/class/i7hy3udaukx6su?cid=159

It was unusually difficult to connect to SNAP today when students were trying to login.  Often they got a message with a red cloud that said: could not connect to: https://snapapps.miosoft.com/SnapCloud

**Comment by cycomachead** [comment]
Keeping #1035 As the main point of discussion for this.
