### ISSUE TITLE
Make a /run/dev page

### ISSUE THREAD

**Issue by liam4** [jmoenig/Snap--Build-Your-Own-Blocks#1033]
You know how we use [`/run`](http://snap.berkeley.edu/run) to run Snap? It would be a bit useful if we had a `/run/dev` page, as well as possibly a button on the homepage to run the development edition.

**Comment by brianharvey** [comment]
Nooooo...  We are encouraging *our friends* to try out a version that is likely to crash and even likelier to change before release, or even end up rejected in favor of a completely different approach.  But this isn't even solid enough to be called "alpha test" and we don't want the whole world to develop expectations based on it.

Feel free to bookmark the page.  :-)
