### ISSUE TITLE
Snap Cloud Unavailable

### ISSUE THREAD

**Issue by galengt-lendup** [jmoenig/Snap--Build-Your-Own-Blocks#1035]
Logging in takes several seconds, and opening project saved to the cloud fails with the attached error.

<img width="281" alt="screen shot 2015-12-01 at 8 38 39 am" src="https://cloud.githubusercontent.com/assets/12899709/11507046/08bc6c16-9807-11e5-8a36-7e386f319503.png">

**Comment by jmoenig** [comment]
Okay, can you be a little more specific, please? Is this in a public network, e.g. in a school, are you behind some kind of proxy etc.? I've been extensively using the Snap Cloud myself all day on a variety of different computers and it has worked flawlessly for me. Could there be a bandwidth issue in your network? Is this the first time this has happened? Are you part of a class that all more or less open log-in and open projects at the same time? Thanks!

**Comment by davelai** [comment]
Same connection issue here today. Public school network. No connection issues known before. No sites blocked at school...

**Comment by jmoenig** [comment]
Thanks, and sorry! Still works fine for me over here in Germany, I just checked. Now investigating into the issues you both are reporting...

**Comment by davelai** [comment]
thanks. I was able to sign in (account: dlai) earlier, then not again for 30 minutes or so, but just now I'm able to sign in again.  (this includes a class of 30 students who left unable to save their projects to the cloud... export to XML worked as a temporary workaround I think/hope).

**Comment by galengt-lendup** [comment]
We are also on a public school network, class of 30 students. Issues are specific to Snap Cloud, other sites work. We haven't had issues in the past, and our usage today is normal. I thought it might be an SSL issue, but whether we access Snap over SSL or not we still have the same problem. It seems like there is a lot of latency on the other end and requests are timing out after a couple of minutes.

**Comment by jmoenig** [comment]
Investigating right now... All I can see from my side of the Atlantic ocean is that everything seems to work fine... but we're looking into this. Thanks!

**Comment by bromagosa** [comment]
Ouch... same issue for me at your same side of the ocean. This is what the JS console says when I try to access the cloud project list:

![gas](https://cloud.githubusercontent.com/assets/1016697/11509523/cfc4f86c-985e-11e5-8509-22bc19e91dc9.png)

**Comment by bromagosa** [comment]
(However, I can still load projects from the cloud by their URL)

**Comment by jmoenig** [comment]
I've now also noticed the issue, it takes forever to load the project list, and sometimes it fails altogether :-(

**Comment by jcaldw737** [comment]
I tried logging out and now I get the "no cloud" error when I try to log  back in.  HELP!!!

**Comment by jcaldw737** [comment]
When I click on a link that I had previously saved, its shared project comes up fine.

**Comment by davelai** [comment]
From my account (dlai) at my personal/home computer, I have lost the ability to login (or save projects from account already logged into). I was able to login and save projects for about an hour before now. I can open links to saved projects.  message:

Snap!Cloud (red cloud icon) could not connect to: https://snap.apps.miosoft.com/SnapCloud

**Comment by jcaldw737** [comment]
For what it may be worth, I can login and save projects to the cloud now, but yesterday afternoon and evening I had difficulty in those areas. (using personal/home computer in MN)

**Comment by bromagosa** [comment]
Just discovered something. Using Chrome or Firefox in private mode does allow you to connect to the cloud and browse projects normally, which I guess means it must be something related to either browser cache, local storage, cookies...

**Comment by jmoenig** [comment]
Well, this morning we've doubled the number of available web servers, so *that's* the reason (we're hoping). This means that it should also work in non-anonymous mode (check whether the version of cloud.js has today's date)

**Comment by bromagosa** [comment]
Just cleaned all BeetleBlocks related cookies and local storage, and still can't log in. It does work in incognito mode though... weird!

**Comment by bromagosa** [comment]
Okay, it works now! Thank you, Jens! :)

**Comment by jcaldw737** [comment]
I am getting the "no cloud" error when I try to use the "open" menu item.  I got it earlier this evening and just tried again and got it.

**Comment by jcaldw737** [comment]
When I try to use the menu item "open", I get "no cloud" using Firefox, but I get in using Chrome.

**Comment by davelai** [comment]
Experiencing similar issues this morning in class...

**Comment by davelai** [comment]
For some reason, incognito window in Chrome, opening snap! from "snap.berkeley.edu/run" ...works!

**Comment by jmoenig** [comment]
This should be mostly fixed by now. Try clearing your browser's cache and - this time only - also make sure to delete all your cookies. Then things should also work reliably on non-incognito mode again.

**Comment by davelai** [comment]
Even in incognito mode, same connection issues with loading snap (not even able to open snap to get to the login issues).... =(

**Comment by davelai** [comment]
http://snap.berkeley.edu/snapsource/snap.html 

waiting for this page to load... and waiting...

**Comment by jmoenig** [comment]
please flush your cache! Just reload the page while holding shift

Von meinem iPhone gesendet

**Comment by jmoenig** [comment]
both ```cloud.js``` and ```gui.js``` should show today's date (in the "about..." dialog). Also, you may need to delete all browser cookies once. But *then* it should totally work!

Please let me know if it doesn't.
Tnx!

**Comment by davelai** [comment]
thanks! It works on my machine now (students are gone now so I won't test the entire classroom until Monay...). I'll make sure to have students verify these items.

**Comment by galengt-lendup** [comment]
Experiencing issues logging in again today, same error message as before. Not all accounts are experiencing the error, but the ones that are experiencing it get the error consistently.

**Comment by Philippe-Capdepuy** [comment]
Hi,

I'm reopening the issue here. It seems the SSL certificate hasn't been renewed in quite some time, resulting in no possible login or sign up to https://snap.apps.miosoft.com/SnapCloud

Here is the provided certificate:
Common Name (CN)	*.apps.miosoft.com
Organization (O)	<Not Part Of Certificate>
Organizational Unit (OU)	Domain Control Validated
Issued By

Common Name (CN)	Go Daddy Secure Certificate Authority - G2
Organization (O)	GoDaddy.com, Inc.
Organizational Unit (OU)	http://certs.godaddy.com/repository/
Validity Period

Issued On	Wednesday, March 30, 2016 at 3:01:40 AM
Expires On	**Friday, March 30, 2018 at 7:15:05 PM**

**Comment by bromagosa** [comment]
Hmm. Where did you find these URLs? We're not using MioSoft's cloud since more than a year ago.

**Comment by Philippe-Capdepuy** [comment]
They're used on a robot called Poppy Ergo JR that supports Snap programming.
What are the new URLs? Do you think we can simply replace them or do you recommend a full update of the Snap that's embedded on the robot? (I guess communication with the server may have changed too).

**Comment by bromagosa** [comment]
I love that robot!

Ideally you should update the full Snap! in the robot. There are changes to the way the cloud works, and, as you suspected, just updating the URL won't be enough.
