### ISSUE TITLE
Key [Alt]+a (polish diacritics) don't work in input field in editor

### ISSUE THREAD

**Issue by DarDoro** [jmoenig/Snap--Build-Your-Own-Blocks#1036]
Polish diacritics [Alt] + [a,e,c,l,n,o,s] don't work at all in editor.
Only [Alt]+a acts as "Select All".

Expected result :  ą	\u0105

Windows 10, Chrome 46.0.2490.86 m

**Comment by cycomachead** [comment]
Yep, unfortunately, this is a known limitation.

Tag #4 #625
