### ISSUE TITLE
Snap Cloud connection problems

### ISSUE THREAD

**Issue by thedudeguy1** [jmoenig/Snap--Build-Your-Own-Blocks#1038]
When I try to log into my Snap! account from http://snap.berkeley.edu/ I receive
![screen shot 2015-12-02 at 8 05 54 am](https://cloud.githubusercontent.com/assets/6992149/11531564/c498cbea-98cb-11e5-9195-25ce6beed30b.png)
I've seen this as a known issue ATM however, if I switch browsers, I can successfully log in using anything but chrome. This has only been an issue on one school computer. Logging in from home on chrome yields no problems even though chrome on the school computer is synced to the school user on my laptop.

One additional strange occurrence is if I try to log into my cloud account from http://snap.apps.miosoft.com, the login window disappears without logging in or passing an error.

**Comment by jmoenig** [comment]
can we maybe have a single issue that we keep open for these reports #1028, #1035 ?

**Comment by liam4** [comment]
Yes, that would keep things organized.

**Comment by cycomachead** [comment]
@jmoenig yeah, let's just use #1035 as the main issue. :)
