### ISSUE TITLE
Reporter didn't report

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1043]
From a Teacher on Piazza:

"Some of my students are receiving errors when creating the plural block for Unit 2 Lab 1. The error says, "Inside: Error.  Reporter didn't report.""
"The code looks perfect.  When my student sent it to me, it ran properly. Does it have anything to do with her not being able to save it to the Snap cloud?"

![image](https://cloud.githubusercontent.com/assets/6549787/11600361/231e6e3e-9a9a-11e5-88b8-f6e902f6f440.png)

(There have also been reports of people having trouble saving, but I believe you have an issue for that already.) Thanks!

**Comment by cycomachead** [comment]
This is one we've been trying to work on for ages. :(
#712
