### ISSUE TITLE
Loop Exits Prematurely?

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#1044]
This one may be total user-error, but I can't see what's wrong...

Look at this project:
http://snap.berkeley.edu/snapsource/snap.html#present:Username=cycomachead&ProjectName=default%20dictionary

Run the function with the comment, and it doesn't iterate over all items of the list. 

The rest of the project is implementing a default dictionary in Snap<em>!</em>, which may be buggy, but the for-each look should still work correctly. :)

**Comment by cycomachead** [comment]
Ok, so the issue is that one of the `run` blocks calls the inside closure which has a report, and that bubbles up all the way. I guess that behavior is intentional...since that's what allows us to break out of loops.

**Comment by jmoenig** [comment]
yes, that's it precisely. It actually took me a lot of effort to support REPORT inside RUN blocks, there were many projects that used these semantics of REPORT - to my surprise.
