### ISSUE TITLE
Please help.

### ISSUE THREAD

**Issue by Evanforest62** [jmoenig/Snap--Build-Your-Own-Blocks#1048]
Do you know how to get an object to glide over to the position of another object? The glide block only gives out the x and y coordinates. For example, my project in Snap involves shooting lasers to other sprites. Can anyone help me plz?

**Comment by brianharvey** [comment]
A good place to ask for help with Snap! is here:

http://scratch.mit.edu/discuss/topic/4455

The github issues list is for bug reports only.
