### ISSUE TITLE
Labels move when project opened after save

### ISSUE THREAD

**Issue by jcaldw737** [jmoenig/Snap--Build-Your-Own-Blocks#1057]
When I save my project to the cloud, the labels are positioned like this
![labels on save](https://cloud.githubusercontent.com/assets/5361659/11676857/cdfe1bdc-9dfc-11e5-841d-a6ca0ec04315.PNG)

but when I then (re)open the project, the labels have moved like this
![labels on re-open](https://cloud.githubusercontent.com/assets/5361659/11676889/1f1cd51c-9dfd-11e5-8787-3e0367be17c1.PNG)

**Comment by bb010g** [comment]
Could you give a link to the project?

**Comment by jcaldw737** [comment]
oops - here is a link to the project

http://snap.berkeley.edu/snapsource/snap.html#present:Username=jcaldw126&ProjectName=Dec%2008%20156%20Area%20f%28x%29%20%3D%201%20%28under%20curve%29

**Comment by jcaldw737** [comment]
here is a link to the project

http://snap.berkeley.edu/snapsource/snap.html#present:Username=jcaldw126&ProjectName=Dec%2008%20156%20Area%20f%28x%29%20%3D%201%20%28under%20curve%29

**Comment by jmoenig** [comment]
Hmm... this works for me. Sorta. Watchers don't get scaled, but they do get positioned according to the stage's scale. Therefore they "shift" when you scale the stage, e.g. when saving the project in edit mode and opening it again in presentation mode. Generally, in Snap watchers are for debugging. If you want "labels" you can use Michael's "label" block from the tools library, or you create your own active label widget (using a nested sprite) that *will* scale and rotate accordingly.

**Comment by jcaldw737** [comment]
Thanks for the fast response and for the tip about the "label" block in the tools library.
