### ISSUE TITLE
File Loading Issues

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1059]
From a NYC teacher:
"Yesterday I cleared all caches and cookies and it worked great.
But again today students are having cloud login issues.
Today the main problem was not signing in, but rather the ability to load a file."

I've requested additional info.

**Comment by cycomachead** [comment]
Closing since this was likely resolved, and I think this was during a time when the cloud servers were a bit problematic.
