### ISSUE TITLE
Can't save & ongoing login issues

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1062]
Hi, I'm working on the curiculum, and I've finally started running into some of the problems that teachers have been describing: 
![image](https://cloud.githubusercontent.com/assets/6549787/11727087/d618dbbe-9f4f-11e5-85b4-a8a8e61c320a.png)

Is there any way to salvage my work at this point?

**Comment by maryfries** [comment]
Teachers seem to be running into problems too: "It is now 3:30 pm Thursday Dec10. We can access the snap website but are unable to log in. We're getting the red cloud message, It was still ok at 2 pm."

**Comment by cycomachead** [comment]
@maryfries Do you still have that tab open?

**Comment by cycomachead** [comment]
If so can you paste `Cloud.prototype.setRoute` into the JS console and share the result? Thanks!

**Comment by mwmckee** [comment]
I'm experiencing this as well. Output of 'Cloud.prototype.setRoute'

```javascript
Cloud.prototype.setRoute = function (username) {
    var routes = 20,
        userNum = 0,
        i;

    for (i = 0; i < username.length; i += 1) {
        userNum += username.charCodeAt(i);
    }
    userNum = userNum % routes + 1;
    this.route = '.sc1m' +
        (userNum < 10 ? '0' : '') +
        userNum;
};
'''

**Comment by Evanforest62** [comment]
Same problem keeps happening to me! I can't even login now. :/

**Comment by cycomachead** [comment]
It seems to be down for everyone or almost everyone...

**Comment by pamtech** [comment]
Same problem. Kids were trying to work on their semester performance assessment, and couldn't log in. Students who already were logged in got the "could not connect" message when they tried to save their work. Does someone from Snap! know if this'll be fixed by tomorrow (Dec. 11)?

**Comment by brianharvey** [comment]
MioSoft was down for a while this (Thu) afternoon.  Should be better tomorrow.

**Comment by pamtech** [comment]
OK -- Thank you! Was worried because they have 3 class periods left for final project.

**Comment by maryfries** [comment]
From a teacher 12/11 morning: "I have a set of individual students who are unable to log in. They get the red cloud error message.
I've had them clear the browser cache and try different browsers. Same problem.
I've had them try logging in on MY computer. Same problem.
And finally, I can login on THEIR computers. 
Everyone else in the class is able to log in OK.
Everything points to something wrong with these specific login ids.
These logins were OK yesterday.
Is there an escalation procedure?
Thanks
 
P.S. one of these ids is lxia9957"

**Comment by maryfries** [comment]
Another teacher report: "...it's back to normal today.
But the individual students having login problems need to be taken care of."

**Comment by maryfries** [comment]
And another (12/11): "It's 11:10 am and everything has just degraded completely - no one is able to log in."

**Comment by maryfries** [comment]
Some reports of ongoing issues early 12/14/15, but they seem to have cleared up by midday.

**Comment by maryfries** [comment]
At this point, the issues on Piazza are so frequent that I'm no longer trying to get them all in here, but here's another one from today (12/14/15): "Most of my students cannot log in to SNAP! If they can login, they can't open any files as they do not show. Any ideas?"

**Comment by jmoenig** [comment]
Yes, this is really, really bad, I'm frustrated beyond telling

**Comment by MeatPopSci** [comment]
FYI - I am seeing a CORS error in my console:

18:49:52.560 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://snap.apps.miosoft.com/SnapCloud?SESSIONGLUE=.sc1m08. (Reason: CORS header 'Access-Control-Allow-Origin' missing).1 <unknown>

You need to address this by adding a special header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by jmoenig** [comment]
The CORS error in your console only affects the error message, it's not the underlying problem. The Cloud people reverted to a stable version last night which required a short downtime, so hopefully you'll be able to log in again today.

**Comment by maryfries** [comment]
12/15/15 from a teacher: "Again today we had issues.  We can get to snap.berkeley.edu/init ok, but when trying to login we can't connect to that backend cloud server.  This seems to happen sporadically, but with probabilities as they are, there are always students that reach their frustration points.

We have flushed the cache.  When we can't save to the cloud we save to the browser.  But students use the cloud to save and share their work when turning it in."

**Comment by aidiken** [comment]
How to register a private cloud

**Comment by cycomachead** [comment]
Closing this because we haven't had big issues in a few months. 

I responded to the above question in #1276
