### ISSUE TITLE
12/15/15 - cloning broken

### ISSUE THREAD

**Issue by CameronParker** [jmoenig/Snap--Build-Your-Own-Blocks#1066]
In student project code working on 12/14, then loaded on 12/15: the block "Create a clone of" is now not working, causing the script to turn red, with the error:
Type error: Block.InitializeVariables is not a function

Please fix or provide status/eta.

thanks
Cameron

**Comment by maryfries** [comment]
Have you cleared all cached images and files? So far, all new issues seem to be coming down to that.

**Comment by CameronParker** [comment]
Clearing the cache cleared it up, thanks a bunch to all of you for the quick replies and follow up.
