### ISSUE TITLE
I can no longer save my project?

### ISSUE THREAD

**Issue by Evanforest62** [jmoenig/Snap--Build-Your-Own-Blocks#1068]
So today, I tried to save my project but I can't because it says file media exceeds over 10 MB. Since it's already so big (64000 KB overall), I need most of the music because they fit in well with the project. Anyway for me to still save my work on the project but not having to deal with the media problem? Also, I  want to know how much space my media is taking up atm. Is it possible for me to even save it anymore without taking out too much out of my project?

**Comment by jmoenig** [comment]
You can either use less music, music at a lower resolution, or use Snap to make music yourself, loop through shorter sections of music. You can also save your project without music and import the music again as you're playing it on your computer.

BUT: Giant projects with tons of music are clogging up the backend and responsible for some of the worst cloud problems we've seen lately, therefore I've decided to impose a size limit. Hey, if memory server it was your project that actually caused some of that :-)

**Comment by Evanforest62** [comment]
http://snap.berkeley.edu/snapsource/snap.html#present:Username=Evanforest62&ProjectName=The%20Heroic%20Starship%20-%20Final%20Project

**Comment by Evanforest62** [comment]
Okay, thanks for the info!

**Comment by jmoenig** [comment]
So, you can have all the code you want, there is no limit for blocks, but for media there is a 10 MB limit. With this you're not limited in your programming in any way. I'm sure 10 MB is enough for a fair amount of costumes and sound, even given the fact that Snap's base64 encoding is somewhat inflating the size of the media.

**Comment by jmoenig** [comment]
Nice project, but FOR THE LOVE OF GOD PLEASE TAKE OUT THE MUSIC!!!!!!
This project is 65 MB big!!!!!
NO WONDER THE CLOUD GOES DOWN FOR EVERYBODY!!

Who's your teacher, I WANT TO SCREAM AT THEM!!!!

Man, didn't we talk about this a week ago? We identified THIS PARTICULAR project to have been a major cause of trouble, and you saved it again without music.

[... obscenities under my breath...]

**Comment by jmoenig** [comment]
to be clear: The 10 MB only applies if you store the project in the SnapCloud. You can totally save the project on your own computer, and make it as big as you want, with all the music and sound trackts you want. But then you'll have to email it to your teacher, or share it via some other service such as Dropbox.

**Comment by brianharvey** [comment]
Jens, he's a kid.  Chill.

Evan, most likely your music is so big because of a high sample rate, so it's in super high fidelity.  If you convert to MP3 at the usual 44MHz sample rate, it'll be smaller, I'm guessing.

**Comment by jmoenig** [comment]
Sorry :-)

Nothing personal against you, @Evanforest62 , I do love your project, it's actually super awesome!

**Comment by Evanforest62** [comment]
Lol, it's okay. Btw thanks! :)

**Comment by cycomachead** [comment]
Closing this because we know the problem. 

Eventually, we will want to put a webpage / guide somewhere that discusses slimming media down, and how to do it or what to look for, as I can see these issues popping up frequently...

Here's two free sites for image compression. I don't know if there's anything we can recommed for music...
https://compressor.io
https://kraken.io

**Comment by mrinteractions2** [comment]
Why cant i save Scratch story mode exported on Snapinator!?

**Comment by cymplecy** [comment]
I would recommend asking this sort of question on the Snap! forum
https://forum.snap.berkeley.edu
