### ISSUE TITLE
It would be convenient to use github pages to run snap

### ISSUE THREAD

**Issue by xtitter** [jmoenig/Snap--Build-Your-Own-Blocks#107]
If a branch 'gh-pages' was made and kept up to date with the master (?) branch, http://jmoenig.github.io/Snap--Build-Your-Own-Blocks/snap.html would be a convenient way to view at the latest dev version.  

http://snap.berkeley.edu/run/ is intended to be more stable then master branch on github, I assume (at least, it seems that it does lag behind).

**Comment by cycomachead** [comment]
Closing an old issue. We have /snapsource/dev on s.b.e
