### ISSUE TITLE
Passing an empty list to length of causes infinite loop

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#1071]
From a recent issue see this screenshot:
![screen shot 2015-12-16 at 1 27 24 pm](https://cloud.githubusercontent.com/assets/1505907/11854455/dbd57f5a-a3f8-11e5-8990-46b2f8abc51e.png)

**Comment by jmoenig** [comment]
yeah, this isn't new in any way, and we'll introduce type checks for all list primitives anyay (already done in my dev version). I don't think any of this is urgent right now. :-)

**Comment by jmoenig** [comment]
Oh, and it doesn't cause an "infinite loop"...

**Comment by cycomachead** [comment]
> Oh, and it doesn't cause an "infinite loop"...

Well, it's more of a hang I guess, which is actually worse, IMO.

(Which is weird in a way because passing in `NaN` does actually cause an infinite loop. And `undefined - 1` is `NaN`...)
