### ISSUE TITLE
Changes coming soon?

### ISSUE THREAD

**Issue by Evanforest62** [jmoenig/Snap--Build-Your-Own-Blocks#1078]
So I know that there is a 10 MB media limit in projects now, but is it ever gonna go away anytime soon? I know that giant projects like mine are causing problems and cloud errors in Snap, but when do you guys expect to fix this problem in the future? I got several projects that I would still like to work on but can't save anymore because of the limit.

**Comment by brianharvey** [comment]
So, first of all, you can save your projects locally using "export project."  As for saving to the cloud, bear in mind that MioSoft donates their services to us, and we don't want them to have reason to regret that if we can help it.
People have talked about things like allowing uploading of projects to Google Drive and/or Dropbox, which would allow sharing if desired.  It's not way high on the priority list, but it might happen someday.
