### ISSUE TITLE
Bug breaking snap. More info inside + screens.

### ISSUE THREAD

**Issue by DirtyoHarry** [jmoenig/Snap--Build-Your-Own-Blocks#1083]
I found this bug today, while using snap, I clicked inside the white spot of the blocks on the side and then I couldn't use snap anymore without refreshing the page.
Got couple of screens here:

Now I press inside the block
![now i press inside the block](https://cloud.githubusercontent.com/assets/16405850/11965088/8818f8ac-a8f2-11e5-81cc-d82a04617310.png)

Now whatever I try to press doesn't work, just highlights because the mouse is hovering on the buttons
![whatever i try to press doesnt work, just because the mouse is hovering on the buttons](https://cloud.githubusercontent.com/assets/16405850/11965080/7ea14fae-a8f2-11e5-9bf9-7826b1d8bd79.png)

The only thing I can do is write inside the block
![the only thing i can do is write inside the block](https://cloud.githubusercontent.com/assets/16405850/11965103/acdbbaa8-a8f2-11e5-8e4e-b51e41c443a0.png)

**Comment by cycomachead** [comment]
Which version of Chrome is this? Thanks!

**Comment by cycomachead** [comment]
AH HA! This is indeed a bug! It relates to recent code to handle native clipboards.

So, it is somewhat reproduicle. You need to have some text in a block input slot selected, then try to drag that block out. Or that's what seemed to "work" for me, after a few tries.

![screen shot 2015-12-23 at 1 43 52 am](https://cloud.githubusercontent.com/assets/1505907/11974248/3d7a1a90-a917-11e5-906c-24d255f56455.png)


The error seems to be in the remove code, where it can't find `clipboardHandler`.  Other than `try/catch` I've not really found a solution.

**Comment by jmoenig** [comment]
Hmm.. I still can't reproduce this, but already I regret pulling the "hidden text" kludge.

We'll find a workaround for sure, e.g. probably a reference to ```CursorMorph >> clipboardHandler``` exists in the Morphic tree but not in the DOM tree, and we can find out whether both somehow got out of synch somewhere. But, see, this is exactly the thing about kludging around with "native" DOM stuff and with caching references for convenience. Sooner or later you'll end up bloating everything with polyfills and consistency checks and then the whole architecture becomes a big mystery that's only accessible to the initiated "high priests of a low cult".

Instead, the *Right* way would be to refuse any kludges that don't access the Clipboard programmatically through an API.

Gosh, I really hate being pressurized into this "web programming" crap. The whole idea of Morphic was to not have to deal with this shit ever.

**Comment by cycomachead** [comment]
> Instead, the Right way would be to refuse any kludges that don't access the Clipboard programmatically through an API.

We are very likely never going to get that.... And this is using a defined area of a the web API. Namely: managing a clipboard through a native text input field.

To reproduce this I quickly select some input in a block (like drag from 1 to 0 in the move block), then try to drag the block onto the stage, with the scripting area.

**Comment by jmoenig** [comment]
I don't understand how you reproduce this... No matter what I select and where I drag this to this doesn't happen to me. Can you describe the exact steps? Does it only happen online / offline?

**Comment by cycomachead** [comment]
Actually. I think I have a simple fix. We just need to `null` out `clipboardHandler` I believe.

**Comment by jmoenig** [comment]
Yeah, I already did this in my code, maybe that's why I can't reproduce it :-)

**Comment by cycomachead** [comment]
It happens online. 

The problem for me, is that this seems to require quick mouse movements. But basically I click+drag to select the input text then try to drag the block out of the palette. That's all that I realize I'm doing. But maybe there's some secret touch.....

**Comment by cycomachead** [comment]
Nope. It doesn't fix it for me. :(

I still see the error, even with that same like in the code... Wtf.

**Comment by jmoenig** [comment]
I still cannot reproduce it. Is this in Chrome?

**Comment by cycomachead** [comment]
Safari. I'll try in Chrome.

What's entirely perplexing is that manually (in the console) `null`ing out the `clipboardHandler` resolves any errors. Somehow it seems like the `clipboardHandler` is being prematurely removed from the DOM.

**Comment by jmoenig** [comment]
Wait! this is interesting: I *can* reproduce this in Chrome, but *only* when I run Snap locally. I cannot reproduce it with the online version. Can you?

**Comment by cycomachead** [comment]
Yep! I've been doing most of my testing there. 

That seems like a coincidence to me... Are you getting the same DOM errors?

**Comment by jmoenig** [comment]
sort of, I'm getting:

```Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.```

Which points to the same issue.

I bet we can't just reference DOM elements, but have to the query them each time by their fucking ids. DOM, you know...

**Comment by cycomachead** [comment]
It should work, because the element gets removed from the DOM. 

I also can't seem to reproduce this in Edgy. Which is weird since the code is almost identical...

**Comment by cycomachead** [comment]
I am entirely confused... Setting the thing to null just doesn't work sometimes.... Neither does `delete`.
![screen shot 2015-12-23 at 3 25 46 am](https://cloud.githubusercontent.com/assets/1505907/11975732/afa46310-a925-11e5-8ef0-8e33602a2e07.png)

**Comment by jmoenig** [comment]
Yeah, the DOM is evil.

**Comment by jmoenig** [comment]
Also, Edgy uses an older and maybe more stable version of Morphic text editing. I had to change many little things in Snap because users...

**Comment by jmoenig** [comment]
I think I've fixed it by iterating over document.body.children and comparing each to the clipboardHandler when removing the node. At least it doesn't happen for me anymore with this this change. But then, I had problems reliably triggering this bug in the first place.

Anyway, I'm going to push this "fix" later

**Comment by jmoenig** [comment]
Can you try it again? (I didn't yet push this version online, so you'll have to download Morphic...)

**Comment by DirtyoHarry** [comment]
it is fixed. Thanks.

**Comment by jmoenig** [comment]
@DirtyoHarry thanks for the quick test! I'll push this version online now.
