### ISSUE TITLE
Morph.fullImageClassic doesn't work for morphs with children to the left/above them

### ISSUE THREAD

**Issue by thomaswp** [jmoenig/Snap--Build-Your-Own-Blocks#1090]
Morph's `fullImageClassic()` function has a comment asking why it doesn't work for all blocks (currently [here](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/master/morphic.js#L2736)). I believe I know the answer.

The function translates the canvas using `this.bounds`, then calls `this.fullDrawOn()`, which uses `this.fullBounds()` to offset its drawing. This works fine, unless the full bounds have a different origin than the bounds, which occurs when a morph's children are above or to the left of it. I believe a few simple changes will fix the problem.

This should fix it:

```diff
 Morph.prototype.fullImageClassic = function () {
-    // why doesn't this work for all Morphs?
-    var fb = this.fullBounds(),
+    var fb = this.cachedFullBounds || this.fullBounds(), // use the cache since fullDrawOn() will
         img = newCanvas(fb.extent()),
         ctx = img.getContext('2d');
-   ctx.translate(-this.bounds.origin.x, -this.bounds.origin.y);
+   ctx.translate(-fb.origin.x, -fb.origin.y);
    this.fullDrawOn(img, fb);
    img.globalAlpha = this.alpha;
    return img;
}
```

Still needs to be tested more thoroughly, but since you only really use this function for screen captures and dragging, should be limited use cases.

P.S. Why do you have both functions in the first place? Efficiency? Seems like it makes it easier for bugs to crop up in one or the other like this.

**Comment by jmoenig** [comment]
Thanks! Just curious: Which part of Snap does this affect, where did you notice something going wrong?

**Comment by thomaswp** [comment]
I don't think it affects Snap at the moment. I'm building an add-on to snap to support hints and feedback and was adding some children to the left of a block. I noticed it wasn't rendering properly when I picked the block up and this changed seems to fix it.

**Comment by jmoenig** [comment]
Sounds interesting! I'll put your fix into Morphic.js and Snap with the next round of changes. Feel free to issue a pull-request. Again, thanks!

**Comment by thomaswp** [comment]
Ok, I filed a pull request: #1105
