### ISSUE TITLE
"When I am" block needs "released" option

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#1092]
It has "dropped" but that won't fire unless the sprite was moved.  (I realized this because I started playing with using this block for the stage, which is fun!)

**Comment by cycomachead** [comment]
Doesn't the "pressed" option still fire?

**Comment by brianharvey** [comment]
Actually, "pressed" doesn't do what I want, but "clicked" does.  Duh.  Closing...
