### ISSUE TITLE
Can't Save Images from new tab in new version of Chrome

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#1093]
We have a few weeks before this one hits users, fortunately!

In Chrome 49, items displayed in a new tab from a Blob URI can't be saved as. This is a problem, because Chrome implements the much more efficent `toBlob()` which is didn't used to and now images are exported and displayed in a new tab (correctly), but can't be saved via a save-as action.

I can fix this - we can simply revert to using data URIs in Chrome if the request is to display in a new window. 

Fortunately, this isn't super urgent. :)

**Comment by jmoenig** [comment]
Hmm... saving images from a new tab still works for me in Chrome 49.0.2610.0 canary (64-bit), but I've only tried fairly small pics (script pics, stage screen shots)...

**Comment by cycomachead** [comment]
When you save an image, do you right click on the image or the white background?

**Comment by cycomachead** [comment]
I think the change is that before, with a data URI you could use the default "Save As" which is _really_ "Save (Page) As" command, that just happened to be an image. Now with a blob URI, if I actually click on the image itself, then I get "Save Image As...". Funny that I never thought to try it as I've always used the Save "page" version... But this seems to work just fine.

**Comment by jmoenig** [comment]
Either way works for me, as does saving from Chrome's menu bar (File menu).

**Comment by jmoenig** [comment]
Mostly when I'm on a Mac I simply drag the pic out of the browser into a folder or right onto the desktop anyway. Can't do this in Windows, though.

**Comment by cycomachead** [comment]
My version is `Version 49.0.2566.0 canary (64-bit)` and this is what I see:

<img width="1440" alt="screen shot 2016-01-03 at 1 30 32 am" src="https://cloud.githubusercontent.com/assets/1505907/12078095/d4988948-b1b9-11e5-82d1-cd32ecb467b7.png">

Weird, but you can still save the file, so this isn't a huge deal.

**Comment by jmoenig** [comment]
weird, here's what I see:

<img width="460" alt="canary" src="https://cloud.githubusercontent.com/assets/2596285/12078145/a05ae89e-b207-11e5-83d5-c1e5cdb6e0dd.png">

**Comment by cycomachead** [comment]
Ah, does that URI start with `data:image/png...` and not `blob://`?

Now I'm wondering if I set some flags in my chrome settings...

**Comment by cycomachead** [comment]
AH HA! I did have a flag on "experimental canvas features" which does implement the `toBlob` method!

Well, I guess it's good to know Google's making some progress on this...but it will be a while before we really need to worry about this. :)

**Comment by liam4** [comment]
Yeah, I had this same problem!
