### ISSUE TITLE
Changing the category of a block does not update the color of the blocks in use

### ISSUE THREAD

**Issue by haritop** [jmoenig/Snap--Build-Your-Own-Blocks#1098]
Changing the block spec does.
Just in case nobody noticed it.

**Comment by cycomachead** [comment]
Yup, pretty sure this one is a regression. (Probably due to caching!)

**Comment by haritop** [comment]
You're right. This does not happen in older versions of Snap.
By the way, I think It would be very helpfull if a feature allowing batch moving of blocks between categories was added to Snap(in the palette menu for example).

**Comment by jmoenig** [comment]
Wait! I don't get it, this totally works for me.

**Comment by haritop** [comment]
I don't know.
I've test this on Firefox and Chrome, after I've cleared history on both browsers.
I did the same on issue #1099.
Anyway, your call.

**Comment by cycomachead** [comment]
This definitely happens.

Make a new block `test`, leave it grey. Drag it out to the scripting area, and then change the cateogry to Motion and click apply.

**Comment by cycomachead** [comment]
> You're right. This does not happen in older versions of Snap.

@haritop How far back did you go to see that it works? That will help narrow this down. Thanks!

**Comment by cycomachead** [comment]
Further restriction: If the command block has input, there's no problem. It's only blocks without inputs that have problems.

**Comment by jmoenig** [comment]
Ah, I was testing with a reporter, and *that* worked. So it's only happening for commands.

**Comment by haritop** [comment]
I've tested it on 4.01 and it works.

(The following are for 4.04)
Sometimes the problem appears to a reporter when nested in a custom command block.
This affects the nesting custom command  block too.
I couldn't figure out when, because i was unable to find a pattern to reproduce it.

**Comment by jmoenig** [comment]
Hmm... I've regretted that optimization when loading projects already in other places. It is almost not noticeable on "normal" computers, but more so on slower ones. But it really broke (and - as this issue shows) still breaks many other things. I'm afraid the little speed-up avoiding redundant redraws brings us isn't worth the instability this has introduced.

This particular case is a very easy fix. But I'm considering rolling back the optimization altogether, to make the code simpler, more stable and easier to maintain / debug again.
