### ISSUE TITLE
export in costume icon does not work

### ISSUE THREAD

**Issue by haritop** [jmoenig/Snap--Build-Your-Own-Blocks#1099]
Throws an error in console

**Comment by jmoenig** [comment]
works for me...

**Comment by cycomachead** [comment]
I see it. Right click from a costume in the Costumes pane.

![screen shot 2016-01-06 at 11 12 27 am](https://cloud.githubusercontent.com/assets/1505907/12152069/24f9d234-b467-11e5-98f4-d316ebda650b.png)

**Comment by cycomachead** [comment]
Yeah, this was my fault! There was an extra `.object` somehow in that call. :/

**Comment by haritop** [comment]
I've tested it on 4.01 and it works.
In 4.04 it does not happen in reporter blocks.
One special occassion is when the reporter is nested in a custom command block.
Then the problem appears in the reporter block also.
I've checked this on 4.01 and the problem appears there too.

I hope this helps.
