### ISSUE TITLE
Export summary adds blank lines to JS Function

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#1106]
From xly@scratch:

Export summary new (?) feature is useful to document a project.
But for strange reasons, when this feature is used to document one project several blank lines are added inside the JS script of blocks using Javascript Function.When reloading the project, blank lines still remain !!!???.

**Comment by brianharvey** [comment]
He's a PC user iirc.  Is the CRLF at the end of each line being treated as two ends of line?

**Comment by cycomachead** [comment]
> He's a PC user iirc. Is the CRLF at the end of each line being treated as two ends of line?

But CRLF _is_ the PC line-end encoding...so it should be fine, I think.

Could he maybe share an exported HTML file, or also give browser info? This should be reproducible.

**Comment by brianharvey** [comment]
> But CRLF is the PC line-end encoding

I know; I'm guessing that there's a bug wherein Export Summary is treating the CR as a newline and then treating the LF as another newline.  But yeah, we need to see where these blank lines are.

**Comment by brianharvey** [comment]
Here's a sample.  It doesn't happen for me (Chrome, Mac).  He's Chrome, Win10.  Note that some lines at the end aren't spread out.

![xly](https://cloud.githubusercontent.com/assets/3885074/12223925/20d7cec4-b799-11e5-9080-b6804382e6b1.png)

**Comment by cycomachead** [comment]
I see what you mean about the lines now. If that's correct I can probably fix it without Windows. Can you maybe ask him if the split by line block works correctly if he pastes that text in?


Thanks! 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment]
IIRC split by line originally failed that way on windows and got fixed.

**Comment by cycomachead** [comment]
Yeah, I fixed that. :)

So, it's in the screenshot where things get changed? Very interesting.

**Comment by jmoenig** [comment]
Trying to look into this, but my Windows Stick PC decided it wanted to install an update and now no longer finds its wifi adapter, so I can neither connect to s.b.e nor to my dropbox files. Did I mention I hate Windows?

**Comment by jmoenig** [comment]
... Gosh, reverting to an earlier Windows build lets me connect to the internet again. Oh. My. God. *Somebody* is having an even bigger customer support issue than Snap! :-)

**Comment by jmoenig** [comment]
Okay, I got Snap! back up and running on my Windows 10 PC, but not matter what I try I cannot reproduce this. first I checked with an existing project that has some JS functions - nothing, then I edited the JS functions in Windows - again nothing, then I copied and pasted JS code into the JS function block in Windows - again, exporting the project summary, saving the project. Re-loading the project, again exporting the summary etc. didn't change anything for me.

I believe Xavier that this is happening to him, and it does sound like a line delimiter issue, but not matter what I try I can't reproduce it on Windows.

**Comment by J0SLAN** [comment]
I know the problem! Copy/pasting newline chars causes weirdness. There's an extra char at the end of each line that duplicates the newlines. I have this problem whenever I copy my functions over for mapping.

**Comment by brianharvey** [comment]
We have another report of this in #1128 (which I'm closing as duplicate).  We also understand the bug:  Both the CR and the LF are being treated as newlines when pasted into Snap!.  I don't understand why Jens doesn't observe this -- maybe he fixed it in the dev version in his sleep?  :-)

**Comment by cycomachead** [comment]
Well, it's a windows thing, so I'm guessing that we just need specific
Windows + browser versions.

I also don't know anything about the windows clipboard manager, but I
suspect there's a chance that some apps read / write to it differently, so
for all we know, it could be dependent on the source of the pasted text...

So, anyone who can reproduce this, it would be helpful to have versions of
Windows / Browser, and the Source app the text came from.
ᐧ

--
Michael Ball | michaelball.co

**Comment by brianharvey** [comment]
I believe the right thing to do is just filter out CR (control-M) characters whenever pasting into Snap! in any context.  It'll fix the Windows problem and not break anything else.

**Comment by jmoenig** [comment]
I'm not convinced it's a Windows issue. I cannot reproduce this in Windows myself, and I am trying hard to.

**Comment by brianharvey** [comment]
Maybe it's Windows-plus-some-particular-browser?

**Comment by J0SLAN** [comment]
I'm on Windows 10 and Chrome for the browser. It happens when I copy/paste from a non-textbox area. I save, reload, and there's the extra lines.

**Comment by J0SLAN** [comment]
It's not specific to the JS block, and also happens with non-newline showing text inputs (You just don't notice it).

**Comment by ToonTalk** [comment]
I've been suffering from this as well.

I tried to reproduce it by making a simple JS function and when I repeatedly saved to the browser's local storage and loaded it nothing went wrong. However, when I saved to the cloud and restored I found new blank lines.

I exported the project before and after the new lines appeared and saw &#xD; became &#xD;&#xD;

Windows 7.

**Comment by brianharvey** [comment]
Uh oh, if saving to localstore works but saving to cloud doesn't, that sounds like a back end bug (and still Windows-specific).  Will enquire.

**Comment by jupiterio** [comment]
@brianharvey Yep, Jens made an issue over on #1455

**Comment by brianharvey** [comment]
Ah, okay, I'm declaring this a duplicate, because the other one has Jens's experiment that reproduces the problem.
