### ISSUE TITLE
Snap web server serving up 403 forbidden

### ISSUE THREAD

**Issue by inthemedium** [jmoenig/Snap--Build-Your-Own-Blocks#1119]
Here's the whole message

Forbidden

You don't have permission to access / on this server.

**Comment by inthemedium** [comment]
(If you're looking for a backup, this works: http://bjc.edc.org/snapsource/snap.html)

**Comment by liam4** [comment]
Nice job finding the backup, I was looking for it earlier.

I mentioned this on the Snap<em>!</em> user discussion page [here](https://scratch.mit.edu/discuss/post/1757208/).

**Comment by cycomachead** [comment]
It should be up now, let me know if things are borked.

**Comment by show0k** [comment]
Yesterday Snap! was offline too for at least some minutes. The homepage image is slow to load. Having a high uptime is very hard ; if Berkeley can offer it, why don't you move your hosting to github pages or dropbox any other hosting compagny with a very good SLA and CDN ?  
You have a simple static website, and you can keep your domain with a simple CNAME dns configuration.
