### ISSUE TITLE
Pasted Newline Characters Multiply

### ISSUE THREAD

**Issue by J0SLAN** [jmoenig/Snap--Build-Your-Own-Blocks#1128]
Sometimes, when you paste text into a block input that shows newlines (Like the JS block), and the thing you pasted has newline characters, after saving and reopening a project the newlines multiply themselves. Looking at the end of each line shows a random space character, and deleting that character stops the multiplying. I've only been able to reproduce this myself on my Win10 desktop.

**Comment by J0SLAN** [comment]
Turns out it happens even without copy/pasting.

**Comment by jmoenig** [comment]
this must be specific to some platform I don't use...

**Comment by liam4** [comment]
Not an issue for me - Chrome 50 on OS X.

**Comment by J0SLAN** [comment]
Yeah, I'm pretty sure it's only on Windows. When I get home I'll check if it depends on the browser. I can't get it to happen on my Chromebook.

**Comment by brianharvey** [comment]
Duplicate of #1106.  Closing.
