### ISSUE TITLE
"Make a block"  should check for text  when  "OK" is clicked

### ISSUE THREAD

**Issue by kbakalar** [jmoenig/Snap--Build-Your-Own-Blocks#1131]
If the user opens the Make a Block dialog and then clicks "OK" without entering any text, the dialog should remain open and they should be reminded to enter the text.  As currently written, if the text is absent then "OK" and "Cancel" buttons have identical functions.

**Comment by cycomachead** [comment]
Yeah, I agree this aspect is confusing.

Another solution is to simply make "OK" not be clickable, but this requires #649

**Comment by kbakalar** [comment]
That would do as well. But it might not be clear to the user why the OK box is unclickable.  A message saying why an OK click is bad would be more helpful.

**Comment by bobbybee** [comment]
Currently working on this.

**Comment by ilayraz** [comment]
I am new to this project. I have been working on this bug for the last week, almost finished. Should I switch to another bug?

**Comment by brianharvey** [comment]
Oh.  If you're almost finished, you might as well finish and file a pull request.  I should explain, though, that Jens is very, very fussy about what code he pulls, and also is on vacation for a few weeks, so nothing will happen about your PR right away, and in the end it might be rejected.  I am saying this not having seen your code, so don't be insulted; I'd say it to anyone.

Do we know you?  How did you come to be interested in contributing to Snap<i>!</i>?

**Comment by ilayraz** [comment]
I was introduced to you through Sean Morris. You directed me to the issue tracker. I have been learning the code for a bit and started picking at this issue some time ago.

**Comment by brianharvey** [comment]
Oh!  Right, I'm sorry, I remember about you, of course, but had forgotten your name.  Mea culpa.  Carry on!

**Comment by kbakalar** [comment]
I have installed ilayraz's fix. It is just what I suggested above. But now I think I was wrong and cycomachead is right: The pop-up is too noisy.  Instead, the "OK" button should be grayed out. A gray "OK" is unambiguous in this context.
