### ISSUE TITLE
Unicode in a variable can prevent saving to cloud; unicode emoji parsing error.

### ISSUE THREAD

**Issue by garthz** [jmoenig/Snap--Build-Your-Own-Blocks#1136]
I have noted two Unicode-related bugs:

Using the http:// block, I fetched Unicode data which included U+1F604, which is an emoji &#128516
denoted "SMILING FACE WITH OPEN MOUTH AND SMILING EYES".  However, the 
unicode decoding block reports it as code point 55357.

More problematically, a sketch with code point 55357 stored in a variable cannot be saved to cloud storage.  Here is a simple test case which creates a single 55357 character and stores it in a global variable:

![unicode-test-case](https://cloud.githubusercontent.com/assets/1271564/13017405/017be098-d192-11e5-892d-fb8b8b4da1a4.png)

When trying to save to a file on my cloud account, the following error dialog appears:

![cloud-error](https://cloud.githubusercontent.com/assets/1271564/13017435/337d7124-d192-11e5-9faa-97cc83ea322c.png)

Exporting the project also fails, however, saving locally to browser storage works.

**Comment by cycomachead** [comment]
Yep... I can see this too.

So, this is a UTF-16 character, but URIs are only UTF-8, so we'd need to do some special conversion, and I don't know if there's a standard practice for URI encoding UTF-16 data?

Local storage works because local storage actually uses UTF-16.

**Comment by garthz** [comment]
I can add another observation which might help.  

The UTF-8 encoding for the U+1F604 example is f0 9f 98 84.

My comment before was not precise; it appears that the http:// operator **is** correctly decoding this character to UTF-16; this requires two code units so it appears in UTF-16 as 0xD83D, 0xDE04 (decimal 55357, 56836).  Both the 'split by letter' and the 'letter # of string' operators are treating these code units as separate letters.

So to focus my concern: since there is a valid UTF-8 encoding for this UTF-16 sequence, perhaps something can be fixed in the UTF-8 conversion to avoid the problem with saving files.

Of much lesser concern is that invalid UTF-16 strings can be constructed by making individual code units in the 0xD8000-0xDFFF range.

For what it's worth, I did a test in Python and it behaves similarly; in my installation, Unicode strings are UTF-16 and this particular character also appears to have length 2.  However, Python **can** correctly encode it as UTF-8 (the four-byte sequence f0 9f 98 84).

**Comment by bromagosa** [comment]
This is also fixed in the new cloud :)
