### ISSUE TITLE
Tables Need Testing In Older Browsers

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#1149]
As far as I understand, `String::repeat` is only available in the most recent browsers...

https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/master/tables.js#L150

Since these are off by default, I don't expect we will see much of a problem for now, but we're limiting ourselves to Chrome < 10 months, Safari < 5 months, and potentially no IE.

**Comment by jmoenig** [comment]
It's always good to test things on older browsers, but let's not forget that String::repeat is officially standard now, and Snap relies on other ES6 features such as Map anyway (hence the minimum requirements we specified elsewhere). But you're right, maybe we should replace it by a more defensive code. I'm open to a PR :-)

**Comment by cycomachead** [comment]
`Map` at least works in IE, and lots of things are in ES6 still aren't supported....c'mon Tail Recursion!! ;-)

**Comment by cycomachead** [comment]
Well it's 2 years later so there's more support now. That's one way to handle browser testing. :D
