### ISSUE TITLE
Service:saveProject Error

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1155]
I've gotten this a few times today...
![image](https://cloud.githubusercontent.com/assets/6549787/13435944/da9ffb9a-dfaa-11e5-8f81-dcd574b2d5fd.png)

**Comment by jmoenig** [comment]
this looks like the cloud backend server hit an exception. I'm sure Bert and Jordan are fixing it...
