### ISSUE TITLE
Need assistance with a student's  SNAP cloud account

### ISSUE THREAD

**Issue by sthembi** [jmoenig/Snap--Build-Your-Own-Blocks#1158]
A student I am working with has attempted to reset her password twice. Each time after resetting and using the assigned new password, she receives a message that the password is invalid. 

We have double checked the password each time, and we have tried to login through different computers with no success of logging in. 

Is there a way to check a SNAP cloud account for problems ?

**Comment by bertbarabas** [comment]
Email her login to snapcloud@miosoft.com and we'll check it out.
