### ISSUE TITLE
Keyboard editing not finding capitalized variables

### ISSUE THREAD

**Issue by brollb** [jmoenig/Snap--Build-Your-Own-Blocks#1163]
When I am using the keyboard editing shortcuts, it doesn't find my variables using all caps.

![snap_caps_bug](https://cloud.githubusercontent.com/assets/4982789/13650523/b2f80b0a-e608-11e5-8c95-c6f4f245c00f.png)

**Comment by cycomachead** [comment]
Do you have `test` as a global variable too?

I thought, perhaps wrongly, that to insert a script var you were supposed to tap `space` and then get a little selection menu.

**Comment by brollb** [comment]
No, I believe I only defined the script variables in there screenshot

**Comment by jmoenig** [comment]
Thanks, good catch, Brian!

**Comment by jmoenig** [comment]
I've just fixed this for the next (upcoming minor release).

**Comment by brollb** [comment]
Awesome - thanks!
