### ISSUE TITLE
I'm not sure where to put typos in documents

### ISSUE THREAD

**Issue by towerofnix** [jmoenig/Snap--Build-Your-Own-Blocks#1166]
But on page 3 of the Linked Lists document it says "Snap's hybrid lists" when it should probably say "Snaps hybrid lists" (or even "Snap_!_s hybrid lists").

Pretty interesting document! I need to make an index of all the documents related to Snap_!_ that are written somewhere..

**Comment by jmoenig** [comment]
thanks!

**Comment by towerofnix** [comment]
This isn't really an issue; either way it's presently "Snap's hybrid lists", which *does* read well enough (certainly better than "Snaps hybrid lists"; I'm not sure why I suggested that..?).
