### ISSUE TITLE
Snap! site says current version is 4.0.5

### ISSUE THREAD

**Issue by liam4** [jmoenig/Snap--Build-Your-Own-Blocks#1169]
I always feel the need to pester you about this.. :)

On the website:
![website](https://cloud.githubusercontent.com/assets/9948030/13899362/18784584-edcb-11e5-8391-eebbcc3081da.png)

In the editor:
![editor](https://cloud.githubusercontent.com/assets/9948030/13899363/1a4dc3c0-edcb-11e5-9e0f-87b724d69191.png)

**Comment by brianharvey** [comment]
Fixed, thank you.  @jmoenig is the version number in some easily accessible place in the repo?  Like, you know, snapsource/version.txt or something, where it could be read into the web page instead of Liam having to remind me every time?

**Comment by jmoenig** [comment]
not in the code. Well, there is, in gui.js, but not separately (and there isn't going to be a txt file either). But on Github we have releases that show the current release tag. Also, we could just say "v4.0" on the website, that'll be true for a little longer :-)

Thanks for updating, Brian!

**Comment by cycomachead** [comment]
I'm a broken record too but there are tools for this: 
https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/releases
