### ISSUE TITLE
fill region paint tool crash

### ISSUE THREAD

**Issue by oceank2** [jmoenig/Snap--Build-Your-Own-Blocks#1170]
each time i try to use fill region tool snap crashed. I use Google Chrome

**Comment by cycomachead** [comment]
Are you using Snap<em>!</em> 'offline' from a downloaded file or from snap.berkeley.edu?

**Comment by oceank2** [comment]
from snap.berkeley.edu. But I just tried it two minustes ago and it seems to work fine know !
and yet i used to try it a couple of day ago and it didn't work.
Do you work on this issue today ?

Best regards

C

**Comment by oceank2** [comment]
Sorry, but i have problem again with fill region.
I think it happens when i click with the fill tool several times on a region
See the video [](https://youtu.be/aGIV0jkdVME)

**Comment by oceank2** [comment]
has any work been done on this
