### ISSUE TITLE
I used cloud to storage my works but I can't find them

### ISSUE THREAD

**Issue by pivari** [jmoenig/Snap--Build-Your-Own-Blocks#1171]
Hello,

I used cloud to storage my works but I can't find them.
My user is pivari.
What's the problem?

Fabrizio

**Comment by pivari** [comment]
I forgot I've not to search in the cloud but in file :(
Sorry for the post.

**Comment by bb010g** [comment]
If your problem has been resolved, please click the "Close Issue" button.
