### ISSUE TITLE
It is not possible to modify the width of the control window

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#1175]
So you do not see what is written on a block when they are bigger than the initial size.

![capture d ecran 2016-04-01 a 21 27 58](https://cloud.githubusercontent.com/assets/17542520/14214956/0e99d236-f851-11e5-8776-911b08bf64d1.png)

**Comment by cycomachead** [comment]
Unfortunately not yet, but it might be on the list. #97
