### ISSUE TITLE
Snap no longer opening projects on bjc.edc.org 

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1177]
initial report: https://piazza.com/class/h8yx482idav52y?cid=732
"When I click on the link to open the U4L3 project file, it gives me a message that says "unable to retrieve project." Please help, my kiddos will be up to that part in class tomorrow!
"The link is: http://snap.berkeley.edu/snapsource/snap.html#open:http://bjc.edc.org/bjc-r/prog/4-internet/U4L3-BigNumbers.xml "

This seems to be pervasive.

For example, projects in other labs don't open either: 
http://bjc.edc.org/bjc-r/cur/programming/3-lists/1-introduction-to-lists/2-exploring-list-processing.html?topic=nyc_bjc%2F3-lists.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment
http://bjc.edc.org/bjc-r/cur/programming/4-internet/1-web-data/3-read-web.html?topic=nyc_bjc%2F4-internet.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment

**Comment by brianharvey** [comment]
... but, as Mary discovered, http://**bjc.edc.org**/snapsource/snap.html#open:... does work.  So either it's a recent change not yet mirrored at EDC or it's a CORS problem.

**Comment by jmoenig** [comment]
Allow me to remind you that it's the *EDC* server that needs to allow its resources to be accessed by other websites such as Berkeley's, not Snap. CORS works that way...

**Comment by cycomachead** [comment]
It's a problem with `.htaccess` on bjc.edc.org

It needs the line
```
Header set Access-Control-Allow-Origin "*"
```
http://enable-cors.org/server_apache.html

The reason it works for bjc.edc.org snap is because the domains are the same and there's no conflict.

**Comment by brianharvey** [comment]
Ah, but you're assuming we have reasonable sysadmins who run Apache.  EDC is a Microsoft shop.  :(  But anyway, if it's EDC's fault I can work on it from here.  (Btw, Jens, I know how CORS works -- I suggested two possible explanations, one of which would be a Snap! problem and the other an EDC problem.  Glad to know which... :-) )

The thing is, it worked before yesterday.

**Comment by cycomachead** [comment]
I'm guessing they did something? It seems to be working now:
```
Michael at Yosemite-Pro in ~
👉 curl -I http://bjc.edc.org/bjc-r/prog/source/sys-blocks.xml
HTTP/1.1 200 OK
Date: Tue, 05 Apr 2016 19:14:28 GMT
Server: Apache/2.4.7 (Unix) OpenSSL/1.0.1e-fips
Last-Modified: Mon, 25 Jan 2016 18:00:45 GMT
ETag: "32eb-52a2c59148d40"
Accept-Ranges: bytes
Content-Length: 13035
Vary: Accept-Encoding,User-Agent
Access-Control-Allow-Origin: *
Content-Type: text/xml
```
