### ISSUE TITLE
using snapp to create standalone files is broken

### ISSUE THREAD

**Issue by JSJBDEV** [jmoenig/Snap--Build-Your-Own-Blocks#1178]
I am not Entirely sure if this is a problem from snap! or citilab's snapp! but I appear not to be able to create any standalone file at all using my exported XML. Please may someone test this with another XML file so I can see if it is just an issue for me (if so, please may someone help me with the file) or if I should try building it on my own website, or any alternative that may fix this
thanks, 
~Acr0

**Comment by brianharvey** [comment]
What OS are you using?  And what error message do you get?  Thanks.

**Comment by JSJBDEV** [comment]
windows 10, google chrome (I have set my target os to 64 bit 32 bit and the same in linux) 
"sorry, something went wrong server-side :( try again later!"

**Comment by bromagosa** [comment]
This must be something on our end, sorry about that!

A couple weeks ago the server went down and I manually started it, but I must have missed something... I'll check this tomorrow!

**Comment by JSJBDEV** [comment]
thank you very much :) much appreciated!

**Comment by bromagosa** [comment]
Is is still not working? I tried the Gnu/Linux 64 version and it did work fine.

If it is not, could you please share your Snap! project so I can take a look?

**Comment by jmoenig** [comment]
Hi Bernat, I've just now again tried the Mac version, and it's working like a charm.
Thanks!

**Comment by JSJBDEV** [comment]
it still appears to not be working for me, How should i send you the file?

there is the possibility that there are bits of my project that snapp doesnt recognise bearingin mind this has been through scratch 2, explore scratcht 2 the snap (I could find certain thigns that i needed)

**Comment by JSJBDEV** [comment]
I've just tried compiling a test file and it worked. I can share the project or I could just send the XML as the project appears to be breaking, rationally I think that there may be some code that snapp can't process and that's why its throwing the error

**Comment by JSJBDEV** [comment]
project share as BED by Acr0

**Comment by jmoenig** [comment]
Hi @JSJBDEV I can open and run this project in Snap (nice project, btw!). At first sight it appears to work fine, but maybe I just didn't get to the part where something breaks yet :-)

**Comment by JSJBDEV** [comment]
Hi @jmoenig Thank you very much, I have been editing this in snap for some time now, the problem does not lie with it working in snap (I know it does I've tried it on 2 OS's) but creating a standalone executable with snapp, the issue now is  my project isn't liked by the citilab servers 9serverside error), which I have a feeling is because it was imported with snapin8r after coming from scratch 2. There may be something wrong with my XML if someone would like to take a look at it I cans end it to them thank you for your help

**Comment by djdolphin** [comment]
Maybe it's [this bug mentioned in the Snapp source code](https://github.com/Rydion/Snapp/blob/master/web_service.js#L432)? The project seems to be pretty large, and when I ran Snapp locally, the log made it past "xml validated" and stopped at "reduced dir added":
````
starting server
listening on port 80
start post
    validations completed
    xml validated
    user preferences obtained
    zippedNWPackage created
    zippedResult created
    attachment set
    package created
    icon added
    reduced gui added
    reduced dir added
````

**Comment by JSJBDEV** [comment]
Damn so close to the end as well! Thank you @djdolphin (sorry for suspecting snapin8r) so this would make sense whith that bug (the project isn't even close to be finished any way) although locally it does look like it gets past that bit. This seems like the only cause, now if it is indeed the archiver, would it work if it was another archive type (like 7z or rar) or if it was running on another program, (I don't really know the difficulty but I could try making a clone in Python.)
Thanks for the help!

**Comment by bromagosa** [comment]
Sorry, ultra-busy here...

I'm roping @Rydion into the conversation, he's the author of Snapp! and may probably know what's going on. Otherwise I'll try to debug this next week myself, although I'm not familiar with the codebase.

One thing that comes to mind is that this project may be using a new Snap! feature that was not present when Snapp! was built.

**Comment by JSJBDEV** [comment]
Thank you very much.  I could be a feature that isn't present but it could also be this archiver bug. Thanks anyway

**Comment by Rydion** [comment]
Hi, so things have been pretty crazy on my end since I finished* Snapp! so I haven't been able to dedicate much time to it, but I'll try to take a look at this issue next week. It's very likely to be an issue with the bug that @djdolphin pointed out. I'll leave a message here once I know what's going on. Sorry for the inconvenience.

*There's still a lot that can be done

**Comment by JSJBDEV** [comment]
thank you very much (all of you!)

**Comment by Rydion** [comment]
Hi, so I took a look at it (nice project btw @JSJBDEV) and as expected the problem is the aforementioned archiver bug. It will take some time to fix so I won't be able to get it done until this weekend.

**Comment by JSJBDEV** [comment]
thank you very much @Rydion some people have questioned my choice of programming language but i think snap is incredibly good at what it does, and has just enough IO for me. thank you for helping!

**Comment by Rydion** [comment]
Hi, good news! I was able to get rid of the bug that was plaguing Snapp! and updated the version hosted at http://snapp.citilab.eu/. I tested it with your project (@JSJBDEV) and everything seems fine, I could generate the .exe and execute it just fine (although because of how big the project is, it takes a few seconds until it loads and starts).
If you find any other issues just let me know.

**Comment by JSJBDEV** [comment]
Thank you so much!

**Comment by bromagosa** [comment]
Thank you @Rydion! :)
