### ISSUE TITLE
Could not login from iPad.

### ISSUE THREAD

**Issue by technosalon** [jmoenig/Snap--Build-Your-Own-Blocks#1181]
Hello, I could not login and even sign in from iPad, and always have seen the **sad** image below:
![image](https://cloud.githubusercontent.com/assets/18400681/14432045/61a66512-0043-11e6-97dc-cc8e7facc31e.jpeg)

The weird thing is that I could sign and login from my laptop under the same home wifi env, and this issue on not being able to connect to https has been the very first time for my iPad.

Is there anybody who have a solution ? I would be very happy to play around Snap on my bed with iPad. Thanks in advance.

**Comment by jmoenig** [comment]
Thanks for the report. I can confirm this issue, something appears to be wrong on the backend side. We're investigating...

**Comment by technosalon** [comment]
Thank you for your swift responding, Jens. Hope our server would fix her mood...

**Comment by jiunweic** [comment]
Any update on this? We have a number of students affected in our classroom. For some reason, on one of our PCs, IE works but Firefox doesn't. On other PCs, no browsers seem to work. Very strange.

**Comment by jiunweic** [comment]
I think I know what the problem is. If you go to https://snap.apps.miosoft.com/ in Firefox, you'll see a warning that the site has an invalid security certification. The issuer certificate is unknown. I'm guessing that's why the connection is sometimes failing (some browsers may not care about this issue, while others do).

**Comment by technosalon** [comment]
Thank you very much indeed, jiunweic. Your advice just has solved mine. Once the unknown certification has been "trusted", I could sign in! even from iPad' safari. When we open the application page(http://snap.berkeley.edu/snapsource/snap.html) from the start page(http://snap.berkeley.edu), we never seen the warning window of "unknown certification", so we cannot notice that issue. Many thanks!

**Comment by jmoenig** [comment]
Wow. thanks guys!!
