### ISSUE TITLE
snap not saving correctly

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1182]
I was editing a script, saved with the block editor open, selected "new" from the file menu, and clicked "yes (replace)" but the block editor didn't go away. Surprised, I closed it only to find that I was, in fact, in a  new file. But when I reopened my original file, the work I had tried to save had not been saved. (Thank goodness I had taken a screenshot!) I'm definitely sure I saved.

**Comment by jmoenig** [comment]
unless you accept or "apply" the block editor changes don't take effect and hence do not get saved with the project.
The block editor staying open is a known misfeature / bug that I'll address once I've dealt with the "right" way to work around the misfeature part :-)
