### ISSUE TITLE
Continuations act different from normal commands, but look the same

### ISSUE THREAD

**Issue by josephcsible** [jmoenig/Snap--Build-Your-Own-Blocks#1186]
Continuations behave as if they end with a stop block, but when a variable with a continuation is viewed, it looks identical to any other variable with a command. This seems very confusing, especially since it isn't documented anywhere. Here's an example:
![snapshot30](https://cloud.githubusercontent.com/assets/16061266/14687796/52fac046-070d-11e6-96e0-9d5887f16a12.png)
The values of the "cont" and the "turn" variables look identical, but the say command after "run turn" is executed and the say command after "run cont" is not, and there's no way to know this would happen other than running them or looking at where the variables were set from.

**Comment by brianharvey** [comment]
This behavior *is* documented in the reference manual.  I agree that everything about continuations is a little counterintuitive, and it's not "as if they end with a STOP block" but something much harder to put in the visual representation.  Mostly we don't expect users to use these blocks directly; we use them to implement CATCH and THROW in the Tools library.  (And so I can claim among programming-language people that Snap<i>!</i> is really Scheme.)
