### ISSUE TITLE
Deleting Clones From a Reporter?

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#1199]
Let's say we create a `clone` reporter like in BYOB, how would we go about deleting a clone that we have stored in memory? 

![clones](https://cloud.githubusercontent.com/assets/1505907/14964399/cfd18d2c-105c-11e6-9210-ffe2de7e522b.png)

**Comment by jmoenig** [comment]
TELL (clone) TO
  DELETE (this clone)

make sense?

**Comment by jmoenig** [comment]
Check the examples from the release notes (Oh, you didn't get them, because this morning all my emails to UC Berkeley bounced). Hmm... check the examples in the pdf in the release, there's tons of deleting clones likes this in there.

**Comment by cycomachead** [comment]
Yeah, I think I realized that 5 minutes after. 

For @brianharvey Can we have a clones library for some of the stuff like BYOB? 
Also can we now change ask and tell to have sprite icons? :)

**Comment by jmoenig** [comment]
Let's not change ASK and TELL, because you can still just type sprite names into them, which is actually really nice sometimes when you already know who you want to address

**Comment by cycomachead** [comment]
> Let's not change ASK and TELL, because you can still just type sprite names into them, which is actually really nice sometimes when you already know who you want to address

Yeah, I guess that's true. I always found the sprite icon really intuitive for what goes in the slot. (Though I guess the word "Sprite" is too, it's just not as cute.)

**Comment by brianharvey** [comment]
What do you think we need in a clone library, other than ASK and TELL?

**Comment by liam4** [comment]
DELETE CLONE (object), and maybe DELETE CLONES OF (object)?

**Comment by cycomachead** [comment]
I was thinking like the clone reporter and maybe a delete clone clone command that has a parameter.
2 blocks doesn't really make a library but I know that many TAs have found the reporter based cloning easier to grasp so I'd like to give that to students at some point. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment]
Oh.  I guess; I kind of think of the reporter as what should be the primitive!  But, yeah, there should be a MYSELF reporter and you could just say DELETE (MYSELF).
