### ISSUE TITLE
Script pic with result not working

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1201]
A teacher caught this: https://piazza.com/class/i7hy3udaukx6su?cid=209

It also does not work for me on Chrome OSX.

It was actually shift-click, right?

**Comment by cycomachead** [comment]
There should be a little popup which asks them to open a new window?

**Comment by brianharvey** [comment]
I replied to the Piazza post telling him to let go of shift and control before clicking the menu item.  This is a minor UI bug that we know about and will get to eventually.

**Comment by brianharvey** [comment]
@cycomachead Huh?  Not for me, it just opens a new tab by itself.

**Comment by maryfries** [comment]
Ok, it's fine for me. Brian straightened me out. Thanks. Sorry. :)

**Comment by cycomachead** [comment]
> @cycomachead Huh? Not for me, it just opens a new tab by itself.

It's probably that the first time you clicked on it, you allowed the domain to open popups. Or maybe you don't have a popup block enabled? 

For reference, this feature still doesn't work on Safari because the popup blocker just dismisses the request for a popup and doesn't even ask the user.

**Comment by brianharvey** [comment]
Interesting.  Maybe I did whitelist s.b.e for popups, but I never think of a new tab as a "popup"; those are new tiny windows. :-)
