### ISSUE TITLE
Snap! site says current version is 4.0.8.2, not 4.0.8.3

### ISSUE THREAD

**Issue by liam4** [jmoenig/Snap--Build-Your-Own-Blocks#1205]
So.. yes.

![](https://cloud.githubusercontent.com/assets/9948030/15011848/73400010-11ca-11e6-9da9-31c3d4660810.png)

![](https://cloud.githubusercontent.com/assets/9948030/15011847/733fe148-11ca-11e6-95a8-6b419dbfcc5c.png)

**Comment by jmoenig** [comment]
Wait! that even is going to change later today to 4.0.7.1 :-)

**Comment by liam4** [comment]
Have we ever had a four-part version number before? :P

**Comment by jmoenig** [comment]
Not officially, although we did have very many updates in between releases. I think the idea is to call it a new release whenever we actually update the official website, so that you can download the latest release on Github to get the same code. But yes, this will be a novelty :-)

**Comment by brianharvey** [comment]
Sigh.  Thank you, Liam.  Someday I'll remember that the web site has the version number by myself.  :)  Or Jens will edit the page when he uploads a new version number...

**Comment by jmoenig** [comment]
I'm starting to re-think (and abandon) my opposition of placing the current version number into a separate  little "release" document, so we can have a script that just reads that...

**Comment by jmoenig** [comment]
... that "release document" could be the main ```snap.html``` page itself...

**Comment by brianharvey** [comment]
I'd prefer to keep the version number in a separate file that we can include, so we don't have to put all of snap.html in the repo.  Right now the repo is just the snapsource subdirectory.

**Comment by jmoenig** [comment]
Oh, I meant just the actual html file named snap.html, which is very tiny. We might be misunderstanding each other (?)

**Comment by brianharvey** [comment]
Oh, right, we are.  I'm thinking about index.html one level up from 
there.  I need to import the version number into that so I don't keep 
getting bug reports from Liam.  :-)  Easiest thing would be just a text 
file that can be included without processing.

**Comment by liam4** [comment]
Looks like it's fixed.. should we close the issue?

(The nice thing is you can still talk on closed issues.)

**Comment by cycomachead** [comment]
> Oh, right, we are.  I'm thinking about index.html one level up from
> there.  I need to import the version number into that so I don't keep
> getting bug reports from Liam.  :-)  Easiest thing would be just a text
> file that can be included without processing.

No....the easiest thing to do is pull in JSON from the Github releases page. 😀 

Then we have a link to any documents / notes etc.

Hacky example:
```js
JSON.parse(getURL('https://api.github.com/repos/jmoenig/Snap--Build-Your-Own-Blocks/releases'))[0].tag_name
```
returns the current version 4.0.7.1

**Comment by cycomachead** [comment]
> Not officially, although we did have very many updates in between releases. I think the idea is to call it a new release whenever we actually update the official website, so that you can download the latest release on Github to get the same code. But yes, this will be a novelty :-)

Yes, please. New separate, distinct notes for whenever the website version changes. They will hopefully also make dealing with caching problems easier.

---

Even using Gitub duplicates the version twice.... Once in gui.js and one on Github, but that seems pretty manageable overall. - since Github releases give us a lot of benefits and a nice way to point to a more human friendly changelog.

**Comment by brianharvey** [comment]
@liam4 Nah, we'll let whoever actually implements this (including updating index.html) close the issue.

**Comment by cycomachead** [comment]
I may actually have someone get to this in a few weeks. :)

**Comment by liam4** [comment]
Again, 4.0.7.1 ≠ 4.0.7.2!

**Comment by brianharvey** [comment]
Thank you, Liam.  Fixed.

**Comment by liam4** [comment]
4.0.8.2 isn't 4.0.8.3. :)

**Comment by brianharvey** [comment]
Yeah, yeah.

**Comment by liam4** [comment]
Whoops.

![Site](https://cloud.githubusercontent.com/assets/9948030/17277095/22bda502-5711-11e6-8123-c062f8c1f1c4.png)

![Snap](https://cloud.githubusercontent.com/assets/9948030/17277094/22b5b8ec-5711-11e6-9bcd-edcb3d7c7edc.png)

**Comment by liam4** [comment]
Bump again for 4.0.8.4 ≠ 4.0.8.6.

**Comment by liam4** [comment]
And here's another quick bump, 4.0.8.6 ≠ 4.0.8.7.
