### ISSUE TITLE
Questions regarding how snap works

### ISSUE THREAD

**Issue by JSJBDEV** [jmoenig/Snap--Build-Your-Own-Blocks#1221]
Hello again!
this isn't necessarily an issue but i thought it would probably be the best place to put this question
so:
me and a friend were wondering if there is anyway to compile the project to pure java script as in run the project on a website in a browser (so basically in presentation mode) 
i have noticed that the whole of snap runs on my phone (so has to be java script really)
this would also help with "productivity" as programs could then be externally compiled to anything that has a browser
and it can be a web app - bonus!
thank you again for your time

**Comment by brianharvey** [comment]
Projects can already be web apps by running them in Snap<i>!</i> in a browser.  But the feature you want is called "codification."  You can specify a text translation for each block, and then translate a script to whatever language you want.  If you do File>Open>Examples>Codification, you can see a project with translations into three different programming languages.

**Comment by JSJBDEV** [comment]
Thank you very much I will try this!
