### ISSUE TITLE
Resizeable Blocks Palette

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#1222]
Hello,

Could it be possible to resize window like that ?

![capture du 2016-05-20 16 46 44](https://cloud.githubusercontent.com/assets/17542520/15428201/ff0fe37a-1eaa-11e6-9e46-6a89a18e23ed.png)

It would be very nice because when I zoom blocks, students often do not see what I want to drag in the script space.

Is it possible to have it for the 14th of june ???
Thanks a lot.

**Comment by cycomachead** [comment]
Yes, others have asked for it for a while, but Jens has concerns about performance. In the meantime, this one is active under #239

**Comment by cycomachead** [comment]
I'll reopen this since #239 was closed...

**Comment by hasso** [comment]
As Estonian texts on blocks are often longer than English ones, I'd like to see it as well.

**Comment by dekrain** [comment]
It;s actualy added, so anybody should close it

**Comment by cycomachead** [comment]
Fixed with 2692f1d4e5c791b9839e700a5c011ddefe63bfe5
