### ISSUE TITLE
Can't right click blocks with error outlines

### ISSUE THREAD

**Issue by quat1024** [jmoenig/Snap--Build-Your-Own-Blocks#1223]
Somewhat annoying when trying to debug a block.

1. Make a block that creates an error in some way (easy way - report "all but first of [null]")
2. Run the block, so it gets a red outline
3. Try to right click the block - no context menu

I want to right click the block so I can go in and fix its block definition, but I can't D:

**Comment by liam4** [comment]
Error blocks also have an offsetted handle, which makes it so that they won't be right under your cursor when you drag them.

**Comment by cycomachead** [comment]
Confirming.

> Error blocks also have an offsetted handle, which makes it so that they won't be right under your cursor when you drag them.

Also a bug.

**Comment by jmoenig** [comment]
fixed and online in the dev version: http://snap.berkeley.edu/snapsource/dev/snap.html
