### ISSUE TITLE
Temporary variable watchers become permanant on save/load cycle

### ISSUE THREAD

**Issue by joefarebrother** [jmoenig/Snap--Build-Your-Own-Blocks#1225]
Whenever I save a project that is currently showing a temporary variable, and then load it again, the watchers stay there and no longer say "temporary". The only way to get rid of them I've found is to create variables with the same names, and delete them again.

**Comment by liam4** [comment]
Try dragging the watchers into the block palette, like you would delete a block.

**Comment by joefarebrother** [comment]
Thanks, that works!

It's still a bug, however, that this happens in the first place.

**Comment by jmoenig** [comment]
Thanks for catching this, @joefarebrother !

**Comment by dekrain** [comment]
It's funny, anything dragged to the blocks palette, dissapears

**Comment by dekrain** [comment]
Oh, noooo!!! I dragged sprite to blocks pallete, and all my blocks on script pallete gone!

**Comment by brianharvey** [comment]
Sure, the whole sprite is gone.  Scripts belong to a particular sprite.
