### ISSUE TITLE
Evaluating reporter

### ISSUE THREAD

**Issue by dekrain** [jmoenig/Snap--Build-Your-Own-Blocks#1232]
A fragment of code:
```javascript
...
/* Input var: CShapedBlock */
this.evaluate(CShapedBlock.blockSequence, null, false);
return ...
```

I can't run this and report value

**Comment by jmoenig** [comment]
Hmm... Can you elaborate a little bit on this? Am I right in assuming that this is a question regarding how to use the Snap source code rather than an issue with Snap itself? Tnx!

**Comment by dekrain** [comment]
Problem: i want to use this to init function in #1227 
I tried to use pushContext but i don't know how this works

**Comment by dekrain** [comment]
Ok, i want to evaluate this block. Process.evaluate takes a ringmorph, but RingMorph is instance of ReporterBlockMorph. Then, i think: "If RingMorph is a ReporterBlock, then i can use this", but
![evaluate](https://cloud.githubusercontent.com/assets/19158291/15687468/3e867744-2775-11e6-83d4-a11ed6114d86.png)

The ring was added "Context >>" and "A Variable Frame"

**Comment by dekrain** [comment]
Ok, ok, i tried to do:
```javascript
if(block) {
this.popContext();
this.pushContext('doYield');
this.context.isCustomBlock = isCB;
this.pushContext(block, out);
this.pushContext();
}
return 'Anything i report, that do command and loop nothing ytasdfcsyfyydsgyfgd';
```

I can't report value !

**Comment by jmoenig** [comment]
Hmm... I'm still somewhat puzzled by this. What exactly are you trying to solve? This looks too complicated to be right :-)

**Comment by dekrain** [comment]
View of the block: `class [name] %upvar{object} init: %c{init}`

I changed this to: (Args: name, **handle**, block)
```javascript
var cl = new ClassMorph(...);
var cont = new Context(null, null, cl.block.blockSequence());
cont.variables = new List([handle /*or 'object'?*/ ]);
this.evaluate(cont, new List([cl]));
return 'Meh, still dont work';
```

I'd like to push to all methods in class the class object, for more free :).
But it don't work :(

**Comment by dekrain** [comment]
Finallllllly !!!!
I resolved this (VariableFrame) problem:
``` javascript
// ...
cont.inputs = [cl];
this.evaluate(cont, new List([cl]));
return '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!jsgfkgsdfjsdjkfgdfiki!!!!!!!!!!!!!!!!!!!!';
```

**Comment by dekrain** [comment]
Yeah, all I must to do:
```javascript
this.popContext();
return "IT'S NOW WORKINGGGGG!!!!!!!";
```
:/ ( :))))))))))) )

**Comment by dekrain** [comment]
No, it's break the context launched before :/ :(

**Comment by dekrain** [comment]
I did it. :/ ( *hahahahahahaha* )
```javascript
Process.prototype.doDeclareClass = function(name, handle, init) {
    if(this.isEnd) {
		var cl = new ClassObj(name,new Context(null,init)); delete this.isEnd; return cl
	}
    var cl, //ctx, 
        myself = this;
    if(init){ init = init.blockSequence()
    //ctx = new Context(null, init);
    //ctx.addInput(handle);
    cl = new ClassObj(name,new Context(null,init))
    
    this.pushContext(init);
	this.context.outerContext.variables.addVar(handle);
	this.context.outerContext.variables.setVar(handle,cl);
	//this.context.addInput();
    this.pushContext('doYield')
	this.pushContext();
    this.isEnd = true;
    return;
    }
    return new ClassObj(name); // :D
    //return 'This is future feature (L) CopyLeft by DK';
};
```
