### ISSUE TITLE
confusing error message pop up in script area

### ISSUE THREAD

**Issue by gengshenghong** [jmoenig/Snap--Build-Your-Own-Blocks#1241]
The error message is confusing sometimes in Snap, below is an example:
1. create 2 sprites
2. in first sprite, write some script for it (which will report some errors)
![image](https://cloud.githubusercontent.com/assets/1018468/15735041/e9091bc4-28c7-11e6-811e-12f1685decad.png)

3. set second sprite as current sprite
4. run it again (click "green flag"), you'll see the error but the script area is empty and very confusing for children.
![image](https://cloud.githubusercontent.com/assets/1018468/15735069/274bd87c-28c8-11e6-811d-636cfa4fccff.png)

is there a better way to report error message? Maybe switch to the sprite and then show the error?

Thanks,
Shenghong

**Comment by brianharvey** [comment]
Yes, we should definitely improve this.  But it'll be part of a more general improvement in error handling, e.g., displaying the actual location of an error inside a custom block.

Meanwhile, Jens, would it be possible to display the error in the sprite corral, next to the sprite where it happened, if that isn't the current sprite?

**Comment by jmoenig** [comment]
Yep, excellent idea!
