### ISSUE TITLE
Error: a variable of name 'arguments' does not exist

### ISSUE THREAD

**Issue by Jonathan50** [jmoenig/Snap--Build-Your-Own-Blocks#1245]
I get an error when clicking on this block:
![](http://i.cubeupload.com/Az6CJE.png)
But when I click on this block (without the let) it works fine:
![screenshot from 2016-06-06 12-10-21](https://cloud.githubusercontent.com/assets/13597222/15809200/b8f0893e-2bdf-11e6-9fd7-84f8d8d5937f.png)
...but the let block seems to work fine:
![](http://i.cubeupload.com/SjyIGB.png)
I don't know what is causing this.
Let is implemented as:
![](http://i.cubeupload.com/98574B.png)

The project is [here](http://snap.berkeley.edu/snapsource/snap.html#present:Username=jonathan50&ProjectName=OOP). My browser is Firefox Nightly version 49.0a1, but it's the same on Google Chrome 50.

**Comment by jmoenig** [comment]
**Solution:** 
expand the variadic input slot of your ```ask``` reporter inside the third input slot of your ```let``` reporter by one and just leave that slot empty.

**Alternative Solution:**
expand the ```call``` invocation inside your ```let``` definition body by one input and just leave that one empty. (Then you can collapse the ```ask```) block again, you'll probably find this solution nicer).

**Explanation:**
Snap treats regards collapsed variadic slots inside rings as semantically "empty" and treats them as implicit formal parameters, binding them to the list of the call's arguments. your "proc" parameter to ```let``` is of type "any unevaluated" and auto-ringifies the ```ask``` reporter stuck into it. In doing so it finds a semantically empty variadic input slot, which it binds to the list of the caller's arguments. When _invoking_ that ring inside ```let``` you don't pass any arguments, thus the error. The solution is thus to either make sure that the variadic slot isn't empty in cases where ```ask``` is reified, or - alternatively - provide a list of arguments.

Make sense?

**Comment by Jonathan50** [comment]
Oh, that makes sense. Great, thanks!

**Comment by brianharvey** [comment]
No, I don't get it.  Why not an empty list (an item for each of the zero actual arguments) instead of an error?

P.S.  It's taken me a while to respond to this because I had trouble parsing Jens's message.  May I suggest that among ourselves (not in user documentation) we try to say "actual argument" and "formal parameter" instead of anything with "input" or "slot," in discussions like this?

**Comment by Jonathan50** [comment]
Ok, this (either solution) doesn't work:
![oop](https://cloud.githubusercontent.com/assets/13597222/15843969/756ffd80-2cba-11e6-9381-e02bb6b72352.png)
![oop2](https://cloud.githubusercontent.com/assets/13597222/15843968/756f02d6-2cba-11e6-883d-e3df1e32c429.png)

Changing
![oop3](https://cloud.githubusercontent.com/assets/13597222/15844022/e6221afe-2cba-11e6-8b6e-d270ebe345e7.png)
to
![oop4](https://cloud.githubusercontent.com/assets/13597222/15844023/e623a64e-2cba-11e6-89f6-dd0bb5e7bd8f.png)
doesn't help.

**Comment by Jonathan50** [comment]
So now I get
![oop5](https://cloud.githubusercontent.com/assets/13597222/15844103/8af496f6-2cbb-11e6-9775-57366d4267b8.png)
where the parent is just empty instead of being object.

**Comment by jmoenig** [comment]
@brianharvey Snap doesn't (yet) have optional arguments and is also not mapping a null value (which it doesn't even have, so we could use an empty string or a zero number). 

@Jonathan50 I don't have time to debug your project. Did I oversee something in my answer to the original question? I *can* see, however (and I've pointed this out before): You *cannot* define an upvar limited to the scope of a ring. I know Brian talks about this, but upvars are *script* vars, their scope is the whole script, not what's inside a ring. Therefore recursive upvar definitions such as your ```of``` block are going to conflate your scope.

Upvars are *not* a solution for functional programming. You want formal parameters. I know you guys love to bootstrap your own programming languages in Snap, and that's great, to a degree. Ultimately what you're going to need is full control over variables, which is something upvars does *not* provide. Instead, once again, use formal parameters. Of course, what you *really* want is variadic formal parameters that you can use on a list of names. This is something Snap doesn't provide, and - frankly - it's not anywhere on my even long-term agenda.

**Comment by Jonathan50** [comment]
> @brianharvey Snap doesn't (yet) have optional arguments and is also not mapping a null value (which it doesn't even have, so we could use an empty string or a zero number). 

I don't understand... If a variadic ring is passed no arguments, why doesn't it just get an empty list?

**Comment by jmoenig** [comment]
In general, the number of actual arguments must match the number of formal parameters in Snap.

**Comment by Jonathan50** [comment]
If it's passed one argument, it gets a list with one item, if it's passed two arguments, it gets a list with two items, so if it's passed no arguments, why doesn't it get a list with zero items?

**Comment by jmoenig** [comment]
I've answered this. The implicit formal parameter mechanism - which I both love (UI wise) and fervently hate (logic- and performance wise) - only kicks in *if any formal parameter is passed*.

**Comment by Jonathan50** [comment]
Oh. But isn't it because of the implicit formal parameter mechanism that collapsed variadic inputs in a ring are special?

**Comment by jmoenig** [comment]
*All* empty input slots are turned into variables when ringifying a block or script, variadic slots are no exception, but they are only assigned values in calls where *any actual arguments are passed*.

**Comment by Jonathan50** [comment]
Oh.

**Comment by Jonathan50** [comment]
Okay, I had an issue with OBJECT. Not a problem anymore! But this does mean you can't call
![args0](https://cloud.githubusercontent.com/assets/13597222/15847070/110cac40-2cd7-11e6-9c6f-c9bc224128a2.png)
with no arguments, and depending on what FOO does calling it with one empty argument won't work.

**Comment by jmoenig** [comment]
Just use explicit formal parameters.

**Comment by brianharvey** [comment]
Jonathan, let's take this conversation to the forum and stop bothering Jens.  Thanks.
