### ISSUE TITLE
don't expand the arrowhead on grey rings in the pallete

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1247]
![image](https://cloud.githubusercontent.com/assets/6549787/15908192/5fcc1b9c-2d8e-11e6-856b-49f56660999d.png)

**Comment by jmoenig** [comment]
Ugh, yes. And if you accidentally do, you can restore the pallette with one of the following:

* hide / show a block in the category
* add / remove a custom block in the category
* switch to dev-mode and back again

I might add a "refresh palette" menu entry somewhere...

Thanks!

**Comment by cycomachead** [comment]
Basically #32 ? (though with a sightly different problem.)

> I might add a "refresh palette" menu entry somewhere...

I don't think this would solve the issue. No one would know when or why to use such an option. 99% of the time users don't need that functionality.

I seems like we need to _redraw_ the palette whenever an arrow is clicked on a block in the palette. Strictly speaking, we don't even need to redraw all the submoprhs, just recalculate the bounds between items, and thus the total width / height.

**Comment by brianharvey** [comment]
I was thinking we could just disallow clicking on the arrowhead in the rings in the palette.  There's really no need to *run* one directly in the palette; the rings are there to be dragged into the scripting area.
