### ISSUE TITLE
Linked lists have NULL added to them on save/load cycles

### ISSUE THREAD

**Issue by joefarebrother** [jmoenig/Snap--Build-Your-Own-Blocks#1251]
This project demonstrates that: http://snap.berkeley.edu/snapsource/snap.html#present:Username=jfb1337&ProjectName=list%20tests

All the lists that were constructed imperatively (with LIST and ADD) are fine, but the linked ones (either constructed with IN FRONT OF or made linked by .becomeLinked()) had an extra, blank element when I saved it and re-opened it. (They might have 2 if you open that link because I didn't remove them)

 Testing on the JS console revealed that this element was null.

**Comment by jmoenig** [comment]
Thanks!

**Comment by jmoenig** [comment]
Okay, I've gotten it fixed in my (local) dev version (not pushed to the "public" dev yet). Hang on, while I'm travelling...

**Comment by jmoenig** [comment]
(not to self - for after the journey -: there were two places that needed to be fixed, ```lists.js``` and ```store.js```)

**Comment by jmoenig** [comment]
... online now (in the dev url). Can you please test again? Thanks!
