### ISSUE TITLE
In Snap! dev version, all blocks are gone after changing language 

### ISSUE THREAD

**Issue by levindu** [jmoenig/Snap--Build-Your-Own-Blocks#1254]
As titled.

**Comment by jmoenig** [comment]
I can't reproduce this. Is it a problem with a particular language or with a particular project? Because when I do that it works and not blocks are gone afterwards, i.e. they are all there again. Thanks!

**Comment by levindu** [comment]
Strange, I cannot reproduce this all the time. But it did happen sometimes. 

Here are the steps:
1. Start with “简体中文” 
2. Press Refresh button to reload the page
3. Drag and drop the "move 10 steps" block
4. Change language to English
5. The block is gone.

**Comment by maryfries** [comment]
I can reproduce it (in dev only) on Chrome Version 51.0.2704.79 (64-bit).

**Comment by bromagosa** [comment]
Yep! It happens to me too. Any language will trigger it.

After trying it a couple times, Snap! became unresponsive and now it seems I can't access either the regular or dev versions, they stay loading forever.

I think it was just a coincidence though, because snap.berkeley.edu takes eons to load too...

**Comment by jmoenig** [comment]
Hmm... Still can't reproduce it. Are you using the online dev version or a downloaded local one? When that happens, do you see any error message in the JS console?

**Comment by bromagosa** [comment]
Nothing in the console :(

Here's what happens:
![vokoscreen-2016-06-17_16-10-20](https://cloud.githubusercontent.com/assets/1016697/16153392/6ac681c6-34a6-11e6-808c-33975d2cf379.gif)

**Comment by jmoenig** [comment]
Wow, thanks, Bernat. This totally does *not* happen for me...

**Comment by jmoenig** [comment]
Checking all my browsers... nope.

**Comment by jmoenig** [comment]
Are you sure your browser isn't caching some old script version(s)? If that happens again, can you post a screenshot of the module version? Thanks!

**Comment by bromagosa** [comment]
Yep, I'm positive. I've just tried it in private mode with the same result:

![image](https://cloud.githubusercontent.com/assets/1016697/16178846/805a35d2-3654-11e6-9f01-8705d47e5952.png)

Please note that you first need to choose a language different than English, then _refresh_ the page, then drop a block in the scripting canvas, then switch languages again.

I'm using Chrome 49.0.2623.87 (official) (64 bits) under Debian, in case it helps.

How can I be of more help? :)

**Comment by bromagosa** [comment]
(just tried it in Firefox, same issue!)

**Comment by jmoenig** [comment]
Ah, *now* I can reproduce it myself, thanks! I forgot the "reload page" part. I think I know how to fix this now. Thanks.

**Comment by jmoenig** [comment]
Can you test it now? Thanks!

**Comment by bromagosa** [comment]
All good now! Thank you! :)
