### ISSUE TITLE
Clarification for placeholders in certain translation terms

### ISSUE THREAD

**Issue by technomancy** [jmoenig/Snap--Build-Your-Own-Blocks#1255]
Some of the translation placeholders are unclear. For instance, the `repeat` block has `'repeat %n %c'` for translation; however when you look in the browser, you can see that `repeat` only takes one argument. The `if` block also has a mystery `%c` argument, as does `warp`.

Could we get some clarification on what's going on here? Thanks.

**Comment by bromagosa** [comment]
It's no mystery, `%c` is for **c**ommand, that is: the function that the C-block takes as a parameter :)

In Snap!, functions are first class, so C-blocks and their "contents" are implemented in the same way as regular command blocks and their parameters. Everything you embed into a C-block is passed as a parameter to the block.

**Comment by technomancy** [comment]
I see; thanks. I wonder if this could be explained in the translator's notes section.
