### ISSUE TITLE
CustomBlock popover with help info (block comment) problems after copy action.

### ISSUE THREAD

**Issue by jguille2** [jmoenig/Snap--Build-Your-Own-Blocks#1258]
Hi,

When a custom block has a block comment, mouse over event on this block in the palette shows a popover with this comment.

The issue is after drag and drop event, when I copy the block from the palette to the scripting area.

When I operate fast, and drag the block without time to show the popover, there is a bug. 'Original' block (in the palette) loose the function (no more popovers) and 'the copy' (in the scripting area) inherits the function. Then, the 'mouse over' on the copy shows the popover but not over the block; it appears in the palette.

![snap_popover_issue](https://cloud.githubusercontent.com/assets/2926315/16180503/ddea84e0-3686-11e6-9f93-3b6ef482700c.png)

Thanks!

Joan

**Comment by jmoenig** [comment]
Yep, that's a bug for sure. Thanks for reporting it!

**Comment by jmoenig** [comment]
Please try it now in the dev version: http://snap.berkeley.edu/snapsource/dev/snap.html

Again thanks!

**Comment by jguille2** [comment]
Thanks Jens!

It's running ok. Now popover is faster and I can't reproduce the problem.

Thanks againg,

Joan
