### ISSUE TITLE
"Backgrounds..." in file menu is not translated.

### ISSUE THREAD

**Issue by levindu** [jmoenig/Snap--Build-Your-Own-Blocks#1262]
1. Select any language other than English.
2. Click "Stage" in the corral area.
3. Click the file menu.
4. "Backgrounds..." is not translated.

**Comment by jmoenig** [comment]
Good catch, thanks!

**Comment by temaps** [comment]
Thanks! I add russian translate https://github.com/temaps/Snap-830/commit/bd54b66ee787d968913fd42ba1dae1d1f8f4a126

**Comment by temaps** [comment]
This is not bug. If add lang-xx.js:
```
 +    'Backgrounds...':
+        'Фоны...',

```
all ok

**Comment by jmoenig** [comment]
Who, that's an even better catch, then!
