### ISSUE TITLE
snap cloud

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap--Build-Your-Own-Blocks#1276]
Snap how to build their own cloud platform, and registered members to the WordPress program

**Comment by DrKat123** [comment]
Huh? What are you talking about?

**Comment by aidiken** [comment]
![38z](https://cloud.githubusercontent.com/assets/20208703/16489604/dda8c4c6-3f08-11e6-8b94-04483880a751.png)
How to register to Si Youyun

**Comment by cycomachead** [comment]
Right now we don't have a way to setup your own clouds. And there's nothing yet that plugs into wordpress. You might be able to talk to MioSoft about hosting your own version.

**Comment by temaps** [comment]
Can be to add in Snap the ability to connect to ownCloud?

**Comment by aidiken** [comment]
I put the version of the code on their own server, how to link the cloud management

**Comment by aidiken** [comment]
I put the code on their own cloud server, one is to open the site how to automatically display the Chinese (in the JS file where to change)

Two student registration how to register to own website (JS code in what place to change), I am a middle school teacher

**Comment by temaps** [comment]
I spoke to the developers when talking about the cloud :-)
I meant to give the ability to connect to [ownCloud](https://owncloud.org/)

**Comment by aidiken** [comment]
@temaps  cloud API ?

**Comment by temaps** [comment]
yes

**Comment by aidiken** [comment]
@temaps    How to register a member to your cloud platform

**Comment by aidiken** [comment]
@DrKat123  Help me test http://code.aidiken.cn

**Comment by temaps** [comment]
@aidiken 
Maybe via API?
https://doc.owncloud.org/server/8.2/developer_manual/ios_library/examples.html
https://doc.owncloud.org/server/8.2/developer_manual/core/externalapi.html
https://doc.owncloud.org/server/8.2/developer_manual/core/ocs-share-api.html

**Comment by jmoenig** [comment]
If you're running your own cloud backend, you should be able to implement Snap's cloud api and then simply replace the "url" property of the SnapCloud with your own cloud url. Then everything should just work, that's the beauty of having an API.

**Comment by temaps** [comment]
I'll try to implement it :-)
