### ISSUE TITLE
"When" hats can be dragged to the Block Editor window

### ISSUE THREAD

**Issue by kbakalar** [jmoenig/Snap--Build-Your-Own-Blocks#1277]
The functionality implied by a second "hat" in a custom block is not documented.  I cannot get it to do anything, so maybe it doesn't have any functionality.

**Comment by cycomachead** [comment]
Yep, that's intentional. All hat blocks are deactivated in custom blocks.

**Comment by brianharvey** [comment]
Reopening.  If it's not meaningful, then you shouldn't be able to do it; the hat block should just zoop back to the palette.
