### ISSUE TITLE
one-line comment right edge chopped off

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#1280]
When a comment box is switched to one-line (boldface) format, the right edge of the rightmost character is clipped.

**Comment by jmoenig** [comment]
Hmm... not sure if I understand this. When you collapse a comment the entire contents is clipped at whichever character happens to be the one bordering the comment's bounding box. You can make sure that the whole text is shown by enlarging the comment before collapsing it.

**Comment by brianharvey** [comment]
No, I mean the character is clipped even though there is plenty of space left in the comment box's width.  But it isn't happening on the computer I'm on right now, so I'll reopen this with a picture if I figure out under what circumstances it happens.
