### ISSUE TITLE
Maximum call stack exceeded when using clones

### ISSUE THREAD

**Issue by lldata** [jmoenig/Snap--Build-Your-Own-Blocks#1281]
I tried making a very simple program to see how clones works, and it surprised me.

The project is attached, but the code is like this:

[When flag clicked]
[create clone of myself]
[delete clone]

[When started as clone]
[forward 10]
[left 15]
[create clone of myself] ≤-- RangeError: Maximum call stack exceeded
[forward 10]
[delete clone]

Of course it would be simple to get the same drawing with just one actor, but I was playing around to learn Snap. I would expect the program to draw a spiked circle.

Is a clone a recursive synchronous call? How else do you get a call stack error?

[maximum call stack exceeded.xml.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/344283/maximum.call.stack.exceeded.xml.zip)

**Comment by jmoenig** [comment]
This is a bug in the current official release, I've already fixed it for the upcoming one. Please try your project with the "development" version here:

   http://snap.berkeley.edu/snapsource/dev/snap.html

And let me know whether it works as you would expect it to.

Thanks!

**Comment by jmoenig** [comment]
so, this works for me in the dev version (the upcoming release):

![spikes](https://cloud.githubusercontent.com/assets/2596285/16577158/ce8b3be8-4293-11e6-83fc-a1d4d19824e7.png)

Looks like we can close this issue. Thanks!

**Comment by lldata** [comment]
Thank you very much for testing this for me :) Had a busy couple of days.
