### ISSUE TITLE
Enlarge font size ?

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap--Build-Your-Own-Blocks#1282]
![_2016-07-03t07-10-02 039z](https://cloud.githubusercontent.com/assets/20208703/16544238/c1f01282-4130-11e6-9b50-7588d2a8535c.png)

Set font size ?

**Comment by jmoenig** [comment]
So, you can just use your browser's zoom function (ctrl + / - / 0) to make everything larger or smaller. Just make sure to click into the url-bar first, so the shortcuts get activated. This is how I wanted people to zoom...

**Comment by cycomachead** [comment]
> This is how I wanted people to zoom...

No, no, no...The problem with the browser zooming thing is that it zooms _everything_. Not all UI elements are created equally, especially if you're dealing with legibility issues. Text is far far more detailed than icons, or the borders separating IDE sections. Those borders don't need to be zoomed when just the text does. 

This is why all browsers have two zooming modes, one which enlarges everything, and on which enlarges text only. Also, I think in "text only" mode, the Canvas might not zoom.... At least it doesn't in Safari.

**Comment by jmoenig** [comment]
So, you know, if you *only* want to zoom all text, you can also do that in the browser settings. I've spent a lot of time and effort support those settings in Snap, and for the most part they work like a charm.

In Chrome (same as in Firefox) you can specify the *minimum font size*:

<img width="1134" alt="minimum_font_size" src="https://cloud.githubusercontent.com/assets/2596285/16757829/83c82a28-480e-11e6-8165-42a0fa430e97.png">

If you shift that to something big, say, 20, all the small labels in Snap will become bigger, and most UI elements will handle this gracefully. It's only certain buttons that don't handle all the increased *width* yet, but the *height* is handled well, and blocks also reflow nicely.

Again, the trick was to integrate Snap well with the browser...

**Comment by cycomachead** [comment]
You have to set the minimum, you can't just use the normal font size settings. That affects all pages and makes Snap! look weird, though it is probably the best option for certain use cases.

> Again, the trick was to integrate Snap well with the browser...

There's only a need for 'tricks' here because of canvas...
