### ISSUE TITLE
Question about clones inheritance

### ISSUE THREAD

**Issue by jguille2** [jmoenig/Snap--Build-Your-Own-Blocks#1283]
Clones inheritance behavior is different in Scratch. I don't know the right behavior.
I try to describe this:

-I make a clone with "create a clone of myself" block
-Then, in the script area, I make a new script (different actions under the block "When x key pressed")
-Now, if I press 'x' key, only 'the original' sprite does these actions. Clones do not inherit the new properties. (In Scratch, it's different: new scripts affects clones too).

There are another issues related to this... but I think this example is clear. I wonder about the right behavior in dynamic programming.

Thanks,

Joan

**Comment by jmoenig** [comment]
your observation is correct, Snap clones share the original's scripts at the time of cloning, but that's really an accidental artefact of shallow-copying them and not an "inheritance feature". In 4.1 there will be explicit inheritance and you will have full control over what gets inherited and when.

**Comment by jguille2** [comment]
Thanks Jens,
I close this issue and wait for 4.1
:+1:
