### ISSUE TITLE
Snap Cloud

### ISSUE THREAD

**Issue by dekrain** [jmoenig/Snap--Build-Your-Own-Blocks#1284]
When I want to log-in at local server (e.g. localhost/), error appears: "Could not to connect: **https://snap.apps.miosoft.com/SnapCloud**!" On Snap server it's normally work.
I using the modified May-June version

**Comment by jmoenig** [comment]
What is this about, I'm afraid I don't understand?

**Comment by dekrain** [comment]
In short, I can't connect to cloud server on my local server

**Comment by jmoenig** [comment]
That's totally intentional, only certain url are whitelisted. The cloud is a service to the Berkeley Snap users, not to anyone who wants a cloud backend for their own app.

**Comment by dekrain** [comment]
Oh, thanks

**Comment by ringoho** [comment]
Hi,

Would you mind to change the cloud backend to open source? 
So that people can have their own cloud server easily .

**Comment by aidiken** [comment]
@cycomachead  How easy to have their own cloud server?
