### ISSUE TITLE
Turning on, then off, dev mode does not restore Snap  to its initial state

### ISSUE THREAD

**Issue by kbakalar** [jmoenig/Snap--Build-Your-Own-Blocks#1289]
Open Snap.  

Drag a block from the palette to the stage.  The block snaps back to the palette and disappears.  Drag a block from the palette to the script area, then drag the same block to the stage.  The block snaps back to the script area.

Hold SHIFT, select the Snap icon on the upper right and then select "Switch to dev mode". The dev mode information popup appears.  Now without holding SHIFT, select the Snap Icon and then select  "Switch back to user mode". The user expects "Switch back to user mode" to be the inverse of "Switch to dev mode".  

Now drag a block from the palette to the stage.  The block remains attached to the hand. Move the hand to the script area and deposit it. Drag the block to the script area.  The block remains attached to the hand. The user's expectation is frustrated.

The code of the three dynamically assigned versions of world.reactToDropOff and the switching between them is wrong, but I have not determined the best way to fix this or if it is in the only issue.

**Comment by jmoenig** [comment]
Okay, I'm really beginning to be annoyed by this shit. Dev mode is *not* for users. Get it?

**Comment by kbakalar** [comment]
Hi Jens,
We seem to be getting off on the wrong foot and I need to understand better
what I'm doing wrong.

I understand that this sort of problem is not  a user priority. But I was
working on the slide back correction #1270, and this had me confused for a
little while, because I was working on a related issue. So I thought I
would put in #1289  to keep a record of it.

I've had a lot of fun with Snap internals in the last few weeks, and I hope
I can make some positive contribution.
Best,
Ken
