### ISSUE TITLE
[question] Quick question: Where are onRightClick method

### ISSUE THREAD

**Issue by dekrain** [jmoenig/Snap--Build-Your-Own-Blocks#1293]

**Comment by dekrain** [comment]
I find it: morphic.js->HandMorph->processMouseDown

**Comment by liam4** [comment]
This section of the morphic.js docs will probably help you: [`VII.3.a` mouse events](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/6170e32248c32270906b18c350a49d474a92fa59/morphic.txt#L455-L493).

**Comment by dekrain** [comment]
I needed this to see how works right-click menu
