### ISSUE TITLE
It can show in English or Chinese according to user's language setting？

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap--Build-Your-Own-Blocks#1297]
![19 757z](https://cloud.githubusercontent.com/assets/20208703/16680311/2cbbb89e-4520-11e6-9225-c41e910770e4.png)

Open the browser how to automatically select the language, how to set up in the code file (locale.js or gui.js)?

**Comment by dekrain** [comment]
Wait what ?

**Comment by aidiken** [comment]
Open the browser how to automatically select the language, how to set up in the code file (locale.js or gui.js)?

**Comment by dekrain** [comment]
How to select browser's language, right ?

**Comment by cycomachead** [comment]
Basically a duplicate of #713
