### ISSUE TITLE
Should pull requests be submitted as changeset.js?

### ISSUE THREAD

**Issue by kbakalar** [jmoenig/Snap--Build-Your-Own-Blocks#1298]
`Contributing to BYOB4.txt` suggests adding a changeset*.js, but existing pull requests don't use that method.  Is there a preference?

**Comment by brianharvey** [comment]
If you do a github PR, do it the regular way, editing the appropriate files.  Jens used to hate git (as don't we all) but has learned to live with it.  I think he'd still be okay with a changeset if you prefer.
