### ISSUE TITLE
Inspector can't save non Morph Object

### ISSUE THREAD

**Issue by dekrain** [jmoenig/Snap--Build-Your-Own-Blocks#1299]
1. Right Click any Morph on world and select "inspect..."
2. Add any new property
3. Set its value to {a:'b',b:null}
4. Inspect this object
5. Set value of b to 'a'
6. >:{

**Comment by jmoenig** [comment]
Yes, the inspector can inspect any object but only modify Morphs. Morphic is not a first-class JavaScript IDE, but a framework I've written to help me develop Snap.
