### ISSUE TITLE
Cap block moving downward attaches to next script

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#1308]
Make two scripts, no hat blocks, one above the other in the scripting area.  Make the top one end with a REPORT block.  Now pull the top script downward.  You'll see a white attachment line and the report block will attach to the block below it.

**Comment by dekrain** [comment]
Yes, I saw this before

**Comment by jmoenig** [comment]
Thanks for catching this one, Brian!

**Comment by dekrain** [comment]
Jens, look here:
![end block bug](https://cloud.githubusercontent.com/assets/19158291/16847789/fa6a78ee-49f2-11e6-80bb-8a1d85d04eb7.png)
