### ISSUE TITLE
IndexSizeError

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1312]
This user has cleared cache and is on 4.0.8. I have the project link below, but I can't replicate it. (Also, this project is currently under development.) There were no other scripts running. He's still having this error.
![image](https://cloud.githubusercontent.com/assets/6549787/16849208/76045230-49c7-11e6-9c0f-1cdead0971cb.png)
http://snap.berkeley.edu/snapsource/snap.html#present:Username=pache76&ProjectName=Create%20project%20-%20Falling%20Mario

**Comment by jmoenig** [comment]
I've seen this very bug yesterday at the SAP headquarters where they were demoing Snap with their enterprise platform software, and it turned out they were using IE on Windows, when I suggested another browser, the bug didn't happen. Could that be the same case here?

**Comment by maryfries** [comment]
This is on a Chromebook, so he has no other browser. Chrome Version 51.0.2704.106 (64-bit)

They've been having enough trouble with this bug (the pic below also threw the error) that they had to switch to another computer. Let me know if you have any ideas, and I'll ask him to try again.

![image](https://cloud.githubusercontent.com/assets/6549787/16850472/52082856-49cd-11e6-9a1c-32428755255e.png)

**Comment by jmoenig** [comment]
I can't reproduce this on Chrome 51.0.2704.106 (64-bit). Please let them re-load the page and clear their caches. Tnx

**Comment by brianharvey** [comment]
We've had half a dozen complaints about this so far.  At least some have cleared their caches.

**Comment by maryfries** [comment]
This user definitely cleared their cache, and I also had them completely restart the browser.

**Comment by jmoenig** [comment]
I don't believe it :-) Can *you* reproduce this?

**Comment by brianharvey** [comment]
Hmm you're right about Efrain's example, at least; it works for me, FOREVER loop and all.  Mary, do you have a pointer to the failing project you're reporting?

**Comment by maryfries** [comment]
The link is in the original post, but the project has been changing as they are actively working on it. Nevertheless, while that bug was happening for them, I couldn't reproduce it with that link on my machine. So, it's something to do with certain system configurations. They just switched to another machine to "solve" the problem.

**Comment by maryfries** [comment]
I'll ask if I can borrow the machine for a bit tomorrow to see if I can do anything to help you debug it. How's approx. 11am EST?

**Comment by jmoenig** [comment]
Okay. People don't actually need to explicitly clear their caches, all they need to do is reload the page without the cache. In all browsers you can do this by holding down the shift-key while clicking on the reload symbol. In most browsers there are also a keyboard shortcut:

Windows:
* ctrl + F5
* ctrl + shift + r

Mac:
* cmd + shift + r

Dunno what's with Chromebooks, but I suspect they have function keys, right?

Then check the status of the modules, and only *then* complain about bugs... :-)

**Comment by maryfries** [comment]
Here's the Piazza thread: https://piazza.com/class/iogthpef4ji5tp?cid=142

I have access to two machines for _today only_ that exhibit this bug even after a cache clear and a browser update.

**Comment by jmoenig** [comment]
Okay, just to recap the Skype call we've just had: We were able to establish that the bug is related to the new retina screen feature. Apparently the Chromebooks that are exhibiting the bug are in retina mode, and the devicePixelRatio is 1.25. This seems to be the problem to address. Doing this now... Thanks, @maryfries for the screen share!

**Comment by maryfries** [comment]
I've checked the devicePixelRatio on two other machines with the problem:
A surface pro 3 (with the bug) has a devicePixelRatio of 1.5.
A Windows 10 machine (with the bug) has a devicePixelRatio of 2.5.

**Comment by jmoenig** [comment]
Thanks, Mary! I think we might be having an issue with non-integer devicePixelRatios, because I've really only tested on my Mac, which has a ration of exactly 2.

**Comment by brianharvey** [comment]
Hey!  You're supposed to test on that Windows machine I got you!  :-(

**Comment by jmoenig** [comment]
The Windows machine is hooked up to an external display with a normal devicePixelRatio of 1, so *of course* it works (as I *have* tested it all along). It's not a question of OS or browser but of devicePixelRatio.

**Comment by brianharvey** [comment]
Ah.  You said "I've only really tested on my Mac" so...
Sorry.

**Comment by maryfries** [comment]
On the dev version, the Chromebook user still gets the IndexSizeError even with morphic July-15. I've probably only got until about 3pm EST with this machine also.

**Comment by maryfries** [comment]
Aha!! I can replicate this on my MBP after all, and I bet you can too!

Set your browser zoom to anything other than 100% and reload the snap site. That both changes the DevicePixelRatio and causes the IndexSizeError bug (for me anyway).

This happens on the current version and on /dev, but not on /stable.

**Comment by jmoenig** [comment]
Awesome, Mary! We've got a reproducible test case. Thank you so much!!
