### ISSUE TITLE
missing "string contains?" block

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1314]
Teachers in the Waltham PD have noticed that the "string contains?" block is missing since the upgrade. Was that intended? Is it in a library somewhere? Is there an alternative?

**Comment by brianharvey** [comment]
There has never been such a block.  I think it's part of a starter project in the curriculum.

**Comment by maryfries** [comment]
Then that might be a problematic strategy. The teachers were confused and looking for the block.

**Comment by brianharvey** [comment]
This is now a curriculum discussion rather than a Snap! discussion.  There are many many places in the curriculum that start by saying "load this project" to provide problem-specific blocks.  Let's talk about it at next week's meeting.

**Comment by jmoenig** [comment]
funny, I remember this "bug" being reported before, always after new releases came out... which is even more funny, because apparently only *then* people ever look for it
