### ISSUE TITLE
[minor bug, repeatable] space is displayed as "0" in variable watcher

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap--Build-Your-Own-Blocks#1316]
It's not as if the watcher can only display numbers, if I set it to "a", it displays "a". But when you set it to " " (space), it displays 0. Strange!

<img width="437" alt="screen shot 2016-07-15 at 10 45 08 am" src="https://cloud.githubusercontent.com/assets/2229297/16878145/68435a30-4a79-11e6-88f2-a01145f12c5b.png">

**Comment by dekrain** [comment]
Hmm... normally if `set` block gets an empty slot, set it to 0

**Comment by cycomachead** [comment]
#564
