### ISSUE TITLE
Internet Explorer fails to load shared projects

### ISSUE THREAD

**Issue by bjr1822** [jmoenig/Snap--Build-Your-Own-Blocks#1325]
Two shared projects as examples (the first is quite simple, the second quite complex, but both fail to properly load):

http://snap.berkeley.edu/snapsource/snap.html#present:Username=bjr1822&ProjectName=BryanReich_IntroToCS_Project3_PongGame

http://snap.berkeley.edu/snapsource/snap.html#present:Username=bjr1822&ProjectName=BryanReich_IntroToCS_Project2_PlatformGame

I used Edge Browser to author these but wanted to make sure they worked ok on IE after I completed them, but trying to load the same projects that work fine in Edge failed to load in IE. I am reproing on Windows 10 Pro with IE version 11.420.10586.0 (Update Versions 11.0.32).

**Comment by jmoenig** [comment]
Hmm... I just opened them on my Windows 10 StickPC in IE without any hiccups, and they work, too....

**Comment by bjr1822** [comment]
Hm, ok. I wonder what the key issue is. Let me reboot my machine to make sure everything is fresh and try again and get back to you.
--
Bryan

-----Original Message-----

**Comment by maryfries** [comment]
Curious if this is related to #1319. Bryan, do you get either of these messages? Are you able to open the project file listed there in your version of IE?

**Comment by bjr1822** [comment]
I just tried on my work PC. The Pong game opens successfully. I get an error on the other game:"Load Failed: TypeError: Object doesn't support property or method 'repeat'"Don't know if that's related to the other one or not.This machine is also Win10 and IE version 11.494.10586.0, Update 11.0.33.The symptom I was getting at home when I filed the initial bug is that it would load with a blank screen and then when I went to the code window view, the code was absent. But I didn't get an actual error message at that time, it just didn't load properly.
 

    On Tuesday, July 19, 2016 11:28 AM, Mary <notifications@github.com> wrote:
 

 Curious if this is related to #1319. Bryan, do you get either of these messages? Are you able to open the project file listed there in your version of IE? —

**Comment by bjr1822** [comment]
closing issue since it would be low priority at this point even if we were able to produce a repro now.
