### ISSUE TITLE
When i change blocks size, buttons on variables caregory still be small

### ISSUE THREAD

**Issue by dekrain** [jmoenig/Snap--Build-Your-Own-Blocks#1327]

**Comment by jmoenig** [comment]
Yes. But with retina support there is now a way to scale *everything* nicely and with high-definition: Just use your browser's "zoom" function to zoom the whole IDE to the level that you like, and then toggle retina support off and on again to redraw the IDE in high-res graphics.

(this currently works fine in Chrome, support for other browsers, especially Firefox, Edge and IE will be patched later today or tomorrow).

**Comment by dekrain** [comment]
In my Chrome browser, isRetinaSupported function returns false :(

**Comment by cycomachead** [comment]
> In my Chrome browser, isRetinaSupported function returns false :(

Is this an error? Or do you just mean that you don't have a hi-res display?

**Comment by dekrain** [comment]
In Chrome browser on my phone, retina checkbox is avalible :OOOOO
