### ISSUE TITLE
Retina mode breaks "touching (color) ?" block

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap--Build-Your-Own-Blocks#1329]
http://snap.berkeley.edu/snapsource/snap.html#present:Username=dan%20garcia&ProjectName=CSPrinciplesReferenceSheetSnap!%20BuggyTouchingColor

The preceding project is one I've been using for CS Principles, it contains a robot which can query the neighbor cells by hitting "down arrow". It works perfectly in non-Retina mode, but when I'm in Retina mode, it seems to be querying another spot on the screen. You can test it manually by setting the size of the sprite to 50% and then clicking the "touching (color)?" blocks yourself.  Here's the screen shot of the current sprite:

<img width="80" alt="screen shot 2016-07-19 at 12 31 38 am" src="https://cloud.githubusercontent.com/assets/2229297/16938652/3a741cee-4d48-11e6-99f0-4e3dd13cd01f.png">

and the result of asking whether it's touching colors around it:

![download](https://cloud.githubusercontent.com/assets/2229297/16938663/60ddad96-4d48-11e6-9807-7b0c5c5f197a.png)

**Comment by jmoenig** [comment]
Indeed, looks like something is wrong with color collision detection in retina mode. Sigh. I knew it was the right thing to avoid this whole retina thing (the logic behind it is ugly as hell), but now we need to put out a string of fires. Looking into fixing this right now. Thanks, Dan, for finding out about this one!

**Comment by jmoenig** [comment]
Okay, looks like I've fixed this in my dev version. There will be another maintenance release later today that also addresses the issue of dragging artifacts we've been seeing in Firefox, Edge and IE in retina mode...
