### ISSUE TITLE
Paint a new costume not working in retina mode on Firefox and Internet Edge

### ISSUE THREAD

**Issue by jimbog** [jmoenig/Snap--Build-Your-Own-Blocks#1333]
The paint a new costume not working in retina mode.
One can switch off retina support and it then works as intended.

**Comment by jmoenig** [comment]
are you sure you've got the latest version? (Try reloading Snap while keeping the shift key pressed). I think this problem got fixed in one of the recent patches... Thanks!

**Comment by jmoenig** [comment]
Oh, it's in Firefox only. I hate browsers...

**Comment by jimbog** [comment]
Sorry, I forgot to include the user agents:
Indeed Firefox and Internet Edge on Windows 10

**Comment by jmoenig** [comment]
I've just fixed this and patched the online version, after testing it with Firefox both on my Mac and on Windows10 in retina- and non-retina modes, and also with Edge in Windows10 in retina- and non-retina modes.

Sigh. The long nose of going retina ...
