### ISSUE TITLE
clones being shown as close in Parent... pop-up menu

### ISSUE THREAD

**Issue by stirlingstout** [jmoenig/Snap--Build-Your-Own-Blocks#1339]
If I create one or more clones of a sprite, then right click on the original sprite in the sprite corral and select Parent..., the clones are shown as **close** not **clone**. I don't know **if** they should be shown, but I think they should be shown as **clone**.

I think this is in Morphic.js, function addItem, where the line 

 `localize(labelString || 'close'),`

should be

`localize(labelString || 'clone'),`

**Comment by jmoenig** [comment]
Oh, now I see, it's when you're playing with inheritance support (which is still under construction). Yep, that's a bug. Thanks!
