### ISSUE TITLE
[FR] Fast Reporter (code)

### ISSUE THREAD

**Issue by dekrain** [jmoenig/Snap--Build-Your-Own-Blocks#1345]
Function:
```javascript
function func(value) {
    return function() {return value;}
};
```

Example:
```javascript
CommandSlotMorph.prototype.getSpec = func('%cmd');
```

**Comment by cycomachead** [comment]
What problem are you trying to solve?

**Comment by dekrain** [comment]
FR is feature request

**Comment by cycomachead** [comment]
I got that, but I mean, why do you need this function?

**Comment by dekrain** [comment]
For fast coding ?

**Comment by liam4** [comment]
I'm not quite understanding.. could you show an example usage of it?

**Comment by jmoenig** [comment]
Okay. We need to talk. You're issuing many feature requests and are trying to contribute a lot of gimmicks that aren't at all clear to me. Can you please explain what you mean or what you want?
