### ISSUE TITLE
[cloud] Opening projects from url not working

### ISSUE THREAD

**Issue by dekrain** [jmoenig/Snap--Build-Your-Own-Blocks#1348]
Example:
http://snap.berkeley.edu/snapsource/snap.html#present:Username=dekrain&ProjectName=Recursion

**Comment by liam4** [comment]
Works for me (Firefox 50, OS X El Capitan).

**Comment by dekrain** [comment]
I have a Chrome browser

**Comment by jmoenig** [comment]
opens and works in Chrome for me

**Comment by dekrain** [comment]
Loading Snap! and removing hash

**Comment by dekrain** [comment]
It happens when language is NOT English

**Comment by cycomachead** [comment]
> It happens when language is NOT English

Yeah, I can see this happening... Not sure what's wrong. But if I load the project in french, then it seems like the URL is being reset too soon.

**Comment by jmoenig** [comment]
Thanks! I've just now fixed this in my dev version and am testing the patch. Will push it later...
