### ISSUE TITLE
snap8inr2 tool doesnt work

### ISSUE THREAD

**Issue by oceank2** [jmoenig/Snap--Build-Your-Own-Blocks#1350]
Hi, 
I try the tool snap8inR2 to convert my Scratch project to snap project.
But, even for ery simple project it does'nt work
Thanks

**Comment by DrKat123** [comment]
You should open a new issue I'm the snap8inr2 repository, not here

**Comment by cycomachead** [comment]
If you have a project to share, @djdolphin Would probably be happy to help!

But yes, these issues generally belong in other repos.
https://github.com/djdolphin/Snapin8r2/issues
