### ISSUE TITLE
Playing with messages

### ISSUE THREAD

**Issue by geaplanet** [jmoenig/Snap--Build-Your-Own-Blocks#1355]
I'm newbie and I was playing with messages. I don't know why this project doesn't work:
http://snap.berkeley.edu/snapsource/snap.html#present:Username=geaplanet&ProjectName=readingspeed

This is the version I'd make normally:
http://snap.berkeley.edu/snapsource/snap.html#present:Username=geaplanet&ProjectName=readingspeed2

Thanks in advance.
(This is not an issue, is there a better place to talk about programming Snap!?)

**Comment by jguille2** [comment]
@geaplanet, I think it's easy.

In the 'change event', 'message' is 'change' (not 'running'). Then, it 'broadcast running' and never 'stopped'.
If you want toogling, you need a 'state var' (like in your other example).

Note: I vote for a forum to share many things and maybe github issues aren't the best way.

Joan

**Comment by jmoenig** [comment]
@jguille2 thanks for explaining this to @geaplanet . I agree, we desparately need a Forum (goddammit)!

**Comment by geaplanet** [comment]
@jguille2, thank you, now I see it.

**Comment by cycomachead** [comment]
> @jguille2 thanks for explaining this to @geaplanet . I agree, we desparately need a Forum (goddammit)!

See emails from months ago?

**Comment by jguille2** [comment]
A humble opinion ...

I would like a forum ... but maybe the tool is not the most important. I guess we need a space for the  community. A communication channel for developers, contributors, translators, helpers, users ... We could ask, share, review, document ... and do it at different levels.

I do not know what possibilities we have. Perhaps there is no time to develop a complex design ... but if we can have a generic CMS (Drupal type ...) could open a first forum and later it will grow and be structured.

Regarding the idea of community, also different people can (we can) bring work (not only ideas and suggestions) about it.

Thanks
Joan

**Comment by bb010g** [comment]
[Flarum](http://flarum.org/) is nice.

**Comment by brianharvey** [comment]
We *have* a forum for this sort of question!  It's at
https://scratch.mit.edu/discuss/topic/4464/unread

(Work on a forum all our own is happening but this works fine meanwhile.)
