### ISSUE TITLE
list creation/initialiszation

### ISSUE THREAD

**Issue by oceank2** [jmoenig/Snap--Build-Your-Own-Blocks#1358]
My query is not  really about a bug but I don't know where to ask this question...

I'd like to create in my program a list named timeList to store timer value.
I create a variable timeList but I don't know what is a best way to add elements during program execution. And I'd like to use the same block for all the elements added (even for the first one).
more details :
========
If I use a [add (timer) to (timerList)] block I got the error message : "type error list.add is not a function"

if I use [set (timerList) to (list ( ) ]   I got a list with one blank first element !

I can use a [set (timerList) to (list (timer ) ] instruction for the first element
and [add (timer) to (timerList)] for the other add-on but I'd like to use the same block in both cases.

So I found this solution which is not really a pretty one
[set (timerList) to (list ( ) ] 
[delete 1 to (timerList)]
with this two blocks snap know timerList is a list and I ot an empty list.
so I can use [add (timer) to (timerList)] for all my add-on even the first one.

Do you any other suggestions ?

Best regards
Thanks for snap, this really a great tool to teach programming
Christophe
France

**Comment by jmoenig** [comment]
When you drag out the ```list``` reporter that makes a new list it has a single empty slot by defaut. You can click on the left arrow to collapse that reporter so it does *not* have any slots and simply makes an empty list. That's how I would do it.

**Comment by oceank2** [comment]
oh, yes, i don't think of deleting this reporter.
thanks
