### ISSUE TITLE
"reset password" keeps sending me a reset email every few seconds

### ISSUE THREAD

**Issue by jeannejeanne02** [jmoenig/Snap--Build-Your-Own-Blocks#1364]
I clicked "reset password" on my snap account.  Now, I receive an email every few seconds with a link to reset, but every time I click the link, it says the temporary password has expired.  How do I stop these emails?

**Comment by cycomachead** [comment]
Hi @jeannejeanne02 

Sorry we can't take care of that directly - please send an email to 
Jens and Bert at Miosoft.

Bert Barabas <bert.barabas@miosoft.com>
Jens Mönig <jens@moenig.org>

**Comment by jmoenig** [comment]
Yeah, I don't know what to do about that, I've been checking the Snap! client (the editor) and can't find anything there that might cause this issue, and Bert is looking at the backend side....
