### ISSUE TITLE
[Joke] Snap! in Snap!

### ISSUE THREAD

**Issue by dekrain** [jmoenig/Snap--Build-Your-Own-Blocks#1368]
I got crazy idea, and I tried to make _Snap!_... in _Snap!_
Screenshot:
![joke snap in snap](https://cloud.githubusercontent.com/assets/19158291/17648923/8fa27f10-6226-11e6-9598-abda75652ac1.png)

**Comment by brianharvey** [comment]
Cute.  Nice that it works.  It could even be useful in making tutorial projects that show things moving around in the sub-world.  But I'm closing the thread because there's nothing for us to do here.  :)
