### ISSUE TITLE
libraries

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap--Build-Your-Own-Blocks#1380]
How to add projects   libraries?
![130z](https://cloud.githubusercontent.com/assets/20208703/17835386/2109b0c4-679d-11e6-84b5-7ee7db51299b.png)

**Comment by cycomachead** [comment]
What's the question - are you asking how to add libraries to your project? Or how to add a your project as a library?

For the first:
If you click on libraries, you'll get a submenu then you can click on that to add blocks to your project.

For the second:
You make a pull request on github that adds a set of blocks to the `libraries/` folder. But you should check with us first if it's something that should be in Snap!

**Comment by aidiken** [comment]
Self built server, how to import the file in the library? (now import library file, why not show it?)

![110z](https://cloud.githubusercontent.com/assets/20208703/17956221/cc8de6c0-6aba-11e6-8e1e-92aac5d96a65.png)

**Comment by brianharvey** [comment]
The libraries in the list are the ones in snap.berkeley.edu/snapsource/libraries/LIBRARIES -- they don't come from the cloud server.
