### ISSUE TITLE
Language input bug

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap--Build-Your-Own-Blocks#1385]
Why such a module can only enter the English language, and can not enter other languages such as Chinese？

![1321](https://cloud.githubusercontent.com/assets/20208703/17876271/766acc3c-690b-11e6-9bb2-7a08376adacb.png)

**Comment by temaps** [comment]
Apparently, in Chinese only. In Russian everything is fine.
![govor](https://cloud.githubusercontent.com/assets/16886413/18021077/0842172c-6bf6-11e6-95f0-bd605af4be6e.png)

**Comment by aidiken** [comment]
@temaps  What's the cause?

**Comment by cycomachead** [comment]
This is a known problem which is being worked on...
See #4 #1165

**Comment by aidiken** [comment]
@cycomachead 
Did not find the final answer
