### ISSUE TITLE
Custom blocks with multi-C-slot glitches

### ISSUE THREAD

**Issue by dekrain** [jmoenig/Snap--Build-Your-Own-Blocks#1389]
Make a custom block with multiple C-Shaped slot, ...aaand:

![c-slot glitch](https://cloud.githubusercontent.com/assets/19158291/18012345/5959419a-6bb9-11e6-8a09-5caf3bc5584e.png)

**Comment by cycomachead** [comment]
See also #181 - I think this is the same, right @brianharvey

**Comment by brianharvey** [comment]
Yes, this is the same (still outstanding) bug.
