### ISSUE TITLE
Really Weird Bug

### ISSUE THREAD

**Issue by TotallyLegitIssue** [jmoenig/Snap--Build-Your-Own-Blocks#1396]
So I was working in Scratch for quite a while and then I looked up and for some reason the word Scratch was spelled wrong. It was spelled S-N-A-P. That does not even make a real word! I immediately closed all my work without saving, losing countless hours on my Noah's Ark Dinosaur Simulator. As you can see this issue is very big and should be fixed ASAP. Please email me when I can safely continue working on my Simulator in Scratch. K thanx *holds up spork*!!!

**Comment by BookOwl** [comment]
Please don't create spam issues.

**Comment by kvackkvack** [comment]
Guys, stop spamming the reactions, it makes it hard to see which are genuine and which are fake. I mean, it doesn't matter too much in this thread which is obviously just a troll, but it can get a bit annoying. :P

**Comment by joker314** [comment]
I do agree. I think this issue should be closed as soon as somebody with closing power can. In case @TotallyLegitIssue wasn't spamming (or at least to patronise them) Snap is a word: it is onomatopoeia. It is the name of a modification for Scratch. If you notice a bug, don't just close the project. BUT OBVIOUSLY you are spamming. Please own up, and I think that is the best thing you can do at the moment :)
