### ISSUE TITLE
Crash when loading a project with 2 sounds on 2 sprites

### ISSUE THREAD

**Issue by michcan** [jmoenig/Snap--Build-Your-Own-Blocks#1410]
Create a  new project
On the default sprite add the block "when flag clicked"
import 2 sounds on the sprites
snap to first block "play the sound ...one on the sounds..."
duplicate the sprite
change the sound on the block "play the sound ....." (on the second sprite)
Save the project and load it, the second sprite doesn't play the sound and if you select "sound tab"(no sound displayed) and change sprite snap will crash.

Here is the resulting file:
[crash2.xml.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/476583/crash2.xml.zip)

**Comment by jmoenig** [comment]
Good catch, thank you!

The bug that causing this is that duplicating the sprite only shallow copies its sound list ("jukebox"), so the sounds end up being shared by both sprites, which isn't what the IDE expects.

**Comment by jmoenig** [comment]
I've just fixed the cause for this problem in my current dev version. You can try it out here:

  http://snap.berkeley.edu/snapsource/dev/snap.html

Please note that the dev version is - at the moment  - in pre-alpha state for the next features that are already in there, so handle with care and expect unrelated glitches :-)

The fix wil not, however, repair your project. Unfortunately you'll have to delete the second sprite manually. But then you can duplicate the first one again and apply your changes to it. After that saving should fix it, and you should be able to reopen the project and continue working on it.

Can you test whether this works for you?
Thanks!

**Comment by brianharvey** [comment]
This sounds like a short-term fix to me.  When we do real sprite cloning, the jukebox won't even be shallow-copied; it'll just be shared.

**Comment by jmoenig** [comment]
fixed.
