### ISSUE TITLE
Is it planned to release as NPM module ever?

### ISSUE THREAD

**Issue by Ohar** [jmoenig/Snap--Build-Your-Own-Blocks#1411]

**Comment by dekrain** [comment]
No, it's HTML 5 application, not node.

**Comment by bromagosa** [comment]
That's right, but [command-line](https://github.com/bromagosa/snap-interpreter) versions are feasible, or even [Cairo](https://github.com/Automattic/node-canvas)-based ones ;)

**Comment by cycomachead** [comment]
A node module might still make sense for some projects. 

You can alway include Git URLs through NPM, do you can still declare Snap<em>!</em> as a dependency if you wish. :) And if you want specific versions you can use commit hashes or version tags in the URL.
