### ISSUE TITLE
IE11: play note fails due to no audio context

### ISSUE THREAD

**Issue by danyoel** [jmoenig/Snap--Build-Your-Own-Blocks#1413]
The Play Note block fails with `TypeError: Unable to get property 'prototype' of undefined or null reference`. 

![untitled](https://cloud.githubusercontent.com/assets/9189744/18650756/a33e9600-7e7b-11e6-9179-6eaaf2b3cddd.png)

Debugging, it seems that obtaining the audio context fails (in `Note.setupContext()`, `ctx` is undefined after trying all the possible `*AudioContext` properties.

```javascript
Note.prototype.setupContext = function () {
    if (this.audioContext) { return; }
    var AudioContext = (function () {
        // cross browser some day?
        var ctx = window.AudioContext ||
            window.mozAudioContext ||
            window.msAudioContext ||
            window.oAudioContext ||
            window.webkitAudioContext;
        // ctx will be undefined here on IE 11
        if (!ctx.prototype.hasOwnProperty('createGain')) {
            ctx.prototype.createGain = ctx.prototype.createGainNode;
        }
        return ctx;
    }());
    if (!AudioContext) {
        throw new Error('Web Audio API is not supported\nin this browser');
    }
    Note.prototype.audioContext = new AudioContext();
    Note.prototype.gainNode = Note.prototype.audioContext.createGain();
    Note.prototype.gainNode.gain.value = 0.25; // reduce volume by 1/4
};
```

**Comment by jmoenig** [comment]
Hmm, I can't reproduce this... Which browser and OS are you on?

**Comment by jmoenig** [comment]
Oh, duh, you said so in the title. Sorry.
Investigating...

**Comment by jmoenig** [comment]
How about Edge?

**Comment by jmoenig** [comment]
Yep, IE doesn't seem to support web audio, but Edge apparently does. This is a browser issue, and - frankly - I don't now why IE is even around anymore.

**Comment by danyoel** [comment]
you'd be surprised :(
