### ISSUE TITLE
Snap! Not loading

### ISSUE THREAD

**Issue by kmf207** [jmoenig/Snap--Build-Your-Own-Blocks#1415]
My students and I are unable to get snap! to run today.  It was working at 9:30am EST but now (12:00pm EST) it just times out and says the site can't be reached.

**Comment by brianharvey** [comment]
This is a Berkeley network problem.  For now, use one of these mirrors:
[http://bjc.edc.org/snapsource/snap.html]
[https://snap.apps.miosoft.com]

**Comment by dekrain** [comment]
Yep, I tried to read history.txt, but I can't.

**Comment by dekrain** [comment]
Oh, now it working.
