### ISSUE TITLE
Can't unringify empty RingMorph

### ISSUE THREAD

**Issue by brollb** [jmoenig/Snap--Build-Your-Own-Blocks#1416]
This is minor but when trying to unringify an empty RingMorph, the following error is thrown:

```
Uncaught TypeError: Cannot read property 'parent' of null @ morphic.js:3377 
```
Also, when clicking on a single, empty RingMorph, "unringify" is an option when it doesn't really make sense as the single RingMorph is not inside a ring.

**Comment by jmoenig** [comment]
yep, it's a bug. Thanks!
