### ISSUE TITLE
How to sort a list of words?

### ISSUE THREAD

**Issue by geaplanet** [jmoenig/Snap--Build-Your-Own-Blocks#1420]
How could I sort a list of words? I'd like to order alphabetically some words in a list or to know what is the first, the second, etc... (always alphabetically).

Thanks.

**Comment by dekrain** [comment]
Use, for example, bubble sort.

**Comment by geaplanet** [comment]
I don't know how to use bubble sort in Snap. What do I have to do? Would it be necessary to include every word in a list?

Would be possible to use something like this in the JS Function block? http://www.w3schools.com/jsref/jsref_sort.asp

**Comment by Jonathan50** [comment]
You could import the "List utilities" library and then use the SORT block, like
![sort](https://cloud.githubusercontent.com/assets/13597222/18801617/fb8a3796-8237-11e6-9839-e4fd0c8e3200.png)

**Comment by geaplanet** [comment]
Cool! @Jonathan50, I didn't know these utilities.

**Comment by introlinux** [comment]
You can use javascript too:
![javascript sort](http://i.imgur.com/9tYFNky.png)

And if you replace "return palabras" by "return palabras[1]" you will get the second element in the list, for example.

Although I much prefer the proposal of @Jonathan50 👍
