### ISSUE TITLE
Reporter call∕cc errors "didn't output"

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#1422]
... which is true, but shouldn't matter because we shouldn't be in that call stack any more after calling it.  Here's a picture:
<img width="1180" alt="google chrome002" src="https://cloud.githubusercontent.com/assets/3885074/18805560/0cc040ea-81c6-11e6-9949-358c8e440447.png">
and the project is at [http://snap.berkeley.edu/snapsource/dev/snap.html#present:Username=bh&ProjectName=call-cc-reporter-bug].

The command version works -- click on the FOO block and you'll see the numbers to the left of the zero in the list SAYed and then when it hits the zero it THINKs 0 as the product.  (Change the 0 in the list to something else and it'll compute the product.)

But the reporter version errors.  (I had to make a reporter-shaped THROW block to use in the reporter IF/ELSE.)  Try it in the dev version with visual stepping turned on, and you'll see that the error is at the CALL to the continuation made by the CALL∕CC.

I don't know if the underlying bug is the same as or different from the one in #1197.

**Comment by jmoenig** [comment]
Yeah, hmm.... not sure if this a bug. This only happens if you click manually click on the unattached ```catch``` block sitting in a scripting area. If you drop the ```catch``` block into the input slot of another block, ```say``` or even a reporter (```+```) it seems to work correctly. Basically the null continuation is treated as ```stop```, I think.

**Comment by brianharvey** [comment]
Ah.  But the continuation isn't null; it's "put the value in a speech balloon next to the script."  But I grant you it's a less urgent bug than I thought.

**Comment by jmoenig** [comment]
Okay, I agree. You know, the "put the value in a speech balloon next to the script" part can't be the continuation, because it's not even in the Snap! language, only in the IDE (I know, I know, we're gonna have *that* discussion some time ^^)

**Comment by brianharvey** [comment]
Nah, I don't insist on Eisenbergifying that.  :)  But it's still the continuation, same as when a Scheme expression's continuation is the PRINT in the REPL.

**Comment by jmoenig** [comment]
Sure, this should work in the IDE, same as ever other reporter :-)
