### ISSUE TITLE
Add something to  "Snap! App" Project

### ISSUE THREAD

**Issue by dekrain** [jmoenig/Snap--Build-Your-Own-Blocks#1423]
Something like this:
# Project: Snap! App

## Unsorted Ideas:
#1414
#1412

## In Progress:
#119
#1417

## High Priority:
#1422
#1418
#1416

**Comment by liam4** [comment]
Right now I'm pretty sure you can just use [GitHub labels](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/labels) for your suggestions, I guess.

For example - [all open issues tagged "important"](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/labels/important), issues with [discussion ongoing](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/labels/discussion%20ongoing) and [controversial issues](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/labels/controversial).

**Comment by dekrain** [comment]
But I mean [this](#B82A9AAABB30EACE73DE05).

**Comment by liam4** [comment]
> But I mean this.

That just links to this issue..

**Comment by dekrain** [comment]
Oh, sorry. Fixed.

**Comment by cycomachead** [comment]
I don't know if it's worth using the projects feature over the labels, currently. We have sooooooo many labels, so it would be nice to organize things, but the Projects is really just a test of things for now. :)
