### ISSUE TITLE
JS Error on previewing (empty) project

### ISSUE THREAD

**Issue by thomaswp** [jmoenig/Snap--Build-Your-Own-Blocks#1428]
To reproduce:
* Open snap in a private tab (to "clear" you browser cache)
* Open the JS console
* Go to File -> Open -> Browser
* Select the "(empty)" project
* You'll see the error in the console: `Expected "=" after attribute name`

Not a show-stopper, for sure, but it does cause an annoying error (that looks pretty scary in logs). I'm submitting a quick fix in a pull request.

**Comment by jmoenig** [comment]
Thanks, Thomas! I really appreciate bug reports that come bundled with a good, surgical fix!

**Comment by cycomachead** [comment]
I don't have a problem with the fix, but I think the _real problem_ is that you can select and open the empty project...

If we need to have an empty state warning it needs to be visually different from an actual project, but I suppose that's a different issue.

**Comment by thomaswp** [comment]
@cycomachead, I agree - the real problem is that the (empty) project isn't handled uniquely. But keep in mind this code isn't executed when the project is opened - it's when it's previewed. In order to show the preview the whole project is deserialized. I don't believe you can actually open it.

**Comment by brianharvey** [comment]
> In order to show the preview the whole project is deserialized.

That doesn't sound very efficient.  When I scroll through my project list in the open dialog it's reading all of each project?  Sounds to me like low-hanging efficiency fruit.

**Comment by jmoenig** [comment]
> In order to show the preview the whole project is deserialized.

Naw. Only a *preview* data structure of the project that contains its meta information is deserialized in the project dialog's "open" tab.

**Comment by brianharvey** [comment]
Whew!
