### ISSUE TITLE
How works internally the speak block?

### ISSUE THREAD

**Issue by introlinux** [jmoenig/Snap--Build-Your-Own-Blocks#1431]
What does it use for text to speech? Is it an online service? Can I configure it for diferent languages?

**Comment by liam4** [comment]
The answer to "how does a custom block work internally" is always going to be "take a look, yourself!" :)

![Context menu](https://cloud.githubusercontent.com/assets/9948030/18883861/5df7f05a-84bb-11e6-8fdc-adde6138ca14.png)

That's what the edit block button was made for.

**Comment by introlinux** [comment]
Thanks, @liam4
