### ISSUE TITLE
Add a Rename button in Open dialog

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#1433]
Right now, to change the name of a shared project, you have to
1.  Open the project.
2.  Choose "Save as..."
3.  Save the project under the new name.
4.  Choose "Open."
5.  Click on the old name.
6.  Click Delete and confirm.
7.  Click on the new name.
8.  Click Share and confirm.

Instead of that, I want
1.  Click "Open."
2.  Click on project.
3.  Click "Rename."
4.  Edit name, click OK.

Alternatively, have a Rename button up on the title line (pen icon, I guess, is standard) that changes the title and sets a flag so that the next "Save" operation automatically does all that.  Maybe there should be a dialog when you rename letting you choose between "keep old project with old name (I'm making a variant of it)" and "delete old project (I changed my mind about the name)."

**Comment by cycomachead** [comment]
#607 :)
