### ISSUE TITLE
Bug in drawing thick dots?

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#1437]
Open this project: [http://snap.berkeley.edu/snapsource/snap.html#present:Username=bh&ProjectName=U2L1p2%20Predicates%20%28answer%20file%29] and click on the last script at the bottom of the scripting area.  Both of the thick dots are supposed to be red, but the first one is actually blue.  (If you look closely, it seems as if a thick blue dot is not quite covering a thick red dot.)  I can't figure out why.

(The second (red) dot has a thin blue tail coming out of it, and that doesn't surprise me once I saw it.)

**Comment by jmoenig** [comment]
Wow. This is weird.

**Comment by brianharvey** [comment]
Mary found a workaround:  If you change the pen size before the pen color, it works.  But neither of those blocks should be doing anything visible at all, until a MOVE happens!

**Comment by jmoenig** [comment]
Yes, I've found several workarounds myself. But this is odd. The problem is clearly that sometimes the ```set pen size (1)``` part of the ```false``` block doesn't take effect right away, so it is setting the color to blue and then moving, but setting the pen-size happens the step afterwards. This almost smells like some asynchronous thingy, which is shouldn't be...

**Comment by brianharvey** [comment]
I moved the project file to my account (link above edited) so that I could save a working version in BJCSolutions and not confuse people.

**Comment by jmoenig** [comment]
I found the bug. Fixing it now for the dev version.

**Comment by jmoenig** [comment]
Okay, I've fixed this bug in the dev version:

  http://snap.berkeley.edu/snapsource/dev/snap.html

to be included in the next release.

**Comment by brianharvey** [comment]
Yay!  Thanks!
