### ISSUE TITLE
Why remove say (Hello!) Turtle also displays (Hello!)

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap--Build-Your-Own-Blocks#1444]
Why remove say (Hello!) Turtle also displays (Hello!)？

![5756](https://cloud.githubusercontent.com/assets/20208703/19035570/db50ab60-899c-11e6-804d-5b7e5841db2f.png)

**Comment by dekrain** [comment]
You must use `say []`

**Comment by cycomachead** [comment]
This is intentional - A `say` block (with no time) is going to show until something explicitly stops it. 

AFAIK, this design follows scratch.
