### ISSUE TITLE
Scrolling on long option lists

### ISSUE THREAD

**Issue by stirlingstout** [jmoenig/Snap--Build-Your-Own-Blocks#1451]
I have an option list for a block input that has 72 options (Minecraft block types). I can't see how to scroll up/down if the pop-up doesn't fit on the screen (as it may do if you've zoomed the block size). Using keyboard editing I can get a 'highlight' which I can move but when it gets to the top it just carries on and then wraps around.

I can't imagine it's a very common problem but it's a bit unsettling.

**Comment by jmoenig** [comment]
Ah, yes, you're right. I want to add scrollable menus, and there already is a PR from a student that I need to go over again. Good point!

**Comment by jmoenig** [comment]
... of course, the other feature I urgently want is dynamic drop-downs (working on it...) :-)

**Comment by bromagosa** [comment]
Fixed in 922dcc279eb7a27f67767f1fabff573007b99f26
