### ISSUE TITLE
CRLF characters in cloud-stored projects double LF when reopened

### ISSUE THREAD

**Issue by jmoenig** [jmoenig/Snap--Build-Your-Own-Blocks#1455]
This bug has been reported for a while in various contexts (see #1106 and #1128) but so far I wasn't able to reproduce it myself. Now I've finally come across a reproducible process:

![crlfcloudbug](https://cloud.githubusercontent.com/assets/2596285/19235648/4382011a-8ef3-11e6-955d-ebc0af9f3c38.png)

here's the link to the actual project that demonstrates this bug:

http://snap.berkeley.edu/run#cloud:Username=jens&ProjectName=CloudBug%20-%20CRLF%20doubles%20LFs

This bug has been so elusive to track down because it _only_ happens when _two_ criteria coincide:

1) text lines are delimited with CRLF (only LF won't cause this)
2) the project is saved to the cloud (saving locally or exporting to disk also won't cause this)

Therefore I'm presuming that this might be an issue with the backend server software and not with the client-side serialization / deserialization code.

**Comment by jupiterio** [comment]
Tested with just CR. Looks like the backend is replacing them with CRLF.

Demo project:
http://snap.berkeley.edu/snapsource/snap.html#present:Username=jrbc2&ProjectName=CloudBug%20-%20CR%20gets%20replaced%20by%20CRLF

**Comment by Jonathan50** [comment]
Then CRLF will be replaced with CRLFLF...

**Comment by bromagosa** [comment]
This is now fixed with the new cloud :)
