### ISSUE TITLE
Make HTTP failure visible to user?

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#1465]
Because some days one HTTP proxy works and other days a different one works, I'd like to be able to write a proxied HTTP tool block that tries all the proxies we know about until one works.  Right now an HTTP failure reports an empty string.  I'd like something that's unambiguously an error, e.g., a singleton list containing the actual error report, e.g., {404 page not found} or whatever the server returned, or {timeout} if that's what happened.

**Comment by jmoenig** [comment]
... of course, this leads up to introducing first-class exceptions in general ... :-)

**Comment by brianharvey** [comment]
That would be cool!  But I'm anxious not to let the best be the enemy of the good here -- we need robust proxied HTTP asap.

**Comment by cycomachead** [comment]
This should be easy. I will try to take this on tonight or this week, but I warning you: It's not going to work everywhere because websites abuse HTTP error codes.

**Comment by brianharvey** [comment]
For _this_ purpose, all I need is the fact that there was an error.  But I can see ways that one might wish to use specific error messages down the road.

**Comment by dekrain** [comment]
Solution is:
```javascript
Process.prototype.reportURL = function (url) {
    var response;
    if (!this.httpRequest) {
        this.httpRequest = new XMLHttpRequest();
        this.httpRequest.open("GET", 'http://' + url, true);
        this.httpRequest.send(null);
    } else if (this.httpRequest.readyState === 4) {
        if (this.httpRequest.status === 200)
          response = this.httpRequest.responseText;
        else
         throw new Error('GET http://' + url + ' ' + this.httpRequest.status);
        this.httpRequest = null;
        return response;
    }
    this.pushContext('doYield');
    this.pushContext();
};
```

**Comment by brianharvey** [comment]
Thanks, but I want the program to keep running and get an unambiguous error signal, so it'll really be something like
`else
   response = List.cons(this.httpRequest.responseText, new List());
`

**Comment by cycomachead** [comment]
> Do you have projects that depend on getting an empty string when a request fails?

Some do, yes, because that's their only option currently.

Otherwise, a lot of things would break in their code.

**Comment by cycomachead** [comment]
(Responding via emails gets weird...)

> For this purpose, all I need is the fact that there was an error. But I can see ways that one might wish to use specific error messages down the road.

What I meant was, with many proxies, there's no way to actually detect an error. If it returns a blank response, but a 200 status code, then you can't do anything. (The Snap!Cloud is a prime example of a site which abuses the 200 status code. :P)

**Comment by dekrain** [comment]
Maybe do something like this:
```
(http:// [snap.berkeley.edu/]) // a List [200, "<!DOCTYPE..."]
```
and this:
```
(http:// [snap.berkeley.edu/dsjfiujdhxifjjji]) // a List [404, "Not found!"]
```

**Comment by brianharvey** [comment]
That would be more uniform and elegant, I agree, but would break _all_ the projects that use HTTP!

**Comment by dekrain** [comment]
Hmm... Maybe project version update?
For example:
```xml
<blocks version="4.0"><block s="say %s"><inputs><block s="http:// %s"><inputs><l>snap.berkeley.edu</l></inputs></block></inputs></block></blocks>
```
to:
```xml
<blocks version="4.1">
  <block s="say %s">
    <inputs>
      <block s="item %n of %l">
        <inputs>
          <l>2</l>
          <block s="http:// %s">
            <inputs>
              <l>snap.berkeley.edu</l>
            </inputs>
          </block>
        </inputs>
      </block>
    </inputs>
  </block>
</blocks>
```

**Comment by cycomachead** [comment]
> That would be more uniform and elegant, I agree, but would break all the projects that use HTTP!

What do you think we should do - any change to error handling is likely to break at least a handful of existing projects. :(

We could modify the more advanced `http` block library to return something different, since that only affects new projects.

FWIW, regardless of solution I don't think a List is an appropriate error format. It would require _every_ use of the http block to type check the response so that the rest of the code fails gracefully. (Rather than the Scratch approach of continuing on as long as possible.) 

Plus a list without explaing what the items are is reallly reallllly weird. 

If we went down the libraries route I propose a block which returns a string, maybe tab-delimited or something and that we provide a block (build in Snap!) called "listify errors" or something more usefully named, and maybe a really simple predicate `(response) is error?`.

**Comment by brianharvey** [comment]
Oh.  This is what I meant about the perfect being the enemy of the good.  What you're proposing is that we spend a while talking about what the best UI is for first class errors (how do they print, etc.), and then get around to implementing something the second Tuesday of next week.  I was hoping for a tiny little change, comparable to dekrain's first suggestion, that could be up over the weekend.  Not that it's really _super_ urgent, but...

The thing about lists is that they're definitely not text strings.  So you know without inventing new data types that you got an error.  And there's no issue about "what the items are" because it'd be a list of length 1.

But, okay, I see the point about failing softly.  So, what we need is a Warning category that's like Error except that the program just keeps running unless you're catching errors.  And a SAFELY DO ... IF FAILED DO ... block.  It wouldn't be a data type because it wouldn't be a returned value.  SAFELY DO would set an internal variable (and clear it when done) to a continuation (woo hoo!) that runs the IF FAILED part.  Or maybe instead of FAILED it'd be an upvar called ERROR and the continuation would take an input, the error message, and store it in ERROR.  So, most of this can be written in Snap<i>!</i>; all we need as a primitive is SET ERROR CONTINUATION TO.

There are a bunch of details to work out.  For example, if catching errors, will the user clicking stop be caught?  (The argument for "yes" is that the SAFELY DO part should be atomic, and if stopped, the error part should back out of the atomic transaction.  The argument for "no" is of course sorcerer's apprentice, but we can disallow catching errors in the continuation.

Oy, now I'm starting to like this, even though it'll take forever to get right.

**Comment by BookOwl** [comment]
>I don't think so. We're not changing the behavior for requests that succeed, just for requests that fail. Do you have projects that depend on getting an empty string when a request fails?

Oh, I thought that you meant making the block _always_ return a list.

If you really need this right now, I could make you a custom block that would do this.

**Comment by brianharvey** [comment]
... or I could do what, apparently, everyone else does, and just assume that an empty string means an error.  :)

**Comment by BookOwl** [comment]
@brianharvey I made it: http://snap.berkeley.edu/snapsource/snap.html#present:Username=bookowl&ProjectName=Error%20Reporting%20http%3A%2F%5B%5D

**Comment by brianharvey** [comment]
Cool, thanks!

**Comment by cycomachead** [comment]
Sorry, I wasn't trying to suggest "perfect".

I was trying to ask what would be a good non-empty string error message? 
How verbose should it be? (Do you care if it is delimited by tabs or some non-printing character?)

I was thinking something along the lines of:
```
Error:\n
Status:\t{number}\n
Message:\t{message}
```

**Comment by Jonathan50** [comment]
> Also, I think "new List.cons" will make a List object and then make another one.

It will but it will get garbage collected. Something like `new List.cons(first, butfirst)` is the way the Snap*!* block IN FRONT OF does it.

**Comment by brianharvey** [comment]
> I was trying to ask what would be a good non-empty string error message?

Oh.  But, no matter what string you pick, it still could possibly be the content of a web page.  That was the point of the list, which is outside of the normal range of the HTTP block.  If I can't have the list, then the empty string is as good as any other non-guaranteed-error value.

**Comment by brianharvey** [comment]
> Something like new List.cons(first, butfirst) is the way the Snap! block IN FRONT OF does it.

I know, I wrote that code.  But there still has to be a better way that doesn't churn memory.

**Comment by liam4** [comment]
> [code]new List([this.httpRequest.status, this.httpRequest.responseText])[/code]

Try ``` `code` ``` :)

**Comment by brianharvey** [comment]
Oops -- I can never remember which forum I'm in, obviously.

**Comment by BookOwl** [comment]
> Cool, thanks!

No problem! Always up for a good excuse to create something with Snap!

> PS How come in your profile you're both Matthew and Stanley? :)

Because I have two names. :) I'm assuming you mean my github profile, right?

> PPS I take it I can delete the two console.log calls at the beginning? 

Yes, you can delete the two console.log statements, they were just for testing.

**Comment by cycomachead** [comment]
> Oh. But, no matter what string you pick, it still could possibly be the content of a web page.

Ah, yeah, that's true in theory, but if we were to pick a string like "Snap! HTTP Error" (instead of just "Error") then there's a virtually nil chance of randomly colliding with a site.

**Comment by brianharvey** [comment]
For the time being I'm going with BookOwl's solution.

**Comment by cycomachead** [comment]
Yeah. Do you have the URL or example?

Also do you want a red ring, stop execution error or a response that is an error message?


Typically if we had real try / catch i would vote for a red ring but without that we could stop scripts unexpectedly. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by cycomachead** [comment]
Well there is problem of existing projects that deal with error cases. That's a true point - it's not clear what is the best thing in that case. 
A list result would definitely break existing projects. 

(I wonder if there was a way we could "version" internal blocks. Well we could do that but it would be tricky. And I don't think Jens would like it.)

We also probably want to think more about what exactly the response format is.

We need something comprehensible by humans but easily parsable by kids. I don't think returning a list makes sense as the default because the reality is - clarity of message is more important than parsability because I don't think most programs will go out of their way to implement error handling, and we also don't want students type checking responses. 

(This is why first class error message objects would be good, but that is a separate story indeed.)

I definitely agree we should surface error codes and error messages but we also need to make it clear where they are coming from - i.e. Which is one we write and which is an error we can appropriately pass along from a website. 


Maybe the solution is to provide an optional http library that includes blocks that auto extract the response code, after we write better messages. 
-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment]
> We need something comprehensible by humans but easily parsable by kids.

Kids aren't human?  :-)

I've solved my immediate problem but I agree with you about try/catch as the long term solution.

**Comment by Jonathan50** [comment]
> Typically if we had real try / catch i would vote for a red ring but without that we could stop scripts unexpectedly.

There is a SAFELY TRY block in the "Catch errors in a script" library by @joefarebrother and @brianharvey, I think.

**Comment by cycomachead** [comment]
> Kids aren't human? :-)

Not exactly sure why I phrased it that way.... 

> There is a SAFELY TRY block in the "Catch errors in a script" library by @joefarebrother and @brianharvey, I think.

You're right! That's what I was thinking of writing myself. Nice! 

Also...oh my...that's like 4 nested `run` blocks. :O

**Comment by joefarebrother** [comment]
> Also...oh my...that's like 4 nested run blocks. :O

Yep, it could probably be done more elegantly, I just tried throwing things together until it worked as expected
