### ISSUE TITLE
Account resets password continuously

### ISSUE THREAD

**Issue by CameronParker** [jmoenig/Snap--Build-Your-Own-Blocks#1467]
Hi,

One of my students is getting a steady stream of new emails that asks him to reset his password. By the time he clicks the link to reset, the reset code becomes invalid.

Can you please investigate/fix?

thanks
Cameron Parker
Skyline HS Comp Sci Teacher

Here's the email he receives (with account info):
Hi ryanv00,

we have received a request to reset your Snap! password. If you would like to reset you password, please follow this link:

https://snap.apps.miosoft.com/SnapCloudResetPW?Username=ryanv00&PWresetKey=6x7z3e,

or copy the URL into your browser's address bar.

If you do not wish to reset your password you can simply ignore and delete this email.

**Comment by brianharvey** [comment]
This has happened once before.  Thanks for providing another example to look at.

He can just ignore the emails.  We'll try to make them stop.

**Comment by brianharvey** [comment]
Update: This specific student's problem is solved.  The general bug remains.

**Comment by cycomachead** [comment]
#1364 (there have been others too)

**Comment by CameronParker** [comment]
Thanks – he’s also not able to log into his cloud account because of the constant resets, so he may need a new password for that to work.

**Comment by CameronParker** [comment]
Thanks for the quick follow up.  Cause is likely server side (not client) because he gets a stream of emails continuously without trying to click the link.
Best of luck tracking it down.

**Comment by brianharvey** [comment]
When you made the initial complaint about the email flood, he got one last email from Miosoft with his new password.  If he didn't get that, send me an email and I'll tell it to you -- I don't want to post it in public.
