### ISSUE TITLE
Text Input Cut Off

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1474]
![image](https://cloud.githubusercontent.com/assets/6549787/19660383/89baf848-99fd-11e6-9a39-8e117ec46946.png)

**Comment by cycomachead** [comment]
:(

This one has been around for too long. 

Tagging #945 Do you know what OS / browser this was?

We can fix this if we do a better job of specifying fonts to use...

**Comment by maryfries** [comment]
OSX 10.9.5
Chrome 54.0.2840.71 (64-bit)
(same as the day I posted this, and I'm certain due to recording it in another forum post 3 days before this one)

Sometimes this is better than other times. Try playing around with the zoom blocks setting to replicate. Also seems to be worse when I first type it in.

**Comment by cycomachead** [comment]
Thanks!
