### ISSUE TITLE
Open this Snap!shown above

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap--Build-Your-Own-Blocks#1475]
http://snap.berkeley.edu/snapsource/snap.html#open:http://bjc.berkeley.edu/bjc-r/prog/Snap/Determinism.xml
![253](https://cloud.githubusercontent.com/assets/20208703/19675629/e9e926da-9ac1-11e6-8f8f-3a5de344c31b.png)

How to make this open snap!

**Comment by jmoenig** [comment]
Not sure what the question is, doesn't the link open Snap for you?

**Comment by aidiken** [comment]
How to open a file without Curitiba

**Comment by bromagosa** [comment]
Is your question how to obtain a URL like that one for your project?

**Comment by aidiken** [comment]
@bromagosa http://block.maocode.com/snap.html   
Web link opens .xml

**Comment by aidiken** [comment]
@bromagosa   How to make web links the snap! File into a state of XML editor ？

**Comment by bromagosa** [comment]
You mean how to get a URL that opens an XML file right into your editor? If so, you can either:

a) Host the XML file somewhere public, then use:
    http://snap.berkeley.edu/snapsource/snap.html#open:url/to/your/project.xml
    or, if you have your own Snap! instance running in your server:
    http://your.snap.instance.com/snap.html#open:url/to/your/project.xml
b) Share the file in the Snap! cloud, and load it via an URL like this:
    http://snap.berkeley.edu/snapsource/snap.html#run:Username=yourUsername&ProjectName=yourProjectName&editMode

**Comment by aidiken** [comment]
@bromagosa
a) 
http://snap.berkeley.edu/snapsource/snap.html#open:http://www.maocode.com/mao/ss.xml
![5307](https://cloud.githubusercontent.com/assets/20208703/19770805/4402af42-9c93-11e6-9c4f-5d0a3b2931b4.png)
??

**Comment by bromagosa** [comment]
Oh I see. That's because:

```

**Comment by bromagosa** [comment]
Oh I see, that's because:

```
gui.js:310 XMLHttpRequest cannot load http://www.maocode.com/mao/ss.xml. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://snap.berkeley.edu' is therefore not allowed access.
```

You need to allow `http://snap.berkeley.edu` in the `Access-Control-Allow-Origin` header in your server. Here's [more about it](http://enable-cors.org/server.html).

**Comment by cycomachead** [comment]
Or a proxy - but there's not much we could do in Snap<em>!</em>. 

Potentinally we could add an error message to this case?

**Comment by aidiken** [comment]
Snap! How do you do it, can you share it?

**Comment by Jonathan50** [comment]
If you are unable to control what headers the server sends, you could use a CORS proxy like http://crossorigin.me/: http://snap.berkeley.edu/snapsource/snap.html#open:https://crossorigin.me/http://www.maocode.com/mao/ss.xml

**Comment by aidiken** [comment]
@Jonathan50 Thank you 
http://block.maocode.com/snap.html#open:https://crossorigin.me/http://www.maocode.com/mao/ss.xml
How to open this ？
Your email address？
