### ISSUE TITLE
Custom block argument with the existing variables

### ISSUE THREAD

**Issue by alex-cres** [jmoenig/Snap--Build-Your-Own-Blocks#1480]
Hi, I was wondering if there is any way the create a dropdown box like argument with the variables that are visible where the block is used.

**Comment by brianharvey** [comment]
In the long form input dialog (the one you get by clicking the arrowhead in the short form input dialog!), right click on the background and choose "options" from the menu that appears.

**Comment by alex-cres** [comment]
It isn't that type of variable, for example in some of the commands like for variable value adding you can see a drop down list of all the variables in that context  but you can't recreate that behavior in a custom block since you have to insert them in that manual manner like you said.
![variable](https://cloud.githubusercontent.com/assets/20164692/19809825/ec18a8d2-9d22-11e6-989a-986da27f1310.png)

**Comment by dekrain** [comment]
You must use spec: set  **%anyUE** to %s. [Here](http://snap.berkeley.edu/snapsource/snap.html#present:Username=dekrain&ProjectName=CB%20Variable%20example) is a project.

**Comment by alex-cres** [comment]
Thank you.

**Comment by jmoenig** [comment]
Hi @alex-cres , seems like what you need is dynamic drop-downs. These are currently not possible in Snap (on the user side, at least), but - that's the good news - that feature is on my short/mid-term list of features I want to add next. So, please hang-on!

**Comment by alex-cres** [comment]
Yes that's actually it, thank you.
