### ISSUE TITLE
Custom blocks are causing an error: this.context.expression.definition.isDirectlyRecursive is not a function

### ISSUE THREAD

**Issue by kmf207** [jmoenig/Snap--Build-Your-Own-Blocks#1486]
None of my programs with custom blocks are working this morning.  I get the error message: this.context.expression.definition.isDirectlyRecursive is not a function.  If I have the same code (even something as simple as move 10 steps) outside of a custom block, it works, but once I put the code in a block and try to call the block, I get this error message. (This error is not occurring on the mirror sites).

**Comment by jmoenig** [comment]
Please flush your browser cache or otherwise "hard reload" your Snap tab, so you get the latest release that we've published over the past weekend. This will make this issue go away. Thank you!

**Comment by mlelmore** [comment]
Can you post some detailed instructions about how to fix this issue? I am teaching a class using Snap an have 30 student computers that I need to get the new version on. We can't work on a project we started until this is fixed. It'd be helpful to have instructions that students can follow.

**Comment by bromagosa** [comment]
Just place your cursor in the address bar and press Control + Shift + R.

**Comment by jmoenig** [comment]
![force_reload](https://cloud.githubusercontent.com/assets/2596285/19887589/9f4d940e-a029-11e6-912f-b8e10d1c80f5.png)
