### ISSUE TITLE
this.context.expression.definition.isDirectlyRecursive is not a function

### ISSUE THREAD

**Issue by jcaldw737** [jmoenig/Snap--Build-Your-Own-Blocks#1490]
Today in class I started getting this error message 

TypeError
this.context.expression.definition.isDirectlyRecursive is not a function

Below is a link to the shared project which I have stripped down to one custom block with one block "inside it"  (and still get the message)

The original project worked fine last Thursday, Oct 27.

I have also tried to upload a screen shot of the error message.

I am dead in the water and would appreciate help before my next class on Thursday.

Thanks in advance  :)

http://snap.berkeley.edu/snapsource/snap.html#present:Username=math126-2016f&ProjectName=00%20question

![snap error](https://cloud.githubusercontent.com/assets/5361659/19900185/9b942664-a030-11e6-9b1a-81981c75ece9.PNG)

**Comment by jcaldw737** [comment]
Just in case there was some vestigial stuff hanging around that I didn't delete when I stripped down the original problem project, I made a brand new project with the same custom block and still got the error.
Here is its link
http://snap.berkeley.edu/snapsource/snap.html#present:Username=math126-2016f&ProjectName=00a%20question

and now if I go into SNAP and make a very simple custom block, I still get the error.

**Comment by dekrain** [comment]
Look here: #1486

**Comment by jcaldw737** [comment]
THANKS!  WAS THAT A QUICK RESPONSE OR WHAT!!!

**Comment by dekrain** [comment]
I respond the same issue but on Scratch thread in quicker time
