### ISSUE TITLE
Miosoft Errors

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1492]
Teachers (and also Dan) have been reporting Miosoft connection problems.

https://piazza.com/class/i7hy3udaukx6su?cid=344

**Comment by dekrain** [comment]
Only snap.berkeley.edu can connect to Snap Cloud

**Comment by brianharvey** [comment]
No, there are several other whitelisted sites.  But that comment isn't relevant anyway, because people aren't trying to connect directly; they're trying to save and load projects!

I'm going to ask Bert if there's anything unusual in their logs.
