### ISSUE TITLE
Broken on IE11

### ISSUE THREAD

**Issue by RobDolin** [jmoenig/Snap--Build-Your-Own-Blocks#150]
Snap does not seem to load on IE11 preview found on Win8.1 preview.  

Specifically this page: http://snap.berkeley.edu/snapsource/snap.html

**Comment by cycomachead** [comment]
This is old, but I believe Snap<em>!</em> loads fine on IE11. @jmoenig Can confrim. Closing this, if there are issues, we could reopen it.
