### ISSUE TITLE
your own server, how to configure the cloud server for example: cloud.js

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap--Build-Your-Own-Blocks#1501]
your own server, how to configure the cloud server for example: cloud.js

**Comment by cycomachead** [comment]
You would have to rebuild your own infrastructure. It's probably easiest to just rewrite cloud.js to use a new API rather than matching Miosoft's API.

**Comment by aidiken** [comment]
@cycomachead
 cloud.js API How to rewrite ？
Thank you

**Comment by aidiken** [comment]
Is there any other way？

**Comment by cycomachead** [comment]
> Is there any other way？

Not really. 

I have a separate implementation at snap-cloud/snap-cloud but it's not complete.

**Comment by aidiken** [comment]
@bromagosa
https://github.com/bromagosa/beetleCloud
How to deploy cloud services ?
Thank you!

**Comment by bromagosa** [comment]
I haven't really documented much of it... it's work in progress and not yet meant to be easily deployable.

I'd say your best choice is to either wait for the official cloud to support what you need (you never mentioned what it is), go through the trouble of learning how to deploy my cloud (Lapis, nginx, etc) or just build your own.

**Comment by aidiken** [comment]
@cycomachead   You have rewritten snap-cluod API? How to write?
