### ISSUE TITLE
should repeat-until require a valid argument?

### ISSUE THREAD

**Issue by danyoel** [jmoenig/Snap--Build-Your-Own-Blocks#1502]
Currently, `repeat-until` without any argument acts as `repeat-until true`. Because of this, I've seen students who use the `repeat-until` without an argument as a `forever` block.

In most languages, the loop would not compile. It seems like SNAP should throw an error here unless there's a good reason to default to `true`.

**Comment by dekrain** [comment]
repeat-until block repeats action UNTIL expression be true. Undefined value is as false

**Comment by danyoel** [comment]
Yes, you're right; I meant that it acts as `repeat-until false`. The behavior is following JS truthiness rules. The issue is whether this is obvious to a student with no CS background.

**Comment by brianharvey** [comment]
We're doing a review of the whole question of strictness of inputs before the next major release.  There are arguments on both sides.  Meanwhile I'm closing this because it overlaps with other such complaints and we'll deal with all at once, or not...
