### ISSUE TITLE
Degree trig functions

### ISSUE THREAD

**Issue by scj643** [jmoenig/Snap--Build-Your-Own-Blocks#1506]
Working with radians in snap without a pi variable is insane and is such a hassle.

**Comment by jmoenig** [comment]
What are working on?
You can pretty easily get both radians and PI using JS-functions...

**Comment by liam4** [comment]
> You can pretty easily get both radians and PI using JS-functions...

Not everyone knows of the JS function block (or even that Snap*!* is made with JS) :)

Here's how:

![Pi JS Function block](https://cloud.githubusercontent.com/assets/9948030/20189060/eb52663e-a751-11e6-865f-ebfd69cca965.png)

You could put that in a custom block or a variable if you'd like it to be more convenient.

**Comment by brianharvey** [comment]
Or, you know, you could just
![pi](https://cloud.githubusercontent.com/assets/3885074/20189441/0b6927b6-a732-11e6-8255-62225c42cc17.png)
even if you don't know about JS Function!  :-P

**Comment by cycomachead** [comment]
Or, the limit -- which works pretty well for large numbers:

![pi](https://cloud.githubusercontent.com/assets/1505907/20191689/80d28c8c-a73b-11e6-93b0-336ddf011f5e.png)

It's really no different than a variable, but it seems more fun :)

**Comment by scj643** [comment]
@cycomachead that's a better solution then the JS version since things like exams don['t want you using the javascript functions.
