### ISSUE TITLE
I'm having issues connecting to the Cloud in my Electron Snap! wrapper.

### ISSUE THREAD

**Issue by BookOwl** [jmoenig/Snap--Build-Your-Own-Blocks#1509]
I'm trying to write an Electron wrapper around Snap! to allow people to use Snap! just like a regular desktop application, but I've hit a major snag. When I try to log in, I'm getting errors saying that the request is coming from an invalid origin (a file:// URL). How can I work around this?

**Comment by brianharvey** [comment]
I don't think you can.  The cloud server has a whitelist of sites with official Snap<i>!</i> mirrors.

**Comment by BookOwl** [comment]
snapp.citilab.eu just compiles a Snap! project into a program that can be run. I'm trying to make a program that lets you run Snap! just like a normal desktop app.

**Comment by BookOwl** [comment]
I'm guessing that it would probably be a security issue to allow requests coming from file:// URLs.

**Comment by brianharvey** [comment]
If you just take an empty project and run it through Snapp<i>!</i> with the "Code accessible" option selected, you get a desktop Snap<i>!</i>.

**Comment by BookOwl** [comment]
Well, I can't get it to work at all.

**Comment by brianharvey** [comment]
Oh!  You're right!  It used to work...

**Comment by cycomachead** [comment]
He is duplicating work that I've been doing about the desktop offline app, which also uses Electron. 

There is a way around this, but I don't know if the intention was for the separate cloud URL to be public? It's out there in public repos, I guess but I'll let @jmoenig share if he wants. (Since the whitelisting was done for a few different reasons.)

**Comment by cycomachead** [comment]
github.com/cycomachead/snap-app

**Comment by jmoenig** [comment]
well, it's not meant to be used by experimental versions. Let's keep it with that.

**Comment by BookOwl** [comment]
> https://github.com/cycomachead/snap-app

Oh, nice! I didn't know that you were already working on one.

**Comment by cycomachead** [comment]
You're more than welcome to contribute! :)

I spent most of the past day getting autoupdating to work - I'm going to upload some new compiled versions tonight - I think it's working!
