### ISSUE TITLE
Point towards ...

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#1510]
Hello,

I have some problem to create a move fonction wich allows to have the pointer direction towards a point.

Would it be possible to have the possibility to "Point towards" a point (with its coordinates),
or to have a function such as : 
directionFromA.To.B 
where A and B are lists of coordinates ?

I have problems with the function arctan to do it. The direction is correct just 1 time to 4...

The direction goes from 0 to 180. And after, how it works ?
-90 is it equal to 270 ?

Thank you for your answer.
Nathalie Carrie, a french teacher.

**Comment by dekrain** [comment]
If it's answer for your question, `point towards 0` sets direction to the right

**Comment by nathalierun** [comment]
No, I already understood the four directions 0, 90, -90 and 180. 
You don't understand my request.

**Comment by nathalierun** [comment]
Here is my script. It does not work at all.

![image](https://cloud.githubusercontent.com/assets/17542520/20245054/a7ff4cf6-a9b0-11e6-9787-4a7155100b9b.png)

**Comment by dekrain** [comment]
Ouch, now I get it, but I'm not on the computer now, so I can't help you at the moment.

**Comment by dekrain** [comment]
BTW -90 and 270 are the same, because it's doing `degrees % 360`.
https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/master/objects.js#L3805

**Comment by nathalierun** [comment]
Fantastic ! 
Thank you for the link ! Really. Because, I wondered wether rotations were wrote on Snap!

I thank you alsow for the visible stepping because I didn't know how to go step by step.

**Comment by dekrain** [comment]
I'm glad I helped.

**Comment by brianharvey** [comment]
Tangent is not an invertible function -- different angles can have the same tangent.  The arctangent function has to pick one of them to report, and by convention it picks rightward-pointing values, in the range -90 to 90 degrees, using the standard math angle measure (counterclockwise from east).  To get to the Snap<i>!</i> angle measure (clockwise from north), compute 90-atan(∆y/∆x), which gets you values between 0 and 180 degrees.  Then you do have to check for wanting to point leftward, ∆x<0, in which case you add 180 degrees to the angle you have.  But I don't think you also have to worry about whether the value returned by atan is positive or negative.

**Comment by jupiterio** [comment]
The way I implemented it is like this:
![Script](https://cloud.githubusercontent.com/assets/6393827/20248589/f9eb38a8-a9ac-11e6-93ed-f4056d21159d.png)
(Supposing the first item on the lists is the x position, and the second the y)

Since atan does not now the difference between -x/y x/-y, nor does it know the difference between -x/-y and x/y, this only checks if the height of the triangle the coords form is negative, and if it is it adds 180 to the angle (Try never adding 180 and you'll see why)

**Comment by jguille2** [comment]
An alternative comment...

If I don't want to work with trigonometric functions with my pupils (in this time), I can use Snap! environment to achieve it. I only need a hidden Sprite to help me: I move this sprite to (x,y) coord and then, I can point to it.

![pointtohiddensprite](https://cloud.githubusercontent.com/assets/2926315/20249649/4846ec94-a9fe-11e6-9145-f5c33dab9557.png)

**Comment by nathalierun** [comment]
Thank you for this answer. I didn't know at all that it was possible to do such action with a sprite.
So, I wonder wether it was possible to do it with clones. And so, how can I do it ?

Because, how do you create your HiddenSprite ? I think that you have to do it manually : I mean that you have to duplicate the actual sprite and to rename it to do it. It is not possible to do that if you want to run automatically the processus.

**Comment by jmoenig** [comment]
Yes, you can totally use a hidden clone for this! I'm sorry the official website isn't very user-friendly or structured better. Here's a link to my documentation about first-class sprites (including clones) that has all the information:

http://snap.berkeley.edu/snapsource/FirstClassSpritesInSnap.pdf

**Comment by brianharvey** [comment]
... but there's no reason it _has to_ be a clone.  You can just have one sprite, with a tiny invisible costume, that's used only for this purpose:
![pointer](https://cloud.githubusercontent.com/assets/3885074/20267647/8e6b6ca4-aa30-11e6-8273-dc57d94dd378.png)

**Comment by jguille2** [comment]
Hi,
@jmoenig This document about FirstClassSprites is greatl!!
@nathalierun You have many options... depends on other aspects of your project. For example, you can create a clone, use this to point the direction and kill it:

![pointtoclone](https://cloud.githubusercontent.com/assets/2926315/20273943/568a6480-aa93-11e6-9dc0-14c06a10a554.png)

**Comment by dekrain** [comment]
Look at https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/master/objects.js#L3819
![image](https://cloud.githubusercontent.com/assets/19158291/20323557/899f4c7e-ab7d-11e6-8023-5fe839a4eda3.png)

**Comment by nathalierun** [comment]
So, I really have choice !
Thank you to all of you.

But I realize that I have really a lot of work to do to progress.

I wondered whether there were such things as summer university on Snap! on july 2017 in Berkeley, or more simply, would it be possible to join your team, in your labs, just for one or two weeks in july. I promise not to disturb you. I just want to progress and be able to do some Snap! 

> non-stop

 during one or two weeks, with the possibility of asking you some questions, sometimes. 
I feel that your soft will become very useful in mathematics education an I am enough crazy to perform the travel from Reunion Island (french department) to come to a summer university.

I have another question : is Snap! on Twitter ? 
my link on Twitter is @nathrune

Nathalie Carrié, french mathematic teacher
http://irem.univ-reunion.fr/spip.php?auteur8

**Comment by dekrain** [comment]
No, Snap _!_ isn't on Twitter.

**Comment by cycomachead** [comment]
There's a couple twitter accounts for Snap! stuff:
`@SnapCloud` is run by Miosoft
`@moenig` is Jens' account
`@cspbjc` is the official for BJC which includes Snap! (and other CS) stuff

**Comment by brianharvey** [comment]
We'll be running BJC workshops in July at Berkeley.  That's not exactly the same as a Snap<i>!</i> workshop, but there's plenty of Snap<i>!</i> stuff in it.  Look on http://bjc.berkeley.edu for information.

**Comment by nathalierun** [comment]
@bromagosa :
So ? Concurrent ? What do you mean ? Should I do a BJC summer course or not ? 

@brianharvey  : 
I understand know how your team is working. Effectively, it would be a problem to come to your development laboratory, seeing that you develop at home ;-(

**Comment by bromagosa** [comment]
Oh, it was just a joke! :)

You'd love the BJC course, so if you can attend, do it!

**Comment by nathalierun** [comment]
Ok, Thank you. I'll see.

**Comment by nathalierun** [comment]
@brianharvey :
definitely, I do not understand how to reproduce this :
https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/1510#issuecomment-260343321
What is your 

> pointer sprite 
? 
A text or a sprite ???

**Comment by dekrain** [comment]
Pointer sprite is a sprite.

**Comment by brianharvey** [comment]
You make a sprite, name it "pointer sprite" (or anything, of course, will work), have it HIDE so you don't ever see it, and then the code I posted will work for pointing to any coordinates on the stage.

**Comment by nathalierun** [comment]
@brianharvey :
No, I still can't reproduce.

![capture du 2016-11-18 07 34 41](https://cloud.githubusercontent.com/assets/17542520/20417808/7ded451c-ad61-11e6-8550-d43162824533.png)

**Comment by cycomachead** [comment]
Ah, you'll need to drag in the point towards block from Sprite to get it to have the option of SpriteH. 

Some of the motion blocks are tied to the sprite they came from. 

---
Admittedly, you should probably be able to point towards the same sprite and it would just be a no-op. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by nathalierun** [comment]
Ok, thanks.
But it does not work.

![capture du 2016-11-18 07 52 34](https://cloud.githubusercontent.com/assets/17542520/20418108/0db0819e-ad64-11e6-91ad-d24c2619ec62.png)

The gray Sprite doesn't point towards SpriteH.

**Comment by Jonathan50** [comment]
Are you sure you are using the block in Sprite, not SpriteH?

**Comment by cycomachead** [comment]
Hmm. I thought that should have worked. 

If you wrap another TELL block around the point towards then I think it should work. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by nathalierun** [comment]
@Jonathan50 :
That's it ! Thank you.

**Comment by brianharvey** [comment]
No, that's not necessary.  In your picture above, it's not working because you have SpriteH selected in the sprite corral (see bottom right corner of screen), and so that's the one you're telling to LOOK AT.  You need to select the sprite that you're trying to turn!  Then use LOOK AT in that sprite.

**Comment by nathalierun** [comment]
Yes @brianharvey . Thank you. I just saw my error.
