### ISSUE TITLE
Project not opening

### ISSUE THREAD

**Issue by hakkas** [jmoenig/Snap--Build-Your-Own-Blocks#1515]
Students of mine try to share their project with me, but when I try to open them I get an error: 

_Error: No project name was supplied_

For instance: https://snap.berkeley.edu/snapsource/snap.html#present:Username=ojp277&amp;ProjectName=School%20boom

**Comment by bromagosa** [comment]
The url looks wrong. Try with:

https://snap.berkeley.edu/snapsource/snap.html#present:Username=ojp277&ProjectName=School%20boom

Basically, remove the `amp;` part and it should be okay. I don't know where you got that URL from, but some "smart" software turned your ampersands into `&amp;`. This is how you escape special chars in HTML, I'm not sure what caused this.

P.S. That project looks empty though.

**Comment by dekrain** [comment]
In name is `&amp;`. You must replace them with `&`
