### ISSUE TITLE
How to put cloud.js on the cloud server to receive their own?

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap--Build-Your-Own-Blocks#1521]
// Global stuff

var Cloud;
var SnapCloud = new Cloud(
    'https://snap.apps.miosoft.com/SnapCloud'
);

// Cloud /////

How to put cloud.js on the cloud server to receive their own?

**Comment by bromagosa** [comment]
I don't get the question. `cloud.js` is the client-side part of the cloud, it should not be placed anywhere in the server... what are you trying to achieve?
