### ISSUE TITLE
Running halo persists after block is deleted

### ISSUE THREAD

**Issue by thomaswp** [jmoenig/Snap--Build-Your-Own-Blocks#1522]
If you delete a block from a running script, the halo/glow that indicates it's running doesn't update to remove the block.

To reproduce:
1. Create and run a script that will run forever:
![before](https://cloud.githubusercontent.com/assets/1750176/20489331/3281dff6-afd8-11e6-8c73-441e4b152004.png)
2. Delete a block
![after](https://cloud.githubusercontent.com/assets/1750176/20489332/3288c5be-afd8-11e6-9c27-40a43db7f4ce.png)
3. The halo remains

I imagine the fix would be as simple as redrawing after a block is deleted, in the same way that it's redraw when a block is added (which does work)

**Comment by liam4** [comment]
Btw, you need to delete the block through the "delete" context menu item, not dragging it out (dragging the block out works as you'd expect).

**Comment by thomaswp** [comment]
Ah, good point @liam4 - I forgot to include that. Which I likely why it behaves differently than adding a block, which can't be done through the context menu.

**Comment by jmoenig** [comment]
Thanks!

**Comment by jmoenig** [comment]
(when I mark this as "fixed in next version" it means that it's fixed in the repo, and "live" at http://snap.berkeley.ed/dev
