### ISSUE TITLE
Project imports in Chrome but fails to import in Firefox (both in a Mac)

### ISSUE THREAD

**Issue by MMSequeira** [jmoenig/Snap--Build-Your-Own-Blocks#1525]
The attached project imports in Chrome but fails to import in Firefox. Both in a Mac.
[Firefox Bug.xml.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/609942/Firefox.Bug.xml.zip)

**Comment by jmoenig** [comment]
another issue that appears to be related to retina display support (cursing under my breath). Investigating a work-around. Thanks for the report, Manuel!

**Comment by jmoenig** [comment]
if I turn off retina support, I can load the project in FF50. God, I hate browsers.

**Comment by jmoenig** [comment]
seems like sometimes FF has "security issues" with overloading the ```width``` attribute of ```Canvas``` with the function that supports retina. Not much I can do about that.

Days like these I hate everything about software. Should stuck to doing divorces...

**Comment by jmoenig** [comment]
Hmm... the *only* thing I can think of is wrapping the retina version of ```Canvas.width``` into a ```try...catch``` structure and performing the "normal" ```width``` operation on case it fails. This lets me load your project in retina mode, but a) it can't be right, and b) who knows about the side effects.

Definitely shoulda stuck to traffic accidents...

**Comment by jmoenig** [comment]
Okay, I've just addressed this issue with c1668c4f15bd1dbf8504869a4ebf50cfce359092 and updated the dev version: http://snap.berkeley.edu/snapsource/dev/snap.html with it. You should be able to load your project in FF using the dev version.
