### ISSUE TITLE
Step by step mode in Snap! ?

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#1528]
My question is in the title.

I saw somewhere in a post that - of course - there was a debug mode (how ?) but it is not very pedagogical for students. I really would be able to show in my classroom how a program goes step by step.

If this possibility could be added to snap! , it would be very great...

**Comment by nathalierun** [comment]
Very nice ! I didn't know that. Thanks a lot !!
Then, I have a knew question : if I stop the visible stepping in a block, how can I inspect local variables in this block ? 
I would be able to follow the value of a local variable during the visible stepping.

**Comment by jmoenig** [comment]
Hi @nathalierun , 
you can right-click on any (running or paused) script to pop-up its context menu. In that context menu you will find at the bottom a list of all local variables:

<img width="278" alt="inspect_local_vars" src="https://cloud.githubusercontent.com/assets/2596285/20706506/f5b57dde-b627-11e6-8d7f-eb64fd9c4248.png">

Selecting a local variable name will then add a watcher on that variable to the stage.

Is this what you were looking for?

**Comment by nathalierun** [comment]
Wouah !! Many many thanks.

**Comment by nathalierun** [comment]
Oh...
But it does not work inside a block.

**Comment by nathalierun** [comment]
And I am not able to visualize the step by step inside ma recursive block.
![capture d ecran 2016-11-29 a 16 17 29](https://cloud.githubusercontent.com/assets/17542520/20709567/9c5d8d6c-b64f-11e6-8eb6-39a28216e49f.png)

**Comment by jmoenig** [comment]
hmm... I think the save-pentrails blocks also works perfectly inside custom block definitions. 

Okay, here's a little (secret) trick how to visibly step inside your recursive block (or an block). First you need to enable (switch on) visible stepping in the setting menu. Only *then* (i.e. when "visible stepping is already turned on) you open the block editor on the definition of your custom block. *Now* you will see the stepping.

Once you turn "visible stepping" on you can open and close block editors at will, whenever you open a block definition it will step, when you close it, it will "warp".

Does that make sense?

**Comment by dekrain** [comment]
You must reopen block editor.

**Comment by nathalierun** [comment]
@jmoenig : I know that I have to switch on "visible stepping". 

@dekrain : That's it !!!! Too happy...

**Comment by dekrain** [comment]
Look at #1536

**Comment by nathalierun** [comment]
A last question for this post :
how can I clean the stage when I have such many things :
![capture d ecran 2016-11-29 a 16 52 22](https://cloud.githubusercontent.com/assets/17542520/20710671/e91ad3da-b654-11e6-8cca-e0f5e3625073.png)

**Comment by jmoenig** [comment]
You can remove *all* variable watchers marked as ```(temporary)``` by executing the ```hide variable``` block once while leaving the input *empty*, such as this:

![hidevar](https://cloud.githubusercontent.com/assets/2596285/20710782/5ace86ac-b63c-11e6-8f82-5d3f504afe4d.png)

**Comment by jmoenig** [comment]
(we really need to document these tricks somewhere..., sorry!)

**Comment by nathalierun** [comment]
Oh, I see. Thank you.

No, I think that it's me who is not sufficiently persevering...
I will make some efforts.
