### ISSUE TITLE
Dumping the stage into a file

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#1530]
Hello,

I already invoke this problem (#1520) , but - because of my poor english - I'm afraid I was not clear enough.
So, I open a new issue with a more evocative title (hope so...).

I am working on beauty of fractals and I would be able to make an image bigger then the resolution of my screen.
So I have an idea : I define the stage with dimensions that I want, and if they are bigger then my screen resolution, I dump the stage into an image file. So, even if I cannot see anything during the execution of the program, I have the result of what happened on the stage into my saved dumped file.

How could I do it ?

I thank you in advance for your help !

**Comment by brianharvey** [comment]
There's been some discussion in your original issue page.  No need to start a duplicate!

**Comment by jmoenig** [comment]
Well, a block that saves the stage into a file should be possible. I'll post that sometime next week. In the meantime you can probably do much of what you want with the existing "save and restore picture drawn by pen" library.

**Comment by nathalierun** [comment]
@brianharvey 
I apologize if I have annoyed you. I just wanted to be sure that you have understood my problem.

@jmoenig 
I thank you for taking my request into account.
About the existing "save and restore picture drawn by pen" library, I don't understand how it works.

**Comment by jmoenig** [comment]
Hi @nathalierun ,

here's a quick little example how you can use the "save an restore picture drawn by pen" library to take snap-shots of an evolving fractal so you can play it back (at greater speed, thus animating it) later:

http://snap.berkeley.edu/run#cloud:Username=jens&ProjectName=Recording%20Fractals

Switch to the stage, there you'll see all the code. Run it by clicking the green flag. When it has completed all the 15 iterations of the dragon curve you can play back a fast animation by pressing the space key.

Is this what you were looking for?

**Comment by nathalierun** [comment]
Hi @jmoenig,
it's not exactly what I would like to have, but what you did is very nice for pedagogic presentations.
It would be perfect if you could add some "export" this :
![capture d ecran 2016-11-29 a 16 54 32](https://cloud.githubusercontent.com/assets/17542520/20710872/02ded964-b656-11e6-8ef3-3c5d4aba3e3a.png)

So we could have the 15 images separately on our computer (locally). svg files would be very nice. If it is too complicated, png will fit enough.

**Comment by nathalierun** [comment]
But I am afraid that it would saturate memory if the stage dimensions are very big.

**Comment by jmoenig** [comment]
Yes, I can see why directly writing to a file makes sense. I'm afraid that currently browsers go out of their way to prevent us from actually doing that. But we'll keep invistigating!

**Comment by jmoenig** [comment]
I've just updated the same project:

http://snap.berkeley.edu/run#cloud:Username=jens&ProjectName=Recording%20Fractals

with another script and a custom block that lets you directly save costumes to files. Look at the stage's scripts to find it. But please be aware that browsers often prevent or otherwise discourage bulk-downloads of several files.

Cheers!

**Comment by brianharvey** [comment]
I'm not annoyed; sorry if I sounded that way.  It's just that duplicate issues make it harder to keep track of what problems are pending.

**Comment by nathalierun** [comment]
@jmoenig : this is exactly what I was dreaming of !
Many thanks again.

I just had to add a "wait 4s" to your script here :
![script](https://cloud.githubusercontent.com/assets/17542520/20718956/e1a653d0-b673-11e6-9ee2-4fc155d8c7d4.png)

because of that : (my processor is very slow)
![capture d ecran 2016-11-29 a 20 28 56](https://cloud.githubusercontent.com/assets/17542520/20718896/b1379ccc-b673-11e6-9067-67585f94e3ed.png)

**Comment by jmoenig** [comment]
that's what I also tried at first, but then I realized that I might as well leave out the ```wait```, and the browser would simply export those pictures asynchronously at some later time :-)

Anyway, I'm glad we seem to have a solution that works for you!

**Comment by cycomachead** [comment]
We will be able to write files with a desktop interface easily enough. 

Didn't someone work on a Python-based server and a set of custom blocks that did this?

**Comment by BookOwl** [comment]
I remember seeing that, but I don't remember what it was called.
