### ISSUE TITLE
Resizing browser window narrower narrows palette

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#1540]
(Chrome on Mac.)  Drag the corner of the browser window leftward and the palette shrinks below what is ordinarily its minimum size.  Then, clicking in the palette makes it snap back to normal size, but then dragging the palette's resize tab leftward can resize it downward (slowly -- the tab doesn't move as fast as you pull!).

**Comment by jmoenig** [comment]
Ugh, who knew? Good catch!
