### ISSUE TITLE
Cannot recover password

### ISSUE THREAD

**Issue by martimveiga** [jmoenig/Snap--Build-Your-Own-Blocks#1545]
When i try to sign my snap's account it says that my password is incorrect. Then, when i ask for a new password it sends me an e-mail with a link, which message says : "password reset key: d7g29e is no longer valid, please request a new one."
What can i do?

**Comment by brianharvey** [comment]
What is your Snap<i>!</i> user id?

**Comment by micahcowan** [comment]
My daughter ran into this, too. The issued password reset key seems to already be expired upon issue!

**Comment by DaneGrinder** [comment]
I have this same problem... I'm 99% sure I didn't forget my password, but it doesn't accept it, and the reset password sends me an expired key.

Did you guys find a way around this?

**Comment by brianharvey** [comment]
Only by manual intervention.  What are your, and Micah's daughter's, user IDs?  (Not passwords.)

**Comment by DaneGrinder** [comment]
I just tried again, and now it worked. If you guys didn't change anything on your end, the only possibility I see is kind of stupid, but it could be, that the "reset link" in the reset e-mail, has a "comma ( , ) " at the end of it, and that makes the link not valid :-) It's stupid, but I saw it today, and copied the link without the comma, and it worked. Don't remember if I noticed that comma on my earlier tries.

Should that be the problem, at least it's a easy fix on your end :-D

Thank you for getting back to me Brian

**Comment by jguille2** [comment]
Hi @DaneGrinder ,
Then, you can close this issue.

I just tried it and the reset link is right. The ending comma is in the text, but the link is the correct.

Maybe we can remove (or separate from text) this comma to avoid problems with 'copy and paste' uses... but this is not urgent.

**Comment by DaneGrinder** [comment]
That is correct. I just tried it using my gmail account, and there it shows up as a clickable link, so there is no problems.

My other accounts (Yahoo and company outlook) does NOT show it as a clickable link, so there I just triple click the link, and copy/paste it into my browser. This does not work...!

**Comment by DaneGrinder** [comment]
close #1545

**Comment by brianharvey** [comment]
Keeping this open because the next back-end revision should remove the comma.

**Comment by brianharvey** [comment]
Closing because Bert fixed it!
