### ISSUE TITLE
Unchecking "Retina Display Support" causes the Snap! logo to disappear

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#1547]
(as the title says)

**Comment by jmoenig** [comment]
Hmm... I can't reproduce this. Works for me...

**Comment by cycomachead** [comment]
Yeah, it works now...

This may have been connected to a weird bit of connection issues I saw to snap.b.e after this happened. (The rest of Snap! Was loaded, so I suppose that makes sense, though I guess there's no need to re-download the logo...)
