### ISSUE TITLE
Script x-position is serialized as infinity

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#1548]
I have no idea how this happened, but a student ended up with an XML file that looked like this:

```xml
<scripts>
    <script x="Infinity" y="23"></script>
    <script x="Infinity" y="33.99999999999977"></script>
    <comment x="Infinity" y="10" w="90" collapsed="false"></comment>
    <script x="Infinity" y="87.99999999999955"></script>
    <script x="Infinity" y="49"></script>
    <script x="Infinity" y="854.0000040000001"></script>
</scripts>
```

This causes an error when loading, but at the point of rendering blocks, which is a bit confusing. 

Since I only got the file from the cloud after it was saved, I don't know how it could have happened, and can't come up with anything while messing around.

**Comment by jmoenig** [comment]
Hmm... it tries to position the block at ```Infinity``` which probably doesn't work. Looks like the IDE was in a broken state when this happened. I have no idea what could have been causing this. Oh, except perhaps some scaling error, like a division by zero. I smell a potential retina issue :-/

**Comment by jmoenig** [comment]
It *could* also be a division by a very small number, doesn't have to be zero. Scaling could be behind this, but I've never seen this happen myself.

**Comment by cycomachead** [comment]
Closing since there's no way to know how this happened, but the issue is here in case anyone else has something related...
