### ISSUE TITLE
SVG from costume library getting rasterized

### ISSUE THREAD

**Issue by nickedens** [jmoenig/Snap--Build-Your-Own-Blocks#1549]
We use Snap for teaching kids 8-18 how to code. We just recently switched from scratch and I love Snap immensely better. The issue we found was when we use Snap offline and I replace the costumes from the costume directory with SVG's (so the students don't have to do the import) for some reason the SVG gets rasterized. If I import the SVG without going through the custom costume selection then the SVG stays an SVG and it scales appropriately.  This behavior should be consistent and I would think with the wide support of SVG now you shouldn't rasterize the SVG's at all. I was searching in the code for a way to prevent this behavior but I can't find it.

Any help much appreciated.

**Comment by jmoenig** [comment]
Hi @nickedens ,

Hold on, I am working on full SVG support as I am writing this. I've already made a bunch of commits this very day in this regard. This is something that will just work in the next minor release upcoming around Christmas!

In the meantime you can import SVG from *files*, then they will not become rasterized, unless you explicitly choose to rasterize all SVGs in the settings menu (there is a hidden setting for rasterization if you click on the gears button while holding the shift-key down).

Stay tuned, I'll announce in this thread when you'll be able to test the release candidate with full SVG support within the next days :-)

Thanks!

**Comment by nickedens** [comment]
Wonderful news!!!! Thank you for the quick response as well. I'll be on the lookout for the updated version!

**Comment by jmoenig** [comment]
Excellent! So, as a matter of fact, I've *just now* added support for importing unrasterized SVGs from the "Costumes" and "Backgrounds" dialog. You can check it out in the "live" development version:

http://snap.berkeley.edu/snapsource/dev/snap.html

with the many new Costumes that we've copied from Scratch, most of which are SVGs. Just please don't rely on the development version to be stable or (always) usable. But this will be in the next release coming up later this month.

**Comment by BookOwl** [comment]
I just tried that on Firefox, and lots of costumes are just black turtles. 😕

**Comment by nickedens** [comment]
@jmoenig That works. Huge appreciation here from us at HackBG. If I find any bugs with this I will post them up over the next week. Otherwise I'll just update that everything worked well for us. Can't tell you again how much I appreciate you not only doing this but the quick response. Keep up the great work!

@BookOwl you need to take the .js files from the "save web page" browser download and move them into your "full" copy of Snap! He doesn't have the costumes in there it doesn't look like. but I am using a costume library that is custom of our svg's for the kids. They are all importing without rasterization and it looks good to me.

**Comment by jmoenig** [comment]
@BookOwl you're right. For some weird reason Firefox won't accept an SVG as a data url for a new Image. As a result, Firefox won't even *load* projects that were previously saved with Chrome or Safari.

Roping in @cycomachead and @bromagosa : Do you guys know how we can create a Blob based dataURI for the svg+xml contents? I did a quick and dirty experiment based on Michael's ```saveFile``` mechanism, which *worked*, but didn't produce permanent data, only what appeared to be temporary hashes.

@nickedens as a result please be super careful using the dev version while we're figuring out these issues. It may well be that I'm going to disable full SVG support again if we can't guarantee it across browsers. Sadly, Firefox has a bad record in this respect.

**Comment by jmoenig** [comment]
@cycomachead , @bromagosa  Nevermind! Duh...
(StackOverflow knew the answer, I just need to URI-encode it, <facepalm>)

**Comment by nickedens** [comment]
@jmoenig instead of disabling it completely can you make it a flag somewhere in the code? We have our students work from raspberry pi's using chromium and this solution worked wonderfully for us. I realize we are a small drop in the overall grand scheme of things but Snap is considerably more stable and resource mindful than Scratch and the couple other alternatives I looked at. As long as things check out stability wise for us I may just continue using the version you posted (since I already downloaded it and we don't need cross browser support). However this shakes out full SVG support, in my opinion, is a much needed excellent feature. Hopefully you can get this working as a permanent fix. Thanks again so much!

**Comment by jmoenig** [comment]
@nickedens nevermind, I did fix this earlier today, now everything works across all the browsers I tested, including the latest version of Firefox. No need to disable it again.

@BookOwl , can you try again? Make sure to reload the dev page without the cache (keeping the shift key pressed), and then open Costumes. It will take forever compared to Chrome, but it does work, right?

Thanks!

**Comment by nickedens** [comment]
@jmoenig That is AWESOME!!! thanks!

**Comment by BookOwl** [comment]
@jmoenig, it works perfectly now! You are right that it took a long time to load, but it works!

Also completely unrelated, but I love the undo/redo buttons

**Comment by brianharvey** [comment]
Boy, I really started a firestorm...  I'd feel guilty except it /was/ what Mary wanted me to do this week. :-)  Can we close this issue now?

**Comment by cycomachead** [comment]
Blobs are _always_ returned as a data hash / ID. They're saved in some browser cache or something which is why they would great for exporting or internal storage but they won't work for serializing to XML. 

You can probably get around this by serializing to a raster format, which sucks but is preferable to no images. Maybe there's a way to get the SVG back. I'll investigate later. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by cycomachead** [comment]
Ah not getting all emails. :) 

Glad it's fixed but yeah this one can be closed I think! (Although it's nice if it's in the commit if Jens hasn't pushed to GitHub yet)

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by BookOwl** [comment]
@cycomachead, Jens added this in 3d905d139cfaa8553f5f6941faa67848c2162e76 and 72c0dcf

**Comment by jmoenig** [comment]
@nickedens , if you continue to already use the SVG support in your own offline version, can you please update to the latest one from yesterday? Otherwise the projects you create with your older one will not (ever) be compatible with Firefox, and they might well end up in the Snap Cloud at one point. Yesterday's version (the current one, as I'm writing this) is stable in this regard.
Thanks!

**Comment by nickedens** [comment]
@jmoenig I'll update from yesterdays. I assume its at the same link?

Also do you folks have a regular stable release schedule or is there an announcement list I can get on for when the new stable releases happen. That way I know to download the stable release since the SVG support will be included (which I like much better than staying on the dev one I downloaded already).

Thanks again for all your help!

**Comment by jmoenig** [comment]
@nickedens you can use the same link, or simply download this Github repo, which right now is stable again.

Yes, we do have regular and even formal releases in this very repository. The current stable release is the one that's online at http://snap.berkeley.edu/run and the latest official release in this repository (this repo uses Github's releases feature). The current commits are going into the development version, which is not a branch, but simply not (yet) the next release.

Make sense? :-)

**Comment by BookOwl** [comment]
Why don't you guys have a development branch and master always be stable?

**Comment by jmoenig** [comment]
@BookOwl The releases are stable. Isn't that the point of releases?

**Comment by nickedens** [comment]
@jmoenig Thanks sir. I went ahead and just downloaded the repo. I appreciate the explanation as well!

**Comment by cycomachead** [comment]
The releases aren't a branch though so it's not as clear how to checkout the latest stable release automatically. You need to get a list of tags and look for ones with the biggest number. 

But there aren't currently any mailing lists that are public but there may be one sometime. We also usually update the version number on the snap front page. 
-- 
Michael Ball
From my iPhone
michaelball.co
