### ISSUE TITLE
Accessing SNAP!

### ISSUE THREAD

**Issue by teresajsmith** [jmoenig/Snap--Build-Your-Own-Blocks#1550]
Run SNAP! Now gives me a page cannot be displayed error.  Can you tell me what is wrong?

**Comment by nickedens** [comment]
If you are talking accessing from their website http://snap.berkeley.edu/snapsource/snap.html then it has to be something on your end or something further out in the internet network. It is coming up for me no problem with no cache.

**Comment by nickedens** [comment]
You could also try one of their mirrors they list on their website
Mirror Sites

If snap.berkeley.edu is ever unavailable, you can run Snap! at any of these mirror sites:
http://bjc.edc.org/snapsource/snap.html
https://snap.apps.miosoft.com/
http://media.mit.edu/~harveyb/snap
We recommend bookmarking these now, while this site is up!

**Comment by dekrain** [comment]
It seems there are some issues with website. Try again later.

**Comment by cycomachead** [comment]
There are DNS problems at Berkeley right now. :/

http://ucbsystems.org/category/active/unscheduled-outage/

http://cs10.org/snap also works as a backup.

**Comment by dekrain** [comment]
The website is working now :smile:

**Comment by brianharvey** [comment]
I added cs10.org to the list.
