### ISSUE TITLE
[bug] Can click reify in custom block in rings

### ISSUE THREAD

**Issue by dekrain** [jmoenig/Snap--Build-Your-Own-Blocks#1560]
I found very interesting bug.
![image](https://cloud.githubusercontent.com/assets/19158291/21073983/d4b60350-beed-11e6-9f48-54a48bfb61e3.png)
## Steps to reproduce:
1. Make new block
2. Put some command blocks in new ring
3. Right click block in the ring -> reify

Tested on latest dev version (16.12.09)

**Comment by jmoenig** [comment]
Haha, this is even funny. Great catch, @dekrain !
