### ISSUE TITLE
IP addresses/URLs necessary to load SNAP correctly in an Internet-restricted environment

### ISSUE THREAD

**Issue by mhuggins16** [jmoenig/Snap--Build-Your-Own-Blocks#1563]
I'm using SNAP via http://snap.berkeley.edu/snapsource/snap.html in a school setting. We have a filtering system in the classroom called NetSupport. If I restrict Internet access for students to just http://snap.berkeley.edu/snapsource/snap.html, the site doesn't load correctly. I am trying to locate the other IP addresses/urls that I need to enable to make SNAP work correctly in a locked-down classroom environment. Thank you in advance for any help!

**Comment by cycomachead** [comment]
Are you allowing only specific files? That will be nearly impossible to maintain. 

You'll need to whitelist all of the following domains:
* http[s]://snap.berkeley.edu
* https://snsp.apps.miosoft.com

Those two should be the only necessary items. If you are using the `http` block a lot of sites won't work, of course.

**Comment by brianharvey** [comment]
@cycomachead really snsp, not snap?

**Comment by cycomachead** [comment]
Good catch.
It's snap! (fixed, sorry!)
