### ISSUE TITLE
Script varilables didn't get it.

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap--Build-Your-Own-Blocks#1564]
![sv](https://cloud.githubusercontent.com/assets/20208703/21257486/797bbf64-c3b3-11e6-854e-8a96c72a1c84.png)
Script varilables didn't get it.

**Comment by jmoenig** [comment]
Hmm... Can you explain?

**Comment by aidiken** [comment]
This command does not know how to use

**Comment by jmoenig** [comment]
Oh, this defines a local variable. You can right click on the block and request help, and then you *should* be able to see this help panel:

https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/master/help/doDeclareVariables.png

Please let me know if that doesn't work for you or if the explanation doesn't make sense.
