### ISSUE TITLE
Why can't music be imported from the desktop?

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap--Build-Your-Own-Blocks#1566]
Why can't music be imported from the desktop?
![Uploading 28.png…]()

**Comment by jmoenig** [comment]
Hmm... it should be... did you try *.mp3 or *.wav files?

**Comment by aidiken** [comment]
wav

**Comment by jmoenig** [comment]
works fine for me...

**Comment by aidiken** [comment]
Voice size is limited?

**Comment by jmoenig** [comment]
no, there is no size limit, only when uploading to the cloud (but you can change that limit in your fork)

**Comment by aidiken** [comment]
Not uploaded to the cloud，but you can change that limit in your fork？
