### ISSUE TITLE
Getting current stage dimensions.

### ISSUE THREAD

**Issue by nickedens** [jmoenig/Snap--Build-Your-Own-Blocks#1573]
We are making a couple of custom blocks for the students for our game curriculum for next year (which is quickly coming upon us :) ) One of the blocks is a wrap screen block so the space ship will wrap around the screen asteroids style. Currently I have input options of screen width and height but I would love it if the block could just check the stage size. There must be a way in javascript to get the width and height of the stage. Tried a ton of things over a couple hours but just couldn't get it to work. You folks have been so good to me up to this point with the visible block and the svg stuff I figured I would check here and see if I was just missing something maybe.

**Comment by brianharvey** [comment]
![dim](https://cloud.githubusercontent.com/assets/3885074/21412699/1afa7712-c7a7-11e6-95d9-76df4c6d463f.png)
![bou](https://cloud.githubusercontent.com/assets/3885074/21412704/222d59d2-c7a7-11e6-96b6-a7e27bf057f4.png)
The difference is that if you scale the stage (e.g. by using the grow/shrink buttons above it), "dimensions" has the number of turtle steps as seen by the program, which is unchanged by the scaling, while "bounds" has the actual number of screen pixels.

By the way, for future reference, I didn't know the answer either, but here's how I found out:

1.  Shift-click on the Snap<i>!</i> logo at the top left corner, choose "Switch to dev mode."

2.  Right-click/control-click on the stage (not on a sprite) and you'll see a menu of the nested regions inside which you clicked.  In this case, IDE_Morph represents the entire Snap<i>!</i> window, while StageMorph is just the stage.  Choose StageMorph.

3.  About halfway down the menu that appears, choose "Inspect."  This will open a window in which you can see the names and values of all the variables belonging to the stage.  By browsing through these, I found dimensions and bounds.

:-)

**Comment by brianharvey** [comment]
![dim](https://cloud.githubusercontent.com/assets/3885074/21412699/1afa7712-c7a7-11e6-95d9-76df4c6d463f.png)
![bou](https://cloud.githubusercontent.com/assets/3885074/21412704/222d59d2-c7a7-11e6-96b6-a7e27bf057f4.png)
The difference is that if you scale the stage (e.g. by using the grow/shrink buttons above it), "dimensions" has the number of turtle steps as seen by the program, which is unchanged by the scaling, while "bounds" has the actual number of screen pixels.

By the way, for future reference, I didn't know the answer either, but here's how I found out:

1.  Shift-click on the Snap<i>!</i> logo at the top left corner, choose "Switch to dev mode."

2.  Right-click/control-click on the stage (not on a sprite) and you'll see a menu of the nested regions inside which you clicked.  In this case, IDE_Morph represents the entire Snap<i>!</i> window, while StageMorph is just the stage.  Choose StageMorph.

3.  About halfway down the menu that appears, choose "Inspect."  This will open a window in which you can see the names and values of all the variables belonging to the stage.  By browsing through these, I found dimensions and bounds.

:-)

**Comment by nickedens** [comment]
@brianharvey Thanks so much for all the detailed info. Works perfect!
