### ISSUE TITLE
Sending & receiving with the "http:// block" - problem with cross-origin resource sharing (CORS)

### ISSUE THREAD

**Issue by seteahconnoc** [jmoenig/Snap--Build-Your-Own-Blocks#1574]
I am not quite experienced with "Snap!", so excuse me, if I bother you with something obvious:

I got two files "write.php" an "read.php" on a PHP webspace. (The files are quite simple, so I did not add them to this issue. If it is necessary, I will do this later.) The purpose is to write a text directly to a file and to read from this file. This is working well by sending http requests via the browser address line.

Now I want to use "Snap!"'s "http:// block".

In order to write, I have to use this address without proxied http (CORS):
`http://...mywebsite.../write.php?content=hello&filename=test.txt`
It is possible to send the parameters "hello" and "test.txt". The file is written as planned, but I get no answer.

In order to read, I have to use this address with proxied http (CORS):
`http://crossorigin.me/http://...mywebsite.../read.php`
I get an answer. Sadly, it is not possible to send any parameters in order to specify the file from which I want to read.

Please let me know, if you need any further details. I would be quite happy, if someone can solve this problem.

---

The makers of "Snap!" did a great work. Thank you.

**Comment by BookOwl** [comment]
Try using the Web services access library (File -> Libraries -> Web services access (https)), it provides a more powerful http request block that might help.

**Comment by seteahconnoc** [comment]
Thank you for your quick response. Obviously, there is a misunderstanding: I am already using the block you mentioned. I did not know, that "Snap!" has another "http:// block".

**Comment by cycomachead** [comment]
Are you managing the website yourself?

If so, you'll need to explicitly enable CORS for that website to work without the proxy method. 
This site has some info: http://enable-cors.org

Otherwise, this isn't something we can solve in Snap<em>!</em>. @technoboy10 runs crossorigin.me and he can probably give you some guidance about whether there are plans for supporting query strings.

**Comment by seteahconnoc** [comment]
Thank you very much for the answer. I just added the line

header('Access-Control-Allow-Origin: *');

to my PHP scripts on the website. Now, `Snap!`s "http:// block" works without `crossorigin.me`. Afterwards, this is quite obvious...

**Comment by technoboy10** [comment]
Sorry for the issues with crossorigin.me - I absolutely plan to support query strings, and should have them implemented within the next month or so.

**Comment by seteahconnoc** [comment]
@technoboy10 That is good to know. Thank you and greetings to Colorado. (Last summer, I had the chance to visit Boulder. I enjoyed it a lot.)
