### ISSUE TITLE
Merry christmas...

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#1575]
... to the entire Snap team
http://nathalierun.net/depotLibre/Sierpinski.Niveau5.webm

**Comment by jmoenig** [comment]
A Sierpinski Christmas Tree!
Thank you, Nathalie, and a merry Christmas to you!

**Comment by liam4** [comment]
Merry Christmas, all!

**Comment by jguille2** [comment]
Merry Christmas to all!
And a happy new year...and of course, enjoying Snap!
I know that it's not an issue... but don't worry, I've asked for an "Snap forum" to the Magic Kings in my letter. :))
