### ISSUE TITLE
nested auto -wrapping

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap--Build-Your-Own-Blocks#1589]
nested auto -wrapping ?What is the use of？

**Comment by bromagosa** [comment]
You know, it's funny you're asking so much and expecting everybody to help you out when you don't even point to the original projects, licenses or authors in your Snap<i>!</i> and Beetle Blocks copies hosted at http://maocode.com.

I don't feel like helping you at all, when all you do is appropriate the work of others as your own.

The free software licenses these projects are subject to absolutely allow you to copy them and modify them at your will. The only single tiny thing it asks back from you is that you _keep the same license_ and _point to the original projects and authors_.

Why you're failing to give this tiny bit back, even after having been asked politely, is something I can't understand.

**Comment by aidiken** [comment]
Thank you. We'll change it right now.

**Comment by DyslexicAwe** [comment]
>>
>>  **Bramagosa**: 
>>   /snip/ 
>>  _keep the same license and point to the original projects and authors_ 
>>   /snip/
>
> **aidiken**:
> We'll change it right **now**.

comment | image
------------ | -------------
It seems that the "Berkeley Snap!" 
[translates to](https://translate.google.com/translate?sl=zh-CN&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Fwww.maocode.com%2Fabout&edit-text=&act=url) "Panda programming",
see image below.
While (Western Practical) "**now**" 
(automagically) translates into (Eastern Philosophical) "Eternal Now" 
in Chinese, by some mystical 
cross-cultural mechanism  
  ;-/ | ![9 1](https://cloud.githubusercontent.com/assets/16387241/21766584/a7177b06-d66f-11e6-8371-67319a8eaab3.png)
