### ISSUE TITLE
Duplicates in Background folder

### ISSUE THREAD

**Issue by jguille2** [jmoenig/Snap--Build-Your-Own-Blocks#1598]
Hi,
I see 4 duplicate pictures in background folder. Their name diff in "_" / "-" character.
These are:  night-city-with-street.gif, atom-playground.jpg, berkeley-mural.jpg and night-city-with-street.gif.
I don't send a PR because you must choose witch is the right name.

Thanks,

Joan

**Comment by jguille2** [comment]
Hi!
Excuse I insist ( @brianharvey )... but this issue is closed, and maybe [my second comment](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/commit/c6fc4c89f5c7d1b51040420a5ce943ca1c940191#commitcomment-20348876) went unnoticed.
It was...
  - You deleted brick-wall-and-stairs.jpg... but don't update BACKGROUNDS string (brick-wall-and-stairs.jpg -> brick_wall_and_stairs.jpg)
  - And 2 more duplicates: brick-wall1.jpg and brick-wall2.jpg

Thanks,
Joan

**Comment by brianharvey** [comment]
OK.  We decided to wait on extending the backgrounds and sounds until we build a hierarchical browser for them and costumes.  But I haven't forgotten.  Thanks!
