### ISSUE TITLE
Keyboard Shortcut symbols should be "dynamic"

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#1603]
See 1843e29

This is so hugely welcome, but the Command symbol only makes sense to Mac users, whereas on Windows (and I guess linux) it should be the Control symbol.

**Comment by jmoenig** [comment]
I don't want to check for the host OS. Yes, the Mac cmd symbol is only found on Macs. I'm hoping that either Windows / Linux users will also identify it as generic "ctrl" key symbol, or we can find another one that's truly platform independent. But I'm also very sensitive about screen real-estate, and spelling out ```Ctrl+O``` is against my aestetics. I've experimented with this and also with displaying this at a slightly smaller font size, but that only made things worse. Let's stick with the CMD symbol for now, after all it's a real unicode character and - I've checked in every browser - displays fine in Windows.

**Comment by cycomachead** [comment]
> I don't want to check for the host OS.

Why?

> Yes, the Mac cmd symbol is only found on Macs. I'm hoping that either Windows / Linux users will also identify it as generic "ctrl" key symbol, or we can find another one that's truly platform independent.

The only reason Mac users know what this symbol means is because it's on every keyboard they see. A non-technical, windows only (and non-Sweedish) user will likely never have encountered this symbol before.



> But I'm also very sensitive about screen real-estate, and spelling out Ctrl+O is against my aestetics. I've experimented with this and also with displaying this at a slightly smaller font size, but that only made things worse. Let's stick with the CMD symbol for now, after all it's a real unicode character and - I've checked in every browser - displays fine in Windows.

My concern is only the confusion. I think it _should_ be a symbol and not text, since that's what users expect - for menus to be like all the other menus they've used.

**Comment by PullJosh** [comment]
> Spelling out Ctrl+O is against my aestetics.

Surely you'd agree that form follows function. It was only fairly recently that I discovered what the ⌘ symbol means. As a Linux (and Windows) user, I would _much_ rather have an understandable but ugly representation than a stylish one which means nothing to me.

But if you could find a single symbol that works for both platforms, that'd be even better.

**Comment by brianharvey** [comment]
I vote for ^ also.  On my Mac, ⌘N opens a new Chrome window, not a new Snap<i>!</i> workspace, for which I have to type ^N.  (⌘N does work in Firefox.)  And I think Mac users mostly do recognize ^ because of multi-modifier things like ^⌘space for the symbols popup.

**Comment by cycomachead** [comment]
Cmd-N in chrome seems like a bug. 

My point about mac users was the while Control is a valid modifier key it is very seldom used and doesn't usually appear in menus. 

Also, I personally feel like detecting the OS is worth the limited code. There's uses for also detecting if they're on a touch device and the language so it's not like something we wouldn't make use of. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment]
OK, I agree, detecting the OS is good.  But if we have to pick one character, it should be ^, which everyone can type.

(People my age all grew up on 7-bit ASCII keyboards in which control and shift were the only modifiers, and control worked only on letters and a handful of punctuation characters whose ASCII codes are up with the letters, such as ^[ for escape and ^@ for null.)

**Comment by cycomachead** [comment]
Also, are the characters ever different in other languages? I've never used a computer in anything other than english, so I don't know what users would expect for "Cmd-S" to be, in some non-ASCII/Latin character set.

`isMac = navigator.platform.indexOf('Mac') !== -1`

**Comment by bromagosa** [comment]
In GNU/Linux this symbol makes no sense, I like Brian's `^` proposal, but Michael is also right in that it's really easy to check for host OS...

**Comment by cycomachead** [comment]
Though this is closed, I still think the current behavior is wrong.
