### ISSUE TITLE
Block context menus are broken in the palette

### ISSUE THREAD

**Issue by jmoenig** [jmoenig/Snap--Build-Your-Own-Blocks#1604]
with the introduction of variable refactoring block context menus in the palette are broken, letting the user delete blocks etc.

Opening this issue for documentation, I'm already fixing this...

**Comment by bromagosa** [comment]
Oops... sorry again :(

**Comment by jmoenig** [comment]
this block context menu has become really complicated with all the special features that have been creeping into Snap over the years... :-/
