### ISSUE TITLE
"rename all" doesn't penetrate into rings

### ISSUE THREAD

**Issue by micahcowan** [jmoenig/Snap--Build-Your-Own-Blocks#1607]
This issue relates to the handy new "rename all..." feature on variables, introduced from pull request #1599 "Variable refactorer".

This issue appears in the latest master (as of ad9c4fe69c), and also in the original pull at 5117cd4a40

## To reproduce:

1. Create a new global variable, "foo"
1. Add a couple blocks to the editing area: a "set" block of foo, and a "run" block on a "set" block of foo within a ring: 
![image](https://cloud.githubusercontent.com/assets/4712979/21748828/f5ed61be-d543-11e6-9a70-742f2e15fb08.png)
1. Right-click on the "foo" global, and choose "rename all...", rename to bar.

## Expected results:
All instances of the global variable "foo", including those found within the ring, should be renamed.

## Actual Results:
The instance of "foo" inside the ring is left alone and not renamed: 
![image](https://cloud.githubusercontent.com/assets/4712979/21748835/3fd34794-d544-11e6-890a-84bd9d27cbf0.png)

**Comment by jmoenig** [comment]
Yes, you're right, it's a bug. only those variable references that are defined as inputs to the ring should be left alone.
