### ISSUE TITLE
 cannot refactor ring-parameter or reporter-upvar

### ISSUE THREAD

**Issue by jmoenig** [jmoenig/Snap--Build-Your-Own-Blocks#1610]
trying to refactor an explicit parameter of a ring fails and throws a JS error:

![ring](https://cloud.githubusercontent.com/assets/2596285/21808824/45ee9590-d745-11e6-8d09-369670fce5e2.png)

EDIT: The same applies to upvars of custom reporters.

**Comment by jmoenig** [comment]
Okay, this turns out to be surprisingly hard, I give up my attempt at a quick fix. The code seems to do many heuristics and the algorithm might need to be thought over and the code rearranged for this. @bromagosa , any idea for a quick fix?

**Comment by bromagosa** [comment]
Oh boy, let me try to fix this tomorrow, I'll spend the day on this.

For future releases, we definitely need to test much more exhaustively. Especially with features so intricate and with so many possible ramifications.

I'm sorry this code of mine is holding back the release :(

**Comment by jmoenig** [comment]
Naw, this isn't holding back the release, Bernat. It's a new feature so it doesn't break anything people are relying on yet.

**Comment by bromagosa** [comment]
Fixed in 3338b0f017407922a92b49fb7156325aee8f2771
