### ISSUE TITLE
SVG costumes should look crisp when scaled

### ISSUE THREAD

**Issue by liam4** [jmoenig/Snap--Build-Your-Own-Blocks#1611]
As you can see:

![size test gif](http://i.imgur.com/P6C20jz.gif)

..the sprite doesn't look as nice as you'd expect an SVG image to when upscaled/bigger.

**Comment by jmoenig** [comment]
I can't reproduce this. Are you sure it's an SVG and you don't have the (hidden) setting "rasterize SVGs" turned on?

**Comment by jmoenig** [comment]
Here's a quick test-project:

  http://snap.berkeley.edu/snapsource/dev/snap.html#present:Username=jens&ProjectName=SVG%20Scaling

this scales super-crisply for me. How about you?

**Comment by liam4** [comment]
Looks lovely to me. Turns out the creator of that image actually embedded a PNG image inside of the SVG! All's working good, it's really my fault for not taking a better look at the file contents.. Oops.
