### ISSUE TITLE
Canceling file selection dialog breaks logo menu

### ISSUE THREAD

**Issue by brollb** [jmoenig/Snap--Build-Your-Own-Blocks#1612]
First:
- Select `Import...` from the project menu
- Press `Cancel` from the file selection menu
Then:
- Click on the Snap! logo and the file selection menu pops up again (rather than the regular snap menu)

**Comment by jmoenig** [comment]
Excellent catch, and thanks for the fix. You're awesome!

**Comment by micahcowan** [comment]
Setting zIndex to a negative value on it also worked.

There's still the issue that (I believe?) every time you perform these steps, a new file-select input will be created and added to the DOM. Probably not a big deal, but maybe if a global is used to do it the first time, and checked for definedness, etc? Anyhoo...

**Comment by brollb** [comment]
@jmoenig thanks!

@micahcowan The IDE_Morph actually keeps track of the `filePicker` and removes the last one before creating a new one: https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/master/gui.js#L2794-L2797

**Comment by micahcowan** [comment]
@brollb D'oh! There it was, right at the top ^_^
