### ISSUE TITLE
Block editor opened while visible stepping has no "Apply" or "Cancel" buttons

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#1619]
see title

**Comment by jmoenig** [comment]
That's intentional and totally has to be that way, because when visibly stepping the editor is in "live coding" mode. Otherwise we wouldn't be able to step.

**Comment by brianharvey** [comment]
So, does that mean that if I drag a block into the editor it gets saved in the script right away?  I need to understand this, because at a minimum I have to document it.

But wouldn't it be possible to save a copy of the script so that Cancel could revert it?  And Apply would re-save the current state as the backup.

**Comment by jmoenig** [comment]
Yes, that's exactly what it means. In single-stepping mode everyting is always "live", because otherwise it couldn't step. You can use "undrop" to revert.
