### ISSUE TITLE
Changing costume says "rename background" even if not a background

### ISSUE THREAD

**Issue by DavidTheMage** [jmoenig/Snap--Build-Your-Own-Blocks#1631]
When I change a sprite's name it says "rename background" even if it isn't a background.

**Comment by jmoenig** [comment]
thanks for reporting this!

**Comment by jmoenig** [comment]
I've just fixed this. You can check it out in the dev version:
http://snap.berkeley.edu/snapsource/dev/snap.html

Again, thanks for the good catch!
