### ISSUE TITLE
Test a new version of the problem

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap--Build-Your-Own-Blocks#1635]
Ctrl+N Why open the browser? Instead of a new project

![325](https://cloud.githubusercontent.com/assets/20208703/22180921/090f6a0e-e0ba-11e6-8851-927ee8483f15.png)

Advantage "简体中文”

![3](https://cloud.githubusercontent.com/assets/20208703/22180920/08e7a10e-e0ba-11e6-9214-2e523466d589.png)

**Comment by liam4** [comment]
I believe Chrome on Windows actually captures a few keyboard commands (^N, ^T, and ^W) and *always* run their default actions (new window, new tab, close tab). So that's why ^N makes a new browser window rather than a new Snap*!* project.

**Comment by brianharvey** [comment]
Yeah, exactly.  There's nothing we can do about this. Run Firefox.

**Comment by cycomachead** [comment]
I really thought this _used_ to work in Chrome?

**Comment by bromagosa** [comment]
It used to, but it seems it doesn't any more. Sigh.
