### ISSUE TITLE
Touching <sprite> block checks not only for sprite, but also for all of its clones

### ISSUE THREAD

**Issue by Costor** [jmoenig/Snap--Build-Your-Own-Blocks#1636]
(1) If in the block < touching "sprite" >  "sprite" has been selected from the drop-down-box, the block will check not only against the original instance of "sprite",  but will also detect collision with clones of "sprite", if any.  
Question: Is this the expected behaviour (i.e. checking collisions with all instances of a sprite at once, and the drop-down-menu is actually giving sprite classes instead of the initial sprite instances) ?

(2) However, if "sprite" is stored in a variable (e.g. SpriteVar), the block < touching SpriteVar > will detect collisions with "sprite" only and will not detect touching of clones of "sprite".
If (1) is the expected behaviour, (2) would be the way to check for a particular instance?

See example:
http://snap.berkeley.edu/snapsource/snap.html#present:Username=Costor&ProjectName=TouchingClones

There might be a relation to issue 1383.

**Comment by brianharvey** [comment]
I agree that this is confusing.  We're going to revisit the whole issue of cloning soon in preparation for the 4.1 sprite-oop release.  Thanks for bringing up this point for discussion.

**Comment by jmoenig** [comment]
That's only confusing if you've never used Scratch. This behavior is one of the subtle but very sophisticated things that Scratch does which took a great effort to reproduce.

**Comment by brianharvey** [comment]
It's the combination of his two numbered points that confuses me, not (1) alone.

**Comment by Costor** [comment]
Got it. 
(1) is a feature from Scratch: the drop-down list actually lists the sprite "classes", tests against all instances
(2) is natural approach to address a particular instance of a sprite (be it original or clone) individually.
Obviously for sprites that do not have clones the behaviour is identical.
