### ISSUE TITLE
Make a block and list operations in the Variables section

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap--Build-Your-Own-Blocks#1637]
Why is "Make a block" in with variables? Why is "list"? And why are list operations nearly the same colour as  variable operations?

**Comment by brianharvey** [comment]
All that is inherited from Scratch, except for "Make a block" which is there by analogy with "Make a list" (which we don't have any more).  We're talking about maybe rearranging the palettes.

Variable orange and list red don't look "nearly the same" to me!  Of course they're close on the color wheel; what can I say, there are only so many colors.  Anyway the point is they're the Scratch colors for those categories.

**Comment by ToonTalk** [comment]
Scratch now has a more sensible scheme:

![image](https://cloud.githubusercontent.com/assets/2138696/22239947/a5141f68-e253-11e6-826b-1e8d950e7caa.png)
![image](https://cloud.githubusercontent.com/assets/2138696/22239965/c13a18f0-e253-11e6-9870-fa012bafe9b7.png)

**Comment by jmoenig** [comment]
Yep, I've noticed, too. The reason I'm resisting adding more categories is that in the grand scheme of things I want to let users and modules defines their own (and thus, unlimited) palette categories. This has been on my list for a long time and there are always other priorities sneaking in :-)

**Comment by cycomachead** [comment]
For reference there's exciting discussion at #377
