### ISSUE TITLE
If global and sprite var exist, checkbox shows the global one

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#1644]
Make a sprite variable.  Uncheck the box.
Then make a global variable in another sprite.  Uncheck the box.
Now go back to the first sprite and check the checkbox.  The watcher will show the global variable even though clicking on the oval next to it says the sprite-local value.

**Comment by jmoenig** [comment]
Hmm... I can't reproduce this one. For me it shows the sprite-local one...
