### ISSUE TITLE
Infinitely long shadow of block in editor

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#1650]
<img width="1143" alt="google chrome001" src="https://cloud.githubusercontent.com/assets/3885074/22528797/ad61898a-e889-11e6-92d6-c3267da17fd3.png">
What I did to make this happen was duplicate a block from the editor, try to drop it at the end, but the editor wasn't tall enough, so the block was dropped on top of its bottom border (overlapping a little bit with the actual editor though) so it wouldn't click in, then I resized the editor taller.  I was unable to grab and move the orphan block, and when I kept trying it gave this shadow.  (I eventually deleted the block in dev mode.)

We used to have a bug that looked like this, but it was fixed, so I think this must be a different one.

**Comment by cycomachead** [comment]
Yeah, I saw this once not too long ago, but couldn't reproduce it.

**Comment by jmoenig** [comment]
hmm.... I remember fixing this not too long ago, and - sure enough - I can't reproduce myself anymore. What's supposed to happen is the duplicated blocks that don't "snap" should slide over to the palette and vanish.

**Comment by jguille2** [comment]
Oh Yes! I can reproduce this.
  - Inside the block editor
  - If I **drag and drop onto the bottom editor area**, this blocks return to their original position (in the editor, the scripting area..) or they were destroyed (if they were from the palette or a duplicate action)
  - But if this **block is originated for a single duplicate action (blue bubble) from the editor script**, it is not destroyed (it appears kept  onto the bottom bar, in the beginning).
  - And this is the problem. This block is not a real instance and its behavior is wrong: shadow...

Joan

**Comment by jmoenig** [comment]
Can you explain this a little more in detail:

> if this block is originated for a single duplicate action (blue bubble) from the editor script

That's the part I'm struggling with. What's the "blue bubble"... ? Is it duplicating via the context menu?

I'd really like to fix this. Thanks!

**Comment by jguille2** [comment]
Oh sorry! It is not always blue... is the color block!
I want to say the "copy only this block" action, pictured with the block itself.

**Comment by jmoenig** [comment]
Ah, I see! Thank you @jguille2 , now I can fix it!!
