### ISSUE TITLE
Import the table view content

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#1652]
Hello,

I need to import the table view content.
Why I cannot simply do a copy-paste of the data calculated in this table ?
Is there another way ?
Thank you.

**Comment by brianharvey** [comment]
You are importing data from another program, like a spreadsheet?

Get the other program to write out a .csv (comma separated values) file.  Make a variable, right click on its watcher, select "import" and open the file in the dialog that appears.  Then
set (variable) to (split (variable) by [line])
The SPLIT block is in Operators, and "line" is one of the choices in its pulldown menu.  This will give you a list of lines.  Now
set (variable) to (map (split ( ) by [,]) over (variable))
This time you leave the first input of SPLIT empty (to be filled by the MAP) and type a comma in the second input slot.  MAP is in the tools library, so you have to "Import tools" first.

**Comment by nathalierun** [comment]
Not at all.
I am sorry. I made a mistake on the title of the issue. I wanted to say import locally to my computer.
(so export the table content ?).

**Comment by brianharvey** [comment]
Oh, I see.  Then you have to do the inverse process:
![make-csv](https://cloud.githubusercontent.com/assets/3885074/22627559/340a6df6-eb7a-11e6-9890-2ce93ead9145.png)
The MULTILINE block is in the next-to-last library in "Libraries..."  In its input slot you just hit the Enter key.  The two JOIN blocks have empty first and last inputs; the middle input of the first one is a comma.

After that you can right-click on the watcher on stage and select "Export..."

**Comment by nathalierun** [comment]
I tried to do that. But it does not work.

<img width="502" alt="capture d ecran 2017-02-06 a 19 46 09" src="https://cloud.githubusercontent.com/assets/17542520/22654154/52b2268c-eca5-11e6-943a-74571e838340.png">

I shared my project here :
http://snap.berkeley.edu/snapsource/snap.html#present:Username=nathalierun&ProjectName=Sierpinski.PS2.temp

**Comment by brianharvey** [comment]
The MAP block isn't quite right.  You dropped the "variable.export" block on the arrowheads, with a red halo showing.  That's why it says "input list:" and no arrowheads.  Instead make sure you drop the variable onto a list-icon input slot, when you see a white halo.

**Comment by nathalierun** [comment]
Hi, I'm sorry but I definitely cannot do it.

I first declared  "variable.export" block as a list.
![telechargement](https://cloud.githubusercontent.com/assets/17542520/22677433/e5fb6d16-ed0b-11e6-9041-781e98f96764.png) 
Then I still have an error message :
<img width="510" alt="capture d ecran 2017-02-07 a 07 59 38" src="https://cloud.githubusercontent.com/assets/17542520/22677370/79326630-ed0b-11e6-8136-5a82ac354ed3.png">

In fact, I don't understand what's happening when I do your how to. May I have a simple exemple please ?

**Comment by nathalierun** [comment]
I have this table to export :
<img width="620" alt="capture d ecran 2017-02-07 a 08 26 15" src="https://cloud.githubusercontent.com/assets/17542520/22677869/86f2ee26-ed0f-11e6-98e9-e982b9d9be44.png">
So I did this first :
![telechargement](https://cloud.githubusercontent.com/assets/17542520/22677876/8f14540a-ed0f-11e6-9b1d-5e9eb8a725f3.png)
And the last block still gives me an error :
<img width="519" alt="capture d ecran 2017-02-07 a 08 27 36" src="https://cloud.githubusercontent.com/assets/17542520/22677881/9fca2126-ed0f-11e6-91e1-c3e319b990b3.png">

**Comment by Jonathan50** [comment]
It doesn't work because MULTILINE's input is empty, so the ring wants to fill it. You need to put an empty line in the block (click in the input and press enter).

Also, COMBINE doesn't work with empty lists.

**Comment by nathalierun** [comment]
It works !

Merci beaucoup ;-)
