### ISSUE TITLE
How can a JavaScript block save a project to the browser's storage?

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap--Build-Your-Own-Blocks#1655]
And also open such a project? And do so without any dialogs popping up.

**Comment by liam4** [comment]
There's lots of methods, but I think one of the most frequently used ones currently is via `localStorage`:

```js
localStorage.foo = 123

// Some time later, even after a reload..
alert(localStorage.foo) // 123
```

Do keep in mind that localStorage is local to each page (..or folder, or something..), and all Snap<i>!</i> projects run on the same page, they share the `localStorage`. So you'll want to avoid conflicts somehow; prefixing all your localStorage variable names could work:

```js
localStorage['toontalk--example-1-project--foo`]
```

..but that's awfully inconvenient, so perhaps make some custom blocks to do it for you? (They'd get the project's creator and title, and concatenate those as I showed above, and finally append the variable name, then set or get that.)

**Comment by ToonTalk** [comment]
Thanks but I was thinking of how to interface to the capability that Snap! already has when you save a project to the "Browser".  I assume it uses localStorage but deals with the work of generating a string that represents the current state of the Snap project.

**Comment by liam4** [comment]
Oh. Duh. Sorry for misreading the post.. :)

**Comment by ToonTalk** [comment]
I've discovered that

`world.children[0].saveProject("some name")`

saves a project. And

`world.children[0].openProject("a name")
`
opens it.

My question is whether there is an more "official" way of doing this? And if not can I depend upon this continuing to work (i.e. will IDE_Morph always be the first child of 'world'?).

**Comment by bromagosa** [comment]
Ideally, you shouldn't be traversing any children array by index to do that. A better way to do it would be:

    var ide = this.parentThatIsA(IDE_Morph);
    ide.saveProject('whatever');

**Comment by cycomachead** [comment]
> My question is whether there is an more "official" way of doing this? And if not can I depend upon this continuing to work (i.e. will IDE_Morph always be the first child of 'world'?).

As far as Snap! goes, this IDE will be the first of a world, and if you're trying to access it from _outside_ of Snap! (i.e. Additional JS scripts or the console) then that's currently the best way. From within a Snap! context Bernat's suggestion is correct. Not that dialog boxes aren't children of the IDE but of the world - in those cases they should be initialized with a pointer to the IDE, though I forget the convention. 

In the future, this might change, but I think we'll document when it changes. (It's a internal thing, but I know many projects do rely on it.)

**Comment by jmoenig** [comment]
yep, @bromagosa and @cycomachead are definitely right that the preferred way is to crawl up the Morphic tree until you hit the IDE, rather than relying on the first child of the World always being the IDE, because this might change in future version where there might be several IDEs in a Morphic World (e.g. so we can move assets back and forth between projects, and also so we can clone whole projects etc.).
