### ISSUE TITLE
strange behaviour of local and global variables

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#1656]
Hi,
According to a friend's mail (this friend -Eric Hakenholz- is a java developper and developped CarMetal and DGPad, see [carmetal.org](https://carmetal.org)), I made this little test.

I have two sprites : chat and ballon.
I create two variables in chat : one for all sprites : "globale", one only for chat "propriete".
Then I create this script for the sprite chat
![telechargement 1](https://cloud.githubusercontent.com/assets/17542520/22686216/a25684e8-ed3c-11e6-9caf-2b093896e6e4.png)

In ballon, I have this script
![telechargement 2](https://cloud.githubusercontent.com/assets/17542520/22686204/9b05d694-ed3c-11e6-953c-a6d398855cc7.png)

At the end of the scripts,  I get this
<img width="291" alt="capture d ecran 2017-02-07 a 13 54 30" src="https://cloud.githubusercontent.com/assets/17542520/22686305/056f2468-ed3d-11e6-817f-6bc240a13d14.png">

The 19 value of chat propriete is strange.
My friend says that it comes from a collision...

Here is a post he wrote on forum Scratch about Object-oriented programming.
https://scratch.mit.edu/discuss/topic/238605/?page=1#post-2434911

I shared the little project
https://snap.berkeley.edu/snapsource/snap.html#cloud:Username=nathalierun&ProjectName=Script.Test.POO

**Comment by bromagosa** [comment]
The behavior looks consistent to me, you're sending a global message that's going to be intercepted by all objects in the Stage.

What were you expecting instead?

**Comment by bromagosa** [comment]
Oh, now I get it. You were expecting the space event to be received by all the clones, so that `chat propriete` would be decremented 10 times as well, is that it?

**Comment by nathalierun** [comment]
Yes, it seems that '''chat propriete should have the value of 10.

**Comment by jmoenig** [comment]
that's a script reentrancy issue, same as in Scratch. Snap does not queue boradcast messages. Events are *not* "messages" in the OOP sense in Scratch, even though calling them "messages" gets teacher all excited about OOP all the time, but it's a misconception.

However, Snap does offer a more "OOP" way to define and invoke methods in other sprites, and that one actually does what your friend Eric Hakenholz (btw, I admire him, he's a great pedagogic programmer) expects. Here's a version of Eric's / your project in Snap that addresses your issue:

https://snap.berkeley.edu/snapsource/snap.html#cloud:Username=jens&ProjectName=method%20invokation

Does that makes sense?

**Comment by erichake** [comment]
Thank's a lot Jens,

I replied to you on the scratch forum, and yes your project makes sense (and actually a lot of sense !). You've done a really great job programming this object.method mechanism : now I'm absolutly convinced that I will use snap! with my pupils...

**Comment by nathalierun** [comment]
@jmoenig 
I'm very happy today because I think that your simple example has finally convinced all my friend's (teachers) to use Snap! in their french classes. 
The most important of them, of course, to be convinced was Eric. Because now, the others look at Snap! with a different point of view...

**Comment by jmoenig** [comment]
Thank you both very much, @nathalierun and @erichake, for focusing on the OOP issue here. As it just so happens, Brian and I are *right now* discussing the next steps towards enabling "full" OOP support in Snap, so this actually helps us!
