### ISSUE TITLE
Options to open a project using an URL

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#1658]
Hello,

When I open a project, I do for example :
http://snap.berkeley.edu/snapsource/snap.html#present:Username=nathalierun&ProjectName=ChasseAuTresor.Simulation

I saw once that I could also do :
https://snap.berkeley.edu/run#cloud:Username=nathalierun&ProjectName=ChasseAuTresor.Simulation

And also :
http://snap.berkeley.edu/snapsource/snap.html#cloud:Username=nathalierun&ProjectName=ChasseAuTresor.Simulation

Where can I find a documentation on those options please ?

**Comment by brianharvey** [comment]
In the mostly-done revision to the reference manual

**Comment by liam4** [comment]
> In the mostly-done revision to the reference manual

Ohhhh, is that public yet? Or are you waiting to finish it up before releasing it?

**Comment by nathalierun** [comment]
In fact, I've found the information here :
http://snap.berkeley.edu/snapsource/BlockEnhancementsInSnap.pdf
Page 15.

Thank you @jmoenig for this nice documentation !!!
I am totally amazed by the new interface command  ''' Find blocks...

**Comment by brianharvey** [comment]
@liam4 Give me a week or so; I have something almost in one piece.
