### ISSUE TITLE
rearrange listing of user created blocks

### ISSUE THREAD

**Issue by jcaldw737** [jmoenig/Snap--Build-Your-Own-Blocks#1664]
It looks like user created blocks are listed in the order they were created.  Is there a way to change that order?

**Comment by cycomachead** [comment]
No, not really. It's on the list of considerations for things that might happen someday, but so far it hasn't been a priority.

If you really want, you can export your project and manually edit the XML. If you reorder the XML then they blocks will be loaded in the new order.

**Comment by jcaldw737** [comment]
Thank you very much! That is just what I needed!
