### ISSUE TITLE
FTP or ssh access for a user on your cloud

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#1668]
Hello,

I have a lot of projects on your cloud and I want to share the majority of them to my students.
I don't want to do it one by one. It would be very very long.
Could you give me a FTP or ssh access to my user directory (nathalierun) please ?

It would be so great !

**Comment by bromagosa** [comment]
I'm afraid there is no such thing, the SnapCloud is not a "traditional" storage system :)

I believe you could however build a Snap<i>!</i> project that iterates over your projects and shares them.

**Comment by nathalierun** [comment]
Le 21/02/2017 à 14:39, Bernat Romagosa a écrit :
> I believe you could however build a Snap/!/ project that iterates over 
> your projects and shares them.

I thank you for this suggestion. But I don't know how to do that.

**Comment by bromagosa** [comment]
These are quite dangerous grounds, so I'm not sure I should be posting this publicly... but here's a block that does that for you:

[share all.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/793299/share.all.zip)

Notice that the block runs in the background, so you'll need to click on it and let it run for a while until the last project is shared.

**Comment by nathalierun** [comment]
Le 22/02/2017 à 16:12, Bernat Romagosa a écrit :
> until the last project is shared.

It worked ! Thank you very much.

You are not going to be disappointed, because I am working on a galery 
projects.
Coming soon...
