### ISSUE TITLE
Problems to open Snap's links in Safari and Firefox

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#1679]
Hello,

I have problems with Snap's links for a while. I don't understand why.
Juste see (the link was for the example http://snap.berkeley.edu/snapsource/snap.html#present:Username=nathalierun&ProjectName=ChasseAuTresor.Simulation1):

With Firefox

<img width="1089" alt="capture d ecran 2017-03-09 a 13 51 27" src="https://cloud.githubusercontent.com/assets/17542520/23745781/fc709556-04d2-11e7-88df-1e7f88782834.png">

With Safari

<img width="1043" alt="capture d ecran 2017-03-09 a 13 50 56" src="https://cloud.githubusercontent.com/assets/17542520/23745787/02af5754-04d3-11e7-9d14-457834c553ce.png">

I work actually on a mac OSX  under 10.11.6

Do you see how Safari has modified the original link ?

What can I do ? It works well with Chrome.

**Comment by brianharvey** [comment]
This sounds like a brief network failure.  Is it still happening?

Don't worry about the changed URL in the Safari error message; it's a harmless bug in the way Safari formats the URL to include in the message.

**Comment by nathalierun** [comment]
Le 09/03/2017 à 21:46, Brian Harvey a écrit :
>
> This sounds like a brief network failure. Is it still happening?
>
No. It works now. I think that the problem was in my local network. (I 
restarted my routeur...)
>
> Don't worry about the changed URL in the Safari error message; it's a 
> harmless bug in the way Safari formats the URL to include in the message.
>
Ok, thank you.
