### ISSUE TITLE
Codification bug?  Map TRUE to code true always returns false

### ISSUE THREAD

**Issue by zeroturn** [jmoenig/Snap--Build-Your-Own-Blocks#1683]
I just discovered codification in snap and have been experimenting with it.  I created a script as follows:

![image](https://cloud.githubusercontent.com/assets/13770851/24056477/df4ff152-0b11-11e7-9926-0317a15653c1.png)

My intent is to look at the code that is produced.  I intend that the boolean value will be true.  Yet, the python script that is generated sets the boolean to false:

![image](https://cloud.githubusercontent.com/assets/13770851/24056569/3d3e2f4a-0b12-11e7-81d6-5bac1aa8c7a1.png)

This actually happens regardless of the language that is selected (except "smallTalk" which returns 

`false ifTrue: ...`

which I don't understand.

I have tried editing the block, but it produces the same code even when I redefine the block like this:

![image](https://cloud.githubusercontent.com/assets/13770851/24056894/5914025c-0b13-11e7-85a2-21bf0be8bff2.png)

This seems like a bug to me.

**Comment by jmoenig** [comment]
Aha, good catch, that's a bug, indeed!
I changed the former ```true``` and ```false``` reporters to a single Boolean reporter with a switchable value, hence the reporter now only maps a single thing with a variable input, which doesn't help much. the solution is probably to introduce an explicit mapping for TRUE and FALSE values.
I'll put it on my list.
Thanks!

**Comment by zeroturn** [comment]
I just discovered that when I click on "code mapping" for the true/false reporter in the Codification examples, the "code mapping" is set to false.  But if I click on the code mapping in another project, the code mapping for the true/false reporter is blank.

**Comment by jmoenig** [comment]
this has been fixed in v4.1
