### ISSUE TITLE
codification question:  how do I access name of selected function in advanced math operator?

### ISSUE THREAD

**Issue by zeroturn** [jmoenig/Snap--Build-Your-Own-Blocks#1690]
I've been playing with the codification examples project.  I'm trying to enhance the python and javascript mapping functions to handle the advanced math operator.  I simply plan to insert an if/then (or case/select) block something like this:
`
case 'sqrt'
  Math.sqrt(<#1>);
case 'abs'
  Math.abs(<#1>);
etc, etc
`
How do I "capture" the name of the function that the user selected?

By the way, I recognize that this is an "issues" page and may not be the place to merely ask questions.  Let me know if I should go somewhere else.

**Comment by brianharvey** [comment]
It's an input.  The block takes two inputs: the function name, and the number.

[https://scratch.mit.edu/discuss/topic/4455](https://scratch.mit.edu/discuss/topic/4455) is a good place to ask questions; more people read it than read issues here.
