### ISSUE TITLE
Why so many write-only variables?

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap--Build-Your-Own-Blocks#1692]
A few sprite properties such as size, costume number, direction, x and y have variables that can be read. But most properties are write only. Examples are pen color, pen shade, pen size, and visible (show/hide). And maybe one should include all the looks effects, the z-ordering layer,  bounce-if-on-edge, etc.

This seems like an odd design that forces one to introduce redundant variables.

**Comment by brianharvey** [comment]
Yes.  Jens won't let me change this until the new OOPy sprites in 4.1, but eventually all attributes will be readable and writeable.
