### ISSUE TITLE
Remove some native blocks from the Snap blocks area

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#1694]
Hi, 

I am working on operators to prepare a lesson to my students.
I think there is something strange here :
![capture du 2017-03-24 14-45-09](https://cloud.githubusercontent.com/assets/17542520/24291724/95a3fb24-10a3-11e7-9cdf-373347904e82.png)
The native operators disappeared from the left side of Snap screen.

I notice also that I cannot view correctly the inside of this table :
![capture du 2017-03-24 14-46-03](https://cloud.githubusercontent.com/assets/17542520/24291815/00485420-10a4-11e7-88fe-2da6d9b9d88c.png)

Finally, I have an **important request** to do :
In order to simplify the use of Snap for earlier beginners, or to prepare some tests for students and to oblige them to use specific blocks, would it be possible for the user to remove some native blocks from the left side of Snap screen ?

Thank you for any answer.

**Comment by nathalierun** [comment]
Sorry, I just found by myself how to make native operators come back to the screen area...

**Comment by nathalierun** [comment]
@brianharvey 
Hello, I think that you closed this issue a little bit fast because, 
1. what do I do with my table on which we cannot access the results ?
2.

**Comment by brianharvey** [comment]
1.  If you click and drag rightward in the header row (the one with A B C D) you can resize the columns.

2.  If you right-click (control-click) a primitive block in the palette, one of the options is Hide.  If you right-click in the background of the palette, you can hide all the primitive blocks of that category.

Was that what you needed?

**Comment by nathalierun** [comment]
Yes for both ! I didn't know those functionalities. thank you.
And now, if I spend a lot of time to prepare a Snap! environment from which I removed a lot of blocks, how can I save this configuration, in order not to repeat this specific configuration again.

To do short, is there another way then saving the project, as in a lot of softs to save the configuration (something like .config ) ?
Moreover, is it possible to personalize the colors of the primitive blocks ?

**Comment by jguille2** [comment]
Hi @nathalierun,
  - The "hidding" info of the primitive blocks **is stored into the project**. Then, you can save a project like a **template**. For me, this is important. The start point of more didactic activities is a template: hidding some blocks, adding other custom blocks, maybe some comments with info... And every teacher build his own basic templates ( a general config for their students: little kids, hight school...) to build later the more concrete activity templates.
  - To personalize color blocks is more hacking... and maybe it is not a good idea. You can hack your IDE with JS. And then you can launch start scripts in your project to do this job. If you want to play... an example is:
![hacking_palette](https://cloud.githubusercontent.com/assets/2926315/24343931/5d61324a-12c9-11e7-8ef0-d7cf20671b56.png)
This changes _motion_ category color with the _sound_ category one. You can play with this to learn more about Snap IDE... and after this, you can evaluate if it is worth it.

Joan

**Comment by brianharvey** [comment]
Yeah, just hide a bunch of blocks and save that as a project.  Then you can load that as a starting point for projects that actually do something.

As for changing block colors, in my humble opinion that's a _really_ bad idea.  There are millions of Scratch kids out in the world who know which color is which.   You don't want to confuse them.

**Comment by nathalierun** [comment]
@jguille2 : I note your idea to make my own templates for my students. I am going to do that now.

@brianharvey : you are right. It was *really* a bad idea to change colors blocks because of kids accustomed to using Scratch.
