### ISSUE TITLE
[very minor] stream library says "prime number block is included as an example"...

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap--Build-Your-Own-Blocks#1704]
...but it's not, only the stream blocks load. Which begs a larger question whether it's ever possible to have examples included in libraries somehow. (I suppose we'd just put them in the examples directory?) I would like to have the prime number stream included in the Examples, Brian... -Dan

**Comment by brianharvey** [comment]
But it is.  The block is called SIEVE.  (Same as in SICP!☺)  I'll fix the comment if I find it.

**Comment by ddgarcia** [comment]
Great. What I would do is make the stream blocks lists color. Then make three other blocks with the grey "Other" color (you already included sieve, but you didn't color it grey):
sieve(stream)
Integers starting from(n)
primes()
...so that you actually do show how we use these in such an elegant way. And make sure you add a link to https://mitpress.mit.edu/sicp/full-text/sicp/book/node71.html in a comment within the primes block. Thanks! -dan
