### ISSUE TITLE
Link to a project when you are on a localhost instance of Snap!

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#1709]
Hi,

I cloned with git Snap! into my Mac. Now, I want to run a local instance of my projects because I have a presentation to do at the University next week, and I cannot be sure of the Internet connexion. I don't want ro take any risk.
So I wonder how to reach for example a project named *ManyBalls.xml*

My own instance of Snap! is here :
http://localhost:8888/Clone.Snap/Snap--Build-Your-Own-Blocks/snap.html

And I tried this:
http://localhost:8888/Clone.Snap/Snap--Build-Your-Own-Blocks/snap.html#present:ProjectName=ManyBalls

And it does not work.

How can I access my own project, locally ?
Where do I have to put my projects in the local instance of Snap! ?

Thank you in advance for your answer.

**Comment by jmoenig** [comment]
Ni Nathalie,

great idea! You can use 

* ```#run:``` (immediately runs your project in presentation mode) or 
* ```#open:``` (shows it in edit mode without directly running it).

the project url can be relative to the one your localhost web server points to, e.g. ```demo/dogwald.xml````

I just tried this myself on my own computer and it worked. Please let me know if you run into issues with this approach.

**Comment by jmoenig** [comment]
This is for Chrome. If you're using Firefox, you can also just open Snap locally (without a local web server), and it should just work.

**Comment by jmoenig** [comment]
getting there: This is *clearly* a Canvas issue. I can consistently reproduce it by opening a console and typing in

```world.worldCanvas.getContext('2d').getImageData(0, 0, 1, 1)````

this immediately slows everything down, and the slowdown doesn't get away until I get a new canvas, which happens when I resize the browser.

I hate Google.

**Comment by nathalierun** [comment]
Thank you Jens !!! 
It works.
I was just testing about the execution speed.  I notice that my recursive Sierpinski project seems to run lower than on line. Is this because of my processor ?

I have another thing to do : I want to get all my projects back home. Because I did many of them directly on your cloud.
Is there any javascript command I could write in Snap! to download all my projects ?

**Comment by nathalierun** [comment]
~test~

**Comment by nathalierun** [comment]
~ test ~

**Comment by nathalierun** [comment]
```tyty
```

**Comment by jmoenig** [comment]
hmm... If you downloaded the current *release* from Github, or the sources from the "about..." menu in Snap, there should not be any slowdown, because that *is* the current version. If you forked the current state of the Github repo that might be slower or even partially broken, because it's the "bleeding" edge in-development version.

Naw, we don't yet have a batch-download-all-projects function for the cloud. Sorry!

**Comment by nathalierun** [comment]
Hi,
ok, I note this.

And now, I wonder whether I could open an url with *open:* , like this :
http://localhost:8888/Clone.Snap/Snap--Build-Your-Own-Blocks/snap.html#open:*myurl*
where *myurl* could be for example https://nathalierun.net/snap/ManyBalls.xml ?

Thanks for any help.

**Comment by nathalierun** [comment]
Hi,

I notice that when I open a project on your cloud, the project keeps memory of the block size you gave to it before saving the project.
But in my local instance of Snap!, it doesn't.

Is there a way to put the size of the blocks you want in the url adress which open the project ?
(something like sizeblocks= )

Thanks for any help.

**Comment by bromagosa** [comment]
Hi Nathalie,

it's not the project that remembers the block size, it's the Snap! instance. If you change the block size in http://snap.berkeley.edu/run, it'll stay that size for every project you open there. The same is true for your local instance. This is an IDE setting, not a project setting.

I'm afraid there's no URL parameter to specify a block size.

**Comment by nathalierun** [comment]
Hello @bromagosa .
Ok, I note that. Thank you for your answer.

Where can I find a documentation about all the parameters you can set when you open an url with snap ?
Actually, I just know : present, cloud, run and open. 
Does other parameters exist ?

**Comment by bromagosa** [comment]
Hi @nathalierun. You're missing two hash parameters: `#dl` to download a project from the cloud and `#lang` to set the language. 

Additionally, there are a bunch of ampersand parameters:

`&editMode` → opens the editor instead of presentation mode
`&noRun` → doesn't fire the green flag event automatically
`&hideControls` → hides the green flag, pause, stop and minimize buttons (makes sense for embedding)
`&noExitWarning` → removes the warning when you close Snap<i>!</i>

**Comment by jguille2** [comment]
Thanks Bernat,

I didn't know these other hashes.
Just write down a suggestion:
  - I'd like _lang_ as a parameter (_&lang=xx_). Then, we could use it with all the others (opening a project...)
  - _#dl:_ hash is running... but I think browsers open the result in an ugly way. Maybe you can add the "download" param to the URL to implement it better.

Joan

**Comment by nathalierun** [comment]
Hi @bromagosa,

Thank you for these _precious_ informations.
I did'nt know about those possibilities.

Would it be possible to associate a block size to a project ? (like *&size=xx*).

I agree with @jguille2 : It would be wonderfull if *lang* was a parameter.

Nathalie
Nathalie

**Comment by nathalierun** [comment]
Hi @bromagosa,

May I have an example with the hash parameter *#dl*.
I'ld like  for example to load a project on your cloud with another instance of Snap!

I tried this :
https://snap.dgpad.net/snap.php#dl:"https://nathalierun.net/snap/Snap.Galerie/ChasseAuTresor/ChasseAuTresor.Simulation1.xml"

Snap! tells me "Fetch from the cloud" but it never finishes.

What is the direct link to one of my projects on your cloud please ?
For example ChasseAuTresor.Simulation1.xml on username ~nathalierun~.

**Comment by bromagosa** [comment]
The `#dl` hash parameter is only used to download projects from the cloud into your hard drive, not to fetch them into your editor. To fetch them you need to use the regular `#open`, `#present` or `#cloud` parameters, as you were already doing. Isn't that working for you?

There is no direct link to a project, the Snap<i>!</i> cloud is not an FTP that stores and serves files, it's a database system that you access via API calls. You need a Snap<i>!</i> instance to fetch a project, you can't do that directly via a URL.

What is it that you're trying to accomplish? I'm sure there's a simpler solution that doesn't involve using any mix of parameters.

p.s. The cloud is not "mine", it was built (and is being maintained) by MioSoft :)

**Comment by nathalierun** [comment]
Le 11/04/2017 à 12:26, Bernat Romagosa a écrit :
> What is it that you're trying to accomplish? 

Hi,

I want to load a project on a server A from an instance of Snap 
installed on a Server B.

What is the exact syntax to do that please ?

**Comment by jmoenig** [comment]
Hi Nathalie,

loading a project that is stored on your own server - not on the SnapCloud - works just like described in this thread using the #run: or #open: hashes followed by a url that has to be reachable by the client. If you're storing your project on one server and run Snap on another I guess you're going to have to set it up in a way that you can reach the project-server. If that is the case, i.e. if you can make a reachable url to the project, you can just use that in the client running on another server. (Hmmm..., I'm sounding somewhat gibberish, does it make sense to you?)

the #dl hash is really just a shortcut to help me debug occasional issues with the souce format and only works for projects stored in the SnapCloud.

**Comment by nathalierun** [comment]
Hi Jens,

This link is accessible :
https://nathalierun.net/snap/Snap.Galerie/ChasseAuTresor/ChasseAuTresor.Simulation1.xml
but I can't open it with Snap doing this :
http://snap.berkeley.edu/snapsource/snap.html#run:"https://nathalierun.net/snap/Snap.Galerie/ChasseAuTresor/ChasseAuTresor.Simulation1.xml"

I have this error :
<img width="444" alt="capture d ecran 2017-04-11 a 16 44 29" src="https://cloud.githubusercontent.com/assets/17542520/24909776/60f71a14-1ed6-11e7-86ea-520c646889b4.png">

**Comment by bromagosa** [comment]
Hi Nathalie,

it seems your server hasn't added snap.berkeley.edu to the CORS policies whitelisted domains. How to do that will depend on your particular server setup. Which one are you using?

As a temporary workaround, here's what you can do:

http://snap.berkeley.edu/snapsource/snap.html#open:http://crossorigin.me/https://nathalierun.net/snap/Snap.Galerie/ChasseAuTresor/ChasseAuTresor.Simulation1.xml

**Comment by nathalierun** [comment]
Thank you @bromagosa 
This link works well.

I'll ask to my web host (OVH.com) how I can add snap.berkeley.edu to the CORS policies whitelisted domains.
