### ISSUE TITLE
Snap! Variable Scrolling

### ISSUE THREAD

**Issue by Knesse** [jmoenig/Snap--Build-Your-Own-Blocks#1713]
I have created enough variables so that when I click on set VARIABLE to – , all of my variables do not show on the list. The list is longer than the height of my browser even in Full Screen. I really need a scroll option.

**Comment by UnnamedMinecrafter** [comment]
maybe it would help to use the 
![grafik](https://cloud.githubusercontent.com/assets/27627336/25071876/59403ae0-22c2-11e7-9bb9-de50cdd80613.png)
block

**Comment by Knesse** [comment]
Okay. I managed to rename variables so it would function, but it is still a
serious hassle.

**Comment by jmoenig** [comment]
If you have so many variables you might want to consider a list...

**Comment by brianharvey** [comment]
I vote that all menus should be scrollable.  I was kind of surprised to learn that there isn't just an isScrollable variable in Morph, but would it work for MenuMorph to inherit from ScrollFrameMorph?

**Comment by jmoenig** [comment]
scrollable menus are on my not-so-long-term list :-) I've implemented them for GP and will just back-port that code

**Comment by Knesse** [comment]
Okay cool. And i dont have a lot of lists. I suppose i dreamed too big lol.

**Comment by micahcowan** [comment]
> Okay cool. And i dont have a lot of lists. I suppose i dreamed too big lol.

Well, of course a project of any size or ambition should ideally be supported by _Snap!_ (at least, up to any limits that the browser allows).

I think what others were trying to get at is that there are better ways to organize your code, and that it's generally undesirable to have a huge set of project-global variables in even large projects: better to use script-local variables (which don't show up in the side list at all), or when necessary, sprite-local variables (which show up in the list, but only for the specific sprite you're viewing).

These techniques can generally help organize your data better. Lists-of-lists, sometimes called "alists" or associative lists, where you have [ [ "key", "value" ] ] structures, are also a good way to organize data, with the disadvantage that there's usually a performance penalty for those, especially if the list gets quite large.

**Comment by cycomachead** [comment]
Closing because #349 #1005 #1772
