### ISSUE TITLE
Problems to open some projects in localhost

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#1716]
Good morning.

I prepare a presentation I have to do on next wednesday. And I can't open some projects but I can open others. I don't understand what's going on.

For example : this link works :
http://localhost:8888/Clone.Snap/Snap--Build-Your-Own-Blocks/snap.html#run:Projets.xml.Local/SpiraleEnTriangle.Couleur.xml

but this one doesn't :
http://localhost:8888/Clone.Snap/Snap--Build-Your-Own-Blocks/snap.html#run:Projets.xml.Local/SpiraleEnTriangle.xml
I have an error message : "Load failed : error..."
<img width="346" alt="capture d ecran 2017-04-08 a 09 44 31" src="https://cloud.githubusercontent.com/assets/17542520/24826132/0630fd0e-1c40-11e7-9cce-e7260b8272af.png">
but if I take my project and put it down into my local IDE, it works.

I have this problem with many of my projects. 

You can see those projects here 
https://snap.berkeley.edu/snapsource/snap.html#present:Username=nathalierun&ProjectName=SpiraleEnTriangle
https://snap.berkeley.edu/snapsource/snap.html#present:Username=nathalierun&ProjectName=SpiraleEnTriangle.Couleur

Thanks for any help.

**Comment by jguille2** [comment]
Hi @nathalierun ,

I've tested with _SpriraleEnTriangle.xml_ and I had no problem with this project, and I ran it from local source.
The error message (_Load failed: Error:Expected..._) is just the same where the fileName is wrong. You must check the path. And take care about CaseSensitive (upper or lower case is important).

Can you check this?

**Comment by nathalierun** [comment]
Hi @jguille2 ,

First of all thanks for your help.
It seems that I had several corrupted files among my xml projects. Very probably because of my internet connection which is not always reliable. 
I need to download again  my projects  from your cloud but I cannot reach your server since this morning in Reunion island (friday night for you). How can I do ?
*Notice that I have problems to reach your sever since a couple weeks on weekends.*

**Comment by jguille2** [comment]
Hi @nathalierun,

Only note that I'm not from Berkeley (I'm from Barcelona, with less time difference :smile: ) and I can't tell you much about the servers changes.
But it's strange... I have no problems connecting to SnapCloud... and I don't hear about these weekend problems.

Anyway, if you have problems connecting... report here. They can check servers if you report specific error data... and we can help you to succeed in Wednesday presentation (although maybe many of us are on Easter holidays :church:)

Joan

**Comment by nathalierun** [comment]
Le 10/04/2017 à 05:12, Joan Guillén i Pelegay a écrit :
> we can help you to succeed in Wednesday presentation 

Thank you @jguille2.

My local instance of Snap! works find now and yesterday, I could 
downloaded from the cloud all projects that I need.

**Comment by nathalierun** [comment]
@jguille2 

Just to tell you that my Wednesday presentation worked well.
It were based on this Zero version of a future snap image gallery :
https://nathalierun.net/snap/Snap.Galerie/

Nice Easter holidays...

**Comment by bromagosa** [comment]
Cool collection, Nathalie! And glad to hear your presentation went well :)

(Can we close this issue?)
