### ISSUE TITLE
Comment contents disappeared when pasting in URL from another browser page

### ISSUE THREAD

**Issue by zeroturn** [jmoenig/Snap--Build-Your-Own-Blocks#1717]
A minor annoyance.  I created a (rather long) comment in one of my projects.  I attempted to paste a reference URL into the comment.  The entire contents of the comment disappeared.  I was unable to "undo" or otherwise recover the lost content.

**EDIT**:  Well, I take that back.  I discovered that if I collapsed the comment and then expanded it again, the contents reappeared.  Never mind.  (I'd delete this issue if I could.)

**Comment by jguille2** [comment]
Hi @zeroturn,
[Ctrl] + [Z] is running ok for me!
