### ISSUE TITLE
Twitter presence

### ISSUE THREAD

**Issue by ghost** [jmoenig/Snap--Build-Your-Own-Blocks#1720]
On Twitter I see a lot of discussion related to Scratch (@scratch, @scratchedteam, etc). It helps me keep up to date with the Scratch community. I'm wondering if there is something similar for the Snap language?

**Comment by jmoenig** [comment]
Hmm... good point. I'm basically tweeting about little else myself...

**Comment by bromagosa** [comment]
But that's right, having a @Snap account would probably make the project more visible.

**Comment by cycomachead** [comment]
So, there is a MioSoft owned `@SnapCloud`. `@moenig` is Jens' handle, and otherwise the BJC twitter account `@CSPBJC` has some relevant stuff at times. 

I also own `@SnapBYOB` but don't use it for anything, but it is available for usage.

**Comment by robtougher** [comment]
Would you guys mind if I created a handle to start discussing snap? I would clearly state non-affiliation. I'll be teaching snap for at least the next high school year (2017-2018) and it would be useful to have a place on twitter to talk about stuff with other users. At teals we have several hundred people using the language for hs teaching.

**Comment by robtougher** [comment]
Never mind, I think for now I'll just tweet from my personal account. :)

Though I still think it would be valuable for you to start tweeting from an official snap handle.

**Comment by jmoenig** [comment]
just to let y'all know: The SnapCloud twitter handle is now under our own control and - as of yesterday - operated by @jadga-h . Yay!
