### ISSUE TITLE
Variable watcher rounds small float to zero [solved]

### ISSUE THREAD

**Issue by Silt-Strider** [jmoenig/Snap--Build-Your-Own-Blocks#1721]
I wanted to make a constant variable, the "Gravitational constant" that is 6.674*10^-11, sadly the program just printed 0, when I switched to  6.674*10^-10 it was able to print 1e-9. :(
Probably not a bug, but I should still be able to have small variables.

**Comment by zeroturn** [comment]
I was able to use the "Gravitational constant" successfully in the code below.  

![small_numbers](https://cloud.githubusercontent.com/assets/13770851/25064211/4449089a-21bb-11e7-89a5-542dad1c1fde.jpeg)

Both scripts returned the same value (which I checked with a calculator!)  Perhaps it is another problem.  It's possible that in the way you have used it, the number was interpreted as text, and then converted to 0 when you used it as a number ... (Though your successful use of 1E-9 seems to rule that out ;-(    )

**Comment by UnnamedMinecrafter** [comment]
you need to use the infinite precision integers library go to file --> Libraries... --> then choose the last library --> import
now just drag the USE BIGNUMS block from the Operators and 1.click on <  > 2.click on the block itself to activate it
now your project should calculate properly

**Comment by brianharvey** [comment]
No, infinite precision _integers_ won't change the behavior of floating point representation.

Scientific notation is entered as dddddEddd not dddddx10^ddd.  It's not quite clear from the text whether or not the OP was expecting the latter to work.

It seems to me that there _is_ a small problem here, namely the variable watcher rounding to zero.  Changing title accordingly.

**Comment by Silt-Strider** [comment]
I didn't expect to see such nice answers, since I had a way to work around it, and started playing with other engines such as Unity and GMS2. Thanks anyways ^^
