### ISSUE TITLE
two not distinguishable table that act differetly

### ISSUE THREAD

**Issue by UnnamedMinecrafter** [jmoenig/Snap--Build-Your-Own-Blocks#1724]
just look in the code and you will see that the two tables should be exactly the same but the second one misbehaves when replacing any item
<details>
  <summary>Code:</summary>

[project](http://snap.berkeley.edu/snapsource/snap.html#present:Username=unnamedminecrafter&ProjectName=List%20Bug) contains even more broken functions
also breaks without "random"

![grafik](https://cloud.githubusercontent.com/assets/27627336/25071744/38f1ad4e-22bf-11e7-81c5-2a54c3ba1e9b.png)
</details>

<details>
  <summary>Result:</summary>

![grafik](https://cloud.githubusercontent.com/assets/27627336/25071635/c99dd974-22bc-11e7-8e14-c3157379b374.png)
</details>

<details>
  <summary>Result without "table support" checked</summary>

![grafik](https://cloud.githubusercontent.com/assets/27627336/25071649/273a12a0-22bd-11e7-9916-05b01b85f538.png)
</details>

**Comment by UnnamedMinecrafter** [comment]
found out that the working one creates each list and the broken one just links to that list. 
How do i fix that ??? since the broken one should be a lot faster on huge scales

**Comment by brianharvey** [comment]
You can't have it both ways.  "The broken one should be a lot faster," yes, but why?  Answer: Because it doesn't have to generate each sublist individually!  If it did what you want, it would take just as long as the other version.
