### ISSUE TITLE
Use COSTUMES.txt instead of COSTUMES for index

### ISSUE THREAD

**Issue by bee8bit** [jmoenig/Snap--Build-Your-Own-Blocks#1737]
I was teaching SNAP in a classroom without internet connection so I had to put SNAP on a Microsoft IIS. (meh, I know. Needed something I could install ad-hoc.)
When browsing costumes from the server, SNAP downloads a list of files from an index file named COSTUMES (without file extension). Unfortunately IIS does not serve files with unknown MIME type (which it derives from the extension) and I could not easily configure that.

Since it's just a text file, I suggest renaming this file to COSTUMES.txt.

**Comment by bromagosa** [comment]
It's a small change indeed, but wouldn't it be better to use a smarter web server? :stuck_out_tongue_closed_eyes:

You could even just use a Python one-liner to serve Snap:

`python -m SimpleHTTPServer`

This will start a web server on your current directory.

Here's a huge list of server one-liners: https://gist.github.com/willurd/5720255

**Comment by bee8bit** [comment]
Like I said, I know it's a poor choice.
When you have no internet connection, you have to use what you already have on your computer.

**Comment by DarDoro** [comment]
I'm not sure, what you consider "easy way" but this problem is described (with solutions) here 
http://stackoverflow.com/questions/19950882/iis-how-to-serve-a-file-without-extension

**Comment by cycomachead** [comment]
I'm going to close this. The plan is to move this file to JSON - and it will be named COSTUMES.json.

Also, I'd just point out to the folks at MS who aren't reading this: File extensions are worthless. You can name any file anything you want! (But yeah, I'm never going to win this war...)

**Comment by cycomachead** [comment]
See #1594 #1621
