### ISSUE TITLE
Rename script variables does not work inside of BlockEditor

### ISSUE THREAD

**Issue by thomaswp** [jmoenig/Snap--Build-Your-Own-Blocks#1751]
Problem: If you try to rename a script variable that is inside of a custom block editor, it will throw an error:

```
Uncaught ReferenceError: ide is not defined
    at ReporterBlockMorph.BlockMorph.refactorThisVar (blocks.js:3144)
    at ReporterBlockMorph.<anonymous> (blocks.js:2389)
    at MenuItemMorph.TriggerMorph.trigger (morphic.js:9291)
    at MenuItemMorph.mouseClickLeft (morphic.js:9586)
    at TextMorph.Morph.escalateEvent (morphic.js:4351)
    at TextMorph.StringMorph.mouseClickLeft (morphic.js:8479)
    at HandMorph.processMouseUp (morphic.js:10805)
    at HTMLCanvasElement.<anonymous> (morphic.js:11455)
```

This is because the BlockEditorMorph is not an ancestor of the IDE_Morph. I'm submitting a quick pull request to fix it.

**Comment by thomaswp** [comment]
P.S. This becomes quite important in the new BJC curriculum, e.g. in the [Tic Tac Toe Project](https://bjc-edc-2017-18.github.io/bjc-r/cur/programming/2-complexity/optional-projects/4-tic-tac-toe.html?topic=nyc_bjc%2F2-conditionals-abstraction.topic&course=bjc4nyc.html&novideo&noassignment), the student is creating a nested for loop inside of a block and needs to rename one of the variables to distinguish them.

**Comment by cycomachead** [comment]
Is this the same as #1639 / #1676?

**Comment by jmoenig** [comment]
Good point, Thomas, and yes, Michael, those are the same issues. Turns out Bernat has already fixed this and I'll integrate the fix once I get to the bottom of my current 4.1 changes. In the meantime you *can* rename script vars manually.

**Comment by brianharvey** [comment]
@thomaswp Renaming the index variable of a FOR is done by clicking on the variable.  I'm not sure it'd ever be a good idea to use Bernat's rename mechanism in that case, certainly not in the "rename all" variant, because, you know, it'd rename all of them!

**Comment by bromagosa** [comment]
Anyway, the "rename all" variant is fixed already, just waiting to be pulled.

**Comment by bromagosa** [comment]
Sorry, I should read *all* the replies before replying myself :stuck_out_tongue_closed_eyes:

**Comment by thomaswp** [comment]
Good to hear the issue is fixed. Never realized I could click on a foreach variable to rename it... but if I tried to right-click-rename, there a 100% chance some student will too :)

Should we close the issue as a duplicate then?
