### ISSUE TITLE
Need some way to distinguish files with blocks from projects

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1753]
I was working on a project, and I tried to import some blocks, but I accidentally dragged in an XML _project_  file with the same name (because the blocks I wanted came from that project), and it opened that project erasing my work. :(

Is there any way that the filename resulting from exporting blocks can be different from the filename resulting from exporting a project?

Maybe "myproject.xml" vs. "blocks_from_myproject.xml" or something like that?

**Comment by cycomachead** [comment]
I thought it should be different. :/ But yes, this can be fixed. 

> I was working on a project, and I tried to import some blocks, but I accidentally dragged in an XML project file with the same name (because the blocks I wanted came from that project), and it opened that project erasing my work. :(

IMO, we shouldn't let this happen without a confirmation step, too. (But that's a separate issue.)

**Comment by cycomachead** [comment]
#1760
