### ISSUE TITLE
Hidden Pages

### ISSUE THREAD

**Issue by ekahl** [jmoenig/Snap--Build-Your-Own-Blocks#1758]
I am using SNAP in my classroom with the FINCH robots.  When the students click on various areas within the code and work space, additional Chrome pages open to other sites: Pokemon Data Base, Mini Clips and many more.  They are not all the same.  This cause an issue and slows the computer.  Plus some page are not appropriate for K-6 students.  Please resolve this issue.

**Comment by jmoenig** [comment]
Whoa! That must be something unrelated to Snap! I can assure you that Snap does *not ever* open any pop-ups or any other websites automatically, neither do the Birdbrain extensions for the Finch or Hummingbird robotic kits. Frankly, it sounds to me as if there might be some malware on your computers. Can you tell us more about your setup?
