### ISSUE TITLE
Teacher reports repeatable FILL crash

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#1764]
http://snap.berkeley.edu/snapsource/snap.html#present:Username=cullan2&ProjectName=outside1.1

Click the "skyscraper" script at the bottom of the screen.

Is this the bug that Bernat has fixed?  If so, the sooner the better pulling it.  :)

**Comment by bromagosa** [comment]
It is the same bug, yep!

**Comment by brianharvey** [comment]
OK, closing as duplicate.
