### ISSUE TITLE
git submodule init failed

### ISSUE THREAD

**Issue by antonymsur** [jmoenig/Snap--Build-Your-Own-Blocks#1768]
I am trying to build Snap4Arduino. 
./prepare --all
Pulling Snap! sources
Submodule 'src/snap' (https://github.com/jmoenig/Snap--Build-Your-Own-Blocks) registered for path 'src/snap'
Cloning into 'src/snap'...
remote: Counting objects: 7707, done.
remote: Total 7707 (delta 0), reused 0 (delta 0), pack-reused 7707
Receiving objects: 100% (7707/7707), 50.51 MiB | 2.27 MiB/s, done.
Resolving deltas: 100% (4541/4541), done.
Checking connectivity... done.
fatal: reference is not a tree: e2b106b63f9f0e9b6abfc4a6971b993833e8d734
Unable to checkout 'e2b106b63f9f0e9b6abfc4a6971b993833e8d734' in submodule path 'src/snap'
\033[37;41mERROR:\033[0m \033[1;31mCould not set up Snap! git submodule.\nPlease make sure that you have access to the Internet and git is installed in your system.\033[0m

Then I tried manually by running  git submodule update --init --recursive , but gives the following error.
fatal: reference is not a tree: e2b106b63f9f0e9b6abfc4a6971b993833e8d734
Unable to checkout 'e2b106b63f9f0e9b6abfc4a6971b993833e8d734' in submodule path 'src/snap'

Am I doing something wrong here

**Comment by bromagosa** [comment]
Hi @antonymsur,

this is a Snap4Arduino issue I should have resolved last week but didn't have the time to, I'm sorry.

It's happened once before (see [this issue](https://github.com/bromagosa/Snap4Arduino/issues/158)) but now we know exactly what's causing it and how to fix it.

In the meantime, you can use @jguille2's workaround in the same thread I've linked you to.

I'll try to get it fixed on Monday first thing in the morning.
