### ISSUE TITLE
Have not been able to login to Snap for the past few days. Is it down for the summer?

### ISSUE THREAD

**Issue by dwchew** [jmoenig/Snap--Build-Your-Own-Blocks#1770]
I have tried on and off for the past few days to login to Snap but failed with the Snap!Cloud error message : "could not connect to: https://snap.apps.miosoft.com/SnapCloud"

I have not logon since end of May (end of school year). Now, I want to get back to my Snap projects to prepare for the next school year and to help the new teachers to prepare, and found that I cannot logon with each try in the past few days. I have triple checked my login and password!

It will be terrible if I lose all my projects from last school year.   Anybody experienced such problem in recent days? Thanks!

**Comment by brianharvey** [comment]
No, it's not down for the summer.  Other people are using it without trouble.  I suspect one of two problems:

1.  The non-school computer you're using now is on a network that's blocking access to miosoft.com.

2.  You are trying to run a copy of Snap<i>!</i> that you downloaded to your computer, which isn't on miosoft's whitelist -- only the official Snap<i>!</i> can use the cloud storage.

**Comment by cycomachead** [comment]
If you can, try logging in using a different browser, or computer. Private browsing / incognito mode would also be a good test.

If one of those works, you should be able to log in again after resetting your cookies.

**Comment by dwchew** [comment]
Using a different browser worked!  Thank you very much for the prompt response!  I was using Chrome on the same laptop outside of school to do all my course prep with Snap for the whole school year and had no problem until now. Will reset cookies!   Thank you!

**Comment by cycomachead** [comment]
Glad it worked!
