### ISSUE TITLE
Input Variable Menus Don't Scroll Past Window Edge

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1772]
![snap-bug-date](https://user-images.githubusercontent.com/6549787/27546985-68123a5a-5a62-11e7-9c2f-d7e680d93816.gif)

**Comment by jmoenig** [comment]
this is on my intermediate list of to-tos. In the meantime your best workaround is to break up very long menus into shorter submenus.

**Comment by maryfries** [comment]
Thanks! What would that look like in a case like this?

**Comment by jmoenig** [comment]
You could, for exempla group the years by 10 by copying the following code into your menu definition:

```
1980={
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
}
1990={
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
}
2000={
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
}
2010={
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
}
```

**Comment by maryfries** [comment]
Cool! Thanks! 

Are there instructions for this somewhere that Snap! programmers can find?

**Comment by jmoenig** [comment]
yes! page 38 of the updated Snap! Manual http://snap.berkeley.edu/snapsource/help/SnapManual.pdf
(yay, @brianharvey !)

**Comment by maryfries** [comment]
Awesome!! Thanks!!

**Comment by cycomachead** [comment]
Closing because of existing issues. :) #1005 #349
