### ISSUE TITLE
How can a JavaScript block use a JavaScript library?

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap--Build-Your-Own-Blocks#1783]
The JavaScript code for a block creates a 'script' element and sets its src and type and appends it to the document head. I then get this error:

Refused to execute script from 'https://github.com/ToonTalk/ai-cloud/blob/master/lib/speech.1.0.0.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

I then tried copying and pasting the contents of the JS file into the Snap! block but it didn't work and the block displayed as this:

![image](https://user-images.githubusercontent.com/2138696/27692660-30ea8d64-5cdf-11e7-9f95-55e64a007298.png)

while before pasting the contents it looked normal.

**Comment by brianharvey** [comment]
Look at the USE BIGNUMS block in the infinite-precision library
File>Libraries>Infinite precision integers

**Comment by ToonTalk** [comment]
Thanks. My problem turns out was with the MIME type of the JS file. I was doing the same as the bignum block but the URL wasn't being served correctly. Working now that I'm getting my file from github.io instead of github.com

Sorry to trouble people (though pasting the contents of a large min.js file into JavaScript block did result in some display problems).

**Comment by cycomachead** [comment]
The display problems are #20 

Glad you figured it out! You might try using https://rawgit.com to access the files, which works pretty well.
