### ISSUE TITLE
Label block not state transparent

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1787]
The label block should not change the state of the sprite but should instead return the sprite to where it started.

This came up while developing this page: http://bjc.edc.org/mini17/bjc-r/cur/programming/3-lists/5-graphing/1-bar-graphs.html?topic=nyc_bjc%2F3-lists.topic&course=mini17.html&novideo&noassignment

**Comment by cycomachead** [comment]
https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/pull/491
Has plenty of discussion on the label block. Though, the existence of JSFunction kind of stopped the hard discussion of building a better block.

I think, given that label handles rotation - calculating the final position isn't super trivial. If you want to stamp multiple things, then this gets tricky.

I don't have strong feelings on this. I would only support doing this if we also give a block to calculate the end position of stamping text. (a reporter that reports a list of x,y values).

**Comment by brianharvey** [comment]
I think this is a nonstarter.  Given that the user has no information about font geometry, it would be very hard to compute the final position!  By contrast, it's really easy to _remember_ the starting position.  (Also easy to build a block that does the remembering and returning.  Yay abstraction!)

Closing.

**Comment by cycomachead** [comment]
> Given that the user has no information about font geometry, it would be very hard to compute the final position!

I do think it'd be useful to have a way to computing this info. I guess this is why the original idea for text stamping was to store all the font properties on the sprite...
