### ISSUE TITLE
Can't login with Chrome

### ISSUE THREAD

**Issue by jcaldw737** [jmoenig/Snap--Build-Your-Own-Blocks#1793]
I can login in fine with Firefox, but when I try to login with Chrome I get

Could not connect to:

https ....... SnnapCloud

Been going on for over a week

Thanks for any help you can provide!
![image](https://user-images.githubusercontent.com/5361659/27939864-147697e6-628d-11e7-8553-ed39908e6c41.png)

**Comment by cycomachead** [comment]
Have you tried clearing your cookies? Also have you tried another browser?

**Comment by jcaldw737** [comment]
THANKS!  I searched my cookies for "snap" and deleted all them and I was able to log in,

Just for the record I have been able to log in with Firefox all along.

Thanks again!

**Comment by cycomachead** [comment]
No problem, glad it worked!
