### ISSUE TITLE
Login Errors w/ Cookies

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#1795]
It's a semi-frequent occurrence that something weird with cookies causes users to be unable to log in. 

We definitely should provide some work-around for this, but I'm not sure what...

1. Simple: The error message for "Can't connect" can give some recommended actions.
2. Can we delete cookies when an error happens? I don't know if this is the best thing to do, but it seems like deleting cookies (just for Snap!) would allow people to log in again.

**Comment by an5rag** [comment]
Any updates on this? We're running into this issue quite frequently and don't want to resort to using incognito / clearing cache.

**Comment by cycomachead** [comment]
tagging @jmoenig to see if he things that 2 is an acceptable solution.

**Comment by brianharvey** [comment]
Do we understand (1) what precisely is the problem with what cookie, and/or (2) whether we can fix Snap<i>!</i> to be more resilient in the case of bad cookies, rather than delete them?  (I'm not saying deleting them would be bad, just trying to understand the space of possible solutions.)

**Comment by an5rag** [comment]
If it helps, this is the console error:
XMLHttpRequest cannot load https://snap.apps.miosoft.com/SnapCloud?SESSIONGLUE=.sc1m15. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://byob.eecs.berkeley.edu' is therefore not allowed access. The response had HTTP status code 404.

Is it a CORS header issue?

**Comment by cycomachead** [comment]
Ah, thanks for the report! That may have been a side effect of the recent server issues, which it might have reported the wrong name for a while. 

If you see that error again let us know - but everything should be OK now.

**Comment by tobiasbp** [comment]
This is a problem for me too. Accessing https://snap.apps.miosoft.com/SnapCloud?SESSIONGLUE=.sc1m15 is the problem. 

I'm using Snap at this URL (Redirected from snap.berkeley.edu), and acessing my account does not work:
http://byob.eecs.berkeley.edu/snapsource/snap.html

Using Snap at this URL works however:
https://snap.apps.miosoft.com/snap.html

Looks like a server issue?

**Comment by cycomachead** [comment]
Ah, I see the issue. 

Ok, I'll fix this later today. In the meantime, if you go to snap.berkeley.edu/run you'll end up in the right spot. 

The byob.eecs server is old and we need to fix the redirects. 

The Miosoft mirror works, but it's an older version of Snap<em>!</em>. (We should probably remove that sometime...)

**Comment by cycomachead** [comment]
Well we fixed this with the new cloud, or at least this same issue can't occur.
