### ISSUE TITLE
Account provisioning

### ISSUE THREAD

**Issue by namoscato** [jmoenig/Snap--Build-Your-Own-Blocks#1805]
I would be interested in helping to add functionality around account provisioning, leveraging third-party authentication systems such as [Google Sign-In](https://developers.google.com/identity/). Is the server side API open source and/or are there plans to implement anything of the sorts?

**Comment by cycomachead** [comment]
Closing this b/c we have a new cloud system at https://github.com/bromagosa/snapCloud

Though, right now, we aren't looking to do any 3rd party sign in systems.
