### ISSUE TITLE
Importing TXT files into SNAP

### ISSUE THREAD

**Issue by lancelotjsmith** [jmoenig/Snap--Build-Your-Own-Blocks#1817]
Hi... Trying to set things up so students can import data from a TXT file (data from a weather station) into SNAP so that they can write code to manipulate this data to do different things with it. I have seen that there is a way to import TXT files into SNAP but I cannot seem to get it to work and I cannot find any support online describing how SNAP works with external files. Any advice on where to turn?

**Comment by jmoenig** [comment]
Hi @lancelotjsmith ,
sorry, we're somewhat behind with documenting things. Here's how you can import text data:

1. make a variable - you'll get a stage watcher (monitor)
2. in the stage watcher's context menu you'll see the option to import data into the variable
3. once you've gotten the txt data in, you'll probably want to parse it (use the SPLIT block) into a list

Does that make sense to you?

**Comment by lancelotjsmith** [comment]
Hi Jens,

Got it. It worked. Thanks.


Thanks,

Lance Smith
