### ISSUE TITLE
Add label separators to settings menu

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#1820]
The current settings menu is long and the distinctions aren't super clear.

Can we have a label for "Browser Settings" and "Project Settings" to the settings menu? This will make it more clear what the divisions in the menus actually are.

(Alternatively, we could use BH's submenus to group them.)

**Comment by brianharvey** [comment]
Great idea, except call it "permanent settings"; I don't think users will get "browser settings."

**Comment by cycomachead** [comment]
Ah true -- though they aren't really permanent. Ideally, these would be tied to each person's cloud account but that's a separate problem.

**Comment by jmoenig** [comment]
I've radically cleaned up the settings menu. Did you check the dev version?

**Comment by cycomachead** [comment]
I like the reduced number of settings. But I still think the menu is unclear. The 3 groupings don’t really make sense to me. Why is visible stepping with the middle group? Why is stage size at the top when it’s a project setting? Isn’t turbo mode a project setting?

**Comment by cycomachead** [comment]
Also I think the blinding box for the fancy check marks is off. 

(I can’t attach a photo from my phone but the bottom is cut off.)

**Comment by brianharvey** [comment]
Visible stepping is a funny special case; it's not really a preference, but a short-term "step right now."  I still say that when the slider is all the way to the right, it should mean to run at full speed, just as all the way to the left means single-step.  If we did that, I think we could probably demote the menu item to shift-click status.

**Comment by cycomachead** [comment]
> Visible stepping is a funny special case; it's not really a preference, but a short-term "step right now." I still say that when the slider is all the way to the right, it should mean to run at full speed, just as all the way to the left means single-step. If we did that, I think we could probably demote the menu item to shift-click status.

Oh yeah, I agree it's totally different in usage! IIRC, you need the checkbox to enable the slider... But my point was that it probably deserves to be it's own section of the menu. (Which seems fine to me. It's a totally useful feature that everyone should be aware of and use.)

**Comment by brianharvey** [comment]
Yes, the checkbox enables the slider, but at present there is no slider setting that means "run at full speed" so you have to keep checking and unchecking the checkbox.  If the slider had a full-speed setting, you could just check the checkbox once and keep it checked.  It could be a persistent user setting.

**Comment by jmoenig** [comment]
I've played with letting the slider be always visible, it felt too easy to accidentally slow down a project. Just yesterday and today I had another two-day workshop with 22 kids and speed and "lagging" is always a major issue.

**Comment by cycomachead** [comment]
This is an improvement, but the key point in this issue is that there should be some _label_ about what's going on. Otherwise, the segmentation is still completely opaque.

**Comment by brianharvey** [comment]
I'm not proposing removing the checkbox, just making it like any other user preference, i.e., changed only rarely rather than all the time.

**Comment by cycomachead** [comment]
In menus across macOS I don't see many options that change behavior based on the position in a menu. There are plenty of various logical (and some illogical!) groups of items, but they act in the same way.
