### ISSUE TITLE
Export variable fails in dev 4.1 in Chrome

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#1825]
http://snap.berkeley.edu/snapsource/dev/snap.html#present:Username=lhs-dmahalko&ProjectName=Hexadecimal%20string%20to%20binary%20v0.1

Run this project and try to export the variable watcher on the stage.  Works for me in Firefox, and in non-dev in Chrome, but dev in Chrome makes a new window that (for the user who reported it) is empty, and for me just flashes in and out of existence.  (Nothing in JS console.)

**Comment by cycomachead** [comment]
I'm assuming this is related to the problem of opening a new window?

Bah, perhaps we should just banish opening a new window altogether? I'm happy to make that PR. I _despise_ functions w/ boolean arguments so I'll be able to remove the atrocity I committed. 😛

**Comment by brianharvey** [comment]
What's the matter with functions with Boolean args?

**Comment by cycomachead** [comment]
You have to inspect the function being called to figure out what's going on. 

`ide.saveFileAs(contents, 'my blocks', true)` doesn't say what's different. 
One of the many posts: https://martinfowler.com/bliki/FlagArgument.html

**Comment by brianharvey** [comment]
So, how does that differ from _any_ argument?  That's why IDEs show you the function prototype as you're filling in the args. :)

**Comment by cycomachead** [comment]
It's a problem for _reading_ code, rather than writing it. When reading you can infer from the names or values of what something does. But there's an infinite amount of values for what a boolean could control...

**Comment by brianharvey** [comment]
Oh.  So you do 
ide.SaveFileAsCloud=function(foo,baz) {ide.SaveFileAs(foo,baz,True)}
ide.SaveFileAsLocal=function(foo,baz) {ide.SaveFileAs(foo,baz,False)}
or whatever that flag means.  If there's more than one flag, then you write your program in a language that allows named actual arguments Foo(a,b,this=True,that=False,other=True).

**Comment by cycomachead** [comment]
Oh yeah. Those are ok. I don’t know why I didn’t do that originally. 

And JS does have keyword arguments but we can’t use them because of supporting older browsers or because we don’t want to use a compiler. 

-- 
Michael Ball
From my iPhone
michaelball.co
