### ISSUE TITLE
Don't work URL block

### ISSUE THREAD

**Issue by SimaDuck** [jmoenig/Snap--Build-Your-Own-Blocks#1833]
![screenshot_1](https://user-images.githubusercontent.com/28606130/29448934-71b64f06-8401-11e7-8804-b677a4b5d8ed.png)

**Comment by cycomachead** [comment]
Some sites, such as GitHub, don't allow their content to be downloaded from another website. You'll need to use a proxy service like crossorigin.me to be able to make the request.
