### ISSUE TITLE
InspectorMorph glitch on move

### ISSUE THREAD

**Issue by merlin2v** [jmoenig/Snap--Build-Your-Own-Blocks#1839]
The InspectorMorph works functionality wise except when moved(<kbd>mouse press down</kbd>+<kbd>mouse move</kbd>→<kbd>mouse press up</kbd> or <kbd>mouse drag</kbd>)
the Graphical Developer Interface (GDI) moves(relatively) back to the same position as well as some shadow glitches happen as well. 
Also the close function fails after (attempted) move.

![Inspector Morph](https://user-images.githubusercontent.com/25653109/29602951-18d0be50-8797-11e7-8b4e-a82eafa369c4.PNG)
<sup>image of Inspector Morph after attempted move</sup>

**Comment by merlin2v** [comment]
Note that this is made available by setting the dev mode to true;

**Comment by jmoenig** [comment]
Can you explain more about this bug? I cannot reproduce it, probably because I don't know exactly what you're doing to make it appear. Thanks!

**Comment by jmoenig** [comment]
Which browser are you using?

**Comment by merlin2v** [comment]
in google chrome set `world.isDevMode=true;`(via console or through the JavaScript block).  Then right click on a block. Select something from the list then select `inspect...`. After the Inspector Morph shows up, If you repeatedly try to move the Inspector Morph it will start to gain the rendering bug above. It will also move back when you try to move it.

**Comment by merlin2v** [comment]
Error does not occur if dev mode is changed via logo <kbd>click</kbd> + <kbd>shift</kbd>.
bug only occurs when `world.isDevMode=true` is inputted into the console or via a JavaScript block
![image](https://user-images.githubusercontent.com/25653109/32030886-cc5960e2-b9b2-11e7-8d3d-71b7865f682a.png)

**Comment by brianharvey** [comment]
I'm inclined to say that we're not responsible for what happens when you mess with things in Javascript.

**Comment by jmoenig** [comment]
```this.parentThatIsA(IDE_Morph).switchToDevMode()```
