### ISSUE TITLE
line break

### ISSUE THREAD

**Issue by merlin2v** [jmoenig/Snap--Build-Your-Own-Blocks#1842]
how do you add a line break in a byob?

<kbd>create new block</kbd>
     ↓     
<code> + hello + world + **\n** + how + are + you? + </code>
     ↓     
block: <kbd>hello world 
how are you?</kbd>

**Comment by brianharvey** [comment]
You use the Multiline library.

**Comment by merlin2v** [comment]
for a label
<kbd>do this 
then(text)</kbd>

**Comment by cycomachead** [comment]
You'll need to use the dev version of Snap<em>!</em> (snap.berkeley.edu/snapsource/dev/) but in your block spec use `$nl` wherever you want to have a line break. (You can get this from the dropdown menu when typing the name of an input / item in a block spec.)
