### ISSUE TITLE
URL Report fail from TCP server on raspberry3

### ISSUE THREAD

**Issue by JingYao0512** [jmoenig/Snap--Build-Your-Own-Blocks#1846]
Hi, everyone

I set a TCP server in C on raspberry3, then I used URLreport on PC to get the message from server like" hello, world!", but I got nothing.
[
![image](https://user-images.githubusercontent.com/20831419/29959571-94ac099a-8f2a-11e7-837e-1d911d6f3a15.png)
](url) 

I tried the same website on browser then it succeed. 
http://imgur.com/mdVjO5Z

I don't know how to fix it, and I guess maybe there are something wrong in response. 
I hoping someone can help me or give me a direction, please.
Following is my code of server.
`char *response_type = 
"HTTP/1.1 200 OK\r\n" 
"Server: Apache/2.47 (Ubuntu)\r\n" 
"Content-type: text/plain\r\n" 
"Content-Length: %d\r\n" 
"Accept-Ranges: bytes\r\n" 
"\r\n";`

[new 2.txt](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/1269531/new.2.txt)

Thanks

**Comment by JingYao0512** [comment]
Hi
I found a solution for send message from server to snap!. Just revise the response content.
http://imgur.com/W7ZYB9r

Because I just send the "string" not file, response content need to be change as following
`char *response="HTTP/1.1 200 OK\r\nServer: Apache/2.47 (Ubuntu)\r\nContent-type: application/octet-stream\r\nContent-Length: %d\r\n"Access-Control-Allow-Origin: *\r\n\r\n`

Most importantly, "Content-type: application/octet-stream" and "Access-Control-Allow-Origin: *" is the key for send message.  

"Content-type: application/octet-stream" means "unknown type" that is "string", but I can't understand what meaning of "Access-Control-Allow-Origin: *" is.

**Comment by micahcowan** [comment]
`Access-Control-Allow-Origin: *` is a way for the web server to signal to the browser that it's okay for JavaScript running from a different server (in this case, **snap.berkeley.edu**), to access content from your web server. It's a means to mitigate cross-site scripting attacks.

Obviously, the request is still _made_ to the other host; but if the headers don't allow it, then your script can't get at any information from it at least.

**Comment by JingYao0512** [comment]
@micahcowan

Thank you!! It's helpful for me, now I understand it.
