### ISSUE TITLE
Doesn't error on this indexing issue

### ISSUE THREAD

**Issue by andylouisqin** [jmoenig/Snap--Build-Your-Own-Blocks#185]
This block:
![snap](https://f.cloud.github.com/assets/3770344/1231769/a8122b80-286e-11e3-89a4-85ae0bc2e049.png)

Doesn't error out, but actually appears to look for the 6th character in the string "A List":
![screen shot 2013-09-28 at 11 47 12 am](https://f.cloud.github.com/assets/3770344/1231778/46db3afe-286f-11e3-8314-bf1b8e13c58a.png)

It's probably looking through the index of the string "A List" in the backend.

**Comment by cycomachead** [comment]
b6efcaf17c0230d5eea3f3d8a6d30e142c8d67cf
