### ISSUE TITLE
Make variable provenance visible

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#1850]
(Enhancement request from Scratch forum)

The request is to make local variables look different from global ones.  I'm assuming the user meant sprite-local.  I don't want to change the shape or color of sprite-local (or for that matter procedure-local) variables, but an inobtrusive thing we could do is put "global" or "sprite" or "procedure" in the context menu of variable blobs.

**Comment by jmoenig** [comment]
Hmmm... You now, Snap's variables are only resolved on evaluation. Blocks are *not* pre-bound to a particular environment (as they are in Scratch). That's why in Snap you can rename (and now even refactor) variable accessor blocks and also move them elsewhere among different scopes.

**Comment by cycomachead** [comment]
Do they mean in the palette or everywhere, like in scripts?

**Comment by brianharvey** [comment]
I'm not sure that they had that much detail in their mind.  Probably _mostly_ in the palette (where we used to have a line separating global from sprite-local, and they were in the other order).  But I'd like to be able to ask a variable in a script, by right-clicking on it, how it would be resolved currently.  I realize that later definitions could change the answer.

**Comment by cycomachead** [comment]
Ah I re-read it. There's a very old PR and issue about separating sprite and script variables. 
I do think it's useful to do.

(Snap! will prevent you from creating a sprite var with the same name as a global but, not the other way around.)

As far as disable: I know BYOB's scope contrast wasn't perfect, but it was something that was useful. If we exempt the viewing of block definitions (and whacky things you can do in JS functions like re-assigning scope or deleting variables), then don't we always know the context in which the script is being executed?

There are still other things we can do:
- Even if we can't determine the exact scoping of a variable w/o execution, we could at least easily highlight where scope issues might arise.
- Won't we always know about in-script conflicts - like a local variable and an upvar clashing or a local and a global? Am I missing something here? (Again, exempting JS functions).
- I would personally accept a solution that for the purposes of globally-available a custom block, all sprite-local variables are highlighted regardless of whether there's a conflict in the current sprite. (If you have a sprite-local variable in a block, and you use it where it's not defined, you'll have issues, and if you're using it to shadow a global intentionally then some highlight makes sense, and if it was unintentional, then a highlight / info thing would tell you to be careful.)

**Comment by brianharvey** [comment]
> (Snap! will prevent you from creating a sprite var with the same name as a global but, not the other way around.)

That sounds like a bug.  You _should_ be able to shadow a global variable with a sprite variable!

But in any case I think there isn't really a problem to be solved here.  It's not as if other programming languages display the scope of variables on every use -- or am I missing something?  Do IDEs color-code variable names by provenance?  And if I really need help understanding the scope of a particular variable reference while debugging, broad categories like "sprite-local" aren't enough, in the OOP world; I need to know _which_ of my ancestor sprites shadows the global.

And when I finally get hybrid scope implemented, you might not know until runtime which procedure created this variable.

**Comment by cycomachead** [comment]
Other tools:

BYOB had scope contrast, and it was useful. Nearly every Javascript project relies on some sort of listing to point out scope issues. 

My view isn't that we need a perfect tool, but that we can build a tool which aids in most cases --  warning of the _potential_ for scope conflicts when it's possible to tell, it's extremely helpful, especially project groups where the left programmer is not talking to the right programmer. 



> That sounds like a bug. You should be able to shadow a global variable with a sprite variable!

IIRC, this was intentionally added -- I think due to people not being able to see the difference.

**Comment by cycomachead** [comment]
Duplicate of #189

**Comment by cycomachead** [comment]
@brianharvey Do the 4.1.1 updates adequately address the issue. I think so, but just want to make sure there aren't other things that should keep this open.

**Comment by brianharvey** [comment]
Yes, this is addressed.
