### ISSUE TITLE
gui.js error in firefox macosx

### ISSUE THREAD

**Issue by foxsan48** [jmoenig/Snap--Build-Your-Own-Blocks#1854]
Name 	Firefox
Version 	55.0.3
Build ID 	20170824053838
OS Mac 10.12.6 Sierra

Getting this error attempting to load snap from http://snap.berkeley.edu/snapsource/snap.html

```
NS_ERROR_FILE_CORRUPTED:   gui.js:2084
IDE_Morph.prototype.getSetting http://snap.berkeley.edu/snapsource/gui.js:2084:9
IDE_Morph.prototype.applySavedSettings http://snap.berkeley.edu/snapsourc/gui.js:1989:18
IDE_Morph.prototype.init http://snap.berkeley.edu/snapsource/gui.js:214:5
IDE_Morph http://snap.berkeley.edu/snapsource/gui.js:204:5
window.onload http://snap.berkeley.edu/snapsource/snap.html:28:5
```

**Comment by cycomachead** [comment]
Hmm -- this looks like a problem with something in local storage. The file loads correctly for me.

Can you open the console and send a screenshot of your local storage data for snap.berkeley.edu?

**Comment by foxsan48** [comment]
All empty apart from cookies, I think I see the issue though it's the 7th here, cookie says it expires yesterday, I'll clear those out and try again
![screen shot 2017-09-07 at 3 44 18 am](https://user-images.githubusercontent.com/495512/30126333-ffe2e712-937e-11e7-8dfb-23e761cfdeae.png)

**Comment by foxsan48** [comment]
Fixed it, error was localStorage corruption discovered by trying 

```js
localStorage.clear();
localStorage.setItem("test",1);
```

fixed by deleting webappstore.sqlite under the profile directory as advised here https://stackoverflow.com/a/26371494

**Comment by cycomachead** [comment]
Glad it worked out! Thanks for debugging. :)
