### ISSUE TITLE
Unable to connect to cloud from Snap! clone

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap--Build-Your-Own-Blocks#1858]
Two strange things about this:

1. When I cloned Snap4Arduino I was able to log in and see all my Snap! projects
2. I was unable to connect when logging into my Snap clone but then later I was logged in (but still couldn't open the list of the projects). Maybe because I stay logged into to Snap!...

I was able to repeat this several times.

The console says:

Failed to load https://snap.apps.miosoft.com/SnapCloud?SESSIONGLUE=.sc1m17: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://afsheenam.github.io' is therefore not allowed access. The response had HTTP status code 404.

**Comment by cycomachead** [comment]
This is intended. The Snap! cloud has access controls which limit the servers that are allowed. This was done to prevent others from piggybacking of the API for non-Snap! uses. A few forks have been added to the approved list. 

It's probably best to discuss this offline, if you email Jens and Brian.
