### ISSUE TITLE
Working with arrays

### ISSUE THREAD

**Issue by geaplanet** [jmoenig/Snap--Build-Your-Own-Blocks#1869]
Is there any documentation for working with arrays in Snap?
Is it possible to create data tables on the fly knowing the dimensions previously? (for example: 4x13)
How to fill it?
How to search elements?
How to delete elements?
...

Thanks.

**Comment by brianharvey** [comment]
Yes, chapter IV of the Reference Manual:
http://snap.berkeley.edu/SnapManual.pdf

**Comment by geaplanet** [comment]
Thanks, @brianharvey
