### ISSUE TITLE
No Good Script Pics

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1872]
I've been out of Snap for a few weeks, and now that I'm back I no longer have a good way to make script pics.

Chrome doesn't work at all, and Safari makes very low-quality images:

![image](https://user-images.githubusercontent.com/6549787/31034860-dbef0180-a533-11e7-8f88-11dab9c8c320.png)
![image](https://user-images.githubusercontent.com/6549787/31034879-e9f31f3c-a533-11e7-9c97-5b34eef83de3.png)

What's the fix? Should I install Firefox and try that?

**Comment by brianharvey** [comment]
Firefox _does_ work, and so does Chrome if you run the dev version of Snap<i>!</i> (soon to be released).  About the poor quality, look for a non-retina computer to make the pictures on.  :-(

**Comment by cycomachead** [comment]
I can't reproduce the low quality thing... Script pics look the same as they always have in Safari on my machine. (Retina)

**Comment by maryfries** [comment]
I agree. Safari seems fine now with the update, and Chrome has been working again too. That "turn retina display off" feature is much appreciated. :)
