### ISSUE TITLE
Everyone can invalid my cloud pass

### ISSUE THREAD

**Issue by javorekm** [jmoenig/Snap--Build-Your-Own-Blocks#1884]
If anybody go to my shared project and try to use cloud menu item "Reset password..." and fill my username, it will send me an email with password reset link. Even I do not click on it, the pass is not working at the moment. It looks like just the "Reset password..." action invalids the pass and the email link only generate new one. I can reproduce it.

From my point of view it is a security trouble as everyone can invalid my pass only with knowledge of my username. If you embed snap project to your page, the url has your username...

**Comment by brianharvey** [comment]
Oh!  Agreed, that's terrible, the old password should work until you actually use the link.

**Comment by jmoenig** [comment]
Whoa! I can confirm this. This is a showstopper. Geez. It's also new, I *know* this used not to be the case, and it absolutely shouldn't.
Thanks for reporting this!

**Comment by brianharvey** [comment]
Our cloud storage provider says this is now fixed.  Please try again!  Thanks.

**Comment by javorekm** [comment]
Seems to be ok. Thanks a lot for a very quick fix!
