### ISSUE TITLE
Error with error display for clones

### ISSUE THREAD

**Issue by KingDavid12** [jmoenig/Snap--Build-Your-Own-Blocks#1885]
If a block under the "when I start as clone" throws an error then the entire containing script and the script that created the clone give the error message "TypeError: Cannot read center of null".

Example script:
![errorsample](https://user-images.githubusercontent.com/12404374/31359375-fa6669ca-ad06-11e7-8f57-1add92f18b27.PNG)

A quick look at the source code says that the error is in blocks.js lines 1938 and 1944. The error bubble over a sprites icon in the corral does not check if the sprite that the error is from is a clone.

This can be fixed by changing line 1938 of blocks.js from
        if (ide && (ide.currentSprite !== target)) {
to
         if (ide && (ide.currentSprite !== target) && target.cloneOriginName !== ide.currentSprite.name) {

and changing line 1944 of blocks.js from
        function (icon) {return icon.object === target; }
to
        function (icon) {return icon.object === target || target.cloneOriginName === icon.object.name; }

**Comment by jmoenig** [comment]
Good catch, thanks!
