### ISSUE TITLE
"rename all" on a global var not working when a block editor is open

### ISSUE THREAD

**Issue by bromagosa** [jmoenig/Snap--Build-Your-Own-Blocks#1889]

**Comment by jmoenig** [comment]
what? what happened?

**Comment by jmoenig** [comment]
Hmm... which part doesn't work for you? I've just done a couple of quick tests and everything worked as I would expect, including renaming parameters with type information and default values... You sure something is wrong?

**Comment by bromagosa** [comment]
This is the weirdest thing. I swear by all that's holy that I was showing this feature to @jguille2 this morning and it failed on me several times when trying to rename a global var.

I've just tried it and it works now. WAT.

Maybe @jguille2 will remember what was the exact situation?

**Comment by jmoenig** [comment]
maybe it was a browser-caching situation? I also started by renaming a global var and it totally worked...

**Comment by bromagosa** [comment]
Got it! Try to rename a global var while a block editor is open and you should be able to reproduce it! :)

**Comment by jmoenig** [comment]
Ah, well. That's a minor glitch I can live with for now. We can fix it for the next minor release which is sure to come soon enough :-)
