### ISSUE TITLE
Can't edit a custom block

### ISSUE THREAD

**Issue by jcaldw737** [jmoenig/Snap--Build-Your-Own-Blocks#1900]
This morning when I right-moused over a block, "edit" was not an available option.  A student said he had had a similar problem.  This afternoon all is well,  Is there any information about something like this?

**Comment by brianharvey** [comment]
Try clearing your cache.  Most problems people are reporting this week clear up when they clear their caches.

**Comment by jcaldw737** [comment]
Thanks for the rapid response!  Right now things are ok, but if the issue comes back, I will know now to clear my cache.
