### ISSUE TITLE
Firefox claims "snap.berkeley.edu uses an invalid security certificate"

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap--Build-Your-Own-Blocks#1901]
HTTPS is needed to access the camera, microphone, or many web services. Chrome and Edge don't complain but FireFox says:

Your connection is not secure

The owner of snap.berkeley.edu has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.

snap.berkeley.edu uses an invalid security certificate. The certificate is not trusted because the issuer certificate is unknown. The server might not be sending the appropriate intermediate certificates. An additional root certificate may need to be imported. Error code: SEC_ERROR_UNKNOWN_ISSUER

**Comment by towerofnix** [comment]
Hm. I don't get this issue when connecting to https://snap.berkeley.edu on Firefox (57.0)..

**Comment by ToonTalk** [comment]
It happens with Windows 64-bit Firefox 56.0 (says it is up-to-date).

**Comment by cycomachead** [comment]
Can you check again? We've been messing with the settings a bit.

**Comment by ToonTalk** [comment]
Works fine today (FireFox 57).

**Comment by bromagosa** [comment]
Can we close this then? :)

**Comment by ToonTalk** [comment]
OK with me.
