### ISSUE TITLE
Cursor Type Beam Stuck Glitch

### ISSUE THREAD

**Issue by merlin2v** [jmoenig/Snap--Build-Your-Own-Blocks#1913]
The flashing text indicator does not disappear when a click inside a type area and drag from the template is done.
![image](https://user-images.githubusercontent.com/25653109/32313073-29a092f6-bf5e-11e7-8372-8243b4bff786.png)
Only occurs when click is made from inside the template window.
![image](https://user-images.githubusercontent.com/25653109/32313254-2e910ea2-bf5f-11e7-8502-e778b526859c.png) ![image](https://user-images.githubusercontent.com/25653109/32313248-25ce25e8-bf5f-11e7-8aea-2a136b91795d.png)

**Comment by bromagosa** [comment]
I've been noticing this a lot, but I never managed to find out when exactly did it happen. Thanks for tracking it down, I can now reproduce it:

![out](https://user-images.githubusercontent.com/1016697/32320236-62da7302-bfbd-11e7-95d8-517936adba54.gif)

**Comment by merlin2v** [comment]
Glad to be of help. 
Also, what did you use to create the gif image?

**Comment by bromagosa** [comment]
@merlin2v I use a tiny GNU/Linux bash script called [gifcast](https://github.com/madx/gifcast).
