### ISSUE TITLE
Can't place a primitive block on the script area

### ISSUE THREAD

**Issue by jcaldw737** [jmoenig/Snap--Build-Your-Own-Blocks#1916]
I have a student who says she can drag a primitive block to the script area, but cannot place it there.  I have suggested to her that she delete her "SNAP" cookies, but am wondering if there is something else she should be doing.

Thanks!

**Comment by brianharvey** [comment]
Clear the browser cache.

**Comment by jcaldw737** [comment]
She just got back to me that deleting the snap cookies worked.  Next time I will clear the browser cache.  Once again, thanks for the fast response!
