### ISSUE TITLE
Long selection lists problem (User interface)

### ISSUE THREAD

**Issue by dekrain** [jmoenig/Snap--Build-Your-Own-Blocks#1917]
For example, when I open the symbols menu (custom block decoration symbols) then the list is too long, so top of it is out of screen boundary. I think the solution may be to change the layout of lists to when list is too long then it would add new row (or scrolling), ie. something like that:
________ <- screen top

[selection A][selection D]
[selection B][selection E]
[selection C]
________ <- screen bottom

**Comment by dekrain** [comment]
Hello?

**Comment by jmoenig** [comment]
I'm working on this...

**Comment by brianharvey** [comment]
Scrolling is the right thing.  I've never heard of a two-column menu.

**Comment by bromagosa** [comment]
Duplicate (#1451). I'm closing this one :)
