### ISSUE TITLE
XML Parse Error due to Variable options Menu '<' '>' Character

### ISSUE THREAD

**Issue by merlin2v** [jmoenig/Snap--Build-Your-Own-Blocks#1918]
Hello I have received a wierd error 
![image](https://user-images.githubusercontent.com/25653109/32411345-6bb9e956-c195-11e7-9abb-76d3ffa80e9f.png)

    xml.js:371 Uncaught Error: Expected to close 
        at XML_Element.parseStream (xml.js:371)
        at XML_Element.parseStream (xml.js:379)
        at XML_Element.parseStream (xml.js:379)
        at XML_Element.parseStream (xml.js:379)
        at XML_Element.parseStream (xml.js:379)
        at XML_Element.parseStream (xml.js:379)
        at XML_Element.parseStream (xml.js:379)
        at XML_Element.parseString (xml.js:322)
        at SnapSerializer.XML_Serializer.parse (store.js:242)
        at listField.action (gui.js:5941)

I have no idea what caused this and have no idea why it is happening. As far as I know it seems that it is trying to find some invisible tag. 

This is a local project.

**Comment by merlin2v** [comment]
I found the cause of the bug. Entering <> into Options for a custom block causes this. This could probably can be fixed by allowing HTML Symbol Entities as well as default encoding to all possibly conflicting characters.**(_'<','>'_)**
<sub>The cause of the error</sub>
![image](https://user-images.githubusercontent.com/25653109/32411834-870fbeb2-c1a2-11e7-859e-b06ab7e1f0eb.png)
Definitely an important bug to be fixed before release.

**Comment by merlin2v** [comment]
<h1>How to Duplicate:</h1>

**WARNING!** This will make your project un-save-able 

![image](https://user-images.githubusercontent.com/25653109/32411916-29046c34-c1a5-11e7-925d-31b50348c420.png) 
![image](https://user-images.githubusercontent.com/25653109/32411923-57d441a6-c1a5-11e7-8948-4b8970105072.png)
![image](https://user-images.githubusercontent.com/25653109/32411940-c51402ec-c1a5-11e7-9469-a4ab5bb5722e.png)
![image](https://user-images.githubusercontent.com/25653109/32411942-f527e692-c1a5-11e7-88cf-6c9db3323755.png)
![image](https://user-images.githubusercontent.com/25653109/32411948-1d29f798-c1a6-11e7-8117-db322619760d.png)

**Comment by cycomachead** [comment]
Definitely a bug. Looks like the XML_Serializer needs another `escape()` call added in a few places.
