### ISSUE TITLE
Running code in a list

### ISSUE THREAD

**Issue by LeadToGold** [jmoenig/Snap--Build-Your-Own-Blocks#1923]
Maybe I'm not doing it right but here's the code
<img width="275" alt="function bug" src="https://user-images.githubusercontent.com/8217635/32563730-d8e13f92-c466-11e7-95c4-46c46cb54d6f.PNG">

When I broadcast next I expect both clones to move, but only the original sprite moves.
lscript is declared as a local.

ltg

**Comment by dekrain** [comment]
The ring lamda procedure is sprite dependent, so it will run for object it is created on. But it can be changed by replacing `next` event handler to:
```
run ((lscript) of (my [self])) // (drag variable reporter to () of () block)
```

**Comment by LeadToGold** [comment]
Thanks much. That works.
ltg

**Comment by brianharvey** [comment]
Hmm, it seems to me that it's a lot to expect of users to get why this doesn't work as originally written.  I'm not proposing a specific change but I'm flagging this as to be discussed.

**Comment by jmoenig** [comment]
I don't follow what needs to be discussed here. This never worked in Snap. Rings capture their environment, isn't that their whole point? You can say ```tell (my self) to lscript``` and that'll make sure ```lscript``` is evaluated within the receiver's context.

**Comment by brianharvey** [comment]
Closing because the same issue (about locality of motion blocks) came up in another thread.  :)
