### ISSUE TITLE
Program crashes while Drawing Costumes

### ISSUE THREAD

**Issue by stezel** [jmoenig/Snap--Build-Your-Own-Blocks#1924]
Please kindly review the following Piazza post:
https://piazza.com/class/h8yx482idav52y?cid=1750

Also see my response to the teacher, which seems to indicate that there may still be issues with bucket filling a region that was already filled with color.
Much thanks for your time.
Selim

**Comment by towerofnix** [comment]
(I can't view that - it asks me to "log in to proceed to your class". Could you quote/screenshot the relevant messages and post them here?)

**Comment by stezel** [comment]
<img width="794" alt="screen shot 2017-11-09 at 1 22 36 pm" src="https://user-images.githubusercontent.com/21223085/32622601-6296483c-c551-11e7-9130-6b50cb8ffb20.png">
<img width="793" alt="screen shot 2017-11-09 at 1 22 50 pm" src="https://user-images.githubusercontent.com/21223085/32622611-6ba93c7c-c551-11e7-8894-43717c75e15a.png">

**Comment by brianharvey** [comment]
Verified.  Indeed, it's the WHEN I RECEIVE [ANY MESSAGE] that's crashing, not the code under it in the script.

**Comment by bfcapell** [comment]
Hi! We were experiencing the same crash. I found a related issue, #1843 and seems to have the same origin: "sometimes alpha is a fraction, and sometimes it's a byte". In this case, when checking the sourcecolor against the new color. 

I'm not sure this will fix it completely, but changing the check in paint.js#775 worked for me: 


replace
-            sourcecolor[3] === this.settings.primarycolor.a) {
with
+            sourcecolor[3] === this.settings.primarycolor.a * 255) {

**Comment by bromagosa** [comment]
@bfcapell I think this fixes it indeed! I'm sending a pull request addressing your change :)
