### ISSUE TITLE
serializing parsed xml can result in invalid xml

### ISSUE THREAD

**Issue by brollb** [jmoenig/Snap--Build-Your-Own-Blocks#1926]
XML_Element.toString does not escape the contents or attributes which can result in invalid xml that cannot be parsed.

**Comment by dekrain** [comment]
Like this: #1918 ?

**Comment by brollb** [comment]
Not exactly. It appears that #1918 is about not being able to serialize a project because of special characters in an input slot options list. In this issue, any block using special characters in the contents or an attribute (such as a comment) will be invalid if parsed into an `XML_Element` and then stringified with `toString`.

Does that make sense?

**Comment by cycomachead** [comment]
Fixed with #1927
