### ISSUE TITLE
The Multiplying Lines

### ISSUE THREAD

**Issue by merlin2v** [jmoenig/Snap--Build-Your-Own-Blocks#1935]
At first it was just this:
![image](https://user-images.githubusercontent.com/25653109/32988422-63290888-ccb9-11e7-9a9c-30d8fe1e69a3.png)
But then *(after saving to the cloud and reloading)* it was this!
![image](https://user-images.githubusercontent.com/25653109/32988424-69f2fc46-ccb9-11e7-81fe-e755975969f6.png)
and then after every save and reload it increased!!!!
and broke my script :(
and this happened in comments too.

**Comment by jmoenig** [comment]
yes, that's unfortunately a known bug in the cloud backend. We're currently working on a completely new version of the cloud that will - among other things - fix this.

**Comment by brianharvey** [comment]
Couldn't we fix this in the front end by just making sure there aren't any carriage return characters in saved and/or loaded data?

**Comment by bromagosa** [comment]
Sometimes people _do_ want to save carriage returns, and will complain if we ignore them :)

The right thing is to focus on the new backend.

**Comment by brianharvey** [comment]
Why?  They'll never see a carriage return unless they're running Windows, in which case the carriage return is _always_ followed by a newline, so we flush the \r when importing a file, and put a \r before every \n when exporting if the OS is Windoze.

Are there ever cases in which Windoze has a \r not followed by \n?

**Comment by bromagosa** [comment]
Sorry, I misunderstood! I often forget Windows exists.

**Comment by jmoenig** [comment]
I agree with Bernat. Sometimes people even make up their own strings by concatenating single characters using ```unicode _ as letter```, and it can mean anything to them. The backend should not alter strings. Period. This is not a Snap! front-end issue, let's not introduce a complicated kludge that'll slow things down.

**Comment by bromagosa** [comment]
Hey @merlin2v, is this still happening with the new cloud? My hunch is it shouldn't :)

**Comment by bromagosa** [comment]
It is fixed, I just confirmed by looking at the test project at #1455
