### ISSUE TITLE
Invoking a callback hangs Snap for 'play sound until done'

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap--Build-Your-Own-Blocks#1938]
![image](https://user-images.githubusercontent.com/2138696/32989892-4b24ebba-cd1f-11e7-911e-61b5b4043284.png)

The first block works fine. The second one freezes the page and nothing works.

**Comment by jmoenig** [comment]
yep, ```invoke``` is only meant to be used with non-interpolated blocks, and really only makes sense if those are reporters whose return value need to be processed by the calling JS function. If you want to programmatically run an interpolated command it's probably best to simply put it on the stack...

**Comment by ToonTalk** [comment]
Thanks. Makes sense. Is there documentation or some code you could point to as to how to put it on the stack?

**Comment by KingDavid12** [comment]
You can use proc.evaluate:
![example](https://user-images.githubusercontent.com/12404374/33240962-6d95101e-d27c-11e7-9646-80eb89990f5b.png)

The first parameter is the action (ring or javascript function) to put on the stack. The second parameter is a list of inputs and the third parameter is a boolean that is true if the action is a command and false if it is a reporter.

**Comment by ToonTalk** [comment]
Thanks. That helps. Getting close. But

![image](https://user-images.githubusercontent.com/2138696/33242606-08741f66-d2d8-11e7-8588-8bac99df0943.png)

doesn't work. It seems that 'proc' no longer has a context when it is finally run. Is there a workaround?

The reason I'm using callbacks is to integrate with services such as speech and image recognition that work asynchronously.

**Comment by KingDavid12** [comment]
Here is a workaround:

Inside the javascript function you can get the stage by storing the result of 
```javascript
this.parentThatIsA(StageMorph);
```

Once you have the stage you can create a new process using the thread manager.
You call start process as follows:
 ```javascript
startProcess (
    block,
    receiver,
    isThreadSafe,
    exportResult, // bool
    callback,
    isClicked,
    rightAway
)
```

Example script:
![example](https://user-images.githubusercontent.com/12404374/33242840-2886fb4c-d298-11e7-8a2f-91df302d77ff.PNG)

**Comment by ToonTalk** [comment]
Thanks again.

I got this to work. However with 'invoke' I was able to pass arguments to the callback. I'm not clear how to do so here.

Regarding avoiding callbacks altogether I've considered it but some services call the callback multiple times. E.g. speech recognition can be set up to provide interim results and the call back is called each time one is generated. E.g. if I say "Read a book yesterday", the callback with be called with "red", then with "read a" and so on.

**Comment by KingDavid12** [comment]
Here's a more complete start process example that validates and passes arguments to the callback:
![example](https://user-images.githubusercontent.com/12404374/33271696-3bf9b5f4-d345-11e7-977e-2b3847309088.png)

initializeFor is used as follows:
```javascript
initializeFor (
    context // A ring (Your callback),
    args // The inputs for the ring,
    ignoreExit  // A boolean that is set to ensure that report does not stop at this context (You don't need this one)
```

Sorry about not really explaining things, I am a little rushed right now.

**Comment by ToonTalk** [comment]
Thank! Working fine now.

**Comment by KingDavid12** [comment]
Whoops! I just realized that my example runs the callback twice if run in single stepping mode. This is probably because it runs after startProcess and then again after initializeFor. When I have a little more time I will post an updated example.

**Comment by KingDavid12** [comment]
Okay, as it turns out the callback running twice is a glitch in Snap! Anyway, here is a slightly shorter script (ignoring the checks): 
![example](https://user-images.githubusercontent.com/12404374/33297931-df606ee4-d3a0-11e7-806a-1de80d169f33.png)

**Comment by ToonTalk** [comment]
Thanks that works well.

**Comment by KingDavid12** [comment]
That's great!

**Comment by bromagosa** [comment]
Closing this since you guys found a solution :)
