### ISSUE TITLE
ERROR: Source code transmission failed

### ISSUE THREAD

**Issue by Octavia888** [jmoenig/Snap--Build-Your-Own-Blocks#1945]
I'm trying to save my completed project to cloud, but an error message pops up saying:
 
"Service: saveProject
ERROR: Source code transmission failed"

I can successfully save it to the browser, but it is imperative that I save it to the cloud to complete a school project. Help would be much appreciated.

**Comment by brianharvey** [comment]
Does your project have a lot of media (sounds and pictures)?  That's the most common reason for a project to be unsaveable.

**Comment by Octavia888** [comment]
Yes, but it doesn't say the storage has been exceeded. It had said that
before, so I cut out a lot of the sound.

**Comment by bromagosa** [comment]
Are you using any special UTF characters, such as emojis, in any of your custom blocks or inputs?

**Comment by cycomachead** [comment]
Closing since this issue should be resolved with the new cloud. :)
