### ISSUE TITLE
Snap!Cloud storage is down

### ISSUE THREAD

**Issue by ew-newtongwc** [jmoenig/Snap--Build-Your-Own-Blocks#1951]
This likely isn't the place to report this bug, but I haven't yet found a better reporting/escalation channel.

The Cloud storage feature stopped working sometime in the last few days. Even though there are multiple mirror servers for Snap!, they all seem to rely on the same cloud storage backend. I can't load anything from Cloud storage, whether the examples on the main site http://snap.berkeley.edu/ or my own personal projects. 

The "Open..." menu option fails with a dialog box reporting the error: "could not connect to https://snap.apps.miosoft.com/SnapCloudPublic"

I get the same dialog box error from any of the "present" links, e.g.

http://snap.berkeley.edu/snapsource/snap.html#present:Username=jens&ProjectName=tree%20animation

http://snap.berkeley.edu/snapsource/snap.html#present:Username=jens&ProjectName=Menuet
http://snap.berkeley.edu/snapsource/snap.html#present:Username=davidrhmiller&ProjectName=Lesson%204.3%20Lab

Since the problem is likely on the miosoft end, the feature request here is to offer users guidance on what escalation path to follow when this happens. I've never heard of miosoft, don't know whom to contact to report the problem or to learn about the status of resolving it.

davidrhmiller@gmail.com

**Comment by brianharvey** [comment]
This is an announced scheduled downtime for the cloud server.

If you're a BJC teacher, you should have seen the announcement on the Piazza group.  It should be up soon.

**Comment by ew-newtongwc** [comment]
Thanks. I am a TEALS teacher, which also uses Snap! in our classrooms
nationwide (see
https://tealsk12.gitbooks.io/introduction-to-computer-science/content/) .
We don't use the BJC Piazza, but instead https://forums.tealsk12.org

I'll ask the TEALS national org if they can also post notices when there is
scheduled downtime (and to strive to avoid downtimes during the school
week).

Cheers,
    David
