### ISSUE TITLE
Color picker doesn't sense pen trails

### ISSUE THREAD

**Issue by ghfhias** [jmoenig/Snap--Build-Your-Own-Blocks#1963]
This is possibly the WORST coding program I have EVER had to deal with!!! It LAGS like no other, the servers that you are paying for are worst than the internet at a run down Mcdonald's. FIX THE DAMN PROGRAM! Second the controls are not fluid at ALL! The fact that there is not a color drop tool so that your sprites don't touch said color is RIDICULOUS! It makes it nearly impossible to do anything with your own stage, because you can't find the exact color that you used. Third there is no autosave! WHY IS THERE NO AUTOSAVE! AND EVEN IF you do save it will bug out and NOT SAVE IT! This is the most outdated technology I have ever used. I am trying to create a Pac-Man game but it is impossible because your STUPID program doesn't know how to handle more than two lines of code! FIX THE SERVERS! What is the point of using this program that lags and has some of the worst consumer friendliness on the market when they're are programs like Scratch that actually can handle more than two lines of simple code and has a DAMN COLOR DROP TOOL (LIKE SERIOUSLY PEOPLE YOU GO TO BERKELEY BUT CAN"T MAKE A COLOR DROP TOOL!!!!!!) To me there is almost no reason to use your program until it is fixed and you people actually listen to the consumers. Your program could be something good, but is far outweighed by programs such as Scratch. (STILL MAD ABOUT THAT COLOR DROP TOOL) I am not saying to get rid of your program but the fact that my colleagues can't play their games that have been created because the servers are running out of the back of a 1980's Saturn is absolutely ridiculous. It is 2017 people and your program is running like something that was made by the original Microsoft (which was in a garage btw). In conclusion BERKELEY STUDENTS FIX YOUR PROGRAM.

Sincerely, someone who cares

**Comment by jmoenig** [comment]
<img width="267" alt="color touching" src="https://user-images.githubusercontent.com/2596285/33854661-cb3a1f46-dec2-11e7-81f5-e4aedec3962c.png">

**Comment by ghfhias** [comment]
That is not a color drop tool, what I meant by that was I should be able to drop a color that I have put onto the stage background and drop that color into the color touching box. If there is something like that please let me know because it is very difficult to find the exact color I used on my stage and drop that into the touching color box. If this tool exists let me know thanks.

**Comment by jmoenig** [comment]
Yeah, that's a bug I only learned about last week, which I'm fixing in the next release. In the meantime, maybe testing for collision with another sprite or - pro tip (!) - with the pen trails might help you.

**Comment by jmoenig** [comment]
(btw. since most of the things that are drawn on the stage are either stamped costumes or pen trails you might be able to get the color from the costume that's been stamped or from the sprite / block that drew the pattern). But - again - I recommend using the ```touching pentrails``` block, which is really cool.

**Comment by towerofnix** [comment]
>I am not saying to get rid of your program but the fact that my colleagues can't play their games that have been created because the servers are running out of the back of a 1980's Saturn is absolutely ridiculous.

I know "it works for me" is the most unhelpful input I can give, but.. the servers work for me. They're a little slow - I have to wait about a second or two every time I save to the cloud - but I don't have lag even close to anything like you're describing?

If you're having trouble saving projects on the cloud you could try saving them locally (either in your browser (file -> save as, then select "browser" instead of "cloud"), or as an external XML (file -> export project; you could email the file if you wanted to).

The type of lag you're describing *also* sounds like a slow frame-rate? Which would be really weird, because the Snap<i>!</i> IDE runs at 60fps for every browser and system I use (save for my rather old iPad mini, which it's just a little slower on). But maybe that's not what you're talking about.

**Comment by jmoenig** [comment]
I've fixed this in the dev version (which will become the next release). You can try it yourself at this url:
https://snap.berkeley.edu/snapsource/dev/snap.html

**Comment by bromagosa** [comment]
The bug is fixed, but someone still needs a good cup of [this](https://www.amazon.com/Yogi-Lavender-Stress-Relief-Packaging/dp/B007M8FRV0).
