### ISSUE TITLE
Error on password reset

### ISSUE THREAD

**Issue by namoscato** [jmoenig/Snap--Build-Your-Own-Blocks#1967]
I am getting a 500 response when attempting to reset passwords via GET `https://snap.apps.miosoft.com/SnapCloudResetPW?Username`:

```
ERROR
Data is temporarily unavailable.
Error ID:20171219185807807
STACK
WSAECONNRESET
...
```

Interestingly, this only appears to be an issue via AJAX; accessing this endpoint directly (i.e. in a new browser window) seems to work fine.

**Comment by cycomachead** [comment]
Closing, since the cloud app has been entirely re-written.
