### ISSUE TITLE
TAB to shift focus in lists

### ISSUE THREAD

**Issue by DavidGasku** [jmoenig/Snap--Build-Your-Own-Blocks#1987]
It would be very useful if you could advance to the next list item by hitting TAB, automatically selecting its contents.

**Comment by bromagosa** [comment]
Hmm, this totally works for me:

![out](https://user-images.githubusercontent.com/1016697/35053777-61e9ab50-fbab-11e7-9f06-251637903ec5.gif)

**Comment by DavidGasku** [comment]
yes, it works for me at home. I'll take at look at school tomorrow, as it happened in a chromebook. By the way, it would be useful if the arrows would be at a fixed position so you can add many elements without moving the mouse, but I'll open a new request for that.
Thanks!
