### ISSUE TITLE
Question about execution paused when Snap! is minimized

### ISSUE THREAD

**Issue by jguille2** [jmoenig/Snap--Build-Your-Own-Blocks#2006]
Hi,
I had not noticed this... but when Snap! window is minimized, the execution is paused.

Is this the desired behavior?

Thanks!

**Comment by jmoenig** [comment]
This is beyond our control now, because browsers are now always pausing execution of all tabs that are not in the foreground. Sigh.

**Comment by jguille2** [comment]
Thanks Jens,

I had not noticed this!
Now I've been reading some details about the possibility of using _requestAnimationFrame_ only to render animations and using another timer to logic... but I think this is unfeasible for our stepper.

So, we only have to document this behavior: **Minimize Snap! window pauses the program**

**Comment by jguille2** [comment]
Hey!

Only a note for Snap4Arduino and other Snap flavors ...

I see nwjs implemented a _--disable-raf-throttling_ flag... and maybe we can consider changing this behavior in desktop flavors.

I'll study it later (tucked inside my my large todo sack...)

**Comment by jpliew** [comment]
This behavior is noted on the installed EXE. Is the EXE also use browser for execution? 

![image](https://user-images.githubusercontent.com/1773147/35827656-ff23c4ea-0b10-11e8-96fa-3088c0eb4f98.png)

**Comment by jguille2** [comment]
Yes!
Snap! runs in a browser.
Snap4Arduino is certainly a "normal" Snap! with some additions (serialport connection with firmata protocol and a webserver). To do this, the app is built with nw.js to allow node modules and a real browser implementation.

So, Snap4Arduino is running in a browser (with a chromium engine)... and browsers issues are our issues.

As I said, we will consider a modification for the desktop version to fix this minimization issue. But not for the next version (probably next week).

Joan

**Comment by jpliew** [comment]
Thanks @jguille2
