### ISSUE TITLE
Should "tell" change the currentSprite?

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap--Build-Your-Own-Blocks#2037]
I assumed that the IDE_Morph would consider the currentSprite to be the one running the blocks. Here is a simple version of my problem:

![image](https://user-images.githubusercontent.com/2138696/36724423-ba70b174-1be5-11e8-9682-ab3723b86143.png)

I think that tell x y should be the same as clicking on y when in x's script area.

I can work around this with broadcasting a message that causes x to run y but would rather not.

**Comment by jguille2** [comment]
Hi Ken,

This has not relation with ask/tell methods.

`ide.currentSprite` is the sprite selected in the corral. You can ask this from any sprite (or stage), and the result will be the same.

**Comment by bromagosa** [comment]
Exactly. `currentSprite` is an attribute, not a function. It will always hold the currently selected sprite.

The sprite you're looking for is referenced by the `this` pseudovariable:

![untitled script pic](https://user-images.githubusercontent.com/1016697/36727971-6ebb4b98-1bbf-11e8-8940-2c83ffae08f0.png)

**Comment by brianharvey** [comment]
... not to mention  ![myself](https://user-images.githubusercontent.com/3885074/36756595-5927e1e2-1bc4-11e8-8e37-d4ee67e6a829.png)

**Comment by ToonTalk** [comment]
Thanks all.
