### ISSUE TITLE
List to Sentence & Join Words blocks both NOT working

### ISSUE THREAD

**Issue by selimtezel** [jmoenig/Snap--Build-Your-Own-Blocks#2046]
From Piazza:
Maxwell Bigman
"List to Sentence & Join Words blocks both NOT working
My student and I are having trouble with both List => Sentence block and the Join words block. I am trying to mess around with the block definition because it doesn't seem to be working properly. Am I the only one with that issue?"

https://piazza.com/class/h8yx482idav52y?cid=1961

I can confirm the issue.  Block definitions seems somehow corrupted.

**Comment by brianharvey** [comment]
Fixed.  I think this happened during the frantic repairs this morning.

**Comment by selimtezel** [comment]
Hi Brian and Jens,
The issue seems to persist even after clearing cache and re-importing
![untitled script pic 14](https://user-images.githubusercontent.com/5288035/36981587-8c734af0-205b-11e8-81ab-acc2622bc2e5.png)
Kindly advise
Selim

**Comment by jmoenig** [comment]
Ack! Please try again now. Tnx

**Comment by jmoenig** [comment]
I've updated the tools library with a fix for this particular case and tested that it now gets the right version. Unfortunately the browser / server case aggressively holds on to the old version, but the right one will eventually come through
