### ISSUE TITLE
CORS problem: Using the "http block" in order to read from a file by using a PHP script won 't work

### ISSUE THREAD

**Issue by seteahconnoc** [jmoenig/Snap--Build-Your-Own-Blocks#2048]
I am using Snap!'s "http block" in order to read from a file by using a PHP script on my webspace. This works well via:

`http://...mywebspace.../index.php?type=read&filename=test.txt`

in the address bar of my chromium browser. (If necessary, I will send the PHP script. It starts with a `Header set Access-Control-Allow-Origin "*"`) Last year, I was able to achieve this by using the "http block" as well. -> #1583 Sadly, it just won 't work right now. Right now, the webspace isn 't protected via .htaccess and .htpasswd. I 'm using chromium's addon `Header set Access-Control-Allow-Origin "*"`. Frankly, I have to say, that I am not an expert in the CORS topic. So, an answer "for dummies" would be appreciated.

Any suggestions would be helpful.

**Comment by bromagosa** [comment]
Can you share your Snap! code? Notice that the `http` block is now called `url` and lets you specify a protocol. If you don't specify it, it will choose https by default, so you may need to include `http://` in front of your URLs.

**Comment by KingDavid12** [comment]
@bromagosa It may not be an issue with the Snap! code, for some reason (at least Chrome) doesn't like Access-Control-Allow-Origin "*". Instead you have to resort to reading the origin of the request and echoing that back as the header.

**Comment by seteahconnoc** [comment]
Thanks a lot for your help and patience - and sorry, I just didn 't pay attention. It 's all there...

- There 's this issue (#782) on related topics.

- There 's `Snap!`'s source code:
```
Process.prototype.reportURL = function (url) {
    var response;
    if (!this.httpRequest) {
        // use the location protocol unless the user specifies otherwise
        if (url.indexOf('//') < 0 || url.indexOf('//') > 8) {
            if (location.protocol === 'file:') {
                // allow requests from locally loaded sources
                url = 'https://' + url;
            } else {
                url = location.protocol + '//' + url;
            }
        }
        this.httpRequest = new XMLHttpRequest();
        this.httpRequest.open("GET", url, true);
        this.httpRequest.send(null);
    } else if (this.httpRequest.readyState === 4) {
        response = this.httpRequest.responseText;
        this.httpRequest = null;
        return response;
    }
    this.pushContext('doYield');
    this.pushContext();
};
```

- There 's this block:
![untitled script pic](https://user-images.githubusercontent.com/23081344/36995665-f37b7d22-20b4-11e8-9923-2ac41e0b13bc.png)

@bromagosa Since you asked: This is my `Snap!` script. (Simple enough.)
![untitled script pic 1](https://user-images.githubusercontent.com/23081344/36995803-67b98c9c-20b5-11e8-8914-15fb2a7bcf5c.png)
This `read` block comes along with a `write` block and a `delete` block. I find it quite useful in CS education.

**The issue can be closed.** I checked out the SSL configuration of my (rarely used) webspace. **It 's all working just fine with a proper `https` site.** Feel free to decide, if a "https reminder" should be part of the `url` block's help or if this point is just trivial today. Perhaps, the **title of the issue should be improved**.

---

Just out of curiosity: Can someone suggest me further JavaScript literature on the source code comment `use the location protocol unless the user specifies otherwise`?

**Comment by bromagosa** [comment]
The location protocol is what precedes the URL. In a web browser it's usually either `http://` or `https://`, and when opening a local file it will be `file://`.

What this code does is look for the protocol in which the page has been loaded, then, if the `url` block has no protocol specified, it will prepend it to it.

Does that make sense? :)

**Comment by seteahconnoc** [comment]
I 'm not sure. So, just to make things clear.

- This script is working just fine:
![untitled script pic 4](https://user-images.githubusercontent.com/23081344/37035472-f6685698-214c-11e8-980c-cc04903cb001.png)

- This refers to the same https site. It 's working fine as well:
![untitled script pic 2](https://user-images.githubusercontent.com/23081344/37035498-0c336404-214d-11e8-8beb-a58b0f079d71.png)

- This won 't work:
![untitled script pic 3](https://user-images.githubusercontent.com/23081344/37035577-45ae388a-214d-11e8-862b-dbf6b7fbbd7d.png)
But if I put the same line into a browser 's address bar, it 's working.

My PHP script has to start with a `Header set Access-Control-Allow-Origin "*"`. My chromium browser needs no further addons. I guess, I still don 't understand the CORS related topics quite right.

**Comment by jguille2** [comment]
Hi @seteahconnoc ,

I think the problem is the environment: if you are into https, http request are forbidden.

So, the problem is not the changes into http-url block. The change is that snap.berkeley.edu/run is now running always over https. Then, you can't make http requests.

If you run Snap in your own server, and you ran Snap over http,  you'll be able to make both (http and https)requests.

**Comment by seteahconnoc** [comment]
@jguille2 That explains, why I could make successful http requests via `Snap!` started directly from the `snap.html` file in the folder that I saved locally. Thank you. So, that 's it for the moment.
