### ISSUE TITLE
Examples wouldn't open

### ISSUE THREAD

**Issue by rmillwood** [jmoenig/Snap--Build-Your-Own-Blocks#2052]
I couldn't open the Examples.

![image](https://user-images.githubusercontent.com/2338141/37036201-cecdbcbe-2146-11e8-8d16-3d802b7ad761.png)

**Comment by jguille2** [comment]
Oh!
Yes, you're right.

We must fix this.

**Comment by jguille2** [comment]
I see the problem is with the new definition of _IDE_Morph.prototype.getURL_ function, from [this recent commit](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/commit/69bb73d1bbdbb5ed12a9bdf02ffcdb4118f7e200#diff-9959318faecdd7b879dff989df73ee94).

**Comment by jguille2** [comment]
Ping @jmoenig,
The problem is that we can not change request.responseType in synchronous operation (I've seen [this docs](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType).)

>setting responseType for synchronous requests will throw an InvalidAccessError exception

I don't know if it is better to force an assynch. operation or change the new code.

**Comment by jmoenig** [comment]
Oh, geez. I hate browsers. Hmmm... We probably should eliminate synchronous requests altogether. In the meantime we need those new changes to properly import sounds. Let me try to fix this. Thanks!

**Comment by jmoenig** [comment]
I've just fixed this. Will release a new version either tomorrow or early next week, then the examples (and loading remotely hosted non-SnapCloud projects) should again work.

**Comment by jguille2** [comment]
Thanks Jens,
Tested and fine!

As you said, maybe we can force all request to an asynchronous behavior.
