### ISSUE TITLE
block search doesn't include TELL

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#2053]
... and probably the other new-in-4.1 blocks.  From Piazza:

Instructor Jerry Kearns posted a new Note. 

Tell command does not appear in search

A minor thing - I was trying to show a student the tell command, and I couldn't find it using the search (command-f or hourglass) function.

Search or link to this question with @1966.

**Comment by jmoenig** [comment]
good catch, will fix, thanks!
