### ISSUE TITLE
New SNAP account not getting verification email

### ISSUE THREAD

**Issue by jcaldw737** [jmoenig/Snap--Build-Your-Own-Blocks#2062]
I created a new SNAP account today, but didn't get a verification email.
Thinking that I had perhaps put in an incorrect email address, I created another account being very careful about my email.  But still no verification email.

**Comment by bromagosa** [comment]
Did you check your spam folder?

**Comment by jcaldw737** [comment]
I'm using Outlook and I checked the junk folder. Is that the same as spam?For what it may be worth, I have created other accounts and gotten my password from the old system very quickly. BTW thanks for getting back to me so quickly.
Sent from a cell phone.
-------- Original message --------From: Bernat Romagosa <notifications@github.com> Date: 3/19/18  06:08  (GMT-05:00) To: jmoenig/Snap--Build-Your-Own-Blocks <Snap--Build-Your-Own-Blocks@noreply.github.com> Cc: jcaldw737 <jcaldwell@2kn2kn.com>, Author <author@noreply.github.com> Subject: Re: [jmoenig/Snap--Build-Your-Own-Blocks] New SNAP account not getting verification email (#2062) 
Did you check your spam folder?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jmoenig/Snap--Build-Your-Own-Blocks","title":"jmoenig/Snap--Build-Your-Own-Blocks","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jmoenig/Snap--Build-Your-Own-Blocks"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bromagosa in #2062: Did you check your spam folder?"}],"action":{"name":"View Issue","url":"https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/2062#issuecomment-374161041"}}}

**Comment by bromagosa** [comment]
Can you let me know your Snap! username so I can check what happened?

**Comment by jcaldw737** [comment]
ICTCM18 is the username. Thanks for investigating!
Sent from a cell phone.
-------- Original message --------From: Bernat Romagosa <notifications@github.com> Date: 3/19/18  12:28  (GMT-05:00) To: jmoenig/Snap--Build-Your-Own-Blocks <Snap--Build-Your-Own-Blocks@noreply.github.com> Cc: jcaldw737 <jcaldwell@2kn2kn.com>, Author <author@noreply.github.com> Subject: Re: [jmoenig/Snap--Build-Your-Own-Blocks] New SNAP account not getting verification email (#2062) 
Can you let me know your Snap! username so I can check what happened?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jmoenig/Snap--Build-Your-Own-Blocks","title":"jmoenig/Snap--Build-Your-Own-Blocks","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jmoenig/Snap--Build-Your-Own-Blocks"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bromagosa in #2062: Can you let me know your Snap! username so I can check what happened?"}],"action":{"name":"View Issue","url":"https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/2062#issuecomment-374275000"}}}

**Comment by bromagosa** [comment]
Our mail server logs show that three verification emails got delivered to your address. I don't know how Outlook works, but junk should be the same as spam, yes.

From what you say, I'm thinking it is possible that your university mail server is rejecting our emails before they reach you. Do you know if this has happened to someone else with the same email domain?

Anyway, I've manually verified your account now, but it'd still be great if we could find out why these never reached you.

Thanks for reporting! :)

**Comment by jcaldw737** [comment]
Thanks so much for working on  this. I am returning home this evening and will pursue this  I was especially concerned because I had introduced a college instructor to SNAP on Saturday and she had done a good amount of startup work on her own new account that I didn't want her to lose. She is at a different institution from me.
Sent from a cell phone.
-------- Original message --------From: Bernat Romagosa <notifications@github.com> Date: 3/19/18  16:54  (GMT-05:00) To: jmoenig/Snap--Build-Your-Own-Blocks <Snap--Build-Your-Own-Blocks@noreply.github.com> Cc: jcaldw737 <jcaldwell@2kn2kn.com>, Author <author@noreply.github.com> Subject: Re: [jmoenig/Snap--Build-Your-Own-Blocks] New SNAP account not getting verification email (#2062) 
Our mail server logs show that three verification emails got delivered to your address. I don't know how Outlook works, but junk should be the same as spam, yes.
From what you say, I'm thinking it is possible that your university mail server is rejecting our emails before they reach you. Do you know if this has happened to someone else with the same email domain?
Anyway, I've manually verified your account now, but it'd still be great if we could find out why these never reached you.
Thanks for reporting! :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jmoenig/Snap--Build-Your-Own-Blocks","title":"jmoenig/Snap--Build-Your-Own-Blocks","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jmoenig/Snap--Build-Your-Own-Blocks"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bromagosa in #2062: Our mail server logs show that three verification emails got delivered to your address. I don't know how Outlook works, but junk should be the same as spam, yes.\r\n\r\nFrom what you say, I'm thinking it is possible that your university mail server is rejecting our emails before they reach you. Do you know if this has happened to someone else with the same email domain?\r\n\r\nAnyway, I've manually verified your account now, but it'd still be great if we could find out why these never reached you.\r\n\r\nThanks for reporting! :)"}],"action":{"name":"View Issue","url":"https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/2062#issuecomment-374372606"}}}

**Comment by jcaldw737** [comment]
First I checked and that account is still receiving emails. Count you tell me the address from which the verification email comes.  I'll contact our IT folks about it.

**Comment by cycomachead** [comment]
The emails comes from postmaster@snap-cloud.cs10.org

Also, if anyone's account is locked, it simply means that they can't log in. No data is lost or deleted when that happens. If the procedures change, then we'll make it very clear before anyone could lose any work. (And it wouldn't be over such a short period anyway.)
