### ISSUE TITLE
Project no longer loads

### ISSUE THREAD

**Issue by beingDevisor** [jmoenig/Snap--Build-Your-Own-Blocks#2065]
After saving my project and reloading it, my project no longer loads in snap. Snap returns the following error after attempting to load the project:

> Load failed: TypeError: Failed to execute 'createLinearGradient' on 'CanvasRenderingcontext2D': The provided double value is non-finite.

Using Chrome version 65.0.3325.162 64 Bit

Any help would be appreciated. Thanks!

**Comment by jmoenig** [comment]
can you share the project and post the link here? Thanks!

**Comment by beingDevisor** [comment]
Here's the broken project:

https://snap.berkeley.edu/snapsource/snap.html#present:Username=mitchellbath&ProjectName=CT_Fight

**Comment by jmoenig** [comment]
Thanks. I've retrieved the project and am investigating...

**Comment by jmoenig** [comment]
Okay, got it. It seems that at some point your browser was very low on memory, which caused the scripts in Sprite1 to assume x-coordinates of ```Infinity```. I've never seen this particular issue before, so I decided not to add code that always checks for this. Instead I've salvaged your project and cleaned up the scripts in Sprite1. You can find the salvaged version here:

https://snap.berkeley.edu/snapsource/snap.html#present:Username=jens&ProjectName=CT_Fight&editMode&noRun

Please open it, and save it to your account, then I'll remove it from mine again.

BTW: What a cool project! My colleague and I just had loads of fun fighting against each other on my laptop!

**Comment by beingDevisor** [comment]
Thank you so much!!! That project is really important to me. I'm also glad that you enjoyed it! My AP Computer Science Principles class will certainly be buzzing about this tomorrow.

Is there anything I can do to prevent this from happening again?

**Comment by jmoenig** [comment]
I'm not sure why this happened, my guess is that at some point your browser must have been very low on memory. If this happens again, please let me know so can research into this some more.

Oh, hey, If you don't mind i'd love to see your project when it's finished, and maybe even show it around here among my colleagues and in workshops at conferences. Would you be cool with that? If wo it would be great if you'd add some credits (to you and possible collaborators) and share the project with me again when it's done. (you can also directly email me at "jens at moenig dot org" or at "jens dot moenig at sap dot com".

Thanks, and good luck!

**Comment by beingDevisor** [comment]
That would be so cool! I'll let you know as soon as it's finished.

Thanks again!
