### ISSUE TITLE
[site] Can't access to projects on non-SSL site.

### ISSUE THREAD

**Issue by dekrain** [jmoenig/Snap--Build-Your-Own-Blocks#2071]
I saw that main server (snap.berkeley.edu) no longer supports non-SLL connections. When I try to access it with http://, I'm redirected to https://, so I no longer can get access in easy way to my projects. My browser (Chrome) doesn't let me to do it outside of the domain. Is there a (easy) way to recover them?

**Comment by superruzafa** [comment]
Please, take a look to #2029

**Comment by bromagosa** [comment]
Nope, I think @dekrain is referring to projects saved in `localStorage`.

Maybe @cycomachead will have an idea as per how to recover those?

**Comment by dekrain** [comment]
@bromagosa Yes, Chrome can show me contents of the cookies, but doesn't show me contents of the local storage (when I have saved my projects).

**Comment by jguille2** [comment]
Hi @dekrain ,

Maybe you will find quicker solutions... but if you have (or you are able to have) a webserver in your pc,  you can change your local dns and run _http://snap.berkeley.edu/_ in a local folder... and then, you will find your http.berkeley lost storage.

I write down some details to do this in a linux (debian-ubuntu) machine:
  - Install a webserver (`sudo apt-get install apache2`)
  - Download Snap source into a "web folder".
  - Test Snap!
    - If your web folder is _/var/www/html/snap/_ -> `http://localhost/snap/`
    - Else if it is _/home/your_user/public_html/snap/_ -> `http://localhost/~your_user/snap/`
  - Edit your local dns to direct snap.berkeley.edu domain to your machine
    - `sudo gedit /etc/hosts`
    - Add this line: `127.0.0.1    snap.berkeley.edu`
  - Restart your dns (restart session or `sudo /etc/init.d/networking restart`)
  - Open your local snap, but changing _localhost_ for _snap.berkeley.edu_
    `http://snap.berkeley.edu/snap/`
    or
    `http://snap.berkeley.edu/~your_user/snap/`
  - Then, opening local projects, you will find your lost projects!

  - After this, you only have to rechange _/etc/hosts_ and restart dns service to return again to the real berkeley site!

That's all. I hope this is useful for you.

Joan

**Comment by KingDavid12** [comment]
@dekrain Should be pretty easy: https://support.rackspace.com/how-to/modify-your-hosts-file/

**Comment by jguille2** [comment]
Yes, @KingDavid12 . This is pretty easy. The idea is to change the host file... but I tried to describe more details, because, you need a snap running by _http_ somewhere... It was a "complete" guide to do all.

@dekrain , if you have already _apache_ running, changing dns mapping will be a quick solution.

**Comment by dekrain** [comment]
Yeah, it worked. Thanks for help.
