### ISSUE TITLE
Too Many Open files on Server 

### ISSUE THREAD

**Issue by jeffstride** [jmoenig/Snap--Build-Your-Own-Blocks#2074]
When opening some project, I will occassionally get an error saying: "Could not fetch project [name]. [file names] too many open files" 
![image](https://user-images.githubusercontent.com/29986773/38008200-4ee75a4c-3202-11e8-97ae-5e578705e88e.png)

**Comment by bromagosa** [comment]
I see, I thought we had fixed this but it seems it keeps coming back.

@cycomachead I've now set the system-wide limits for the number of open files for user `cloud` to unlimited. I hope that fixes it for good.

@jeffstride please let me know if this issue happens ever again.

**Comment by bromagosa** [comment]
Just for the sake of documentation, I've set the limit in `/etc/security/limits.conf`

**Comment by bromagosa** [comment]
Aaand apparently there's a bug in Ubuntu that prevents these changes from being applied. I followed this answer in SO and it seems to have worked now:

https://unix.stackexchange.com/a/370652
