### ISSUE TITLE
Visible Stepping Slider Changes Stage Size

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#2080]
Version 65.0.3325.181 (Official Build) (64-bit)

I have visible stepping on, and whenever I move the slider all the way to the right (whether or not I am running a script), the stage resizes...

![visible-stepping-slider-changes-stage-size](https://user-images.githubusercontent.com/6549787/38648803-217b8360-3dc1-11e8-842c-4d228b47bb16.gif)

**Comment by brianharvey** [comment]
Yes, this is because you're actually moving the mouse a little past the end of the slider and hitting the stage resize button.  I agree that this is wrong behavior.

**Comment by towerofnix** [comment]
This is exactly the same issue as #1586, by the way.

**Comment by brianharvey** [comment]
Right, thanks.  Closing this one.
