### ISSUE TITLE
Cannot load XML generated by 'download script' if it contains custom block

### ISSUE THREAD

**Issue by boyzhirui** [jmoenig/Snap--Build-Your-Own-Blocks#2088]
The 'download script' generated XML cannot be loaded if it contains custom blocks. 

For example, if download the following blocks using 'download script', then reload in Snap!, the 'load failed' issue will occur.

<img width="206" alt="Example" src="https://user-images.githubusercontent.com/6066749/39412170-10580cc4-4be6-11e8-807f-f829e3658abd.png">

In Chrome:
<img width="571" alt="Load failed in Chrome" src="https://user-images.githubusercontent.com/6066749/39412136-8d811534-4be5-11e8-9e44-893608ab38f3.png">

In Safari:
<img width="541" alt="Load failed in Safari" src="https://user-images.githubusercontent.com/6066749/39412140-94bc8efa-4be5-11e8-96d4-8361e3be98ed.png">

I know this feature is not supported now, but it would be nice if the information of custom block can be serialized as well when just downloading the script. Or showing the custom block as 'obsolete' without loading failed.

**Comment by jmoenig** [comment]
Can you share your project and post the link to it here, I'd like to investigate. Thanks!

**Comment by bromagosa** [comment]
@jmoenig, @boyzhirui is talking about the hidden "download script" functionality:

![image](https://user-images.githubusercontent.com/1016697/39423512-852de780-4c72-11e8-82ea-3fc1d5e1adab.png)

This limitation is something we are aware of and the reason why we decided to hide the functionality in the first place.

We should discuss what should happen when you try to load back a script that contains a block that doesn't exist in the project, or maybe yank the block definition into the XML, but that means going down the dependency handling rabbit hole.

**Comment by jmoenig** [comment]
Oh! So *that's* not even an official feature yet, but something that's under construction.

**Comment by brianharvey** [comment]
@bromagosa We don't have to have dependency checking for this non-feature, but we do need it for Export Blocks.  (And we have a PR doing that, but Jens doesn't like it.)
