### ISSUE TITLE
Sound removing bug?

### ISSUE THREAD

**Issue by stezel** [jmoenig/Snap--Build-Your-Own-Blocks#2098]
Here is a Piazza post about a possible bug in removing sounds in Snap! by John Nelson:
https://piazza.com/class/h8yx482idav52y?cid=2159

Snap Bug - Removing Sounds
As a final project, I have some students re-creating a music playing device (ala IPod).  Their project has a lot of sounds; however, when students try to remove a specific sound, it will only allow them to remove the last sound in their list.  Is there any work around for this?  (We've tried clearing cache, and we've tried to make this work on multiple computers, neither options seem to work.)
Edit: including link to project -> https://snap.berkeley.edu/snapsource/snap.html#present:Username=rahshebalewis&ProjectName=Ipod

**Comment by jmoenig** [comment]
Yes, that's a bug. I did discover it a while ago and I've already fixed it for the next release with this commit: c84e2bd777b1d2c6b1b05c5e3a9001976f724c87 (it's live in the dev version).

**Comment by cycomachead** [comment]
Closing now that 4.2 is out.
