### ISSUE TITLE
Can't open big project (2MB)

### ISSUE THREAD

**Issue by gdavid04** [jmoenig/Snap--Build-Your-Own-Blocks#2106]
I saved a project that was 2 MB and now i can't load it. There are 2 arrays with size ~680x480, each element contains an array, with 4 numbers in it. I can't manually remove the lists, because Visual Studio Code won't show the entire file, many editors crash or say can't open file, too big. I really need that project.

**Comment by gdavid04** [comment]
It now loaded, but it took about 5 minutes. Now i remove the giant lists and save it.

**Comment by brianharvey** [comment]
If you right-click on a variable in the Variables palette and check the Transient box, the value of that variable will automatically be changed to 0 when you save the project.  This is a convenient way to avoid that problem in the future.

**Comment by gdavid04** [comment]
And what if i want to save the list with the project or somehow load it when the project loads?

**Comment by towerofnix** [comment]
@gdavid04 It sounds like those lists are processed from an image. Perhaps you could store them as a costume, load the "Pixels" library, and use "pixels of (current costume)" like this?

![(pixels of (current costume)) -- "pixels of" is from the looks category and "current costume" is from the sensing category](https://user-images.githubusercontent.com/9948030/40886345-5f3d664a-670c-11e8-9bfa-889c4e5799f1.png)

I don't know if Snap<i>!</i> resizes costumes that are bigger than the stage. If it does, you might have to click on the cog-wheel settings button, select "Stage size...", and change the stage size to the dimensions of your image (or bigger).

**Comment by brianharvey** [comment]
When you have a really long list, one of two things is true: (1) Your program computed it.  (2) You got the data out of a file or web page somewhere.  In case 1, you just recompute the list every time you load the project, or if that really takes a long time, you write the data out into a file, and then you're in case 2.  In case 2, you use the URL block to read the data, and then SPLIT to turn it into a list.
