### ISSUE TITLE
'Download source' menu item lacks libraries

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap--Build-Your-Own-Blocks#2113]
It downloads snap.zip but there are no libraries in it.

Also the zip file has a folder named __MACOSX that isn't part of Snap!.

**Comment by brianharvey** [comment]
There is no "source" for the libraries, which are Snap<i>!</i> projects.  As for __MACOSX, it's harmless but I agree it's unnecessary.

**Comment by ToonTalk** [comment]
I imagine I'm not the only one who thought that "download source" was a way to have Snap! locally. But it lacks help, examples, sounds, costumes, and libraries. I see it has the advantage of being 1MB instead of 56MB. But I doubt I'm the only one mislead by this.

**Comment by gdavid04** [comment]
Why there's no download source and libraries button? I was missing the libraries and examples too when i downloaded the source. (i don't use help, so i didn't notice first that it was missing)

**Comment by bromagosa** [comment]
Here's a link to download the whole thing from GitHub:

https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/archive/master.zip

Download source downloads just the source, but maybe there could be a menu item that links to this URL and fetches the whole repo.

**Comment by ToonTalk** [comment]
Yes, I think there should be such a menu item. I eventually used that link but for a long time I thought the source was the source for the whole system.

**Comment by cycomachead** [comment]
IMO, such a link is better off on a website where it can be explained / documented.

Anyway, if you need a zip, I would suggest people use the "Releases" page, and not necessarily the mac

**Comment by cycomachead** [comment]
Duplicate #347
