### ISSUE TITLE
Why are there 241 sounds but only 12 in Sounds/SOUNDS?

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap--Build-Your-Own-Blocks#2114]
So the Sounds... menu item displays only 12 sounds and yet at https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/tree/master/Sounds I see 241 sounds.

**Comment by brianharvey** [comment]
I originally copied the entire sound, costume, and background collections from Scratch, but then the selection window took forever to appear and so as a temporary measure picked a small subset of each to show.  Eventually we'll either make the selection window much faster or make the collections hierarchical.
