### ISSUE TITLE
login issues today

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#2117]
I've been working in snap today and suddenly gotten 'not logged in messages' on two occasions. The cloud menu insists that I am logged in, but I can't save or open projects until I log out and log in again.

![snaplogin](https://user-images.githubusercontent.com/6549787/41182755-0f37d882-6b45-11e8-8363-148562c8771c.png)

I do have snap open in multiple tabs.

**Comment by cycomachead** [comment]
I can't find anything specific that would have been an issue. :/ 

I did notice that you logged into without "remember me" being checked a few times - i'm not sure how that'd play into the issues, but if you were remembered, then it should have stayed that way.

Closing for now, but maybe we'll find more info at some point.
