### ISSUE TITLE
A "How many costumes a sprite currently has?" option

### ISSUE THREAD

**Issue by DyslexicAwe** [jmoenig/Snap--Build-Your-Own-Blocks#2122]
I guess it is not only me that would appreciate greatly to have an option, such as 
![proposal script pic](https://user-images.githubusercontent.com/16387241/41291226-603fe190-6e4f-11e8-881e-df096a406dc4.png)  (_or however you want to word it_) 
added in the **`of`** block in the Sensing palette 
along other pulldown options. ![12 06](https://user-images.githubusercontent.com/16387241/41291085-037c1a1e-6e4f-11e8-80b9-acc5a6b437d5.png)

**Comment by DyslexicAwe** [comment]
Thanks, Jens, but what to choose when making a new block that can report this for any sprite. 
I don't know how to achieve this in the Block Editor. Can you help?

![build_my_block](https://user-images.githubusercontent.com/16387241/41294815-375b4e90-6e59-11e8-88fe-27d569a53b4f.png)

**Comment by KingDavid12** [comment]
@DyslexicAwe I don't think you can do it in the block editor. I just tried editing the save file, but Snap! does not appear to render the sprite input correctly when it is used in a custom block. Short Form (TLDR): As of now, you can't.

**Comment by DyslexicAwe** [comment]
If by any chance, Jens, you are going to add `n_of_costumes` option, I would appreciate very much if you could add a `sprite's name` (for another sprite) in the `of` block from Sensing palette, as well. Thank you again. 

Thank you for explaining the limitations of using the sprite input when it is used in a custom block, @KingDavid12.

**Comment by KingDavid12** [comment]
@DyslexicAwe Your welcome.
I do have to agree that Jens should add either a `sprite's name` option to the `of` block or a new block that has the list of sprites as an input, and returns the sprite you selected.

**Comment by DyslexicAwe** [comment]
Why the sprite's name?, you may ask, if there's already a block that reports a list of `my _other sprites_`. Well, let me explain why this is not sufficient - in a recent project I have a dozen of sprites, which all have very similar costume, which is a simple small full circle and even if they have all different colors, I still am not able to recognize and tell one from another even if I can see them listed in the list of sprites.

**Comment by jguille2** [comment]
Hi @DyslexicAwe and @KingDavid12,

If you want a dropdown menu with all the available Sprites, you can just use _ask_ and _tell_ blocks directly, without a custom block

Then, you can do
![ask1](https://user-images.githubusercontent.com/2926315/41312697-0264b4f4-6e88-11e8-92bb-e74af15d1bac.png)

And if your request is complicate, and you want to do it for your users, you can make the reporter of the request.
![ask2editor](https://user-images.githubusercontent.com/2926315/41312786-4fe41ce2-6e88-11e8-8cd0-9d307e2a119b.png)
and then, just...
![ask3](https://user-images.githubusercontent.com/2926315/41312813-6cefdfe2-6e88-11e8-9852-74e7fb0d65d4.png)

**Comment by DyslexicAwe** [comment]
@jguille2 thank you.
