### ISSUE TITLE
Keyboard input doesn't complete in translation for custom blocks

### ISSUE THREAD

**Issue by kephas** [jmoenig/Snap--Build-Your-Own-Blocks#2142]
When activating keyboard input, you can type the name of blocks as they are translated, which to get an `if` block in French, I can type "si". But this doesn't work for my cutsom blocks although I provided a translation. For example, if I have a `draw` block which is translated to `dessiner` in French, as soon as I input "de", the block disappears from the search panel.

**Comment by jmoenig** [comment]
Oh, that's a bug for sure. Thank you for reporting it!

**Comment by jmoenig** [comment]
fixed for the next release. You can check the dev version at https://snap.berkeley.edu/snapsource/dev
Please let me know if you encounter any further issues, and again thank you for notifying me of this bug!

**Comment by jguille2** [comment]
Tested, it's perfect!!

**Comment by jmoenig** [comment]
Thanks for the quick test, @jguille2 ! Now I'll integrate the pending translation updates...

**Comment by kephas** [comment]
That was quick! Thanks!
