### ISSUE TITLE
Parameter menu disappears upon save and reload

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap--Build-Your-Own-Blocks#2145]
When I save

![image](https://user-images.githubusercontent.com/2138696/42572210-1e45edce-8511-11e8-941b-07c9fd0230dc.png)

Then when I load it I see

![image](https://user-images.githubusercontent.com/2138696/42570182-f7ea29ac-850a-11e8-87a9-06e5561ea420.png)

If I then open the editor and immediately click OK the menu is restored.

I tried to create a simpler example but wasn't able to recreate this problem.

Project is here:
[choice.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/2184477/choice.zip)

**Comment by jmoenig** [comment]
thanks, Ken. Investigating...

**Comment by jmoenig** [comment]
I can reproduce it, and also home in on what's happening...

**Comment by ToonTalk** [comment]
Great, thanks. Works fine.
