### ISSUE TITLE
Can't get verification email for new SNAP user

### ISSUE THREAD

**Issue by va2yes** [jmoenig/Snap--Build-Your-Own-Blocks#2148]
I have not received the verification email (it's not in spam folder). I believe I had a typo in my email address when I signed up for the account and there seems like no way to verify/change my email address. Please help!

**Comment by brianharvey** [comment]
Hmm, it's probably a good idea not to let people change the email address for an account without knowing its password.  Perhaps you should make a different account?

**Comment by va2yes** [comment]
Thanks, Brian. It would be great to be able to verify my email address without changing my user name. Any administration people I can contact regarding this issue?

**Comment by brianharvey** [comment]
Oh, if you can log in, don't worry about it.  It'll be important only if you want to change your password.

**Comment by va2yes** [comment]
but it is saying that i only have 1 day left to verify or........? What?

**Comment by brianharvey** [comment]
Oh.  It should mean we turn your account off, but I don't think we've invented that feature yet.  Anyway, I'll look into it.

**Comment by brianharvey** [comment]
Oh, wait...  What's your Snap! account user name?

**Comment by va2yes** [comment]
It's the same one, va2yes. Thanks for the help in advance, Brian!

**Comment by cycomachead** [comment]
We don't yet have a way for users to change their email. In the meantime, I've verified your account for you. Can you email snap-support@bjc.berkeley.edu and we'll update your email address.

Try logging out and logging in again and your verification status will update. :)
