### ISSUE TITLE
How to know the costume name of a clone?

### ISSUE THREAD

**Issue by geaplanet** [jmoenig/Snap--Build-Your-Own-Blocks#2152]
If I create clones and I assign each one a different costume...how to know the costume name of a clone when I click on it?

**Comment by jmoenig** [comment]
there is a block in the "Pixels" library that lets you query the name of a costume, including the "current" one.

**Comment by geaplanet** [comment]
Thanks, @jmoenig

**Comment by geaplanet** [comment]
I think "current costume" block doesn't work with clones :-/

**Comment by jmoenig** [comment]
it does so for me:

![costume name of clones](https://user-images.githubusercontent.com/2596285/43045000-90bb0522-8db0-11e8-9c17-9c0661dfcfff.png)

![stage](https://user-images.githubusercontent.com/2596285/43045008-b148cedc-8db0-11e8-965e-2df7769d429e.png)

**Comment by geaplanet** [comment]
Thanks for the examples.
