### ISSUE TITLE
Title for Snap! home page says 4.1

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap--Build-Your-Own-Blocks#2160]
![image](https://user-images.githubusercontent.com/2138696/43390880-306acf8a-93e7-11e8-8ad2-b03f8c05d7ec.png)

**Comment by brianharvey** [comment]
Fixed, thanks.

**Comment by jguille2** [comment]
Thanks Brian,

I see 4.2 now. But my suggestion would be to remove the version of the title. In fact, it is the Snap! project home page... with all the Snap! info (latest version, maybe testing versions, past stable versions...)

Joan
