### ISSUE TITLE
Multiple inputs type parameter and empty list argument

### ISSUE THREAD

**Issue by haritop** [jmoenig/Snap--Build-Your-Own-Blocks#2176]
![multiple_inputs](https://user-images.githubusercontent.com/8059587/43842447-125ab67e-9b2e-11e8-9b9f-b1b51811f713.jpg)
Shouldn't they behave the same?

**Comment by brianharvey** [comment]
Yup.  This fails too:
![untitled script pic](https://user-images.githubusercontent.com/3885074/43867677-0ecb35d8-9b1f-11e8-8b17-8be328aaaafa.png)
But it works if there are inputs in the INGREDIENTS block.

I think we may already know about this bug.  Michael will find it if this is a duplicate.  :-)

**Comment by jmoenig** [comment]
Ah, that's an old one that should've been fixed long ago. Investigating...

**Comment by jmoenig** [comment]
Okay, found it. Now testing the fix...

**Comment by jmoenig** [comment]
all tests passed, will push the fix shortly

**Comment by jmoenig** [comment]
fixed. Please give it a try yourself in the dev version:

https://snap.berkeley.edu/snapsource/dev/snap.html

I'll probably make a maintenance release with this later today.
Thanks!

**Comment by jmoenig** [comment]
This patch just now went live in the newest maintenance release.

**Comment by haritop** [comment]
![snap_params](https://user-images.githubusercontent.com/8059587/45267836-95626c80-b47c-11e8-9434-850c9701362e.png)
In the first, as well as in the third, case we get "no args"
But in the second we get 50.
This is probably an extreme case, and I don't know how it fits in the boader Snap design.
But in my opinion, when we pass no arguments to a function we mean no arguments, regardless of context.
Anyway Jens, you are the one to decide if it's worth dealing with.

**Comment by jmoenig** [comment]
both cases are what I'm intending. The first one has no args because you're specifying an explicit format parameter which exclipses implicit ones. The third example uses the ```list``` primitive whose variadic input is special in that it cannot be passed a list (you also cannot drop anything on the expansion arrows there). The special list primitive behavior is something I'd like to get rid of at some point, but currently it's the correct thing.

**Comment by haritop** [comment]
I see. 
And you can always use the third expression, if you explicitly mean "no arguments".
Thanks for clearing this up.
