### ISSUE TITLE
How to add the values (instead of the object itself) with "add {list_as_variable} to {another_list_as_variable}" block? 

### ISSUE THREAD

**Issue by DyslexicAwe** [jmoenig/Snap--Build-Your-Own-Blocks#2186]
The `add list_as_variable to another_list_as_variable` block seems to be adding the object itself to the other object. And using it in a loop, in which values of the first list_as_variable are changed before it is added to the other list_as_variable, _what you get after the loop is through_ is the resulting list not containing the values as they were at the moment when the list was added, instead what you get is - which is what I don't want - multiple copies of what were _the values of the list in the last step of the loop_. 

I want values to be added. How can I achieve this? 

![how to add values instead of object itself](https://user-images.githubusercontent.com/16387241/44027865-4e4a040a-9ef8-11e8-859d-88e0310c144a.png)

**Comment by DyslexicAwe** [comment]
I can solve the problem with `map over` block or as I have for fun renamed the function in the 50 sec long video [here](https://www.youtube.com/watch?v=okGVP1CbKY4) `use the glasses on` block (see the transparent glasses in the video).

**Comment by DyslexicAwe** [comment]
Here's the resulting list of lists of lists (i.e. the list of a costume_pixels' rows, made of lists of pixels' columns, made of lists of RGBAs).   
![costume_pxls_positioned__list_view](https://user-images.githubusercontent.com/16387241/44031409-37132544-9f04-11e8-8ac5-fa2e8572ea72.png)
The number of pixels' columns is the costume's width.

**Comment by brianharvey** [comment]
In the List library there's an APPEND block which will do what you want.

**Comment by DyslexicAwe** [comment]
Thank you for the answer.

**Comment by DyslexicAwe** [comment]
It turns out that APPEND makes _**b)**_ in the following 3D structure **_a)_** rows **list of** **_b)_** columns **lists of** **_c)_** RGBA **lists** dissappear. So the structure is flatened (which I don't want). 

The solution, mentioned above, from the video, however, retains the structure intact, while succesfully "valuefying" the b) before adding it to the a).
![valuefication](https://user-images.githubusercontent.com/16387241/44089203-336c0cf4-9fc6-11e8-8f05-bcb3877074f9.png)

**Comment by brianharvey** [comment]
Oh, sorry, I thought flattening was what you wanted!  Never mind.  Your solution is great, very elegant.
