### ISSUE TITLE
List of the names of the sounds attached to a sprite

### ISSUE THREAD

**Issue by jonbus** [jmoenig/Snap--Build-Your-Own-Blocks#2194]
Dear colleges,

I'm trying to get a list with the names of the sounds attached to a sprite. It would be like to get the costumes names of a sprite (I can do it).
I've been looking for a way, but I can´t find a solution.

Maybe it's a easy question, but I feel I need a bit of help.

Thanks in advance,

Jon.

**Comment by KingDavid12** [comment]
@jonbus Just to clarify, you want to be able to get the names of the sprite's costume and the sprite's sounds?

**Comment by jonbus** [comment]
@KingDavid12 : The sprite's sounds names

**Comment by KingDavid12** [comment]
@jonbus I just finished updating my previous comment with a solution. It includes a solution for both costumes and sounds, as you had not answered at the point when I started answering.

**Comment by jonbus** [comment]
Thank youuuuuu !!!!
It's just what I need !!!
Maybe I've to start to learn JavaScript ;-)

**Comment by KingDavid12** [comment]
@jonbus Your welcome!
