### ISSUE TITLE
Localhost XMLs not opening

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#2200]
Hi,

I'm on my alternate machine, I have XAMPP running, and in my current copy of the repo, I can't get the BJC 1.2.1 starter project file to load, it just says "unable to retrieve project."

https://snap.berkeley.edu/snapsource/snap.html#open:http://localhost:/bjc-r/prog/1-introduction/U1L2-Gossip.xml

from /bjc-r/cur/programming/1-introduction/2-gossip-and-greet/1-gossip.html?topic=nyc_bjc%2F1-intro-loops.topic&course=bjc4nyc.html&novideo&noassignment

It loads fine on the edc.org server...

What do I need to change to make this project load?

Thanks,
Mary

**Comment by bromagosa** [comment]
I have a feeling that your URL may be wrong, because there's a colon after localhost and no port is specified. It should either be `localhost:[port]` or just `localhost`, with no colon.

**Comment by DarDoro** [comment]
Probably the CORS issue. Possible fixes:
- localhost server must be configured to support CORS (Access-Control-Allow-* headers at least) 
- Chrome client side CORS extension can be used 
- browser SECURITY can be temporarily DISABLED with command line switch


Up to date info - Google keyword "CORS localhost bypass"

**Comment by maryfries** [comment]
It's not happening today, so whatever was the problem is now resolved. The colon is still there (http://snap.berkeley.edu/snapsource/snap.html#open:http://localhost:/bjc-r/prog/1-introduction/U1L2-Gossip.xml), but it loads properly now. Go figure!
