### ISSUE TITLE
Include help and predefined costumes in offline version

### ISSUE THREAD

**Issue by SanderTacker** [jmoenig/Snap--Build-Your-Own-Blocks#2206]
We've been using Scratch and BYOB in our german school for years and are planning to switch so SNAP!, which is really a great improvement.

To be independent from the internet, especially during exams, we want to use to offline version which we downloaded via the SNAP! menu point "download source". Unfortunately in the offline version there seams to be no help content (right click on a block -> help does nothing) and no predefined costumes (file -> costumes does nothing) available. I'm using an up-to-date Firefox browser.

Is there a possibilty to include help and predefined costumes in the offline version?

Thanks for your help!
Sander

**Comment by brianharvey** [comment]
To get the complete system, just download this Github repo to your computer!  The "download source" option is to satisfy the AGPL principle that the source of a service should be examinable.

@jmoenig Maybe we should include a README in the zip file saying this.

**Comment by SanderTacker** [comment]
Thank you, that's what I needed. In deed, a comment in the zip file would be helpful.
