### ISSUE TITLE
Can't go to https://snap.berkeley.edu/

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap--Build-Your-Own-Blocks#2213]
I get

![image](https://user-images.githubusercontent.com/2138696/45808854-bae24800-bcbe-11e8-8834-af1fba49a7d4.png)

and if I enter my Snap! username and password the dialog just comes back. Chrome and FireFox.

**Comment by towerofnix** [comment]
Weird - it loads for me. (So does the Snap<i>!</i> editor.)

**Comment by ToonTalk** [comment]
Someone must have fixed it. It was a problem on multiple browsers (and 2 computers) for at least 15 minutes.

**Comment by towerofnix** [comment]
Good to know! :tada:

**Comment by cycomachead** [comment]
The snap.berkeley.edu server died for some reason during an update, and it failed over but to the wrong site. The fail over should be fixed the next time something goes down.

If snap.berkeley.edu goes down, https://cs10.org/snap is the best backup.
