### ISSUE TITLE
MacBook Pro + Safari: blank screen when click on "move"

### ISSUE THREAD

**Issue by jcaldw737** [jmoenig/Snap--Build-Your-Own-Blocks#2223]
One of my students says:  I have a MacBook Pro, and I am using Safari. It lets me key in the "controls" that I want to happen, but when I click to make the pointer move, the screen goes blank and the pointer disappears.

**Comment by jmoenig** [comment]
Hmm... I've got a MacBook Pro, and I am also using Safari often. Just checked right now, everything works fine, can't reproduce this...

**Comment by jcaldw737** [comment]
Thanks for getting back so quickly!  The student is coming to my office Tuesday. Why don't we close this now and I'll reopen then if there's still a problem. 
Sent from a cell phone.
-------- Original message --------From: Jens Mönig <notifications@github.com> Date: 10/4/18  16:00  (GMT-06:00) To: jmoenig/Snap--Build-Your-Own-Blocks <Snap--Build-Your-Own-Blocks@noreply.github.com> Cc: jcaldw737 <jcaldwell@2kn2kn.com>, Author <author@noreply.github.com> Subject: Re: [jmoenig/Snap--Build-Your-Own-Blocks] MacBook Pro + Safari: blank screen when click on "move" (#2223) 
Hmm... I've got a MacBook Pro, and I am also using Safari often. Just checked right now, everything works fine, can't reproduce this...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jmoenig/Snap--Build-Your-Own-Blocks","title":"jmoenig/Snap--Build-Your-Own-Blocks","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jmoenig/Snap--Build-Your-Own-Blocks"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jmoenig in #2223: Hmm... I've got a MacBook Pro, and I am also using Safari often. Just checked right now, everything works fine, can't reproduce this..."}],"action":{"name":"View Issue","url":"https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/2223#issuecomment-427167452"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/2223#issuecomment-427167452",
"url": "https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/2223#issuecomment-427167452",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [jmoenig/Snap--Build-Your-Own-Blocks] MacBook Pro + Safari: blank screen when click on \"move\" (#2223)",
"sections": [
{
"text": "",
"activityTitle": "**Jens Mönig**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@jmoenig",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"jmoenig/Snap--Build-Your-Own-Blocks\",\n\"issueId\": 2223,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"jmoenig/Snap--Build-Your-Own-Blocks\",\n\"issueId\": 2223\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/2223#issuecomment-427167452"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 388173444\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by brianharvey** [comment]
Next time, get the student to export the project and include it with the bug report!  :-)

**Comment by jcaldw737** [comment]
Will do!
Sent from a cell phone.
-------- Original message --------From: Brian Harvey <notifications@github.com> Date: 10/5/18  22:36  (GMT-06:00) To: jmoenig/Snap--Build-Your-Own-Blocks <Snap--Build-Your-Own-Blocks@noreply.github.com> Cc: jcaldw737 <jcaldwell@2kn2kn.com>, Author <author@noreply.github.com> Subject: Re: [jmoenig/Snap--Build-Your-Own-Blocks] MacBook Pro + Safari: blank screen when click on "move" (#2223) 
Next time, get the student to export the project and include it with the bug report!  :-)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jmoenig/Snap--Build-Your-Own-Blocks","title":"jmoenig/Snap--Build-Your-Own-Blocks","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jmoenig/Snap--Build-Your-Own-Blocks"}},"updates":{"snippets":[{"icon":"PERSON","message":"@brianharvey in #2223: Next time, get the student to export the project and include it with the bug report!  :-)"}],"action":{"name":"View Issue","url":"https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/2223#issuecomment-427542581"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/2223#issuecomment-427542581",
"url": "https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/2223#issuecomment-427542581",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [jmoenig/Snap--Build-Your-Own-Blocks] MacBook Pro + Safari: blank screen when click on \"move\" (#2223)",
"sections": [
{
"text": "",
"activityTitle": "**Brian Harvey**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@brianharvey",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"jmoenig/Snap--Build-Your-Own-Blocks\",\n\"issueId\": 2223,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/2223#issuecomment-427542581"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 388173444\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by jcaldw737** [comment]
Student was clicking on the icon which gave her a new sprite and made her work-space switch and become empty.

![image](https://user-images.githubusercontent.com/5361659/46690454-f5594980-cbc7-11e8-809e-a9398b8d22a0.png)
