### ISSUE TITLE
Better error messages needed when nonlist given as list input

### ISSUE THREAD

**Issue by xtitter** [jmoenig/Snap--Build-Your-Own-Blocks#240]
When a list variable is uninitialized -- making it not a list -- Snap doesn't give a great error message to list operations attempted on it.

http://snap.berkeley.edu/snapsource/snap.html#present:Username=nate&ProjectName=error%20reporting

When there is a script
![script](https://f.cloud.github.com/assets/825869/1597480/f21f28e0-5311-11e3-90eb-07a8bdc10025.png)
the error message is ok, but would be better referring to the object pointed to by the variable named 'a'.

When this error is in a block, you get no error at all.  I haven't done a lot of testing to see which errors propagate out of custom blocks to their callers; maybe most do?  It would be great if this one did!

I run into this problem myself a lot; I'm guessing kids do as well.

**Comment by cycomachead** [comment]
Closing because we have moderately improved the message but also tagging #1629

**Comment by brianharvey** [comment]
So, are we going to do the Really Great Error Message thing where we (when appropriate) say "you're probably missing the base case of a recursion"?

**Comment by cycomachead** [comment]
Maybe. But there are so many more straightforward and useful improvements we can make before then. 

-- 
Michael Ball
From my iPhone
michaelball.co
