### ISSUE TITLE
contains doesn't check for deep-equality?

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap--Build-Your-Own-Blocks#265]
Is it that 'contains' checks for 'eq' but '=' checks for 'equal'?

![screen shot 2013-12-04 at 2 27 32 pm](https://f.cloud.github.com/assets/2229297/1679096/f9b04326-5d45-11e3-9c78-c3a8b27e7506.png)
![screen shot 2013-12-04 at 2 26 46 pm](https://f.cloud.github.com/assets/2229297/1679098/f9b5ac80-5d45-11e3-8209-23479b88e8b2.png)
![screen shot 2013-12-04 at 2 26 53 pm](https://f.cloud.github.com/assets/2229297/1679099/f9b75db4-5d45-11e3-823f-c734126094ff.png)

**Comment by cycomachead** [comment]
This can be closed now?

Seems like contains is working correctly.
