### ISSUE TITLE
Forever block appears to interfere with blocks nested within it.

### ISSUE THREAD

**Issue by Aetalas** [jmoenig/Snap--Build-Your-Own-Blocks#269]
Without "forever" block:
![screen shot 2013-12-08 at 3 29 11 am](https://f.cloud.github.com/assets/5885080/1700213/8dc67202-5ffc-11e3-82f1-5a218a47fe11.png)
![screen shot 2013-12-08 at 3 30 48 am](https://f.cloud.github.com/assets/5885080/1700214/9747f7f6-5ffc-11e3-8c85-e036054b9589.png)
![screen shot 2013-12-08 at 3 31 04 am](https://f.cloud.github.com/assets/5885080/1700215/9bd736ce-5ffc-11e3-81cc-c0cc8d0130c4.png)
Internal loop works correctly.

With "forever" block:
![screen shot 2013-12-08 at 3 28 58 am](https://f.cloud.github.com/assets/5885080/1700216/b0cc7ea4-5ffc-11e3-9841-dc4f57ffd990.png)
![screen shot 2013-12-08 at 3 30 48 am](https://f.cloud.github.com/assets/5885080/1700217/b9992bf4-5ffc-11e3-93f4-91c7ec6a87f4.png)
![screen shot 2013-12-08 at 3 31 46 am](https://f.cloud.github.com/assets/5885080/1700218/bc61ae7e-5ffc-11e3-877d-dd64645fc774.png)
The internal invalid move script fails to occur. Instead, the blocks show an error. 

How can the "forever" block have such an effect upon a nested block that is in a loop?

**Comment by cycomachead** [comment]
Closing this because there's nothing we can do for now, but we can reopen if neceesary.
