### ISSUE TITLE
Entering text in an input slot does not update the scrollbar

### ISSUE THREAD

**Issue by nathan** [jmoenig/Snap--Build-Your-Own-Blocks#31]
When more text than fits onscreen is entered into an input slot, the text continues offscreen but a scrollbar does not appear to indicate that there is more content.

![Screen Shot 2013-04-12 at 19 03 06](https://f.cloud.github.com/assets/1578238/375589/61d1c87a-a3c5-11e2-8d9c-5dda6be0f90b.png)

**Comment by cycomachead** [comment]
Closing because #1576 is more recent.

**Comment by liam4** [comment]
@cycomachead this issue wasn't actually closed :)

**Comment by cycomachead** [comment]
Whoops. Thanks.
