### ISSUE TITLE
Block Editor does not rename parameter references

### ISSUE THREAD

**Issue by fturbak** [jmoenig/Snap--Build-Your-Own-Blocks#337]
The block editor does not rename references to a block parameter when the name of that parameter is changed. For example, suppose I first define the following block

![screen shot 2014-02-23 at 3 32 18 pm](https://f.cloud.github.com/assets/831842/2241299/0e21fffc-9cca-11e3-9cfc-ca30008c757f.png)

and then I rename the numeric parameter from "dist" to "len"

![screen shot 2014-02-23 at 3 32 40 pm](https://f.cloud.github.com/assets/831842/2241304/4be1eff0-9cca-11e3-9a98-b07b6923f064.png)

The previous variable references dragged from "dist" remain named "dist", but I expect them to change to have the name "len".  The Scratch 2.0 "make a block" editor and Blockly blocks editor have the same bug. But the App Inventor blocks editor (both Classic version and new version 2) correctly rename all references when the declaration is edited.

**Comment by cycomachead** [comment]
Tag #46 #1049 

Closing this because the more recent discussion is there.
