### ISSUE TITLE
Savings takes ages and then doesn't save!

### ISSUE THREAD

**Issue by lordtopcat** [jmoenig/Snap--Build-Your-Own-Blocks#341]
Hi there,

I'm trying to save my project and it takes about 5 minutes and then doesn't even save. When I try exporting the project Chrome comes up with the "AW SNAP" page and when I try to save it to disk it comes up with the "AW SNAP" page as well.

I thought it was because my sprite file sizes were quite high, but I've considerably reduced these and the problems still persist.

Any help please? It's getting really frustrating having to redo all my work because of this.

Cheers.

**Comment by cycomachead** [comment]
Should be fixed with 4.0.4
