### ISSUE TITLE
Snap doesn't account for Menus longer than the window height

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#349]
This makes it really hard to use long lists. One common-ish example, is the letters drop down menu one small screens or with zoom blocks of 1.5x+ (Common for presentations).
The other is with absurdly long lists. :)

See two screen shots.
![screen shot 2013-12-18 at 2 57 09 pm](https://f.cloud.github.com/assets/1505907/2393905/cfb68d5c-a9a1-11e3-8c7a-b1d5598e9a90.png)
![snap menu bugs 2](https://f.cloud.github.com/assets/1505907/2393906/cfb8083a-a9a1-11e3-9a98-22f58b5ee850.png)

There are two things we could do:
1. First detect usable window height...
2. We could either have options that say: "[Next Items]" and "[Previous Items]" 
 Or we could have scrollable menus. 

Personally, I like the second option better, but I don't know what's easier to implement.

**Comment by jmoenig** [comment]
fixed with 922dcc279eb7a27f67767f1fabff573007b99f26
