### ISSUE TITLE
Copy and Paste on TextMorph and StringMorph (for variable)

### ISSUE THREAD

**Issue by tomoki** [jmoenig/Snap--Build-Your-Own-Blocks#353]
Sometime,I want to copy variable value to textmorph.

Snap! has paste function already (Control V).
But there is no copy. I think,it is because there is no way to support it in cross-browser.

So,how about make clipboard variable in WorldMorph?
I mean,

```js
WorldMorph.prototype.init = function() {
    ...
    this.clipboard = "";
    ...
};
WorldMorph.prototype.initEventListeners = function () {
...
    document.body.addEventListener(
        "paste",
        function (event) {
            if (myself.cursor) {
                myself.cursor.insert(this.clipboard);
            }
        },
        false
    );
    document.body.addEventListener(
        "copy",
        function (event) {
            console.log(myself.cursor.target);
            if (myself.cursor && myself.cursor.target) {
                this.clipboard = myself.cursor.target.selection();
            }
        },
        false
    );
...
};
```

And, I also implemented copy and paste menu on textmorph and stringmorph for test.
But, there are following issues.
- TextMorph for variable is not editable.(Why not editable?)
- When I want to use system clipboard paste,how can I do that?(Add menu?)

**Comment by cycomachead** [comment]
Ok, so @StevenBird is currently demoing edge and they have working C&P, in Chrome and Safari and FF. It's simple and amazing and uses a hidden text box. 

Would everyone be OK if we ported this to main Snap<em>!</em>? It should be fairly straightforward! :grinning: 

@brianharvey @jmoenig

**Comment by cycomachead** [comment]
JS link for simplicity: https://github.com/snapapps/edgy/blob/master/edgy/clipboard.js

**Comment by jmoenig** [comment]
Oh, lovely! Can we perhaps just tweak the already existing "virtual keyboard" for this? https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/master/morphic.js#L10173

**Comment by cycomachead** [comment]
I will look, but a cursory glance seems like it might be more complex that way.
