### ISSUE TITLE
Browser Usage Stats?

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#359]
Would it be possible to add google analytics to snap.html so we could track what browsers students are using?

**Comment by cycomachead** [comment]
Closing because this isn't really a Snap! thing. :)

**Comment by bromagosa** [comment]
@brianharvey , there are free alternatives to EvilCorp's surveillance analytics, if that's what you're looking for. I know of http://www.openwebanalytics.com (GPLv2) and https://github.com/piwik/piwik (GPLv3).

If what worries you is collecting user data as a concept, even when not sending it to the NSA via a third party, then disregard my suggestion :)

**Comment by brianharvey** [comment]
Well since the person who opened it closed it, I'm happy.  :-)

**Comment by brianharvey** [comment]
Oops actually he only _said_ he was closing it.  So I'll do it for him.

**Comment by cycomachead** [comment]
lol oops. I think I just clicked the wrong button. :)
