### ISSUE TITLE
Bignum support in Snap!

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#390]
This used to be in BYIOB.

There's also this:
http://jsfromhell.com/classes/bignumber
Or this:
https://github.com/jtobey/javascript-bignum

**Comment by ToonTalk** [comment]
When I tried to use the bignum library I found that 1000! was infinity and 999! < 1000! was false.

![image](https://cloud.githubusercontent.com/assets/2138696/24389410/dec3844c-13b3-11e7-8e7f-095da64e9c18.png)

**Comment by ToonTalk** [comment]
My problem is that I run Snap with https (necessary to use the camera and microphone and web services). The console has this error

> Mixed Content: The page at 'https://snap.berkeley.edu/snapsource/snap.html#' was loaded over HTTPS, but requested an insecure script  'http://snap.berkeley.edu/snapsource/libraries/biginteger.js

Changing the URLs to look like this fixed the problem:

//snap.berkeley.edu/snapsource/libraries/biginteger.js
//snap.berkeley.edu/snapsource/libraries/schemeNumber.js

**Comment by ToonTalk** [comment]
This is a tricky case for error reporting since I don't think there is an exception to catch here. Note that it looked like USE BIGNUMS was running fine when only opening the console showed that there was a problem.

**Comment by brianharvey** [comment]
@jmoenig Fixed in PR 1797.
