### ISSUE TITLE
Indicate sprite with problem (was:"When I start as a clone" event ignores errors)

### ISSUE THREAD

**Issue by studej** [jmoenig/Snap--Build-Your-Own-Blocks#438]
If you run these hats blocks by mouse then error is shown. But no error is shown when clone is created. Project is<a href="http://snap.berkeley.edu/snapsource/snap.html#present:Username=bpitvpfjcu2014&ProjectName=clone_ignores_error"> here</a>
![clones_ignores_errors](https://cloud.githubusercontent.com/assets/7092949/2956435/5ddab4be-da8f-11e3-9b43-434534704886.png)

**Comment by cycomachead** [comment]
Somewhere along the line, this was fixed. An error will now show in the script for `when I start`
