### ISSUE TITLE
LOVE the find-blocks / open-project / save-project, we want people to find them though

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap--Build-Your-Own-Blocks#444]
Nobody will ever know about open/save project unless we change the menu for "Open..." to "Open... ^-O" and "Save" to "Save   ^-S", easy changes. (I would also propose a "Find Blocks...   ^-F" menu item, but there doesn't seem to be a menu that is appropriate for it. the first is for files, the second is for clouds, the third is for configs)

**Comment by cycomachead** [comment]
Aside from the edit menu, the original issue of displaying keyboard shortcuts has now been resolved. :)
