### ISSUE TITLE
Renaming variables should rename all occurrences within the scope of the variable

### ISSUE THREAD

**Issue by nathan** [jmoenig/Snap--Build-Your-Own-Blocks#46]
As it currently functions, choosing "rename…" from a variable reporter's context menu only changes the label of that variable reporter—it doesn't actually change the declaration of the variable or any of its other occurrences.

Before renaming:
![Screen Shot 2013-04-14 at 11 28 19](https://f.cloud.github.com/assets/1578238/378106/0cc9d706-a518-11e2-8128-8aaf62d70894.png)

After renaming:
![Screen Shot 2013-04-14 at 11 28 52](https://f.cloud.github.com/assets/1578238/378109/21cdfcf4-a518-11e2-8d7e-cbd3f307043d.png)

_Renaming_ a variable means changing its name, so when a user renames a variable its declaration (with `script variables …` or as a sprite or global variable) should also be changed to reflect the new name, as should all reporters within the variable's scope which refer to it.

Desired result:

![Screen Shot 2013-04-14 at 11 37 00](https://f.cloud.github.com/assets/1578238/378131/2fa4cec4-a519-11e2-9188-fe5f1f765b22.png)

In addition to being a much more intuitive result for the "rename" command, this process is also consistent with Scratch 2.0's variable renaming feature.

Users should still be able to change the variable to which the reporter points (i.e., change only its own label), but this feature should be available from the "relabel…" command rather than the "rename…" command.

**Comment by cycomachead** [comment]
Fixed with Bernat's refactoring tool.
