### ISSUE TITLE
Underscores not working in think or say blocks

### ISSUE THREAD

**Issue by Pvollucci** [jmoenig/Snap--Build-Your-Own-Blocks#503]
Using Snap in Chrome, Underscores are not appearing in the think or say blocks. (this includes in incognito mode)

![snap bug](https://cloud.githubusercontent.com/assets/5395638/3534918/fb17f21c-07f5-11e4-8753-336463ff88be.PNG)

**Comment by cycomachead** [comment]
Closing b/c #945 has more recent discussion.
