### ISSUE TITLE
bug using backspace in Internet Explorer

### ISSUE THREAD

**Issue by doffen** [jmoenig/Snap--Build-Your-Own-Blocks#569]
When using IE 11 on Windows 7, if you press backspace (such as when logging into and correcting your cloud account name or password), the program tries to exit by giving you the "leaving page" question.  For this reason, I cannot recommend using IE to my students.

**Comment by bl-nero** [comment]
I've conducted Snap workshops yesterday, where students needed to BTOH (Bring Their Own Hardware, pun intended). A lot of them had IE, and we were struck by this bug.

**Comment by jmoenig** [comment]
Ah. Fascinating that you led a Snap! workshop! I'm intrigued and would love to learn more about your experiences!

Yes, the backspace problem with IE really is a show-stopper issue, so I've heard from others, too. Such a bummer that I don't have a Windows computer anymore, I'm pretty sure it's not hard to fix this, can't be. Hey, if you have any spare time at your hands, I'd really, really appreciate any help I can get with this!

**Comment by bl-nero** [comment]
I actually have some spare time, probably next weekend, but I also don't have a Windows computer. However, I'm gonna take a look at that VM solution that @cycomachead mentioned (I just need to fire up some sort of torrent, because it weighs 5 GB).

**Comment by cycomachead** [comment]
I also found this today, which is probably less work than a VM
https://remote.modern.ie

But it looks like you've solved the issue already. :D
