### ISSUE TITLE
Missing text in Chrome

### ISSUE THREAD

**Issue by DevanWolf** [jmoenig/Snap--Build-Your-Own-Blocks#574]
When I usually use Snap! in Chrome, usually I don't see the text appear all around here. Usually I can't know what block I'm gonna take out, such as the words that say "move (10) steps" are missing. This is why I have to try a different browser, such as Firefox, and the other browsers rather than Chrome may appear fine.

UPDATE: THE TEXT BUG FIXED ITSELF! I don't know why.

**Comment by cycomachead** [comment]
@brianharvey @jmoenig This could be closed. :)
