### ISSUE TITLE
Maximum amount of costumes?

### ISSUE THREAD

**Issue by jimmy5517** [jmoenig/Snap--Build-Your-Own-Blocks#576]
Is there a limit for how many costumes I can import? I use chrome browser and it crashes when I try to save a project with a large number of costumes, sometimes crash at 900 images and sometimes at 500.
Also a suggestion, maybe add a scroll bar for the drop down menu, it only shows up to 99 in my browser, so often an operator block is needed to set the number.

**Comment by cycomachead** [comment]
Tag #804
