### ISSUE TITLE
Can't select from dropdowns on some computers

### ISSUE THREAD

**Issue by tylermenezes** [jmoenig/Snap--Build-Your-Own-Blocks#578]
Some of our students are having a problem where Snap interprets clicks on a dropdown as drag events. In the screenshot below, for example, I clicked in the red circled area (sorry -- can't install a third-party util which captures the mouse) and, rather than expand the menu, it's turned into the drag state.

![untitled](https://cloud.githubusercontent.com/assets/173390/4252525/adc801fe-3a96-11e4-9ec0-5e879c201c9e.png)

This happens intermittently on student computers and reliably on our projector computer. The only solution for the students is to log out and back in. There is no solution on the projector computer.

- Chrome 34.0.1847.116 m
- Windows 7
- Lenovo desktops, stock Lenovo mouse (no touch screen or anything fancy)
- Projector computer is dual screen, but happens on both screens
- Projector is running SMART Ink program, student computers are, to my knowledge, not
- Happens regardless of Chrome or in-SNAP block zoom

Please let me know what other information would be helpful. This has been costing our TEALS class significant time and frustration.

**Comment by SillyInventor** [comment]
The MouseMove event starts occurring before the MouseUp event even on very fast clicks. This is probably a chrome problem, but it's so hard to reproduce, I can't tell.

A simple solution is to check to see if the mouse has moved before pickup on grab events, though you could use a timer to accomplish the same thing.

    HandMorph.prototype.processMouseMove = function (event) {
    ......
    if ((this.children.length === 0) && (this.mouseButton === 'left') && (event.movementX != 0 || event.movementY != 0)) {

Hope this helps.

**Comment by wortzmanb** [comment]
Just as an FYI, this and #753 may be the same issue.  Of course I could be wrong, but wanted to call it out just in case.

**Comment by cycomachead** [comment]
Hopefully Fixed with 6061403a89bbbdd448a9086d3f443b5a5f88a330

@brianharvey @jmoenig This could be closed. :)

**Comment by jmoenig** [comment]
Yes, let's hope it's fixed now! When Brian first gave me that Windows stick I got this issue right away, and it kept coming up. After the fix it hasn't happened to me anymore.
