### ISSUE TITLE
Append does not really report a new list

### ISSUE THREAD

**Issue by tmwangi** [jmoenig/Snap--Build-Your-Own-Blocks#640]
I am using SNAP to teach Intro to CS to a high school for TEALS. So the description for append is that it returns a new list given lists as input. The problem is that if I do list3 = append(list1, list2) and then add something to list2, then it also shows up in list3. If something is added in list1 however, it does not show up. I would think that the intended behavior is that list3 should not share memory with list1 or 2 but it seems that append does not its own space for the last input list. I am not sure if this is the intended behavior.

Thanks.

**Comment by cycomachead** [comment]
@brianharvey 

This one came up again fairly recently... Shouldn't append create a new list?
I guess it's fine if it doesn't but it's worth clarifying / knowing either way.

**Comment by bb010g** [comment]
The issue can be traced through reportCONS to [`List.prototype.cons`](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/6061403a89bbbdd448a9086d3f443b5a5f88a330/lists.js#L126), which does just set the cdr to the cell. What would be *nice* would be a smarter clone that doesn't actually duplicate the list until forced (keep the tail the original as long as possible, but on write clone up to that point?), but a normal full list clone would work as well. (I think for that smarter clone you'd need to pass along purity metadata when you call to enable or disable the clone. You could probably do it with a special case (optional last param?) on a Clone list.)

**Comment by cycomachead** [comment]
I don't think we need to modify the list primitives for this case, at least not yet...Since append is a custom block, we should have it create and report a completely new list.

**Comment by bb010g** [comment]
I put some thought into it, and all you really need `(clone data)` to be is `(map ((id x) input names (x)) data)`. Bonus points if it's the dev `map`, because that preserves the original structure. (Side note: I can't figure out how to do `λx.x` in a ring; it just keeps unringifying.)

**Comment by cycomachead** [comment]
> (Side note: I can't figure out how to do λx.x in a ring; it just keeps unringifying.)

Yeah, that's a bug... Here's what I did...
* Create an input param
* Drag a #1 out
* Right click and ringify #1
* add input params

![map](https://cloud.githubusercontent.com/assets/1505907/11204229/905fe802-8cb1-11e5-8359-560dfa1c76b4.png)

**Comment by cycomachead** [comment]
Also, I realized you can drop a variable into a regular ring when it's not an input like in map, so if you drag a new ring to the script area, then you can drop the #1 in there just fine.

**Comment by jmoenig** [comment]
Oh yes, that's the idea :-)

**Comment by cycomachead** [comment]
To the original question, if we remove a small optimization from append, then we fix one case, where `append (l)` returns the same list, which is actually the case that came up with TAs. However, in recent testing the original problem of shared memory, over the 2nd list `append (l1, l2)`..I can't reproduce this.
http://snap.berkeley.edu/snapsource/snap.html#present:Username=cycomachead&ProjectName=append%20test

![append](https://cloud.githubusercontent.com/assets/1505907/11209787/4fc3055a-8cd8-11e5-8186-61b858e7f457.png)

**Comment by brianharvey** [comment]
The behavior of APPEND is just what it's supposed to be -- i.e., it does what APPEND does in Scheme.

The wording "a new list" in the documentation may be confusing.  What it is trying to say is that all of the input lists are unchanged; they are not chained together by mutation.  (Cf. APPEND!, which appends by mutation.)

Our general rule in Snap<i>!</i> is that you should manipulate a list either functionally or imperatively, but you shouldn't try to mix modes.  Even if we made the change you're suggesting, you could still get in trouble by mutating *elements* of one of the input lists.

We should provide a DEEP-COPY library block that copies recursively down to the atomic elements, for people who insist on mixed mode programming.

**Comment by cycomachead** [comment]
> The wording "a new list" in the documentation may be confusing.

Ah, that was part of my assumption about what "new" meant.
