### ISSUE TITLE
Clicking on temporary clone open and allow him to edit as normal sprite

### ISSUE THREAD

**Issue by studej** [jmoenig/Snap--Build-Your-Own-Blocks#648]
This should not happen. You can control your sprite like normal sprite -> add and execute blocks in script pane, create own blocks and variables, draw costume (EVEN import costume :)), but after you switch back to normal (parent) sprite then every change you have done are not included in him... only in temporary clone

**Comment by jmoenig** [comment]
I've fixed this today with https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/commit/a0b39a4dafd41214ebf52f2db149486a2bdf27b7

Thanks, @studej !
