### ISSUE TITLE
Support a "Disabled" state for buttons (Open Dialog, others?)

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#649]
I noticed this in the Open (and Save) Dialogs, but there might be other places.

If you don't have a project selected, you can still click the Share and Open and delete (cloud panel) buttons. Of course they don't do anything, but it would be nice if there was a "disabled" state for these buttons.

**Comment by bobbybee** [comment]
Currently working on this.

**Comment by cycomachead** [comment]
Yup! You’re totally right. :) 🎉
