### ISSUE TITLE
Text tool

### ISSUE THREAD

**Issue by geaplanet** [jmoenig/Snap--Build-Your-Own-Blocks#686]
There isn't any drawing text tool?

**Comment by cycomachead** [comment]
Not a full text too -- not yet.

The easiest option is "text stamping" which is currently an custom built function. You can import it from the "JS Functions" project under "Examples".

The XML file for that block is here: https://github.com/cycomachead/snap-tools/blob/master/text-stamping.xml and you can import that manually.

**Comment by cycomachead** [comment]
See also #122

**Comment by geaplanet** [comment]
Really useful, thanks.

**Comment by studej** [comment]
@geaplanet please, close your issue when it's ready to be closed :)

**Comment by geaplanet** [comment]
Sorry, I'm new using github and snap. Allow me one last offtopic:
Is this the only meeting place for Snap? Isn't there a forum or mailing list? Is this the correct site for help? Is there any repository for all resources that is not in the main branch?

**Comment by brianharvey** [comment]
We've been using the Scratch forum.  Developer discussion at
http://scratch.mit.edu/discuss/topic/4464
User discussion at
http://scratch.mit.edu/discuss/topic/4455

**Comment by studej** [comment]
Shouldn't we add these links into `README.md` on GitHub, @jmoenig & @brianharvey  ?

**Comment by cycomachead** [comment]
> Sorry, I'm new using github and snap.

No worries! It's easy to get lost in everything Github related.

So far the issues page and the two forum links are the best places. 

Everything in the repo is all you need for Snap! (The exception is the Examples directory which is here, http://snap.berkeley.edu/snapsource/Examples/ but I'll add that to the repo soon!).
