### ISSUE TITLE
JSFunction rendering bug

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#688]
Try importing the JSFunctions example project. Things look normal. Then zoom blocks.
The window them looks like this:

![screen shot 2015-01-02 at 5 23 02 pm](https://cloud.githubusercontent.com/assets/1505907/5601157/d4f80e02-92a4-11e4-9730-a4589aa4a3a2.png)
(Notice: The input code to all JSFunction blocks is black and they aren't rendered as inputs).

After trying to click on the input code, the text moves around:
![screen shot 2015-01-02 at 5 26 21 pm](https://cloud.githubusercontent.com/assets/1505907/5601160/e64f38e2-92a4-11e4-8458-1ce77131cd89.png)
In the middle block, the "code" move over to the left when you click on it. After trying to type, that block returns to the way it normally looks. Editing other blocks has the same effects.

**Comment by jmoenig** [comment]
these rendering artefacts sometimes happen in low-memory situations. Try quitting / restarting Chrome!

**Comment by brianharvey** [comment]
Hmm, does that point to the possibility of a Snap! memory leak within our control?

**Comment by jmoenig** [comment]
I don't think so. Browsers are memory hogs, there are lots of blog posts about this phenomenon. Of course, you people (not you, Brian, but those high-res artists over at Berkeley ;-)) need to be aware of is that constantly using "zoom blocks" creates dramatically bigger bitmaps for many elements, and thus is dramatically tougher on system resources...

**Comment by cycomachead** [comment]
I don't think this is a memory issue.

Try this in the latest Safari. So far it has persisted across restarts and I'm not using a high zoom level..this occurred going from 1.4x → 1x. 

I realize zoom blocks uses some more resources, but these are bugs which cause students problems. The main reason I know that I and students use zoom blocks is for accessibility reasons, and often times it's within a factor of 2.

**Comment by jmoenig** [comment]
I'm sorry but it cannot be an accessibility factor, unless you scale up your screen resolution *above* what's reasonable anyway. If you have problems reading small print, just change your screen resolution (up to native, but not beyond and many - including myself - like to do), don't make the fonts bigger!

Chrome and Firefox have these memory issues all the time, this has been discussed all over. It's really sad, because it should give a warning instead of just omitting ops. But, bottom line, I think this is beyond or influence

**Comment by cycomachead** [comment]
> If you have problems reading small print, just change your screen resolution (up to native, but not beyond and many - including myself - like to do), don't make the fonts bigger!

I use my screen at native resolution, I always have and I almost always will. Making the fonts bigger is always an option, in addition to generally zooming the screen.

I have worked with a couple students who would have dropped CS10 if not for zoom blocks. 

(And yes, the font size was an issue with BYOB, though BYOB's block font is more contrasty than Snap<i>!</i> and the input text is quite a bit bigger.)

**Comment by cycomachead** [comment]
Haven't seen this since, so closing!
