### ISSUE TITLE
Edit image from stage

### ISSUE THREAD

**Issue by geaplanet** [jmoenig/Snap--Build-Your-Own-Blocks#693]
If you click an image in the stage, appears a menu (duplicate, delete, move, edit...). "Edit" option doesn't work.
In the tab costumes edit option works right.

**Comment by studej** [comment]
i think that it means "edit sprite scripts", not costume

**Comment by geaplanet** [comment]
@studej, anyway, it doesn't do anything. I think it would be better if on stage and in the corral sprites menu were equal. Suggestion: duplicate, delete, move, edit, encode, raise and export.

**Comment by studej** [comment]
I don't understand you. Edit works everywhere for me. Can you provide screenshot or GIF?

**Comment by cycomachead** [comment]
> @studej, anyway, it doesn't do anything. I think it would be better if on stage and in the corral sprites menu were equal. Suggestion: duplicate, delete, move, edit, encode, raise and export.


If you edit the currently selected sprite, it doesn't appear do anything because the code is already being shown. However, if you edit a different sprite the scripting area should change. Does it not do that even with multiple sprites?

**Comment by geaplanet** [comment]
Ok, ok, I was in costumes tab and sound tab and I expected it automatically switch to scripts tab. Sorry, it works right.

**Comment by studej** [comment]
- that's ok, @geaplanet 
- thanks, @cycomachead

**Comment by cycomachead** [comment]
> I expected it automatically switch to scripts tab. Sorry, it works right.

Ah, no worries! What edit really does, is switch to the currently selected tab of the new sprite. (So, if you're editing costumes, it will now reveal the new sprite's costumes. My reference to code was only correct if you're viewing the Scripts tab.)
