### ISSUE TITLE
Failing to log in 

### ISSUE THREAD

**Issue by alexayala** [jmoenig/Snap--Build-Your-Own-Blocks#701]
It says that I cannot connect to the cloud.

**Comment by jmoenig** [comment]
Yep, we had it down for maintenance, but it's now up again. Make sure to flush your browser's cache (or reload Snap until the version for cloud.js shows today's date - in the "about" dialog)

**Comment by tylermenezes** [comment]
Permissions on school computers don't let students fully purge the cache, any workaround? Ctrl+Shift+R doesn't seem to work. Can you version the URLs in the future?

Please don't do maintenance at this time of year, by the way. This is right before the end of the semester for most high schools; this has completely shot shot schedule for the end of the year.

SNAP is being used in a lot of TEALS classes so it would be great if you could take requirements of high schools into consideration.

**Comment by jmoenig** [comment]
Sorry, guys, we had to put more resources into the backend. Okay, here's what you should do if your browsers hang on to cached versions of outdated scripts:

1) press and hold the "shift" key while you reload Snap!
2) check Snap's "about dialog" (click on the Snap logo), and switch to "modules":

![aboutsnap](https://cloud.githubusercontent.com/assets/2596285/5706958/36161a20-9a85-11e4-9b75-deeed92d8f3d.png)

if the module named "cloud.js" doesn't show today's data:

![modules](https://cloud.githubusercontent.com/assets/2596285/5706978/4f7a6746-9a85-11e4-9d4a-c099603b56be.png)

repeat reloading the page until it does. Usually it'll be alright after 1 - 2 reloads.

**Comment by brianharvey** [comment]
We did post on the BJC-Teachers Piazza group asking if this weekend would be okay for downtime.  I guess we need to arrange for the TEALS teachers to be in that group.
