### ISSUE TITLE
sprites with empty local custom blocks can not duplicate

### ISSUE THREAD

**Issue by haritop** [jmoenig/Snap--Build-Your-Own-Blocks#702]
The debugger shows
TypeError: this.body is null  byob.js:214

**Comment by jmoenig** [comment]
Good catch, thanks for the report!

**Comment by jmoenig** [comment]
I fixed it in my dev version. I'm going to push it tomorrow, right now I'm busy testing the new stuff and replying to panic emails :-) Thanks!
