### ISSUE TITLE
Adding a carriage return?

### ISSUE THREAD

**Issue by hansellynn** [jmoenig/Snap--Build-Your-Own-Blocks#704]
Hey folks, anyone know how to add a carriage return to a string?  And/or a tab? Trying to do it via join to get a little bit of better formatting in the text.  Not sure how to escape characters?  Tried \n and \t but they seem to come out literal.  Thanks!

**Comment by brianharvey** [comment]
Use UNICODE (12) AS TEXT for newline, or 8 instead of 12 for tab.

**Comment by hansellynn** [comment]
Thanks Brian, do you mean as in attached?  Unfortunately it still doesn't seem to put a carriage return in the output, also attached.  Tried 8 for tab as well.  Did I do this correctly?  Is there another way to format text?

---- On Fri, 23 Jan 2015 11:48:31 -0800 Brian Harvey&lt;notifications@github.com&gt; wrote ---- 

Use UNICODE (12) AS TEXT for newline, or 8 instead of 12 for tab.
 —
Reply to this email directly or view it on GitHub.
    
 
 




_________________________________________________________________________________
Summer Coder Camps are ready to roll!  Check em out at www.thecoderschool.com/camps!

Hansel Lynn, Founder3441 Alma St, #150, Palo Alto
www.thecoderschool.com

**Comment by brianharvey** [comment]
Sorry, I'm not seeing an attachment.  Here's what I mean:
![newline](https://cloud.githubusercontent.com/assets/3885074/5881955/2a061eb0-a2fa-11e4-9ddb-b41fe76bd3bb.png)

**Comment by hansellynn** [comment]
Oops, thanks I used 12 instead of 10.  Thanks Brian!!  Got a cool little chatroom app almost running here... (using a simple php server to hold messages).  Kids will love the pseudo-network function!

---- On Fri, 23 Jan 2015 12:20:31 -0800 Brian Harvey&lt;notifications@github.com&gt; wrote ---- 

Sorry, I'm not seeing an attachment. Here's what I mean:
 
 —
Reply to this email directly or view it on GitHub.
    
 
 




_________________________________________________________________________________
Summer Coder Camps are ready to roll!  Check em out at www.thecoderschool.com/camps!

Hansel Lynn, Founder3441 Alma St, #150, Palo Alto
www.thecoderschool.com
