### ISSUE TITLE
Bug when executing my own blocks

### ISSUE THREAD

**Issue by luis140219** [jmoenig/Snap--Build-Your-Own-Blocks#705]
In Snap!, in the 23rd of November of 2014, I've experienced an error on the console:
The object does not support the method "allReportBlocks"
The object was a instance of the CommandBlockMorph class.
Please add a allReportBlocks as follows:

``` javascript
  // allReportBlocks
  CommandBlockMorph.prototype.allReportBlocks = function() {
    return this.children.filter(function(child) {
      return child instanceof BlockMorph && child.blockSpec === "report %s";
    });
  }
```

**Comment by jmoenig** [comment]
does this happen in the current version, too? Is there a project that could help me reproduce this issue? Tnx!

**Comment by luis140219** [comment]
Let's try. Make your own custom command block.

**Comment by luis140219** [comment]
I've opened a pull request with the fix, #706.

**Comment by jmoenig** [comment]
Yeah, I've seen that. I'm just trying to understand the issue here. Why do we need to add that method? Didn't I make that one obsolete some time ago?

**Comment by luis140219** [comment]
Hey, Jens, can you help me out with a bug in [my Starlings game](https://github.com/luismark/luismark.github.io/blob/master/starlings/starlings.html)?
Go to StarlingsManagerMorph.prototype.step --> this.drawOn.
Can you put the background black? Please accept my invitation to Luismark and commit.
I will pull to my local Git. Comment here your full 40-character commit SHA1 hash with the solution.

**Comment by luis140219** [comment]
My last commit on my game was 7ed16017715455388e2cdfa5b7d7a2f80d2ac33f.

**Comment by luis140219** [comment]
Now it is [de5d10f](https://github.com/luismark/luismark.github.io/commit/de5d10f).
