### ISSUE TITLE
IS __ A NUMBER block reports true for some non-numbers

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#715]
A text string that starts with a digit but isn't a number, e.g. "5k", is considered a number (and not a text) by the IS __ A __ block.
(from BJCTeachers@piazza)

**Comment by jmoenig** [comment]
yep, it'a bug - will fix. Thanks!

**Comment by luis140219** [comment]
You can do `!(/^[0-9]+/.test(`*text*`))`, where *text* is the text to test for being a number or not.

**Comment by Gubolin** [comment]
This was the same as #458, which was followed by my pull request #603 4 months ago.
@jmoenig, you said you would have a look at the pull requests;
#542, #551, #606 are rather easy fixes.
(Maybe also #558, #605.)

I understand if you need some time to review #544 and #631.
Just poking a bit :-)
