### ISSUE TITLE
Custom pulldown ends with "close" if last option ends with newline

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#716]
Make a custom block, make an input with a pulldown menu, and in the text box for options put a newline after the final option.  The result is an extra "close" option.  Empty lines should just be ignored, I think, but if not, an empty line at the end should be treated specially.

**Comment by jessej-luo** [comment]
How do we make a block with a pulldown menu as input?

**Comment by cycomachead** [comment]
> How do we make a block with a pulldown menu as input?

When you go to edit the inputs for a block, and you see the big window with all the input type options, right click in the spot where you can see a default value for an input.
