### ISSUE TITLE
"Piano Keyboard" menu morph

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#720]
I just realized that this is missing from Snap<i>!</i> but was in BYOB. It'd be nice to have as it gives clear (musical) key values to Scratch's notes.

**Comment by jeeves833** [comment]
I'd be interested in tackling this

**Comment by jeeves833** [comment]
I'm interested in working on this

**Comment by jmoenig** [comment]
great!

**Comment by cycomachead** [comment]
#1007 #852
