### ISSUE TITLE
Export Woes Continue... :(

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#726]
I definitely think the URL issue will solve most of the problems I've seen, but this project was shared in the BJC teachers Piazza and I can produce the Aw, Snap screen in the most recent releases. 

(I re-saved to my account.)
http://snap.berkeley.edu/snapsource/snap.html#present:Username=cycomachead&ProjectName=mario%20party

**Comment by jmoenig** [comment]
sure, that's why I added "Save to disk"

**Comment by cycomachead** [comment]
> sure, that's why I added "Save to disk"

Save to Disk still crashes....

**Comment by jmoenig** [comment]
Browsers suck

**Comment by cycomachead** [comment]
Yeah, I'm curious to see where the problem is occurring. This is a weird case becase the exported XML file isn't even thaaat big. So I'm not sure where the error is occuring, but I'll play around after I get some other work done.

**Comment by jmoenig** [comment]
Bummer. I don't encounter any problems in Firefox...

**Comment by cycomachead** [comment]
> Bummer. I don't encounter any problems in Firefox...

Apparently, it's still a weird edge case of the URL thing in Chrome, because the encoded version is longer than Chrome's limit....(Which is an open bug that they aren't willing to fix. :( ) And apparently, the reason for the page still crashing is because the context of clicking the URL is in the current page?? I don't get why exactly that matters, for Chrome... Calling `window.open` also has some issues in Chrome, but it doesn't always crash the _current_ tab, sometimes it crashes the tab of the new window, which is OK (In a way), since that doesn't lose any work in progress.

I've been looking into other solutions and using the `Blob` API apparently doesn't have such restrictions in Chrome, though I haven't tested...

(I'm also hopefully going to build a download project as zip page that would work for public cloud projects.)

**Comment by jmoenig** [comment]
No, but this doesn't make any sense, because if you save the project directly to your disk Chrome shouldn't be doing any of this, it doesn't even open another tab or window!

**Comment by cycomachead** [comment]
> if you save the project directly to your disk Chrome shouldn't be doing any of this, it doesn't even open another tab or window!

There's still a really long data URI in `a[href]` that's causing issues.

**Comment by cycomachead** [comment]
Closing because the newer stuff will fix this.

**Comment by cycomachead** [comment]
Closing because #966 has all the fixes / details.
