### ISSUE TITLE
Weird! Bug with Block Not being "saved" when Apply is clicked.

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#730]
Ok, so I don't know what exactly is going on here, and I suspect this will be tricky to reproduce, but on my machine, it so far has persisted across refreshes. 

Browser: Safari 8, OS X 10.10

Project: http://snap.berkeley.edu/snapsource/snap.html#present:Username=cycomachead&ProjectName=michael%20hw3

Try editing the "simple map" block so that it works correctly. That would be adding the recursive call of:
`simple map (fn) over (all but first of (list))` to 

The thing is  -- when I click apply after fixing the block, it still doesn't work correctly! But when I go to edit the block again, the changes appear to be saved. If I then save my project (to the cloud) and refresh the block goes back to its previous state...

**Comment by jmoenig** [comment]
Yep, I can reproduce it, it's clearly a bug. I think I know what's causing this, let me investigate...

**Comment by cycomachead** [comment]
Cool, thanks! I just tested in Chrome as well.

At least it's reproducible! :)
