### ISSUE TITLE
Not Refreshing custom oop blocks after editing

### ISSUE THREAD

**Issue by SnapSitin** [jmoenig/Snap--Build-Your-Own-Blocks#731]
While running Snap! in chrome, while defining my own custom blocks to implement object oriented message passing (I created a "class" for complex numbers and another class for 3d points with a method showme reported after receiving a showyou message) Everything goes ok... but sometimes, when I edit my classes, and re run my project the version actually executed is the previous one. I have applied and clicked ok to include the changes on my classes.

It seems to go ok again if I re-open my project from a new fresh web-brower session (it seems to go better when I browse Snap! on firefox)

**Comment by jmoenig** [comment]
I'm pretty sure this bug is related to #730 which I've only just fixed last night. It's already installed an online, so please make sure you are loading the current version of byob.js with today's date (either clear your browser's cache or just keep re-loading Snap a few time while keeping the shift-key pressed). This should take care of the bug.

Also, please let me know if it doesn't.
Thanks!

**Comment by SnapSitin** [comment]
Thanks so much for your almost instantaneous answer (I am really
impressed) I will try asap.

I lead a research group of an Spanish University that is using Snap!
to introduce people (of any age) to programming. Snap! is a fantastic
platform...
I lead a research that includes the implementation of programming into
Schools for childer.

Would you like the collaboration with a group like us?? (I'm serious)
You seem to be a fantastic team!!!

Congratulations from Spain.

**Comment by brianharvey** [comment]
Oh, yes!  I'd love to know more about your work.  Right now especially at the high school level, since we are working on a more high-school-friendly revision of the BJC curriculum (http://bjc.berkeley.edu).  But I'm interested in all ages.

**Comment by SnapSitin** [comment]
Great!

Summary:
- I am an Associate Professor (what in Spain we call Profesor Titular
de Universidad) I have my "own" place in Universidad Autónoma de Madrid
Computer Science Faculty, Higher Polytechnical School, Languages and Systems
Area.
- I have, hence, already my PhD in Computer Science.
- I have started last year my PhD in Education (teaching programming  
in any School) We have started using Snap! in High School
(for 12-16 years old students) (we are actually using it in the
classrooms)
(to introduce programming, robotics - arduino-, etc...)
and we plan to try it also for younger people.
But, I have also possibility to explore Snap! to introduce programming
(specially higher topics - functional and object oriented paradigms )
in the University. But I like too much Snap and we could try to incorporate
other topics (my research group is also interested in new programming
paradigms and how to make them accesible to non computer scientist, why
not to extend Snap! for this?)

Could it be possible to use a (rather) private email to discuss that?

Thanks in advance.

Greetings!

**Comment by brianharvey** [comment]
Sure.  bh@cs.berkeley.edu

**Comment by SnapSitin** [comment]
Hi !!!!

Thanks a lot... I have checked that, at least for the problematic case, it seems to work fine!!!!

Greetings!

**Comment by jmoenig** [comment]
Thanks for confirming that this bug seems to be solved! Let's get in touch about everything else...
