### ISSUE TITLE
Space bar won't work when up and left arrows are pressed

### ISSUE THREAD

**Issue by nametabrelyt** [jmoenig/Snap--Build-Your-Own-Blocks#733]
Specifically this block, only when up and left keys are pressed and I try to press space bar.
![image](https://cloud.githubusercontent.com/assets/11308402/6479169/ca52c2d2-c1f5-11e4-8bdc-030a6649b7ed.png)

**Comment by jmoenig** [comment]
I *believe* this isn't a Snap! issue (please correct me if I'm wrong, though), but a choice of the underlying OS/platform, as I'm not getting the space event either when pressing several arrow keys in other applications (e.g. text editors).
