### ISSUE TITLE
save/open problem

### ISSUE THREAD

**Issue by jowede** [jmoenig/Snap--Build-Your-Own-Blocks#734]
I made a little project yesterday. After saving it (in the cloud) and reloading it, several definitions of operators are missing (my older projects are ok, fortunately). First I thought, changing the language caused it, but it happens in both languages.
Exporting and then importing the XML-file works correct.
I am confused ...

**Comment by brianharvey** [comment]
There was a bug about this briefly, but it's been fixed.  Please make sure to clear your browser cache and try again.

**Comment by Thedv8ed1** [comment]
I'm having the same issue, clearing the cache didn't fix the issue.

**Comment by jmoenig** [comment]
Can you reproduce the issue and post a screenshot of the where it's appearing / a link to a shared project? This would help me track it down. Thanks!

**Comment by jowede** [comment]
Clearing the cache seem to be the solution. My save/reload Problems are patched.

**Comment by jmoenig** [comment]
Thanks, @jowede . Incidentally, there's another bug report over on the Piazza site that points towards another bug concerning my recently introduced inputs caching optimization. So I'll probably push another patch within the next days.
