### ISSUE TITLE
Duplicate Bug

### ISSUE THREAD

**Issue by fchinn** [jmoenig/Snap--Build-Your-Own-Blocks#736]
When I attempt to duplicate the "tank maneuver" custom block from the 2nd if statement over to the third if statement, and then replace the "move steps" with a "turn block", it acts as if it was still a "move steps".
However, if I were to pull the "tank maneuver" custom block from the palette and change out the "move steps" with a "turn block", it then works.

![image](https://cloud.githubusercontent.com/assets/11339298/6515351/13c7b3de-c33e-11e4-90e0-717b0aed61c5.png)

This is the code for the "tank maneuver" custom block:

![image](https://cloud.githubusercontent.com/assets/11339298/6515443/b9bdfbea-c33e-11e4-9eea-028e8e83ec4a.png)

I hope the images uploaded. Never used GitHub before.

**Comment by jmoenig** [comment]
Got it, thanks for the report! I'm fixing this right now...

**Comment by jmoenig** [comment]
@fchinn can you please make sure that you have the latest version (flush your browser cache until the version of blocks.js has today's date), and try again? Thanks!
