### ISSUE TITLE
Duplicate Bug with variables

### ISSUE THREAD

**Issue by fchinn** [jmoenig/Snap--Build-Your-Own-Blocks#738]
Although the previous bug #736 was resolved, here is another problem involving the duplicate function if you right click a block.

This one involves variables. If you made two local variables, random and value. Then make the following:
![image](https://cloud.githubusercontent.com/assets/11339298/6544481/cf86e6a2-c506-11e4-9bb6-498aa435f1a5.png)

If you right click on the "if" statement to duplicate it. Then select the 2 if and duplicate it so that you now have 4 if statements. Then change the number of random and value as follows:
![image](https://cloud.githubusercontent.com/assets/11339298/6544484/0180e22a-c507-11e4-99e6-07fc28ac748f.png)

If you were to check the watch for random and value, as random changes from 0 to 3, value remains as 0 always. However, if you were to remove "set value to 100" and replace it by dragging over "set" and manually select value and 100 then you get 0 for everything and 100 for 1. (as if 1 now works)

Likewise, if you were to do that for all of the variables then it would work.

**Comment by jmoenig** [comment]
Thanks for this report, I'll investigate!

**Comment by jmoenig** [comment]
this one should be fixed now. Thanks!
