### ISSUE TITLE
long text input

### ISSUE THREAD

**Issue by jcaldw737** [jmoenig/Snap--Build-Your-Own-Blocks#740]
Is there a way to input long amounts of text? I know this question may sound out of place in such a visual world, but we used to do this in LOGO and some of my students really got into writing long adventure stories that presented their own readers the opportunity to make choices and get different results.  The only solution I have so far is to write the text in a text editor and paste it into a "say" block.

**Comment by jmoenig** [comment]
Good question! You've already found out about pasting (which currently works for Chrome). There are two other ways:

* make a variable, right click on the watcher and chose "import" to read a text file. Once you've got it you can parse it into a list or transform it so something else inside Snap.

* use the HTTP reporter block (in the sensing category) to dynamically query a web page or - better - data from a web service. The service/website you're querying the data from must have their cross-origin-resource-sharing option enabled (CORS) - this isn't Snap specific, though. That way you can interact with databases etc.

Do you have any other suggestion? Which would be a good way to input data for the kind of projects you're having in mind?

**Comment by jcaldw737** [comment]
Thank you so much for the rapid response!  I know what you said will be useful in many situations, but here is my problem.  There are students, many not tech savvy, who are going to write,and no doubt edit as they go along, an interactive story. It seems to me that two things would really help, 
1.  be able to put a carriage return in their input
2.  for the input box to allow them to a few lines of their input and scroll to see the rest

**Comment by jcaldw737** [comment]
FYI, I know there's work to be done in presenting the long text, but I can handle that through blocks that break up the text and spoon feed it to a "say" block.

I just need a way to get the long input input into a block.

**Comment by cycomachead** [comment]
> 1. be able to put a carriage return in their input

I think this would be nice as well, w/o having to work around it. AFAIK, the input type is supported for built in blocks, right? (Code mapping and JSFunction use it, I think.)

**Comment by jcaldw737** [comment]
for a "say" block, if I enter its input box and hit these keys

a [enter key] b

only the "a" shows up in the input box and when I click that "say" block only the "a" shows up in the resulting output on the stage  ???

**Comment by jmoenig** [comment]
Snap (as well as Scratch, too) currently only supports single-line user input in the stage prompter (ask-block). I'm pretty sure that this is in the best interest of beginners, and that mulit-line input would actually freak out a lot of students (and teachers). That said, we do want to improve working with text drastically in the future. For this we want some kind of first-class text boxes (similar to sprites) that support finegrained programmatic interaction and - of course - multi-line edits.

**Comment by brianharvey** [comment]
I'm not suggesting that this be high priority or anything, but we could echo <enter> as ↩ (LEFTWARDS ARROW WITH HOOK, Unicode: U+21A9, UTF-8: E2 86 A9) in the input box and then display it multiline on output.

**Comment by jmoenig** [comment]
Good idea!

**Comment by cycomachead** [comment]
> I'm not suggesting that this be high priority or anything, but we could echo as ↩ (LEFTWARDS ARROW WITH HOOK, Unicode: U+21A9, UTF-8: E2 86 A9) in the input box and then display it multiline on output.

How does a user enter this key or know it exists? I don't know why a simple `\n` won't work? They currently display fine in Snap<i>!</i> there's just so easy way to enter them... The say block doesn't have to by default support multiline text, but if we have an input option then people can use it for their own blocks when necessary.

**Comment by jmoenig** [comment]
well, we could just do what everybody else does and treat cmd-enter as special thing and make it produce that character. But anyway, this isn't anywhere close on my near-term agenda, because it could totally creep users out. Also, I'd start with only allowing it in the stage prompter. But, again, not in 4.0 anymore.

**Comment by cycomachead** [comment]
> well, we could just do what everybody else does and treat cmd-enter as special thing and make it produce that character.

Why not expose the multiline input morph for custom blocks? And, since so many apps (including Google, Facebook, and most twitter clients) use some form of the <key>+enter combo, I don't think it'd creep users out.

**Comment by jmoenig** [comment]
no power user features. Well, next to none, anyway. That's paramount for designing a friendly system. I'd much rather leave out many, many features, than overwhelm newbies. We're in the business of flirting with people who might never become power-users, ever :-)

**Comment by brianharvey** [comment]
@cycomachead: I think you missed the word "echo" in my comment.  My idea is that users type plain old enter, no bucky bits, and they *see* a visual representation of a newline, without any text disappearing.
@jmoenig: Since users type the plain old enter key, and since nothing disappears when they do so, there's nothing to freak them out.  And certainly multiline SAY won't bother anyone -- they already get that, in effect, for long text strings.

**Comment by jcaldw737** [comment]
As we all know there is an effort to reach groups of people who are underrepresented in the software world, and that one of those groups is the female population.  I can tell you from experience there are a number of them who really get into writing stories and having their users make choices.  This they could do easily in LOGO, but not yet in SNAP.  If you could give us some way to put in some new line character in the input box of SAY or "SAY LONG" OR "SAY A LOT", that would be wonderful.  BTW, I really appreciate the attention and thought that you have given this discussion.

**Comment by jcaldw737** [comment]
Jens -
Sorry to bother you but when I go to snap.berkeley.edu and click "Run SNAP now"
I get "This webpage is not available"  
BTW, the url at the top then is
 snap.berkeley.edu/run
I am making a presentation at 10:30 PT on using SNAP to help students learn math.
This is my own fault for not loading BYOB on my laptop, and I can get by with screen shots, but if the site could work, that would be great.
thanks for whatever you can do,Jerome Caldwell

**Comment by jmoenig** [comment]
there is a problem at the Berkeley system today. apparently @brianharvey is working on it. Hang on!

**Comment by jcaldw737** [comment]
Thanks so much for getting back to me.
SNAP site came up and I installed BYOB, so I am ok.
Thanks so much,Jerome Caldwell

**Comment by brianharvey** [comment]
It seems to be working again -- fingers crossed.

**Comment by jcaldw737** [comment]
Thanks so very much - things went very well!

**Comment by deader69** [comment]
I sort of wish the (http:// [ ]) reporter block allowed the 'file://' specifier... and why not other specifiers to?

Equivalently, you could add a separate (file:// []) reporter block, but that'd add more blocks, and be inextensible.

So what if (http://) could just secretly recognize any ':' prefix, maybe even support the 'javascript:' prefix, etc?

Are there technical or security reasons that would make this a bad idea?

I would LOVE to be able to slurp in data from a 'file://' URI, and be editing that local text file with my favorite text editor.

**Comment by cycomachead** [comment]
File:// URL's wouldn't work when Snap! Is accessed from a web server, which is really how most people access Snap<i>!</i>. Plus, this would render projects to be dependent on user's personal OS / file systems which makes it hard to share projects.

You could do this with the current JS Function block and make your own most extensible request methods. 

I do think some way to have file system access would be nice, but to do it right, someone would need to build a small desktop companion app that exposes certain methods to access the file system.

**Comment by jmoenig** [comment]
Last time I checked XHR2 (XMLHttpRequest) did not work with "file:" addresses.

**Comment by RedMikePumpkin** [comment]
Multiple line text **would** be epic, for now you can use the "multiline" block in the "allow multiline text input" library

**Comment by jcaldw737** [comment]
This is just what I needed.  Thank you so much.  There is a subset of my students who really get into writing adventures.  That task was easy in Logo, but has been difficult in SNAP - until now that it!

**THANK YOU AGAIN VERY MUCH,.**

**Comment by Jonathan50** [comment]
You could edit the MULTILINE block and change it to something different (like SAY A LOT) but without changing the type of the TEXT input.
