### ISSUE TITLE
I cannot access Snap!

### ISSUE THREAD

**Issue by luis140219** [jmoenig/Snap--Build-Your-Own-Blocks#742]
I cannot get access to Snap! because the URL is invalid.

**Comment by jmoenig** [comment]
yep, Snap seems to be down at the moment. @brianharvey to the rescue!

**Comment by brianharvey** [comment]
I don't know what's wrong, but this works:
http://eecs.berkeley.edu/~bh/byob/run

**Comment by jmoenig** [comment]
works again, closing
