### ISSUE TITLE
check for correct index types in list accessors

### ISSUE THREAD

**Issue by jmoenig** [jmoenig/Snap--Build-Your-Own-Blocks#745]
from Dan. Throw an error if the slot reference is an invalid type (not an integer and not one of the allowed special descriptors). The current misfeature is that Snap somehow converts an invalid string into the first index of the list and silently does the wrong thing.

Scratch 1.4 used to not do anything and flash a red border around the list watcher for a split second. Scratch 2.0 doesn't flash the red border anymore and just silently does nothing. We could  either also just do nothing (which I would prefer), or raise an error explaining that the block expects a number (an integer, even, or we could truncate/round whatever float is passed into it) or a special option.

**Comment by brianharvey** [comment]
"Do nothing" would work for the list command blocks, but it's not an option for the ITEM reporter.  And in any case, silently doing nothing makes it hard to debug.  I believe in flagging errors.
