### ISSUE TITLE
Write less, do more.

### ISSUE THREAD

**Issue by luis140219** [jmoenig/Snap--Build-Your-Own-Blocks#747]
Jens, did you know that 60% of all web sites use jQuery?
My GitHub Pages websites count in that number.
Using jQuery turns your code:
- cleaner
- simpler
- easier to understand
- and more!
I'm doing that in my fork and in my game.

**Comment by luis140219** [comment]
Why have you closed this issue, Jens?

**Comment by bb010g** [comment]
I think a good example would help with your argument, instead of just buzz (justified or not).

**Comment by carloslfu** [comment]
Snap is drawn over a [Canvas element][Canvas], therefore jQuery isn't useful.
[Canvas]:http://www.w3.org/TR/2dcontext/

**Comment by luis140219** [comment]
jQuery turns the code more understandable.
Example:
```javascript
  (function() {
    var world = new WorldMorph($("canvas")[0]);
    world.add(new StringMorph("Not clicking"));
    $(world.worldCanvas).mousedown(function(e) {
      if (world.children[0].containsPoint(new Point(e.clientX, e.clientY))) {
        world.children[0].text = "Clicking!";
      }
    }).mouseup(function() {
      world.children[0].text = "Not clicking";
    });
  })();
```

**Comment by jmoenig** [comment]
see:
https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/master/contributing%20to%20BYOB4.txt

Avoid
-----
	* accessing the DOM

	* frameworks (e.g. JQuery)

	* modules and namespaces (e.g. IIFE)

I'm not saying JQuery is bad, and it's great if you find it useful for your fork, but it has no place in the Morphic Snap! architecture. That's why I closed this issue.
