### ISSUE TITLE
Drop down list of variables for "set" block, etc.

### ISSUE THREAD

**Issue by minnesnowtan** [jmoenig/Snap--Build-Your-Own-Blocks#748]
If you have a large number of variables, the drop down list only shows as many as will fit vertically on your screen leaving off the earliest created variables.  There doesn't seem to be any way to select these variables at this point.
By setting the zoom on my browser to 75%, I could access my whole list of variables, but after a certain point, things get too small to read and/or work with.
Either a way to scroll through the drop down is needed or more than a single column of variables needs to be listed in the the drop down.

**Comment by cycomachead** [comment]
Duplicate #349
