### ISSUE TITLE
Cant type into boxes on the beta on website

### ISSUE THREAD

**Issue by JohnSmith-LT** [jmoenig/Snap--Build-Your-Own-Blocks#760]
Hi,

I've been playing with the beta on Chrome on a Galaxy Tab N8010 and for some bizarre reason I cannot type into any of the boxes. I get a cursor and the box clears but typing puts nothing into the box...

Anyone else see this or have any ideas?

**Comment by brianharvey** [comment]
Yeah, this is an Android bug that we've been struggling with since forever.  For now, get a Bluetooth keyboard, sorry.  :-(

**Comment by JohnSmith-LT** [comment]
Ah ok. Cheers, at least I know :-)

**Comment by Gubolin** [comment]
It's an issue with Webkit/Chromium. I built [an offline app](https://github.com/Gubolin/snap/releases) with crosswalk and the latest release, the keyboard works fine.
