### ISSUE TITLE
Set 'brightness' to (var) makes sprite white-ish, Set 'brightness' to (var + 0) works fine.

### ISSUE THREAD

**Issue by deader69** [jmoenig/Snap--Build-Your-Own-Blocks#770]
Setting the 'brightness' of a sprite via a global variable makes the sprite appear with strange white-ish discoloration.

Adding zero to the global var fixes it... I'm guessing it forces the expression to be a numeric type?

Here's a link to my 'Simon Says' app that contained the bug. It's inside the 'play (button)' custom block.

http://snap.berkeley.edu/snapsource/snap.html#present:Username=deader-tcssm&ProjectName=Simon%20Says

**Comment by jmoenig** [comment]
Yep, that's a bug. I'll push a fix for it within the next days. Good catch!
Thanks, for reporting it

**Comment by jmoenig** [comment]
I've just patched Snap with the fix to this issue. You can now remove the coercion. Thanks!
