### ISSUE TITLE
Feature request: Initialing script variables when they're declared?

### ISSUE THREAD

**Issue by deader69** [jmoenig/Snap--Build-Your-Own-Blocks#773]
Would love to be able to declare AND init local script variables in a single statement.

Currently, you have to use a 'script variables' block to declare them.
And then, one by one, use 'set' blocks to initialize them.

I wish I could just have an initialization expression a the point of declaration.
The equivalent of  int  square = x * x;

There's already a UI paradigm for this in Snap!
Custom block parameters have an optional 'default value' (though that only accepts constants).

I understand that his is may or may not be such an easy feature to implement.
Apologies if I'm posting too many feature requests... let me know!

**Comment by jmoenig** [comment]
Good idea, @deader69 , and actually very easy to implement in Snap! itself. See, Snap is fun because it lets you Build Your Own Blocks instead of having to request features :-)

![let](https://cloud.githubusercontent.com/assets/2596285/7122911/cbb96754-e21e-11e4-80e8-abc9fa6789a1.png)

**Comment by brianharvey** [comment]
Feature requests are great as long as you don't expect them instantly.  :-)

**Comment by deader69** [comment]
Understood! Believe me!! (said the former-software-engineer-now-educator)  :-)

I'll keep posting my observations, since the innocent virginity of fresh newbie eyeballs tends to fade quickly...

**Comment by brianharvey** [comment]
By the way, this particular feature will be implementable in Snap! itself once we get macros implemented, the other big feature I think we need besides sprite OOP.

**Comment by jmoenig** [comment]
Wait, now I'm confused. Doesn't my custom block totally take care of this? Why would we need macros for this?

**Comment by deader69** [comment]
Would love to have it built in, since it's universal useful to everyone. It's not a specific library, but some sweet syntactic sugar, applicable to practically every app.

And it'd help even absolute beginners... and I never load Snap! libs (kinda slow, don't wanna confuse newbs)... and I don't introduce kids to custom blocks the first month or two, depending on their skills.

But... it's your call.

**Comment by brianharvey** [comment]
Oh, oops, yeah.  I always forget that upvar scope works that way...
