### ISSUE TITLE
Play Note Until Done?

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#775]
There is a play sound until done, but is there a similar way to do this for notes?

**Comment by jmoenig** [comment]
notes always play until done. I don't understand your question...

**Comment by cycomachead** [comment]
Try playing the note in a repeat until loop with a constantly true condition. (Like not key space pressed)

-- 
Michael Ball
From my iPhone
michaelballphoto.com

**Comment by jmoenig** [comment]
you mean, like this:

![play note](https://cloud.githubusercontent.com/assets/2596285/7196800/f1efbcfe-e4d8-11e4-90d5-5c37aec36c83.png)

works for me

**Comment by jmoenig** [comment]
some here:

![note while](https://cloud.githubusercontent.com/assets/2596285/7196815/32f7509a-e4d9-11e4-9daa-ddc3fd93deb1.png)

**Comment by jmoenig** [comment]
or here:

![more notes](https://cloud.githubusercontent.com/assets/2596285/7196829/544fcfec-e4d9-11e4-9e50-459750cea532.png)

**Comment by cycomachead** [comment]
Hmm..I was filing this on behalf of other TAs and students -- I think the issue may actually be more caused by a repeated broadcast (that also used a loop). If you try a when space pressed, then I at least hear a 'popping' sound that sounds like the note is restarting each time.

**Comment by cycomachead** [comment]
Actually...this may be a thread safe scripts issue.

**Comment by jmoenig** [comment]
thread safety might be an explanation, but I believe it's more of a ```broadcast and wait``` issue:

![broadcast and wait](https://cloud.githubusercontent.com/assets/2596285/7196991/944cbf0e-e4db-11e4-851a-c33f1182e616.png)

**Comment by cycomachead** [comment]
Closing this...I forget what the conversation was a few months ago about this, but the play note block works just fine!
