### ISSUE TITLE
Question : how to add documentation to custom bloks

### ISSUE THREAD

**Issue by show0k** [jmoenig/Snap--Build-Your-Own-Blocks#777]
Hi,
The help popup seems only to be made for js blocks. If it is true, have you an idea how to add a kind of documentation ?
We thought to attach custom blocks with comments block in a second sprite, to make a kind of documentation sprite, but it is an ugly hack.

**Comment by jmoenig** [comment]
it's somewhat of an open issue, but here's what you can do already:

You can create a help PNG whose file name is exactly all the block label strings concatenated (without the input slots), and put that into your local HELP folder. This is how we do it for the "official" tools library, and it will work for your custom bocks, too, but only offline (I think). So this is probably not what you'd wand anyway.

BUT how about this:

In the Block Editor you can attach a comment to the prototype hat block:

![prototype comment](https://cloud.githubusercontent.com/assets/2596285/7230865/c192512a-e771-11e4-94f5-17f4ede6188c.png)

Then, when you accept the Block Editor, you get a tooltip with the comment when you mouse-hover over the block's template in the palette:

![custom block tooltip](https://cloud.githubusercontent.com/assets/2596285/7230886/e2c87392-e771-11e4-8fe8-d3719c9d8ba8.png)

And if you select "Help" for a block instance in the scripting area Snap pops up a dialog box also showing the comment:

![custom block help](https://cloud.githubusercontent.com/assets/2596285/7230907/03b32c46-e772-11e4-9762-4db046864492.png)

This is currently the "official" way so supply help for you custom blocks.

Now, if only we could add pictures to comments... :-)

**Comment by show0k** [comment]
Thanks a lot, it is very useful !
I just seen it in the documentation pdf p65, but I misread it, sorry...

**Comment by jcaldw737** [comment]
This is wonderful!  Thank you so much!

I can get right click help to work, which is what I really need, but being a greedy soul, I am wondering why mousing over in the palette doesn't give me the help.

Thanks again!

**Comment by brianharvey** [comment]
My fault -- I convinced Jens that the mousing over was too aggressive and made it hard to see other things obscured by the help balloon.

**Comment by jcaldw737** [comment]
Thank you for the information.  Right-mouse, help is really what I need, and thanks to you folks, I've got it!
