### ISSUE TITLE
Allow https:// requests from the http:// block

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#782]
Would it be possible to amend the `http://` block so that `http://` is a pulldown menu with [http://, https://]?

There are many services which require https to work, and it'd be nice to not need a custom JS block, at least for the simple ones.

**Comment by show0k** [comment]
In the same way, it would be nice to allow POST requests with a pulldown menu on the http block

**Comment by bromagosa** [comment]
I have a block exactly like this one working in our Snapi fork, but if you only need this functionality, it can be built as a simple JS block that could be bundled in a library, like this one:

http://snap.berkeley.edu/snapsource/snap.html#present:Username=bromagosa&ProjectName=REST%20block

Hope it helps :)

**Comment by cycomachead** [comment]
@bromagosa Yeah, I've been working on a simple ish block to allow headers in requests
(http://snap.berkeley.edu/snapsource/snap.html#present:Username=cycomachead&ProjectName=HTTP%20Test)

However, I think the default Snap<i>!</i> installation should include support for https://, for a couple reasons:
1. More and more sites require https
2. Generally, there's no harm in making an https request to an http site
3. It makes serving snap over https connections easier, because there are some rules which prevent loading http content from https domains. (Though I don't know which of them apply to XHR stuff....)

**Comment by jmoenig** [comment]
Okay, can you point me to some services that you or some students/teacher have tried that don't work? (Just trying to understand the scope of the issue here). Thanks!

**Comment by cycomachead** [comment]
Closing because #1762 has far more interesting discussion - and has my more current views whereby I've decided the dropdown menu is a bad idea.
