### ISSUE TITLE
Removing 0 from the front of a number

### ISSUE THREAD

**Issue by Pure-Diamond** [jmoenig/Snap--Build-Your-Own-Blocks#783]
This is hardy a bug, it's more of a complaint. SNAP removes 0(s) from the front of a number. That makes multivariate recall (BJC's pascal activity in particular) much more difficult. In other languages this isn't a problem. It would be great if this was fixed or there was some tweak that I could use. Because of this I either have to make my list 20x as long or I have to completely redo my script

**Comment by brianharvey** [comment]
So, if you load the "words/sentences" library, there's a block "all but first letter of," and if you apply it to the number 304 you get the string 04 including the zero.  It's only if you do arithmetic on it that you lose the zero.

**Comment by cycomachead** [comment]
Why not make a block called `pad (num) to (places)`?

For storing values it should be fine, watchers seem to be the only real issue with displaying a padded number.
