### ISSUE TITLE
Load failed: TypeError: myself.target.vars[myself.getter] is undefined

### ISSUE THREAD

**Issue by deader69** [jmoenig/Snap--Build-Your-Own-Blocks#784]
CRITICAL BUG! I've lost a lot of work on this one...

Somehow, the following file didn't save properly, and/or appears to be corrupted:
http://snap.berkeley.edu/snapsource/snap.html#present:Username=deader-tcssm&ProjectName=yoyo_ants

This happened twice last night.

Normally I do more investigation before reporting, but this one is serious.
Will try on other machines/wifi networks asap.

**Comment by jmoenig** [comment]
I've investigated a little. The good news is that it's *just* a bug, your project is not corrupted and can be reclaimed. I'm working on a fix, and once that's patched in you will be able to retrieve your project and continue working on it.

**Comment by deader69** [comment]
:-) :-) :-)

**Comment by deader69** [comment]
Dunno if it's relevant, but I renamed and deleted some sprites...

There was an old 'yoyo', then I developed a new 'yo'... eventually, to clean up the code, I deleted the original 'yoyo', then renamed 'yo' to 'yoyo'.

I did something similar for the hand.

Just in case there was some hidden info bound to the symbol 'yoyo'... could I have confused some internal symbols maybe? Probably irrelevant, but I thought you should know.

Here's a link to the prev version of yoyo, which DOES load okay...
http://snap.berkeley.edu/snapsource/snap.html#present:Username=deader-tcssm&ProjectName=yoyo%20sean%20devgan

**Comment by jmoenig** [comment]
Hi @deader69 , I've just patched Snap with a fix for this issue. Could you please check whether your project loads again (it does so for me now, plz make sure to reload Snap until the module ```store``` has today's version date). Tnx!

**Comment by deader69** [comment]
Hmm, it still doesn't load... I get the exact same error message.

And when I examine the "store.js" file...
  http://snap.berkeley.edu/snapsource/store.js
I see 
  modules.store = '2015-March-15'
not the April-26 version.
???

Is my (FireFox) browser somehow caching an old store.js file?
How do I flush it?

I tried adding a &foo=bar to the Snap! URL, but that doesn't affect the included files like store.js, right?
http://snap.berkeley.edu/snapsource/snap.html#present:Username=deader-tcssm&ProjectName=yoyo_ants&foo=bar

I'm not seeing your Apr-26 changes, for some reason.
I'll try rebooting my machine, and let you know...

**Comment by deader69** [comment]
Reboot fixed nothing. I'm still seeing
  modules.store = '2015-March-15';
in the file
  http://snap.berkeley.edu/snapsource/store.js

**Comment by deader69** [comment]
OKAY, my CHROMIUM browser works, and has April-26 version of store.js!

HOW do I flush FireFox caching of store.js?

**Comment by deader69** [comment]
OKAY, found the dialog box to manually flush the FIREFOX browser cache!
Bug squashed, thanks! Now I can squash some ANTS, lol!

Can I ask a completely unrelated question? I have lots of 'forever' loops in my yoyo app, looping "as fast as possible", with no 'wait' or other timing control...
So won't my yoyo run waaay faster on future machines that are waaaay faster?
Or does Snap! have some automatic governor to limit the rate at which blocks are interpreted?

Should I be putting 'wait' statements at the end of any/all 'forever' loops that contain 'move', etc?

**Comment by jmoenig** [comment]
Usually you can force browsers to reload a page completely without any caching by keeping the shift key pressed while clicking "reload".

If your project has may threads / sprites doing things in parallel (which is the case if you have a lot of forever loops) you're way better off (and will enjoy dramatically increased performance) with the "Prefer smooth animations" setting:

![smooth](https://cloud.githubusercontent.com/assets/2596285/7346285/de1cddfe-ecaa-11e4-87ee-2083c077af47.png)

Also, this setting will ensure that your project runs the same on most computers. By default Snap *will* run pretty fast, and it will also run faster on faster hardware, but it optimizes the scheduler for recursive operations in just a very few parallel threads. Whenever you make an interactive game you're way better off choosing "smooth animations", and you'll also be able to run many more "forever" scripts (and even many more on faster machines).

**Comment by deader69** [comment]
Looks like 'Prefer smooth animations' setting gets stored in the project file, right? As do all settings?

Also, I'm assuming 'Flat design' make Snap! run faster, correct? It's purpose is to avoid the cost of shading all the widgets, right?

Putting my app in 'turbo' mode really reveals the lack of timing control! The ants travel huge distances between render frames! Will experiment with some 'wait' statements... I COULD write everything as a function of 'current milliseconds', but that'd make my code very non-kid-friendly!

I've also noticed that moving code into custom block definitions makes things run MUCH faster too. I guess because you can bypass all the 'hilight when execucting blocks' render overhead.

Finally, I've seen several bugs when adding 'warp' blocks... haven't reported them yet, because I want to methodically document and categorize them... I've just stopped using them altogether, for the moment.... will eventually file a new bug report, once I get around to experimenting with the conditions.

**Comment by jmoenig** [comment]
flat design may actually be slower, and yes, "smooth animations" gets stored in the project. I don't think that turbor or warp is buggy, but you need to be careful with using them. Also, putting things into block definitions does not per se make anything faster...

**Comment by deader69** [comment]
I definitely had something speed up once when I moved code from an event handler into a block def... will try to remember the project and reproduce!

**Comment by jmoenig** [comment]
smoothness and turbo are mutually exclusive

**Comment by deader69** [comment]
It might have been the difference between direct function call versus broadcasting an event, then waiting to get the message later... probably that was the factor, the order and timing of events in the queue.

**Comment by maryfries** [comment]
https://piazza.com/class/h8yx482idav52y?cid=728
