### ISSUE TITLE
Recent changes and "obsolete"

### ISSUE THREAD

**Issue by sharived** [jmoenig/Snap--Build-Your-Own-Blocks#787]
Seems like there was an update today - well I saw it for a few minutes at least. - seems to be gone again...  Is there  a way to get notifications about changes so I can test that my code doesn't break?  I saw 2 new options from file menu - "Export project as plain text..." and "Export all scripts as pic..."  When I tried this second options I  see something that says obsolete on one of my blocks.  What here is obsolete?
![obsolete](https://cloud.githubusercontent.com/assets/1163591/7376985/59724a6e-ed98-11e4-822e-2799c3497669.png)

**Comment by jmoenig** [comment]
Ah, yes I've patched Snap with a little unrelated bugfix. The options you've been seeing are experimental features that have been part of Snap for a long time and are - sort of - "hidden", i.e. you only see them if you keep the shift key pressed while you click on menu buttons. Try them, you'll discover a few interesting experiments! :-)

Dunno what that "obsolete" block is doing, could be a bug in Snap... (Can you share the link to your project with me, then I could investigate...)

Thanks!

**Comment by sharived** [comment]
ah, thanks for the clarification.  That's pretty tricky!  Unfortunately I already deleted the obsolete block.  Everything has been working fine, so I'll close the issue.  If it pops up again I'll let you know.
