### ISSUE TITLE
Question: how to implement a kind of Thread.join block

### ISSUE THREAD

**Issue by show0k** [jmoenig/Snap--Build-Your-Own-Blocks#789]
Hi,
I would like to make a block to run concurrently many command blocks, but which waits for the end of execution of all launched blocks before closing.
It's easy to make a block which iterate over inputs to launched them
![test1](https://cloud.githubusercontent.com/assets/3891499/7381739/f6bac328-ee06-11e4-9a53-dbe78e838505.png)
But, how to have a 'end' signal information ?
I saw two solutions, none of them works.

I could use message/broadcast/send feature, but:  
* I can't receive a message in a block
* Even it is possible, as we can't specify destination/namespace of the message, it may have problems with many <parallel> block running at the same time

I could use the return value (report) of the running blocks, and check the return value after the launch. I try that: 
![test_2](https://cloud.githubusercontent.com/assets/3891499/7382053/9b9f034c-ee0a-11e4-9580-4a47260df9e1.png)
The only difference with the first version, is that only the last element of the input list is launched  (list length times) instead of each element.

N.B. to test if its working, I use as input a block with a global variable modification and a variable waiting:
![test_block](https://cloud.githubusercontent.com/assets/3891499/7381901/f06a78c2-ee08-11e4-9552-684aa5ced5d1.png)

Have you any idea ?

**Comment by brianharvey** [comment]
Quick and dirty way: Set a global variable to the number of threads, and have each of them decrement it when done, and wait for it to be zero.

More interesting way: Build your own thread system using continuations; see the call with continuation section in the manual for an example (the last thing in the manual).

**Comment by show0k** [comment]
Thanks for the fast answer.
The global variable way won't works if I run many parallel blocks at the same time.

I read the continuation part more carefully, I'll try tomorrow.

**Comment by jmoenig** [comment]
Sure, @brianharvey 's global variable way totally does work! See my parallel factorial demo project:

http://snap.berkeley.edu/snapsource/snap.html#cloud:Username=jens&ProjectName=Slices

at it's heart it slices an operation into an arbitrary number of threads, waits until all threads are done and then combines all the results:

![factorial slices](https://cloud.githubusercontent.com/assets/2596285/7383277/a87c2c4a-edea-11e4-8f6f-0220e3670843.png)

Isn't this *exaclty* the problem you're trying to solve?

**Comment by show0k** [comment]
Yes thanks a lot. It is approximately what I want.
To be more specific, I want a `parallel` and a `sequential` block which can take each other on inputs.
Ax represents an action block (a reporter or a command). I would like to make something which can execute this type of expression: 
`parallel(A1,A2,sequential(A3,parallel(A4,A5)))`

Your example is very helpful. By the way, is there something or a place where we can browse all your public projects ?
I manage to make it thanks to your help: 
![working](https://cloud.githubusercontent.com/assets/3891499/7394699/7c7bac78-ee95-11e4-9756-58850b8fae75.png)
The yield block (wait 0.00000001s) is very important, without it th iteration is not working. Why ? It would be the first language i've to wait to be sure a variable is set !
I've another question but I'll make another thread.

**Comment by jmoenig** [comment]
I've had this "thread slicing" experiment lying (unpublished) around for a couple of years, so you couldn't possibly have missed it before :-)

Yes, ```yield``` is important when you try to parallelize reporters, because Snap tries to run (even nested) reporters atomically (i.e. in a single step frame, the equivalent of ```warp```). Therefore you have to artificially "yield" somehow if you do expect reporters to run for a long time (which usually you don't).

BTW, if you do happen to want to "yield" it's far better to just execute an empty ```warp``` than a tiny ```wait 0.00001``` block:

![yield](https://cloud.githubusercontent.com/assets/2596285/7405077/78c614e4-eebb-11e4-86ff-2abbc16bb9ef.png)

because it will yield precisely *once* and not try to compare elapsed times. I've updated my above example and it now runs twice as fast but still perfectly parallel.

**Comment by show0k** [comment]
The change of yield block double the performance ? Impressive !

**Comment by jmoenig** [comment]
Well, not really. You see, If I didn't put in explicits ```yield```s  everything would be *much* faster to begin with, but then I wouldn't be able to demonstrate parallelism...

**Comment by show0k** [comment]
If it can help someone, I made a pool map block. It works as the map block but it run everything concurrently. It is not as elegant  as the JMoening map, but it works.
![pool map](https://cloud.githubusercontent.com/assets/3891499/7455695/abb76c42-f27e-11e4-9489-fa28918aa6bd.png)

Quick example: 
![capture du 2015-05-04 16 55 54](https://cloud.githubusercontent.com/assets/3891499/7455825/bd07a114-f27f-11e4-92e7-9809afeca57d.png)
vs
![capture du 2015-05-04 16 55 15](https://cloud.githubusercontent.com/assets/3891499/7455833/c8e3a7d0-f27f-11e4-826e-a0f98acb5c52.png)
