### ISSUE TITLE
Invisible first item in the drop-down menu for the 'when __ pressed' block?

### ISSUE THREAD

**Issue by deader69** [jmoenig/Snap--Build-Your-Own-Blocks#790]
I've noticed an invisible item at the very top of the drop-down menu on the 'when ___ key pressed' hat block.

What is it? It's selectable, but doesn't seem to correspond to any key on my (laptop) keyboard.

I was HOPING it corresponded to the TAB key, or some other invisible char.
(I would love to have access to the RETURN key, but I can understand how that's reserved for the Snap! UI itself).

Anyway, I was just wondering why it's there, what it does, etc.

**Comment by deader69** [comment]
I couldn't figure it out by looking at the code in blocks.js either. In fact, it doesn't seem to appear there...

        case '%key':
            part = new InputSlotMorph(
                null,
                false,
                {
                    'up arrow': ['up arrow'],
                    'down arrow': ['down arrow'],
                    'right arrow': ['right arrow'],
                    'left arrow': ['left arrow'],
                    space : ['space'],
                    a : ['a'],
                    b : ['b'],
                    c : ['c'],
                    d : ['d'],
                    e : ['e'],
                    f : ['f'],
                    g : ['g'],
                    h : ['h'],
                    i : ['i'],
                    j : ['j'],
                    k : ['k'],
                    l : ['l'],
                    m : ['m'],
                    n : ['n'],
                    o : ['o'],
                    p : ['p'],
                    q : ['q'],
                    r : ['r'],
                    s : ['s'],
                    t : ['t'],
                    u : ['u'],
                    v : ['v'],
                    w : ['w'],
                    x : ['x'],
                    y : ['y'],
                    z : ['z'],
                    '0' : ['0'],
                    '1' : ['1'],
                    '2' : ['2'],
                    '3' : ['3'],
                    '4' : ['4'],
                    '5' : ['5'],
                    '6' : ['6'],
                    '7' : ['7'],
                    '8' : ['8'],
                    '9' : ['9']
                },
                true
            );
            part.setContents(['space']);
            break;

**Comment by deader69** [comment]
Ahhh, now I see EVERY dropdown has a blank... to clear the field entirely, right?

I think I just answered my own question :-)

**Comment by jmoenig** [comment]
all drop-downs in Snap! have an "empty" item in them, so you can reset an input slot to be "empty". Empty input slots can be treated as implicit formal parameters...

Ah, yes, you beat me to the answer :-)

**Comment by deader69** [comment]
Yes... I'm forcing myself to "read the code" before asking stupid questions, lol!

And sometimes, the answer becomes obvious 2 minutes after I post!

**Comment by deader69** [comment]
BTW, I noticed the 'warp' block SOLVES a problem I was having with my Morse Code app long ago...

The OS generates auto-repeat events when you hold a keyboard key down long enough...

This created a problem for me where a second instance of the 'when ___ pressed' handler started running before the previous one(s) had completed, because the keyboard events are coming so fast...

So my dots and dashes (drawn with pen commands) were getting all inter-mingled, out-of-order in time.

Putting a 'warp' around the whole event handler solves that problem.  :-)

Does it solve the problem simply because it's executing faster? Or because 'warp' explicitly takes over, and doesn't relinquish control to another event thread until it's done?

**Comment by jmoenig** [comment]
the latter, ```warp``` basically locks a thread until it is done warping, except for emergency yields, so you can still press the red stop button.
