### ISSUE TITLE
Cloning snap with git for windows

### ISSUE THREAD

**Issue by carloslfu** [jmoenig/Snap--Build-Your-Own-Blocks#791]
I'm now working in a laptop with Windows and I have tried to clone the Snap repo but I get the next log:
```
error: Invalid path 'help/list->sentence.png'
error: Invalid path 'help/sentence->list.png'
```
I found that in Windows  `>` is a not valid character for a file name.

**Comment by cycomachead** [comment]
Duplicate #145, I believe.

In any case, you can ignore those files. They're not even needed anymore for the recent tools blovks.

**Comment by carloslfu** [comment]
Ok, thanks

**Comment by cycomachead** [comment]
@brianharvey @jmoenig This has been fixed and can be closed.

(I could do it too, if I were added as a collaborator! :smile:)
