### ISSUE TITLE
Question: how to make object introspection in Snap!

### ISSUE THREAD

**Issue by show0k** [jmoenig/Snap--Build-Your-Own-Blocks#792]
Hello,
Is there a way to proceed a kind of object introspection in Snap! ? 
For example, I would like to be able to iterate over blocks which are contained in a ring or an object from a c-shape input.
Am I missing something or is it voluntary limitation ?

**Comment by brianharvey** [comment]
Funny you should ask -- we just sketched out a design for how to do that in 4.1.  Stay tuned.

**Comment by show0k** [comment]
ok, thanks. Just to know, when do you approximately plan to release the next version ?

**Comment by brianharvey** [comment]
There will be a more-or-less usable release in time for the Scratch conference in Amsterdam in August, we hope.
