### ISSUE TITLE
Feature request: improve list manipulation

### ISSUE THREAD

**Issue by show0k** [jmoenig/Snap--Build-Your-Own-Blocks#794]
Hi,
I think it could be useful to add the possibility to access list elements from the end by a negative reference. 
![item](https://cloud.githubusercontent.com/assets/3891499/7473179/6283723a-f339-11e4-875c-3f59ed293c66.png)
Moreover, I think Snap! misses a block like this one to extract easily a sublist from a list:
![multiple_inputs](https://cloud.githubusercontent.com/assets/3891499/7473430/67c8edae-f33b-11e4-8dd2-35b7442a47a5.png)

examples:
![sublist_rignt](https://cloud.githubusercontent.com/assets/3891499/7473318/a0a8d0b8-f33a-11e4-9771-341c6f6654d5.png)
![sublist_inverse](https://cloud.githubusercontent.com/assets/3891499/7473323/a3fc2ef4-f33a-11e4-8f2f-b8f89a4bfab9.png)

**Comment by brianharvey** [comment]
As a rule, if a user-written block (such as your ITEMS) is just as good as a primitive, better the user should write it!

But also, I think you're assuming that the list is really stored as an array.  If it's a linked list (which it will be, if the user is doing functional programming), LENGTH takes linear time, and so your negative item numbers take linear time too.

All our list primitives, I think, take (amortized) constant time provided that (for a given list) you're consistent in using functional or imperative programming.  (Sorry, except for ITEM other than ITEM 1, on linked lists.)

**Comment by show0k** [comment]
Okay I understand you point of view for your first sentence, but it can be a bit confusing for new users. For example without importing iteration library you have no "for" loop, but at the same time you have a "forever" block and a "repeat until bool" block which are -as far as I know- redundant. 
I'm not very familiar with functional programming and I have too much imperative programming habits, this may be the problem.

I totally agree with you for the negative item, it wasn't a good idea, sorry.

**Comment by brianharvey** [comment]
Yeah, some of those redundant blocks were inherited from Scratch; we didn't want to introduce unnecessary reasons for projects not to work.

I think everyone should import tools first thing; I think of those blocks as primitives, even though implemented in Snap<i>!</i> itself.

**Comment by bb010g** [comment]
[**@brianharvey**](https://github.com/brianharvey) commented on [May 6, 2015, 11:32 AM PDT](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/794#issuecomment-99565508 "2015-05-06T18:32:31Z - Replied by Github Comment Enhancer"):
> I think everyone should import tools first thing; I think of those blocks as primitives, even though implemented in Snap_!_ itself.

`stdtools`? ;)


[**@brianharvey**](https://github.com/brianharvey) commented on [May 6, 2015, 11:32 AM PDT](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/794#issuecomment-99565508 "2015-05-06T18:32:31Z - Replied by Github Comment Enhancer"):
> Yeah, some of those redundant blocks were inherited from Scratch; we didn't want to introduce unnecessary reasons for projects not to work.

Any reason the redundant forms aren't in tools as block variations of the "primary" primitive?

**Comment by brianharvey** [comment]
No, no reason.  Jens just implemented all the Scratch stuff unless we had a specific reason to eliminate it (the only example I can think of right now is the Make a List button).
