### ISSUE TITLE
Equality comparisons of ringified functions

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#797]
Should this work?

![screen shot 2015-05-10 at 1 35 22 am](https://cloud.githubusercontent.com/assets/1505907/7553580/1da1e276-f6b5-11e4-935d-7b1191a8c421.png)

In any event, it would be handy if it did! :)

**Comment by bb010g** [comment]
What about <((round _)) = ((round x) with inputs (x))>? The problem with function comparison is that it can't be determined always. You could probably get it to work on the functions themselves, not ringified, but literal, and only to the extent that the syntax elements are the same, but trying to determine lambda function equivalence is [impossible](https://en.wikipedia.org/wiki/Lambda_calculus#Undecidability_of_equivalence).
