### ISSUE TITLE
Snap! Bug: Exporting Sprites and Blocks

### ISSUE THREAD

**Issue by lmock** [jmoenig/Snap--Build-Your-Own-Blocks#800]
From the BJC Piazza: https://piazza.com/class/h8yx482idav52y?cid=471

One of my students has been trying to export his sprite called "Enemy" and his custom block called "player controls".  He is unable to do so unless he disconnects the comments.  If there are no comments, then it works.  I'm guessing this is a bug because I try to get my students to use comments.  If this doesn't work, then I have to tell them not to comment so they can combine projects.  Here is a link to his project.  
 
http://snap.berkeley.edu/snapsource/snap.html#present:Username=99011378&ProjectName=Trapped%20in%20time%20v5.7
 
Any thoughts on what is causing the problem?
 
Thanks

**Comment by jmoenig** [comment]
Yep! This isn't about comments. Exporting the "Enemy" sprite and importing it into another project works fine for me, including the comments. Did this teacher actually try exporting the sprite himself?

When exporting / importing sprites you have to be careful to setup the target project so it has everything the sprite needs, especially any *global* blocks. Exporting a sprite only exports all the sprite *local* block definitions and does *not* check for dependencies on global blocks. Therefore if your sprite relies on the tools library, you have to make sure first to import the tools library in the new project, before you import the sprite. Likewise if your sprite relies on global custom blocks, you have to make sure those also exist in the project you want to import your sprite into. In this particular project you can either export *all* the global blocks first, or only the two ones which are actually used by the "Enemy" sprite ("enemy movement" and "clone maker").

P.S. Please don't mark such issues as "Bugs" until they are, in fact, confirmed bugs.

**Comment by lmock** [comment]
This looks like a bug to me. I'm attaching two screenshots. One of the original Enemy sprite, and another of a screenshot of what the sprite imported into a new Snap! project looks like. Not all the comments copied over and we don't know what's going on.

![original](https://cloud.githubusercontent.com/assets/5467107/7580927/cd8ce0fa-f831-11e4-8e42-dbb45194c158.png)

![exported](https://cloud.githubusercontent.com/assets/5467107/7580930/d0fed874-f831-11e4-8217-067a1b015cbc.png)

**Comment by jmoenig** [comment]
```empty movement``` and ```clone maker``` are *global* blocks and need to be exported separately using "export blocks". Otherwise each individual sprite would overwrite the whole global environment.
