### ISSUE TITLE
What to do when wifi issues

### ISSUE THREAD

**Issue by sharived** [jmoenig/Snap--Build-Your-Own-Blocks#802]
Hi,
  I'm demoing at maker faire and the wifi iis causing a lot of issues.  I have one more day at the show any suggestions on how to solve this?

Thanks,
Shari

**Comment by brianharvey** [comment]
Download the source files (click on the Snap! logo in the corner of the window) and serve them from localhost.  (If you don't know how to set up a web server on your laptop, tell us what OS you're running.)

**Comment by sharived** [comment]
Thanks!  Will give it a try.  I'm on Mac OS.

**Comment by sharived** [comment]
This helped, but still was having issues with wifi.  Was strange at one point I was running with wifi off and everything worked and another time if I wasn't connected it wouldn't run.  I am communicating to the ev3 with http calls, so I'm guessing I still have a dependency here.  

Closing the issue - thanks!
