### ISSUE TITLE
Scroll Views don't Account for Scrollbar height

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#804]
In the project list view, the scrollbars overlap with the content of the view. This is making it really difficult to click on text that is (in this case) the last item in a list.

**Comment by jmoenig** [comment]
yep, that should be fixed at some point. In the meantime you can workaround this by making the project dialog wider, until the horizontal scroll bar disappears...

**Comment by cycomachead** [comment]
Duplicate of #638, my own issue. Lol
