### ISSUE TITLE
Help with codification

### ISSUE THREAD

**Issue by sharived** [jmoenig/Snap--Build-Your-Own-Blocks#807]
I'd like to try codification to improve my performance when I have wifi issues.  I looked at the example, but I'm not sure I have the concept right and I have some questions.

Are the blocks in the codification example in any libraries - I couldn't find them anywhere - or should I just copy from the example.  I exported 

![pic3](https://cloud.githubusercontent.com/assets/1163591/7782204/99f04766-00bd-11e5-8344-38437a54ba51.png)
But I couldn't figure out where to get
![pic1](https://cloud.githubusercontent.com/assets/1163591/7782199/7d94637c-00bd-11e5-8bf4-13083fabc232.png)
or
![pic2](https://cloud.githubusercontent.com/assets/1163591/7782201/8168698a-00bd-11e5-8149-9307c199509b.png)

I wanted to try using the C codification method.  After I create the "code".  What's next.  I assume I need to somehow copy the code onto my device and compile and run there.  Is that correct? I just realized that if I right click on the code I can export it.

Anything else I'm missing?

Thanks,
Shari

**Comment by studej** [comment]
To enable codification blocks in 'Others' category, you must check item in settings (see image below)
![codifsupport](https://cloud.githubusercontent.com/assets/7092949/7783595/a34dd24e-0147-11e5-8aa7-e4b99b80de88.png)

**Comment by sharived** [comment]
Thanks!  That provided the missing blocks.  Unfortunately my code isn't converting very well.  I tried C and python.  I'd recommend adding any unknown blocks as comments if they can't be converted directly.  For example I have a bunch of custom blocks that are being dropped.  Also, neither C or Python are converting my "Repeat until" block and everything within the loop is dropped as well.

**Comment by brianharvey** [comment]
You have to provide the translations yourself for custom blocks or other missed ones.  Look at the actual code of the example project to see how it adds translations for each of the blocks it needs.

**Comment by sharived** [comment]
Ah, got it.  Thanks.  Closing issue.
