### ISSUE TITLE
Linked lists and their structure sharing after July 17, 2014

### ISSUE THREAD

**Issue by studej** [jmoenig/Snap--Build-Your-Own-Blocks#811]
It's been a while since I've been active here on GitHub (Are you rested enough? :D) and I have a question about linked list and their structure sharing.

Look at image below. Help image of `in front of` block has note, that `The new list can share structure with the old one!`. There is also an example where comparing references  with `is identical to` results in `true`. I needed to show this to someone else and I found out that this does not work anymore. At the bottom of my image you can see that replicated example from help image results in `false` instead of `true` (as help image declared)... but I also know that it worked as help image shows.

![linkedlistsharingstructure](https://cloud.githubusercontent.com/assets/7092949/7795102/df45bfc4-02d1-11e5-8456-5a084847c766.png)

So I tried the same script on older versions of Snap! and it turned out, that version from June 19, 2014 returns `true`, but version downloaded month later -- from July 27, 2014 -- returns `false`. 
Something must changed in implementation, so I went back to history of commits on GitHub, where I found (https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/commits/master?page=7) commits from July 17, 2014 and July 18, 2014 fixing something with linked lists.

My question about sharing linked list structure actually is:
<b>Is current behavior correct or something wrong happened during implementation fixes?</b>
(if it is correct then help image should be updated)

Thanks for answer,
and congrats to Snap! official release guys! Good job, keep it up.

**Comment by studej** [comment]
Any answer on this @jmoenig ?

**Comment by jmoenig** [comment]
Hm... sorry, I've been vacationing the last two weeks. So, apparently someting changed when we fixed lists. Let's rope @brianharvey into this discussion :-)

**Comment by cycomachead** [comment]
This was fortunately fixed at some point.
