### ISSUE TITLE
Paint editor: filling tool freezes Snap! on local

### ISSUE THREAD

**Issue by studej** [jmoenig/Snap--Build-Your-Own-Blocks#812]
as title says (local = downloaded and opened in browser offline)
I know that we can't choose colors etc., but this freezes whole environment... :(
And this is not new issue, its here at least half a year

**Comment by jmoenig** [comment]
Yes, there are some "security" issues when running Snap locally, i.e. not serving it from a local web server, and this is one of them. Basically most attempts to access image data is frowned upon by the browser

**Comment by birbilis** [comment]
interesting, with Silverlight I had the opposite issue with ClipFlair Studio, visual content coming from remote locations (like video and images) couldn't be grabbed programmatically (e.g. to add screenshot button to component windows I have there). Maybe search for "CORS HTML5 local"

**Comment by bromagosa** [comment]
If it helps, I always run Snap! locally by using a **very** lightweight http server. I either user a NodeJS [httpserver](https://www.npmjs.com/package/httpserver) or this super simple Python one-liner:

``python -m SimpleHTTPServer``

This will run an HTTP server at localhost:8080 and fix all these issues.
