### ISSUE TITLE
[Minor Bug] the open dialog box always lists Cloud projects when it finally loads even if you clicked Examples/Browser first and that's what you wanted

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap--Build-Your-Own-Blocks#813]
Whenever your own Cloud projects load, it always shows them, regardless of whether you had clicked "Examples" and were scrolling through them to choose one.  Then what the user sees is inconsistent state: the "examples" tab is highlighted bold, but the Cloud projects are listed. (see attached image)

![screen shot 2015-06-01 at 2 38 10 pm](https://cloud.githubusercontent.com/assets/2229297/7920406/d151eeba-086c-11e5-997a-4afcd32521e6.png)

**Comment by jmoenig** [comment]
Yep, it's callback hell :-)
