### ISSUE TITLE
Enhancement: remove hardcoded URLs in Snap! sources

### ISSUE THREAD

**Issue by show0k** [jmoenig/Snap--Build-Your-Own-Blocks#814]
Hi,
I wanted to host Snap! locally on my computer and add my custom blocks in 'librairies' and 'Example' folders. As it was not working, I looked at the code of gui.js file and saw that the path of librairies, examples and others files are harcoded... 
```
menu.addItem(
        'Libraries...',
        function () {
            // read a list of libraries from an external file,
            var libMenu = new MenuMorph(this, 'Import library'),
                libUrl = 'http://snap.berkeley.edu/snapsource/libraries/' +
                    'LIBRARIES';

            function loadLib(name) {
                var url = 'http://snap.berkeley.edu/snapsource/libraries/'
                        + name
                        + '.xml';
                myself.droppedText(myself.getURL(url), name);
            }
```
One of the big advantage I see in Snap! is to be able to start the application from the internet  (with http://snap.berkeley.edu/snapsource/snap.html) than on my own computer, without web access. With that, loading examples or libraires without web access become very tricky...

I tried to change all reference of 'http://snap.berkeley.edu/snapsource/' on gui.js by a variable *base_url* defined by:
```
var full_url = window.location.host + window.location.pathname ;
// Remove the last part of the full url (e.g. "snap.html")
var base_url = full_url.split('/');
base_url.pop(base_url.length-1);
base_url = base_url.join('/')+'/';
``` 
But it does not works well. 
Don't you think it should be a good idea to remove hardcoded urls ?

**Comment by brianharvey** [comment]
Yes, we've gotten rid of some of those, and I think there's a pull request already in the queue that will get rid of all of them.  I'll try to prioritize that -- there doesn't seem to be any downside.

**Comment by show0k** [comment]
Thanks for the reply.
I've searched on pull requests and found nothing similar (I may have wrong keywords).

**Comment by brianharvey** [comment]
OK, I'll look into it.  Thanks for checking it out!

**Comment by luis140219** [comment]
Awesome tip! I'll remove hardcoded URLs for the [Starlings game](https://github.com/luismark/luismark.github.io/tree/master/starlings) this week!

**Comment by cycomachead** [comment]
I had a response, but I was on vacation and I guess it didn't get posted. :/

Anyway, I don't think there is a PR, but I do recall multiple issues at various points discussing this -- and yes it would be helpful to make snap a little more "portable" for installing it other places. 

There is a function in `gui.js` called `getSbeOrRelative` (I believe that's the title, capitalization may be off... :P) that tried to do something similar, though I forget exactly why we were trying to load from s.b.e?

Also, @show0k I think for `full_url` you could just use `document.url`, unless there's a reason that doesn't work?

**Comment by show0k** [comment]
You're right @cycomachead , it's better to use document.URL.
I made a pull request #821
