### ISSUE TITLE
Green flag event also triggers "when I receive any message" hat blocks

### ISSUE THREAD

**Issue by bromagosa** [jmoenig/Snap--Build-Your-Own-Blocks#815]
I think I may have found a little inconsistency, IMO it should either be that the green flag does trigger all ``when I receive any message`` blocks (as it is actually just like any other message) and then the ``message`` reporter reports ``__shout__go__``, or it doesn't trigger them at all.

The current situation is as I show in this project:

http://snap.berkeley.edu/snapsource/snap.html#present:Username=bromagosa&ProjectName=green%20flag%20bug

The first time you click on the green flag, everything goes as expected, the second time, both sprites speak at the same time.

**Comment by jmoenig** [comment]
Bernat, this is actually intentional. The "green flag" event is nothing but a specially named message, with the message string ```__shout__go__```. you can always programatically trigger the green flag by broadcasting  ```__shout__go__``` (it doesn't translate, btw), which is something I quite often do myself in my test-harness.

The reason it doesn't trigger the first time in your example is because the ```message``` buffer is empty when you first load the project.

Is this a problem for something you do (i.e. should we change it?) or is it just something you noticed?

**Comment by bromagosa** [comment]
Well, the thing is that IMO the behavior is a bit inconsistent. When the green flag event is triggered, the (message) reporter block doesn't report ``__shout__go__``, so from a user's perspective you don't understand why has the green flag triggered your previously sent "regular" message.

So, in a way the green flag is just another event (triggers the ``when I receive`` block), but in another way it is not (isn't reported by the ``message`` block).

**Comment by jmoenig** [comment]
Oh, now I understand! Sure, the ```message``` reporter block absolutely should report the ```__shout__go__``` last message when the user presses the green flag, you're right!

**Comment by brianharvey** [comment]
I have to say, as a user I'd be surprised if clicking the green flag fired my "when I receive" block.  Of course I'm delighted that a program has a way to push the button, but I wonder if it wouldn't be better not to include that message in the domain of "any message."

**Comment by bromagosa** [comment]
My biggest concern was that the behavior is inconsistent and thus it's quite hard to justify it to students. In this sense, any of both solutions work for me.

Still, in our fork I chose @brianharvey's approach because, although the green flag is nothing but another message -and it's nice to demonstrate that to kids- we still have to agree it's kind of a special one. Actually, it's so special it even has a dedicated button that fires it...

I feel having the ``message`` reporter report ``__shout__go__`` would usually result in structures like this one:

![image](https://cloud.githubusercontent.com/assets/1016697/8039291/f6b4494a-0e08-11e5-8427-0d771323a518.png)

**Comment by bb010g** [comment]
Perhaps an "any message (w/ shouts)" option? Then the default would still be sane, but you could get `__shout__`s just fine still.

**Comment by jmoenig** [comment]
Good points, both @brianharvey and @bromagosa . Maybe you're right and we should just filter out the ```__shout__go__``` message from the ```any message``` option.

**Comment by bromagosa** [comment]
If you agree on this, I've actually made the change in a fork, so I guess I can send you a pull request straight away :)

**Comment by jmoenig** [comment]
Oh, great! Sure, go ahead, I'll pull it along with some minor translation updates I've been getting. Thanks!
