### ISSUE TITLE
Input caret can't lose focus and still blinking

### ISSUE THREAD

**Issue by studej** [jmoenig/Snap--Build-Your-Own-Blocks#820]
This happens really often to me (unintentionally) and I noticed it two maybe three weeks ago. I guess, that template block in palette with active caret is completely duplicated even with caret activation (input focus). That's why we still see caret blinking.

<b>GIF DURATION</b> - 0:31
![caretblinking](https://cloud.githubusercontent.com/assets/7092949/8023212/61931d9a-0d00-11e5-9a59-0cb318767745.gif)

**Comment by cycomachead** [comment]
I've noticed this too, and I think it also started around that time.

**Comment by jmoenig** [comment]
interesting! I doubt that this has been introduced recently (although https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/commit/585d1541b8ce45ba2be1367ab4ddac1b9a1095d6 could be a candidate, I'll check), it's just we've never come across it until now :-)

Anyway, should be an easy fix, thanks for reporting it!

**Comment by jmoenig** [comment]
... https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/commit/30e43a359e5ba1a7ec3c6ab331e8f9ec7e43ca7e could also be responsible...

**Comment by jmoenig** [comment]
... okay, you were right, I can confirm that this bug has been introduced recently ...

**Comment by birbilis** [comment]
there is a probably related issue with text input (tried in IE11/Win8.1) at the login/sign up dialogs. You start typing and the text goes to the browser address bar instead (but you see the caret blinking in the text field). Then it's quite hard to move focus back to that text field
