### ISSUE TITLE
Get into the Any Browser initiative

### ISSUE THREAD

**Issue by luis140219** [jmoenig/Snap--Build-Your-Own-Blocks#822]
You should include luismark.js (http://luismark.github.io/apis/luismark/v1.2.0/luismark.js) and get rid of all browser-specific behaviour.
The initiative consists of making the websites it is applied to, "Best Work on Any Browser".

**Comment by jmoenig** [comment]
Can you explain a little bit about this initiative? Which code in Snap is browser-specific? Tnx.

**Comment by birbilis** [comment]
sounds a bit like a spam post (?)

**Comment by luis140219** [comment]
The any browser initiative is here: http://www.anybrowser.org/
The initiative states that the code should run on any browser, so comment code inside on-HTML Javascripts like the following:
```
<script type="text/javascript"><!-- 
// JS code
var world = new WorldMorph(document.getElementById("#canvas"));
--></script>
Also there is the excanvas.js library, for adding canvas element support for browsers that do not support it.
There is a issue/PR about the noscript element in this repository.

**Comment by bb010g** [comment]
Snap*!* is somewhat useless without JS, so I think not XML commenting out the inline JS is fine. It breaks either way on such a browser.

**Comment by jmoenig** [comment]
hm... I don't get it...

**Comment by birbilis** [comment]
he means that some browsers have no script tag I think, so people comment out the contents of the <script> tag. Of course this results in more ugly code for no useful reason

as for fallbacks for canvas and other technologies of modern browsers, they're using Flash etc. for fallbacks
