### ISSUE TITLE
No support for non-English keyboards

### ISSUE THREAD

**Issue by bl-nero** [jmoenig/Snap--Build-Your-Own-Blocks#825]
It's impossible to type Polish diacritic signs using Alt key; for example, pressing Alt+a doesn't write "ą", but selects the entire text in the input box. This happens on Win and Mac. The only way to select entire text should be Ctrl+a and Command+a, respectively.

**Comment by cycomachead** [comment]
See also: #4

**Comment by jmoenig** [comment]
That might be amore complicated issue, because *some* characters can be typed in. I get all the special German umlaut characters and the "sharp ß', the € and @ signs on my Mac keyboard, but no accented characters, but I get those on my other USB keyboard on Windows.
