### ISSUE TITLE
Minor: Hiding Primitives leaves space for the block search bar

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#838]
See the following screenshot. This has actually been in Snap<i>!</i> for a little while, but I don't think I've reported it. 

![screen shot 2015-06-17 at 8 20 06 pm](https://cloud.githubusercontent.com/assets/1505907/8223624/5d4e0ea2-152f-11e5-82bf-d4257c47ce6f.png)

**Comment by jmoenig** [comment]
This isn't about the search bar. There is a padding in between primitives and custom blocks, this padding could vanish if *every* primitive in a palette is hidden. OTOH if you see the padding at the top you know that *every* block is a custom one :-)

**Comment by cycomachead** [comment]
Yeah, you're right. I could have sworn I noticed something about the placement of blocks after the search bar was added, but I tested a few things and this looks the same as it always has. 

...maybe I'm just going crazy...
