### ISSUE TITLE
Invalid path error for  /help/sentence->list.png when cloning repository

### ISSUE THREAD

**Issue by miklobit** [jmoenig/Snap--Build-Your-Own-Blocks#840]
Using '>' character in filename is causing error when clonig repository under windows.
This character is used  to redirect output  and should be considered as prohibited if you want the project to be portable.

**Comment by cycomachead** [comment]
You can safely ignore the files, they're there for help screens in older blocks which have been renamed.

See also #791 #145

**Comment by miklobit** [comment]
I can't ignore this  because Eclipse IDE stops at this file with error message while cloning repository....

**Comment by cycomachead** [comment]
I'm not sure about eclipse, but is it possibe to clone w/o eclipse using the Github app or something else?

**Comment by luis140219** [comment]
I have a fork without those help files. Clone instead from luis140219/Snap--Build-Your-Own-Blocks (`git clone https://github.com/luis140219/Snap--Build-Your-Own-Blocks.git`)

**Comment by cycomachead** [comment]
@brianharvey @jmoenig This also has been fixed and can be closed. Inadvertently fixed by #944.

**Comment by jmoenig** [comment]
Thanks for checking, Michael!
