### ISSUE TITLE
Is it possible to load images by link reference?

### ISSUE THREAD

**Issue by geaplanet** [jmoenig/Snap--Build-Your-Own-Blocks#841]
I was wondering if it would be possible to load images (or other media) by link reference into the XML file generated when you export a game.

**Comment by cycomachead** [comment]
There's a similar issue from a little while ago where you could use a JSFunction to add this functionality, but right now, it's not in Snap<i>!</i> by default.

@bromagosa I think has the code in a project somewhere?

**Comment by bromagosa** [comment]
Yep, I do :)

![image](https://cloud.githubusercontent.com/assets/1016697/8277700/a761cb20-18c5-11e5-8d2a-643c590593a8.png)
