### ISSUE TITLE
[minor] script variables can't be "shown" during a pause, even though "show variable" lists them

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap--Build-Your-Own-Blocks#842]
"show variables" lists script variables as "showable", but they never get shown, so it's very hard to debug code with lots of script variables using "pause all". This came up during "BJC Alumni" teachers week.

![screen shot 2015-06-23 at 2 04 26 pm](https://cloud.githubusercontent.com/assets/2229297/8317225/d0d00030-19b0-11e5-8579-ab8cff86a4ab.png)

**Comment by cycomachead** [comment]
Hmm, this seems to work for me --
http://snap.berkeley.edu/snapsource/snap.html#present:Username=cycomachead&ProjectName=script%20vars

(We actually teach this in CS10 Lab 4).

**Comment by cycomachead** [comment]
@ddgarcia Do you have a sample project for this?

**Comment by liam4** [comment]
(@cycomachead, doesn't the works for me fit here? :package:)

**Comment by cycomachead** [comment]
@liam4 I'm using the "can't reproduce" tag since it has the same meanimg. :)

**Comment by ddgarcia** [comment]
I tried the same code as I initially posted, but now it seems to work. I'm happy to have this closed.

**Comment by cycomachead** [comment]
:+1:
