### ISSUE TITLE
[Minor] Confusing error message "TypeError list.at is not a function" for common error (using "item of" of a variable not set yet defaulting to 0)

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap--Build-Your-Own-Blocks#859]
I've seen this several times in actual teacher work. Learners forget to click the "set variable to list" block, then call "item of" the (unset, defaulting to 0) list, and it errors with "TypeError list.at is not a function", which doesn't help the learner know what to fix. I'd prefer "Item requires a list argument, but instead was given 0"

<img width="803" alt="screen shot 2015-07-08 at 10 32 17 am" src="https://cloud.githubusercontent.com/assets/2229297/8572989/64c6319e-255d-11e5-9405-d8f86ca44d65.png">

**Comment by jmoenig** [comment]
fair enough.

**Comment by cycomachead** [comment]
Tag #632 #533
