### ISSUE TITLE
Bug: List Equality Comparisons with Empty items seems broken.

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#863]
Look at the following project in the sprite called "Contains".

http://snap.berkeley.edu/snapsource/snap.html#present:Username=cycomachead&ProjectName=2048_starter_file-list-bugs

When using the contains block with empty items, the results are unexpected.
It seems like either `add` or `=` isn't doing the right thing here.

![](https://s3.amazonaws.com/uploads.hipchat.com/121233/1059215/eVVdBIBknFjnHQh/doesntWork.PNG)

![](https://s3.amazonaws.com/uploads.hipchat.com/121233/1059215/RNyoVZ58ennyMXZ/works.PNG)

`GAME BOARD` is 16 empty items, made using the `add` block.

**Comment by jmoenig** [comment]
did that ever work? We don't have an explicit NIL value in Snap, which always scares CS instructors, still people constantly want to check for it. There are also all kinds of type-casting issues inherited from Scratch, since the empty *square* input slot can also mean an emtpy `text`, or the `number` zero. What this boils down to is that I don't want to support NIL this way.

**Comment by cycomachead** [comment]
> did that ever work?

Which part? To be honest -- I'm not sure if there's something new here, or what exactly is wrong. I'm fairly certain that checking for empty items in a list is that's saved as a variable has always worked, but I guess I'm not 100% sure. I know that people have successfully checked for contains on "nothing" though.

In this case, I was interpreting things more as an empty string `""` rather than as a NIL value. 

What's confusing to me is that adding to a list with the add block and using a list with empty inputs show up as equal when you compare items. Even if there's type casting going on -- I don't see why the results should be different for a list saved as a variable or one that's make from the `list` primitive.

**Comment by jmoenig** [comment]
now that you mention it I seem to remember that checking for empty list items indeed used to work. Can we find out when that was last the case and which commit broke it?

**Comment by cycomachead** [comment]
I guess the biggest thing that I don't get is this:

1. len(A) == len(B)
2. item 1 of A == item 1 of B
3. Therefore, A == B

**Comment by cycomachead** [comment]
> now that you mention it I seem to remember that checking for empty list items indeed used to work. Can we find out when that was last the case and which commit broke it?

Sure, I can try. Though it will take me a little while. I'm not sure what exactly is wrong here, since individual comparisons are working correctly. My guess is that it was something last summer.

**Comment by cycomachead** [comment]
Based on simply looking at the history for lists.js I see 2 likely candidates to test on:

Prior to either of these:
c1d5910f33584837a5c33c98f1e750789e6221fc (Last year's list fixes)
24ad14399c0ef5d7fa27e18dd0c6279099da1d78 (18 months ago list equality)

**Comment by jmoenig** [comment]
Great! I always use my local copy of

http://snap.berkeley.edu/snapsource/archive/

to simply extract a version of the `snap_yymmdd.zip` and load a test project to find the last version something worked...

I can do this for this example once I have a little more time at hand

**Comment by jmoenig** [comment]
Do you happen to know a specific project that used to work and that now is broken?

**Comment by cycomachead** [comment]
Not particularly, no. This was discovered while working on a new project.



> Great! I always use my local copy of
> 
> http://snap.berkeley.edu/snapsource/archive/
> 
> to simply extract a version of the snap_yymmdd.zip and load a test project to find the last version something worked...

Oh, yeah. I always forget those are there... I usually just use `git checkout -b test-branch <hash>` to get a past version.

**Comment by cycomachead** [comment]
Hmm, we're having a bunch of students encounter issues with this for a recent HW assignment. I'm going to take a closer look at things tonight but so far playing around hasn't turned up anything.

**Comment by jmoenig** [comment]
What's the assignment? Why do they feel they have to check for nil values? Can you encourage them to instead check for positives?

**Comment by cycomachead** [comment]
It's 2048, we were using empty values in a game board to represent values that hadn't been set. We have work-arounds, like also using 0's but since we shared a starter project it's a bit hard to switch some stuff.

**Comment by jmoenig** [comment]
using 0's could work, but empty slots sometimes behave as 0's and identify as numbers. So maybe initializing empty slots on the board with a letter might work better. 

At some point - and I'm very reluctant about this - we could add an explicit NIL type and initialize everting with it. This would raise all the type errors everybody wants to avoid for beginners but is eager to introduce for intermediate users :-)

**Comment by cycomachead** [comment]
> At some point - and I'm very reluctant about this - we could add an explicit NIL type and initialize everting with it. This would raise all the type errors everybody wants to avoid for beginners but is eager to introduce for intermediate users :-)

Lol, I _think_ most of us agree that such things would be too much.

Why don't we just re-write all the primtities with a special `Error(msg, ERROR_LEVEL)` function? :P Then we can provide a block in Snap<i>!</i> called `set error level to ___`
I'm totally joking about this, though similar things have been suggested.

**Comment by jmoenig** [comment]
great idea, Michael. And *then* we introduce a text-only mode with compile-error messages, because, after all, students need to attain literacy in syntax, which mandates that students need not only to be able to consume such errors but to engage in authoring new ones :-)

**Comment by cycomachead** [comment]
Look at this file: http://snap.berkeley.edu/snapsource/snap.html#present:Username=cycomachead&ProjectName=List%20Blank%20Bug

Re-serializing the file shows that the list using an add block is coerced to a `0` which should just be blank.

**Comment by cycomachead** [comment]
So, the `contains` reports true if you add a blank and check for contains `0`

**Comment by cycomachead** [comment]
Ah, ha! I've got it. It's a super simple fix -- but I am worried about the possible consequences. I don't expect anything to break since this actually makes behavior more consistent with other parts of Snap<i>!</i>. I'm submitting a PR in a few.
