### ISSUE TITLE
Can't Import Tools in this starter file.

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#864]
This one is a bit weird --

When students open this project (at this url at least) the import tools menu option doesn't "do" anything -- it's a little weird because this is just loading a normal XML file, as far as I can tell.

http://snap.berkeley.edu/snapsource/snap.html#open:https://inst.eecs.berkeley.edu/~cs10/labs/cur/programming/algorithms/../../../prog/algorithms/algorithms-framework-new.xml

**Comment by jmoenig** [comment]
Something to do with https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/pull/821 perhaps

**Comment by cycomachead** [comment]
> Something to do with #821 perhaps

Good call, yep! I see the bug. I'll have a fix soon.

Also tag because #118 - Snap<i>!</i> should also probably show a message when loading a library / costume fails.
