### ISSUE TITLE
Minor: Folders with files (Costumes etc) should have an index file

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#867]
the `libraries/` folder makes use of a simple index structure for its menu -- all the others should do the same. 

The main reason is that this reduces Snap<i>!</i>'s currently dependecny on parsing a directory listing file, and needing to have the server setup in a particular way.

Secondly, an index file like there is with `libraries/` would be easier to parse, quicker to load, and would allow us to use better formatted names in the menus.

This change would require only the slightest bit of extra effort to add a new background/costume/etc to Snap<i>!</i>.

**Comment by jmoenig** [comment]
This sounds good to me! Parsing a directory listing file didn't sound like a particularly sustainable idea to begin with.
