### ISSUE TITLE
JSFunction can hang snap. 

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#870]
This issue is definitely minor, and I probably wouldn't report it, except for I make typos while testing things. 

If you try to do `call JSFunction (return this.propThatDoesntExist)` then the function will just sit there forever with a halo and can't be stopped.

**Comment by jmoenig** [comment]
yeah, well, JS doesn't expose its call stack to us...

**Comment by dekrain** [comment]
//  (Sprite|Stage)
`this.propThatDoesntExist` yields undefined, but in `Process.prototype.returnValueToParentContext(value):+2` is `if value !== undefined`.
Finally, `undefined` NEVER be return value in _Snap!_

**Comment by brianharvey** [comment]
I hope I'm correctly representing Jens's position with those labels.

**Comment by cycomachead** [comment]
Yeah, sure. If that's the case, we might as well close this.

There are certain issues we couldn't recover from (like `while (true) {}`), but I do think that we could get around this at least via a `try catch`.
