### ISSUE TITLE
"undo delete sprite" (and "delete script")

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap--Build-Your-Own-Blocks#872]
A student had a ton of code in a sprite, clicked "delete" and didn't mean to.  Huge panic.  Then they emailed everyone (including me) asking where the undo button was.   Sadly, I had to say there wasn't one.

**Comment by cycomachead** [comment]
Tag, #78

**Comment by lmock** [comment]
+1 really though. one mis-click and you're toast.

**Comment by kbakalar** [comment]
I've done this too.  It is too easy to delete a sprite with lots of code attached. We could ameliorate the problem by popping up an "ARE YOU SURE??" dialog box when the user deletes a sprite.
