### ISSUE TITLE
#open causes Libraries, import tools, and Examples to fail

### ISSUE THREAD

**Issue by BrandonAPrice** [jmoenig/Snap--Build-Your-Own-Blocks#873]
If I use #open to open an xml file that I have hosted on a local server, so something like this: http://snap.berkeley.edu/snapsource/snap.html#open:http://192.168.1.10:12345/project.xml
If I try to go to examples (file->open-> Examples) it appears empty. If I try to import tools or open a library, that also fails. It seems like using #open interferes with the GET request the server is sending and instead of a get request for the Examples folder or Libraries index file, it is sending a GET request for the snap.html file.

**Comment by cycomachead** [comment]
Yep, this was broken by #821 and fixed with #866 :)

**Comment by jmoenig** [comment]
this has been fixed now, right?

**Comment by cycomachead** [comment]
Yep, just tested and it works for me, at least.
