### ISSUE TITLE
Export with w/o media makes difference, Chrome

### ISSUE THREAD

**Issue by dan3dewey** [jmoenig/Snap--Build-Your-Own-Blocks#899]
Earlier version of the project below exported fine in Chrome.
Once I added additional instructions (stages) the export failed,
however Export without media works fine.
I wonder if something in the "MS PowerPoint slides exported to jpg on Mac"
images are causing the failure?
http://snap.berkeley.edu/snapsource/snap.html#present:Username=dan3dewey&ProjectName=TrafficJam_CPT

**Comment by cycomachead** [comment]
This is unfortunately, a known bug with Chrome. :( A project greater than about 2MB cannot be exported in Chrome. You can export using another browser, like Safari or Firefox.

**Comment by dan3dewey** [comment]
Yes that does seem to be the limit...  Without media the project is 100k but the size of the costumes put me over the 2000k.  Turns out that a 66k jpg (size 573x434) used for the stage turned into a 250K png when saved with the project...  Gotta watch the graphics ;-)   Thanks,

**Comment by cycomachead** [comment]
Tagging #966 #983
