### ISSUE TITLE
[repeatable error] This big project crashes export blocks (to xml) in just about every browser

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap--Build-Your-Own-Blocks#905]
Here's the project:

http://snap.berkeley.edu/snapsource/snap.html#present:Username=utieshell&ProjectName=Binary%20Counter_Skyline

Thought I would share this to help track the "Awww... Snap!" error.

dan

**Comment by cycomachead** [comment]
Closing and tagging #966 #983 

http://snap.berkeley.edu/snapsource/michael/snap.html#present:Username=utieshell&ProjectName=Binary%20Counter_Skyline
