### ISSUE TITLE
keyboard editing adds spaces to text input

### ISSUE THREAD

**Issue by tjvr** [jmoenig/Snap--Build-Your-Own-Blocks#907]
- Enable keyboard input
- Highlight a text field with some content
- Press enter key repeatedly

The input field will slowly grow longer, like spaces are being added to the end. Except Jens thinks these might not be spaces. :P

**Comment by jmoenig** [comment]
Thanks, Tim! Turns out it doesn't add spaces but - worse - carriage returns....
