### ISSUE TITLE
Share with URL is not working

### ISSUE THREAD

**Issue by davelai** [jmoenig/Snap--Build-Your-Own-Blocks#915]
Using Chrome on a PC, I create a new project and add a single block (e.g.: move 10 steps).
I save-as the project in the Cloud (as "a-test").
I save-as again, click the existing project name ("a-test"), and Share.
The URL of the page updates: http://snap.berkeley.edu/snapsource/snap.html#Username=dlai&ProjectName=a-test
--> Updated URL doesn't have the "#present" included:
http://snap.berkeley.edu/snapsource/snap.html#present:Username=dlai&ProjectName=a-test

My students and I could reproduce this behavior from a variety of computers, all within a classroom.
I'm not sure how to get the "#present:" included in the URL to share a project (we're hoping to use the Share link to submit work via a Google Form). Maybe TMI. =)

**Comment by cycomachead** [comment]
@jmoenig I can take a look at this -- not sure why it's getting left off.

If you re-open the project, the URL _should_ be correct.

**Comment by davelai** [comment]
Yes, if I open up a different program, or log off and then log back in, then when I re-open the Shared project, the URL works (it includes ":present"). 

There's a thread of teachers/volunteers on a TEALS Piazza group that will have a party when this is changed. :)

**Comment by brianharvey** [comment]
@cycomachead Yes, please fix this.  Jens is on vacation.

**Comment by brianharvey** [comment]
Followup from BJC TEACHERS on Piazza:

Joshua Underwood posted a response to the followup "<p>Thanks, Brian. We tried this in both Mozilla and Chrome. Same results. If a student is logged in, they see their proj...":

Just as an update, I had students submit a project last night and one did it 30 seconds ago and the present is missing.  I'm guessing this is a SNAP bug

Go to https://piazza.com/class?cid=idm3a4vns117ou&nid=h8yx482idav52y&token=YPcDnaExFNp to view details. Search or link to this question with @494.

**Comment by davelai** [comment]
Students were sharing projects today and their URLs didn't include "present:".... I'll share more later, but wanted to let you know.

**Comment by cycomachead** [comment]
> Students were sharing projects today and their URLs didn't include "present:".... I'll share more later, but wanted to let you know.

You might need to force clear the browser cache. Try holding `shift` when clicking refresh. (or using Cmd-R)

If you use the Snap<i>!</i> icon menu in the upper left, click about, and then "modules". Gui should say 2015-September-9.
