### ISSUE TITLE
Minor: Use • as a password character.

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#920]
Would anyone be opposed to using • as the character instead of * ?

There's no functional change here, but • looks much nicer. :smile:

**Comment by khotchkiss13** [comment]
I agree, • is a nicer and more modern character to hide the actual value of the text. It is also inline with how many different password fields do it as well.

**Comment by an-OK-squirrel** [comment]
I was testing this out today, and here's a few problems I saw:

The &#x2022; symbol is a square in the font that is used

It is smaller than every other char, meaning that the cursor moves too far right

**Comment by brianharvey** [comment]
Not gonna do it b/c doesn't work for everyone.

**Comment by cycomachead** [comment]
Fine by me, though those sound like underlying font bugs but...someone else can take a look. :P
