### ISSUE TITLE
Fill tool issues

### ISSUE THREAD

**Issue by sbillcliff** [jmoenig/Snap--Build-Your-Own-Blocks#923]
Running Snap but encountering just one issue when we try to use the fill tool when creating a graphic -  at that point the webpage crashes.

We are running Snap on the following system:
Ubuntu 14.04 LTS 64 bit minimal kiosk installation just running Google Chrome (Chrome 43.0.2357.125 64 bit) 

Incidentally, the fill tool works fine on Scratch online. Any ideas?

**Comment by Hardmath123** [comment]
Is there a particular region/color/situation that fails to floodfill, or does this behavior happen on every place you try floodfill?

**Comment by oceank2** [comment]
each time i try to use fill region tool snap crashed. I use Google Chrome
