### ISSUE TITLE
"Unable to get property 'prototype' of undefined or null reference"

### ISSUE THREAD

**Issue by plaforet** [jmoenig/Snap--Build-Your-Own-Blocks#924]
Some of my students have gotten this message when using the sound block "play note __ for __ beats." I can't figure out what is causing it, and it's not happening on all the computers. Help, please!

![error msg](https://cloud.githubusercontent.com/assets/14203425/9769171/23cde084-56ee-11e5-8d7c-c9fd05fad9cf.png)

**Comment by brianharvey** [comment]
I believe that sound is working on some browsers but not others.  Could you please find out the OS, browser, and browser version of the nonworking ones, and maybe see if it's different on the working ones?  Thanks.

**Comment by cycomachead** [comment]
@plaforet Do you know what the browser/OS was when this happened?

**Comment by plaforet** [comment]
Hi,

I want to say the issues only occurred when using Internet Explorer on Windows 7.

Paul Laforet


-------- Original message --------

**Comment by cycomachead** [comment]
Thanks. 

Unfortunately, this is a known problem with IE, that we can't use sound with. There's some discussion in #985 #989
