### ISSUE TITLE
ask for <reporter> from <sprite> vs local sprite variables

### ISSUE THREAD

**Issue by A2Zog** [jmoenig/Snap--Build-Your-Own-Blocks#925]
When I use an "ask for" block in an if conditional, it seems to break local (sprite) variable references in the then and else blocks. Code available on request.

![ask for from error](https://cloud.githubusercontent.com/assets/3846118/9779154/b7576f52-5746-11e5-901a-b44b57a22ec3.PNG)

**Comment by bromagosa** [comment]
I think what you're looking for is ![image](https://cloud.githubusercontent.com/assets/1016697/9786978/bf05e7c4-57be-11e5-8f44-885e34024565.png).

What the ``ask for`` blocks does is asking the user to input some text.

**Comment by A2Zog** [comment]
Thank you for the reply...

One of my original concerns was that I was using the wrong block(s) to 
begin with, so thank you for the guidance.
However, it seems that my original call was returning the same value as 
the call you suggested, so I don't think that is the issue.

As soon as I do either one, subsequent references to local sprite 
variables seem to fail. Even as simple as this



Hopefully, someone else will have another suggestion to offer.

**Comment by jmoenig** [comment]
this is a bug. Thanks for submitting it!

**Comment by jmoenig** [comment]
Okay, I've found the bug and I'm going to commit the fix shortly.
In the meantime I'd like to point out that you can use the ```() of () ``` reporter to directly query many attributes of another sprite, including the values of the other sprite's field variables and most of its attributes, including its coordinates.

**Comment by jmoenig** [comment]
I've put the new version with the fix online. Please reload the Snap! page until the version of the module named ```threads.js``` shows today's date (or younger) and then try your project and examples again. My own test-cases all (appear to) work correctly with this fix, but please do let me know if you still encounter anything.

Thanks!

**Comment by A2Zog** [comment]
I tested my original ask version, the call version mentioned by another 
poster, and the () of () that you suggested and they all work with the 
update.

Thank you for these changes and your support in general.

[Also, thanks for the () of () suggestion. Much nicer but apparently 
easy to miss. My learning experience for the day.]

**Comment by jmoenig** [comment]
Thanks for the quick testing and for verifying that the fix works for you!
