### ISSUE TITLE
"for each" needs a help page

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap--Build-Your-Own-Blocks#930]
Everything else in "tools" in the Variables palette does...
(oh, and it should probably live in the Control palette, but that's for another day)

**Comment by cycomachead** [comment]
Tag #332 

> (oh, and it should probably live in the Control palette, but that's for another day)

Interesting discussion. I like it in lists because it operates on lists. (As a bonus it's much less crowded than control.) But control does go with the other loops.

**Comment by brianharvey** [comment]
Fixed.  Jens will close when he puts it in the repo.  He knows how to git.  Unlike some of us.

**Comment by cycomachead** [comment]
You can drop an image here and I can do it 

-- 
Michael Ball
From my iPhone
michaelballphoto.com

**Comment by brianharvey** [comment]
It's done on s.b.e, just has to be put in the repo.

**Comment by cycomachead** [comment]
Fixed now!

**Comment by liam4** [comment]
Woohoo!
