### ISSUE TITLE
problem with smartboard

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#933]
BJC/Smart Board Conflict  (9/16/15 2:28 PM)

My U1L1 Click on Alonzo script will not work if I start my browser after the smartboard is started.  It will work before I start the smartboard, but once I start the smartboard I can't restart the browser.  At least that is what I have it narrowed down to after hours of debugging.

Here is the info for my smartboard:
Board Model M685 s/n G012GW19O1520
Projector model UF70w s/n B012GA10R0203

The computer is running Windows 7 64bit Enterprise SP1.  I updated to the latest version of Chrome and that did not help.
I can sent you the exported XML if you want it.  

Go to https://piazza.com/class?cid=ien4gbkh6cx3yi&nid=i7hy3udaukx6su&token=YPcDnaExFNp to view.

**Comment by brianharvey** [comment]
http://snap.berkeley.edu/snapsource/snap.html#present:Username=gludovici&ProjectName=aU1L1-ClickAlonzo

**Comment by jmoenig** [comment]
Hmm. I don't understand what this script is supposed to do:

![funny](https://cloud.githubusercontent.com/assets/2596285/9932106/7681f94c-5d41-11e5-9410-10b57feba4e4.png)

Once Alonzo is clicked once, this script runs forever, so clicking Alonzo *again* won't do anything...

**Comment by brianharvey** [comment]
Only in thread safe scripts mode.

**Comment by brianharvey** [comment]
This problem seems to have been solved by a smartboard software update.
