### ISSUE TITLE
It would be cool to have a lasso, selection box capability in project area

### ISSUE THREAD

**Issue by SheilaBrady** [jmoenig/Snap--Build-Your-Own-Blocks#936]
Hi there Jens!
It would be really great to have a lasso, or box selection function in the script writing area of the screen.  I write a lot of practice scripts and am trying to keep all my project's practice blocks on the same project page. So I clean up a lot.  It would be nice to be able to select a bunch of scripts at one time, either with a lasso, or box selection tool, instead of moving them all one by one.
many thanks, and thanks for Snap! in general!
I realize that this is an enhancement request rather than an actual bug.  Not sure how to denote it as such.  If you tell me I will always note enhancement requests as such in future.
Cheers!
Sheila

**Comment by brianharvey** [comment]
Same as #1016.  We closed that one too.
