### ISSUE TITLE
Snap server down?

### ISSUE THREAD

**Issue by hansellynn** [jmoenig/Snap--Build-Your-Own-Blocks#939]
Hey guys, anyone know anything about the Snap server being down?  http://snap.berkeley.edu/run seems to be unresponsive since 9am PST (at least) this morning, until now (noon PST).

**Comment by khotchkiss13** [comment]
This is from the university:

At approximately 7:00 pm Friday evening there was a small fire in the campus data center that triggered the building’s fire suppression system which ultimately led to the powering down of the data center in Warren Hall. All main campus IT applications were nonoperational for most of the evening and continue to be offline.
We are working diligently to bring campus systems back online. Email is still working and even if you are unable to access your mail at this time, it will be there waiting for you when CalNet authentication is restored. Your phone and external email clients can still be used to access your account.
Once our systems are again available, we ask instructors to provide students with appropriate accommodations for possible missed assignments or other problems stemming from the outage.

**Comment by hansellynn** [comment]
Awesome, many thanks for the heads up Kyle!!


> On Sep 19, 2015, at 12:15 PM, Kyle Hotchkiss <notifications@github.com> wrote:
> 
> This is from the university:
> 
> At approximately 7:00 pm Friday evening there was a small fire in the campus data center that triggered the building’s fire suppression system which ultimately led to the powering down of the data center in Warren Hall. All main campus IT applications were nonoperational for most of the evening and continue to be offline.
> We are working diligently to bring campus systems back online. Email is still working and even if you are unable to access your mail at this time, it will be there waiting for you when CalNet authentication is restored. Your phone and external email clients can still be used to access your account.
> Once our systems are again available, we ask instructors to provide students with appropriate accommodations for possible missed assignments or other problems stemming from the outage.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/939#issuecomment-141700074>.
> 

__________________________________________________________________________
"I think everyone in this country should learn to program a computer
because it teaches you how to think" - Steve Jobs

Hansel Lynn, Owner/Founder (guy who makes new schools)
3441 Alma Street, #150 in Palo Alto
www.thecoderschool.com

**Comment by brianharvey** [comment]
There is a mirror of Snap! at
http://media.mit.edu/~bharvey/snap
