### ISSUE TITLE
Feature request: comment block

### ISSUE THREAD

**Issue by thomasgeissl** [jmoenig/Snap--Build-Your-Own-Blocks#948]
This is a feature request. I really miss the option to add comments. Please correct me, if there is already a kind of comment block.

Some points that came in my mind:

* Simple comment block vs. comment block, which groups a couple of blocks
* Option to comment-out some blocks

What do you think about adding comments? Are there difficulties or any points against adding comment blocks?

**Comment by brianharvey** [comment]
To add a comment, right-click or control-click on the grey background of the scripting area and choose "add comment."  After you write your comment, you can attach it to a block in a script by dropping the comment block over the script block.

This doesn't allow commenting out code.  I've occasionally used IF <FALSE> for that purpose, but mostly I think we don't want to encourage leaving a bunch of dead code in projects.

**Comment by cycomachead** [comment]
There are comments in Snap<i>!</i> :)

In the scripting area, simply right click and select "add comment...". This gives a little yellow text box that can be attached to any block. (They can also be resized and sit anywhere you want, and even live inside the defition of custom blocks.)

There's no standard way of "commenting out" code like you could do in a text language, like
```js
/* this was a test
if (x < 5) {
    throw new Error('testing....')'
}
*/
```
However, the usual approach in Snap<i>!</i> is to simple remove that section of code from the script it belongs to and and a attach a comment saying why it's just floating around. Any blocks that are on the scripting area that aren't attached to some event (like a green flag clicked, or recieving a broadcast, etc) won't be executed when the project is run.

**Comment by cycomachead** [comment]
Here's an idea if you wanted "inline" comments where you could turn a section of code "on of off". You can actually build this as a custom block in Snap<i>!</i> :)

![screen shot 2015-09-24 at 2 22 21 pm](https://cloud.githubusercontent.com/assets/1505907/10087311/02aacf58-62c8-11e5-84e9-459f6682aab3.png)

Also tagging #520 Because that might make the basic commenting feature more discoverable.

**Comment by thomasgeissl** [comment]
Wow, thanks a lot for your detailed answers. I get your points and i like the toggleable comment.
I didn't know that those comments can be assigned to blocks, I should have read the docs more accurately. Shame on me.
