### ISSUE TITLE
Can't find projects saved to the cloud

### ISSUE THREAD

**Issue by jcaldw737** [jmoenig/Snap--Build-Your-Own-Blocks#950]
Today I created 5 projects and saved them to the cloud.  I can't find them tonight.
User = jcaldw126 [ I am pretty sure I was logged in as this user when I saved]
Here are 3 of the Projects
Sep 24 - Homework due then
Sep 24 Square and Sun
Sep 24 Triangle

thanks for whatever you can do.

Now I can see the projects when I am not logged in -

![image](https://cloud.githubusercontent.com/assets/5361659/10092826/570fd2d0-6310-11e5-8fb0-3442f9f0ca40.png)

I need to share those projects
But I can't share them if I am not logged in - right?
And if I log in I am concerned that I won't be to see them any more as above,

**Comment by jmoenig** [comment]
Not sure if I understand the issue. If you log in you can switch between the cloud and local storage by clicking on the cloud or storage symbols. They're like tabs. The only difference is that if you're logged in Snap shows the cloud tab *by default* whereas it shows the locally stored project *by default* if you're logged out.

Did I understand the issue, or am I missing your point?

**Comment by jcaldw737** [comment]
Thank you very much, Jens!  Once again you amaze me with your concern and availability.
In trying to express the situation better I stumbled on the fact that some projects were saved to the cloud and others to the browser.
Now all is well!!!
Thank you!
Jerome Caldwell
