### ISSUE TITLE
The Answer reporter Filters duplicate Spaces

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#951]
For instace answering "Hello        World" will be reported as "Hello World".

Is this intentional? This has been confusing students on a recent assignment.

(edited: code blocks don't show spaces very well apparently...)

**Comment by cycomachead** [comment]
Ugh... I can't get github to show that there's a dozen spaces bettwen hello and world in the first case, but that's what I was trying to show....

**Comment by jmoenig** [comment]
Yes, this is intentional. All input fields in Snap normalize spaces except when they're showing the brownish dots to specifically support spaces

**Comment by cycomachead** [comment]
Thanks, not sure why I never noticed that...
