### ISSUE TITLE
Export Project Summary Doesn't Work In Safari (8+)

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#964]
It's possible there's no work around here, but it seems like Safari's auto popup block is blocking the new summary feature. 

This is the same as the "script-pic with result" problem in Safari as well, I believe.

**Comment by jmoenig** [comment]
Hmm... works for me with Safari 9.0 (10601.1.56.2)

**Comment by cycomachead** [comment]
Does "script pic with result..." work as well?

Mine just doesn't show anything for both actions, though I don't really get why b/c it's just `window.open()` but when Safari used to have a disable-able popup blocker, turning it off solved the issues.

**Comment by jmoenig** [comment]
No, "script pic with result..." doesn't work for me. Also, I'm just now updating to El Capitan, so maybe that'll break things...

**Comment by cycomachead** [comment]
Hmm, so apparently the issue in Safari was a big project...Safari just doesn't do anything for a big project, but for smaller ones it seems fine. I'll do a little more testing. But Safari has never had issues with a big project so that's weird. :/

**Comment by cycomachead** [comment]
Haven't seen this recently, even with decent sized projects, so closing for now.
