### ISSUE TITLE
Opening a New Project Should Reset Location.hash

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#965]
Scenario:
Open up a shared project, and you have a proper shareble URL.
Now open up a new project, one that isn't shared, and the URL isn't correct anymore.

The problem here is the way IDE_Morph handles opening projects and URLs isn't consistent. 
I think the best solution would be an  `IDE_Morph.prototype.updateURL()` method that could be called whenever a project is saved / opened / dropped into Snap<i>!</i> etc.

**Comment by brianharvey** [comment]
Seems to be fixed.

**Comment by cycomachead** [comment]
Whoops, didn't mean to do that. it has been fixed. Weird though, I don't think this code changed recently...
