### ISSUE TITLE
getting location from within snap code

### ISSUE THREAD

**Issue by K0T3R** [jmoenig/Snap--Build-Your-Own-Blocks#967]
Hi,

I want to get the current latitude and longitude from within snap. 

I am trying to use "Javascript operator" and this example http://www.w3schools.com/html/tryit.asp?filename=tryhtml5_geolocation with no success.

Please help!

Thanks
Koushik

**Comment by cycomachead** [comment]
The problem is that `navigator.geolocation.getCurrentPosition(showPosition)` is using a callback function to return the results. I've actually never used Snap<i>!</i>'s JSFunction for asynchronous tasks, so I'm not sure about the process... @jmoenig Do you know if there's a good way to use a JSFunction in Snap<i>!</i> where the result comes in a callback?

**Comment by bromagosa** [comment]
If you don't need much precision, you can get a very approximate location from your IP:

![image](https://cloud.githubusercontent.com/assets/1016697/10304828/d5ee7b00-6c1c-11e5-8014-d536e5af99a8.png)

![image](https://cloud.githubusercontent.com/assets/1016697/10304834/dec74586-6c1c-11e5-8f3f-abc298d52423.png)

We're using our own CORS proxy in there. There may be a GeoIP service that doesn't need one.

**Comment by K0T3R** [comment]
hi,

Thanks a lot for the prompt response. Approximate location is good enough
for my use case.

Jsut fyi - I had to use script varialbes in order for call to work. I am
using this version of snap http://snap.berkeley.edu/snapsource/snap.html.

Here is my final code.
[image: Inline image 1]

Thanks again Bernat! I learned a lot from your response.

Thanks
Koushik

**Comment by K0T3R** [comment]
Hi,

I realize I need more accuracy than what I get from the IP address. Do you have any alternate recommendation?

Thanks
Koushik

**Comment by K0T3R** [comment]
Hi,

I have a related question, Is there a way to update a global variable from inside a JSFunction.

I tried to do this.<variable_name> with no success. Please help.

Thanks
Koushik

**Comment by jmoenig** [comment]
sure, since a global var is "global" you can just assign a value to it.

**Comment by jmoenig** [comment]
http://snap.berkeley.edu/snapsource/snap.html#present:Username=jens&ProjectName=JSVars&editMode

**Comment by djdolphin** [comment]
I managed to get geolocation working by borrowing some code from the launch block: http://snap.berkeley.edu/snapsource/snap.html#present:Username=djdolphin&ProjectName=Geolocation&editMode Is there a better way of starting new processes?

**Comment by K0T3R** [comment]
Thanks jmoenig and djdolphin.

Special thanks to djdolphin for writing the code which I have been tying to write for a week in vain! One silly question, where did you get the variables(for example "latitude") to drag and drop into the join?

This community is very helpful and responsive. Thanks everyone!

**Comment by K0T3R** [comment]
Hi,

One follow up question - I wanted geoLocation to be single block which returns a list. So I modified djdolphin's code a litle. Here is my version.

http://snap.berkeley.edu/snapsource/snap.html#present:Username=k0ush1k&ProjectName=Geolocation

The line before the "return" statement is a hack. I do not know why we need the 2 seconds delay. Without that hack, I get 0,0 as coordianates for the same code. Can some one explain to me what kind of a race condition this is and the right way to circumvent this?

Thanks
Koushik

**Comment by djdolphin** [comment]
Those variables are the ringified procedure's formal parameters. They're explained on page 36 of the Snap! Manual: http://snap.berkeley.edu/SnapManual.pdf#page=36

The get current location block I made is asynchronous, and if you want to turn it into a reporter, you'd need to make the rest of the script wait until it's done. A 2 second delay would work most of the time, but something like this would work better:
![getlocation](https://cloud.githubusercontent.com/assets/5834370/10418623/6daf4b9e-702e-11e5-8013-ed9733a3ef7c.png)

**Comment by K0T3R** [comment]
Thank you - This works awesome!

On a related topic, for the past 2 weeks in my expirements the location detected when accessing from my laptop has been accurate. But in between in my testing, for 10 minutes, the latitude and longitutde were off by about 300+ kms. The accuracy is back to being good now. Any idea why this happens?

**Comment by djdolphin** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation,
> By default, getCurrentPosition() tries to answer as fast as possible with a low accuracy result. It is useful if you need a quick answer regardless of the accuracy. Devices with a GPS, for example, can take a minute or more to get a GPS fix, so less accurate data (IP location or wifi) may be returned to getCurrentPosition().

It looks like modifying the get current location block to pass a third argument,
````javascript
{enableHighAccuracy: true}
````
to getCurrentPosition() will disable it.

**Comment by K0T3R** [comment]
Thank you!
