### ISSUE TITLE
Duplicated projects?

### ISSUE THREAD

**Issue by davelai** [jmoenig/Snap--Build-Your-Own-Blocks#969]
Students sometimes see a duplicate project when they save a project (two projects with the same name, but with different times that they were worked on last). Once in a while, they delete this duplicated project, since they didn't intend for it to be there. This has caused a few students to lose all of their costumes, sometimes ones they spend hours making. I hope this all makes sense. I don't know why projects get duplicated like this, but my request is that project duplicates aren't shown to users so they don't get deleted.

**Comment by jmoenig** [comment]
Can you post a screenshot of how a project duplicate is shown to a student? I'd love to investigate into this. Thanks!

**Comment by davelai** [comment]
Sorry it's so low tech. I took pictures of the screen for screenshots. Had to do it quickly while students kept working...

![2015-10-07 09 53 38](https://cloud.githubusercontent.com/assets/6028802/10360062/b362eec2-6d52-11e5-961c-a4c22ffc4660.jpg)
![2015-10-07 09 53 44](https://cloud.githubusercontent.com/assets/6028802/10360063/b364871e-6d52-11e5-885e-0649709a115e.jpg)

**Comment by davelai** [comment]
The students only saved this project with one name, and the duplication happened all on its own-- and the costumes were all lost as a result of this (this happened a month ago to another student),

**Comment by jmoenig** [comment]
Woah! Thanks, this helps a lot. I'm investigating, this clearly should not happen!

**Comment by jmoenig** [comment]
I've wildly tried to reproduce this, creating test projects with lots of media and code and saving, sharing, unsharing, opening them at insane intervals while the previous cloud operation was still in progress, but so far have not been able to reproduce this.

Can you tell me more about the account (the username) - perhaps via email - so I can further investigate? Thanks!

**Comment by davelai** [comment]
sent email with account username! thanks!
