### ISSUE TITLE
Migrate s.b.e/demos → Examples/

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#973]
Mostly for @brianharvey 

Why do we have two folders in `snapsource/`? Couldn't we put the demos/ projects under examples?

**Comment by brianharvey** [comment]
I've never seen that "demos" folder before.  Ask Dan or Jens.  (I'd say Dan for sure, except that some of the file names are in German.)

As a meta point, I think we are beyond needing to use the Scratch example projects as Snap<i>!</i> examples.  It should all be stuff you can't do in Scratch, or at least stuff you can't do as easily.

**Comment by jmoenig** [comment]
Oh yes, those are all mine, and I've completely forgotten about them, and haven't used them since we have the SnapCloud. They're not even examples, I think, just my bunch of experiments back then. I'll remove that folder next time. Thanks for reminding me!

**Comment by cycomachead** [comment]
I'd go through them and see what could be migrated over! The animated tree is really cool and should be an example project, IMO.

**Comment by brianharvey** [comment]
Isn't live-tree already in examples?

**Comment by cycomachead** [comment]
There's "live-tree" but not this: http://snap.berkeley.edu/snapsource/snap.html#open:demo/tree%20animation.xml

**Comment by brianharvey** [comment]
Oh.  Cute, yeah.

**Comment by brianharvey** [comment]
We decided to delete the directory.  :-)

**Comment by cycomachead** [comment]
Awww, what about the animated tree? (otherwise, I think that's fine.)
