### ISSUE TITLE
Blurry text

### ISSUE THREAD

**Issue by bromagosa** [jmoenig/Snap--Build-Your-Own-Blocks#981]
Since about a week ago, some fonts look blurry. Here's a comparison between what they used to look like and what they look like now:

![gas](https://cloud.githubusercontent.com/assets/1016697/10726809/82fbc33a-7bd5-11e5-8804-d9f0e9652ce3.png) 
![gas](https://cloud.githubusercontent.com/assets/1016697/10726817/8fa4bda8-7bd5-11e5-8d2e-b1c7aa9569e4.png)

It's even more apparent in flat mode:

![gas](https://cloud.githubusercontent.com/assets/1016697/10726830/a27afe10-7bd5-11e5-9f79-5b30bc2cb9ce.png)
![gas](https://cloud.githubusercontent.com/assets/1016697/10726834/aa86e16e-7bd5-11e5-9c04-41b51bb7403d.png)

I've noticed it happening in categories, labels and buttons in the paint editor, and variable watchers (if you resize the Stage they sometimes look OK again).

I guess this has something to do with recent changes meant to support retina displays?

**Comment by jmoenig** [comment]
This definitely *is* strange. It's unrelated to experiments about supporting retina displays, since I haven't pulled any of those yet. Could be newer versions of browsers, especially Chrome. I've noticed Chrome's fonts getting worse in the last version (46).

**Comment by jmoenig** [comment]
Browsers! </sight>

**Comment by jmoenig** [comment]
I can see Chrome blurring fonts on Windows 10 (non-retina), but not on Chrome OSX (non-retina). Which browser and OS are you using (I assume it's Ubuntu, right)?

**Comment by bromagosa** [comment]
It's Chrome (46.0.2490.71) on Debian 64b, but it also happens in Firefox (Iceweasel 38.3.0). Sorry about that, I feel your pain! What can I do to help?

**Comment by cycomachead** [comment]
This seems almost exactly like how Chrome on OS X retina has looked, and somewhat worse than non-retina.
