### ISSUE TITLE
operators can be dropped into "when I am" trigger

### ISSUE THREAD

**Issue by wortzmanb** [jmoenig/Snap--Build-Your-Own-Blocks#982]
It seems users are able to drop values into the drop-down in the "when I am" trigger, like so:
![download](https://cloud.githubusercontent.com/assets/8575915/10741848/14b4493a-7be7-11e5-956c-c103caf4563b.png)
![download 1](https://cloud.githubusercontent.com/assets/8575915/10741849/14b5a2f8-7be7-11e5-9ad9-713603a604c8.png)

The first one isn't so bad, though it doesn't seem like the right way to do that.  The second one is, of course, nonsensical.

This does not appear to be an issue with any of the other trigger blocks.

**Comment by jmoenig** [comment]
Good catch, that's a bug! I'll fix it with the next release. Thanks!

**Comment by wortzmanb** [comment]
Thank one of my students.  ☺

Brett Wortzman
Issaquah High School
Computer Science Teacher  ·  FIRST Robotics Advisor (FRC #1318)

**Comment by jmoenig** [comment]
I've fixed this in my dev version, and will commit the patch along with the next batch of pushes

**Comment by wortzmanb** [comment]
Thanks!  FWIW, it looks like you can drop values into the drop-downs in a couple of sensing blocks too:
![download 1](https://cloud.githubusercontent.com/assets/8575915/10946098/47cda01a-82d5-11e5-8a83-bf84e5b561d0.png)
![download](https://cloud.githubusercontent.com/assets/8575915/10946099/47d2185c-82d5-11e5-8690-1c75b98e08a0.png)

Not sure if that's by design, or if it's a separate bug, but thought I'd mention it.

**Comment by jmoenig** [comment]
those actually (should) make sense :-)
