### ISSUE TITLE
CTX Undefined Error with Play Note Block

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#985]
The EDC BJC site has received several error reports about this script, however it loads and runs fine on most computers. 

I saw this error in an NYC classroom and grabbed a pic:
![play-note-ctx-error](https://cloud.githubusercontent.com/assets/6549787/10795250/4fcf049a-7d6f-11e5-81bc-5dd21980e39e.JPG)

The script is referenced in problem 9 on this page: http://bjc.edc.org/bjc-r/cur/programming/1-introduction/3-control-commands/3-the-for-block.html?topic=nyc_bjc%2F1-intro-loops.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment

**Comment by jmoenig** [comment]
I've last seen this error back in the day when browsers still had different ideas of web audio, and some didn't support web audio at all. Could it be that these are old browser versions (haven't been updated for about a year)?

**Comment by maryfries** [comment]
It's possible. I have a few other Snap! issues to input from the NYC trip, and some of those include browser/OS data, but I don't think I have it for this one.

I'll add it if I do.

Thanks Jens,
Mary

**Comment by cycomachead** [comment]
Yeah, definitely an underlying web audio issue. Do you think we could catch it and send a friendlier message?

**Comment by cycomachead** [comment]
Tag #924 #989
