### ISSUE TITLE
Costume Switching Not Possible (Sometimes)

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#986]
In NYC, one student had multiple costumes for the stage but could not switch between them. Neither the "next costume" block nor directly selecting one worked. I looked through her code and I couldn't find anything that I thought could have been breaking it. Reopening the project fixed the issue.

**Comment by jmoenig** [comment]
Those could be tainted (cross-origin restricted) costumes, alhtough I *am* checking for those, now. Also, this could just be a low-memory situation. Hey, sounds like you're doing *massive* media projects. Those are fun, but remember, you need adequate hardware and network resources to have fun with those :-)

**Comment by maryfries** [comment]
The massive media stuff was a teacher-design project (which was really great). I think the solution is to make it clear to teachers that they will be just as limited by their school's bandwidth for BJC as they are for everything else.

**Comment by jmoenig** [comment]
Yeah. Bummer, I love massive media myself :-(
