### ISSUE TITLE
Sound Importing - MP3s Not Working

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#988]
In NYC, students are trying to upload MP3s, and it's not working for them.

It would be great if that were possible (since MP3s are common and smaller than WAVs), but if it's not going to be possible, users need a clear notification of that.

**Comment by jmoenig** [comment]
which media types work depends on the browser and security settings, not on Snap. Snap supports anything the browser supports. There must be something in that school's security settings that prevents mp3's in browsers.

I just checked myself: I can import and save mp3's just fine

**Comment by maryfries** [comment]
Oh, interesting. Something for the Teacher Guide then... Thanks!
