### ISSUE TITLE
Importing Scratch Code

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#990]
It would be great if students were able to import scratch code. Some of the students in NY have projects that they want to be able to use in Snap!

**Comment by jmoenig** [comment]
Yep, I agree! We really should make Snapin8or available on the Snap website. @brianharvey ?

**Comment by djdolphin** [comment]
Hi Jens, I wrote [Snapin8r2](https://djdolphin.github.io/Snapin8r2/). I could help add it to the editor, website, or whatever would work best. :)

**Comment by jmoenig** [comment]
Excellent! I'd really like it on the website!

**Comment by djdolphin** [comment]
I've made a version of the Snapin8r2 site using the Snap! site's style: http://djdolphin.github.io/Snapin8r2-test/ I've been planning on modifying Snapin8r2 to fetch projects from the Scratch website and save to the Snap! cloud, so I could also add that.

**Comment by brianharvey** [comment]
That would be awesome!  What was the outcome of the finger-pointing exercise between you and Nathan about my nonworking project?

**Comment by djdolphin** [comment]
The problem with Nathan's SVG code only seems to happen in Firefox. [I converted the project using Chrome](http://snap.berkeley.edu/snapsource/snap.html#present:Username=djdolphin&ProjectName=tree), and the output doesn't run correctly, so that part is probably my fault. I'll look into that.

**Comment by jmoenig** [comment]
Neat! this looks really polished...

**Comment by djdolphin** [comment]
Thanks! @bharvey, it looks like the problem was that a script in Sprite1 tries to use an undefined variable called log. Scratch allows that and creates the variable for you, but Snap! throws an error.

**Comment by brianharvey** [comment]
Hmm, that must be a debugging thing I forgot to take out.  Thanks!

So, let me know when to put this on the Snap<i>!</i> site.

**Comment by djdolphin** [comment]
It could probably be put on the Snap! website now, but how would it be updated?

**Comment by brianharvey** [comment]
Oh, either I put it in an iframe, if that works, or I just put a link to it behind a screenshot.

**Comment by djdolphin** [comment]
I guess either would work. I might as well replace the old Snapin8r2 page with this one so I don't have to maintain both.

**Comment by djdolphin** [comment]
I've updated https://djdolphin.github.io/Snapin8r2/ with the new style.

**Comment by brianharvey** [comment]
I put a link to it on s.b.e
