### ISSUE TITLE
Bradcast

### ISSUE THREAD

**Issue by splegos** [jmoenig/Snap--Build-Your-Own-Blocks#992]
Did snap get an update because my sprite is having trouble broadcasting for the stage to switch costumes. Started on 10- 28-14

Here is the project. It's a game for my compsci class. 
http://snap.berkeley.edu/snapsource/snap.html#present:Username=shubhu1&ProjectName=Game

**Comment by jmoenig** [comment]
nope, no patch in the last weeks. Can you share your project? Then we can help. Tnx!

Von meinem iPhone gesendet

**Comment by splegos** [comment]
http://snap.berkeley.edu/snapsource/snap.html#present:Username=shubhu1&ProjectName=Game

Here is the project

**Comment by jmoenig** [comment]
nice game! Can you explain a little more in detail which part doesn't behave as you would expect it to?

**Comment by splegos** [comment]
When I'm on the second stage (called landscape) I can't move on to the third stage. Also my enemies don't appear sometimes but other times they do. Could you please tell me where the code went wrong?

**Comment by jmoenig** [comment]
Snap seems to work correctly, afaik. You'll have to be more specific and isolate how I can reproduce something. Doesn't seem like a bug to me.
