### ISSUE TITLE
How would i go about doing this problem

### ISSUE THREAD

**Issue by splegos** [jmoenig/Snap--Build-Your-Own-Blocks#993]

**Comment by splegos** [comment]
Write a custom SNAP block called "day in year" that takes a year number and a number between 1 and 366 and says the date that corresponds to that numbered day of the specified year. For example, in non-leap years day #1 is January 1, day #32 is February 1, day #365 is December 31, and day #185 is July 4. Give an error message if the number is 366 and a nonleap year is specified.

**Comment by brianharvey** [comment]
Is this a homework problem or something?

**Comment by splegos** [comment]
Extra credit question

**Comment by brianharvey** [comment]
And don't you think that asking someone else to do it for you might be considered, umm, unsporting?

**Comment by splegos** [comment]
I just need help going about it without having 366 off blocks

**Comment by khotchkiss13** [comment]
This is a place to discuss the implementation of Snap!, such as current bugs, feature requests, and behaviors of the language, and to provide code fixes and helpful perspectives to further the development of the language. This is NOT a place to ask for help on your homework. 
But I will suggest that you look into modular arithmetic to figure out how to complete the problem.

**Comment by splegos** [comment]
Sorry

But thanks
 have you seen the issues with broadcasting to the stage to switch costumes
