### ISSUE TITLE
directory "liam4" is open to public, allows for CSS injection.

### ISSUE THREAD

**Issue by roconnorpattonair** [jmoenig/Snap--Build-Your-Own-Blocks#994]

**Comment by cycomachead** [comment]
I'll fix this, I think I can...

**Comment by cycomachead** [comment]
@brianharvey I don't have permission to fix this, so you'll have to.

**Comment by brianharvey** [comment]
I don't understand the issue.  The directory is rwxr-xr-x.  Isn't that what it should be?  Don't browsers have to be able to read the directory?  Sorry for being ignorant about the issue -- I never worry about css because NoScript worries for me!  :-)

**Comment by cycomachead** [comment]
Wait, you're right! It's not world writable. I misread the `ls` output..., but the settings do currently seem correct. (755). I suppose 644 would also work, but I don't see what's wrong with the current setup, actually.

**Comment by cycomachead** [comment]
@roconnorpattonair Can you send some information about what we should do to fix the problem, and what the correct permissions should be?
