### ISSUE TITLE
Won't fetch my project

### ISSUE THREAD

**Issue by Kathie-Quick** [jmoenig/Snap--Build-Your-Own-Blocks#998]
When I try to open my project from the cloud, the "fetching project from the cloud" message shows and stays without actually fetching my project.

**Comment by cycomachead** [comment]
Do you have a lot of media (sounds, costumes) in your project?

**Comment by alan-kolar-1516** [comment]
This is my project, and I do have quite a few costumes. I think I took out the sounds before I saved it to help with the size though.

**Comment by jmoenig** [comment]
can you please share the project and post its url? I'd like to investigate. Thanks!

**Comment by alan-kolar-1516** [comment]
I published it, but I don't know how to find the url.

**Comment by cycomachead** [comment]
When you click "Open" in Snap! the URL should update so you can paste it here.

**Comment by alan-kolar-1516** [comment]
That's the problem. When I click open, the url doesn't change and nothing other than the "Fetching project from the cloud" box comes up.

**Comment by jmoenig** [comment]
Well, okay. So, did you mark the project as shared? If so, I just need your username and the name of the project. Thanks!

**Comment by alan-kolar-1516** [comment]
It is marked as shared. My username is "Snazzy" and the game is called "Police Chase."

**Comment by cycomachead** [comment]
Interesting, I can't open it, or see that the project exists. It should show here:
http://snap.berkeley.edu/snapsource/snap.html#present:Username=Snazzy&ProjectName=Police%20Chase.

Could you maybe post screenshot of the Open dialog?

**Comment by m0dern** [comment]
I am having this same problem. I do have a lot of music in my game, but the music files are very small.
My username is modern
the project name is pong

If there is anything I can do to retrieve this project please help, it is for a school project

**Comment by jmoenig** [comment]
Hi @m0dern , your project is really, really big, like 50 MB big! you can download it now, but we need to spread the word that these kinds of projects are causing problems for other users, @brianharvey @cycomachead can we please spread the word to teachers again?

Thing is: These music files *appear* to be only short, but their real size is ... *gian*

**Comment by bromagosa** [comment]
We now have a cap on project size, so I'm closing this one too.
